= How to execute SQL against CSV

Assuming there is a project containing VIVIDUS-based tests
(e.g. https://github.com/vividus-framework/vividus-starter[VIVIDUS Starter])
and the goal is to execute SQL queries against CSV resources to get the various
subsets of the data.

As a prerequisite add the required DB plugin dependency to the project `build.gradle`

[source,gradle,subs="attributes+"]
----
implementation(group: 'org.vividus', name: 'vividus-plugin-db', version: '{current-version}')
----

== Execute SQL against CSV resource

. Add the CSV and CSV driver dependencies to the project `build.gradle`
+
[source,gradle,subs="attributes+"]
----
implementation(group: 'org.vividus', name: 'vividus-plugin-csv', version: '{current-version}')
implementation(group: 'net.sourceforge.csvjdbc', name: 'csvjdbc', version: '1.0.38')
----

. Configure connection to the CSV resources
+
[source,properties]
----
db.connection.csv-data.driver-class-name=org.relique.jdbc.csv.CsvDriver
db.connection.csv-data.url=jdbc:relique:csv:classpath:path/to/csv/data
----
+
`driver-class-name` should be the same for all CSV connections. `url`
includes the mandatory path to CSV resources and may also contain
https://github.com/simoc/csvjdbc/blob/master/docs/doc.md#driver-properties[a set of options configuring CSV parsing], e.g.:
+
[source,properties]
----
db.connection.csv-data-2.driver-class-name=org.relique.jdbc.csv.CsvDriver
db.connection.csv-data-2.url=jdbc:relique:csv:classpath:another/path?separator=;&quoteStyle=C
----

. Use the configured connection to execute SQL
+
.Execute SQL against CSV
[source,gherkin]
----
When I execute SQL query `
SELECT * FROM capitals
` against `csv-data` and save result to scenario variable `csv-records`
Then `${csv-records}` matching rows using `country` from `csv-data` is equal to data from:
|country |capital |population |
|Belarus |Minsk   |1975000    |
----
+
where `capitals` is the name of CSV resource (the full resource path is
`path/to/csv/data/capitals.csv`).
+
The complete guide on SQL syntax and supported functions can be found in
https://github.com/simoc/csvjdbc/blob/master/docs/doc.md#features[CSV Driver documentation].

== Execute SQL against in-memory CSV

. Configure connection to in-memory database as described xref:use-in-memory-db-to-manage-test-data.adoc[here]

. Populate database with CSV dataset
+
.Create table with data from CSV
[source,gherkin]
----
!-- For demonstration purposes we hardcode the CSV file content, you can use variables and expressions as a sources of CSV instead.
When I create temporary file with name `egg-miners` and content `
id,name,race
1,Miner Gor,Redguard
2,Daynila Valas,Dark Elf
3,Miner Juillen,Breton
` and put path to SCENARIO variable `egg-miners-csv-path`

!-- Create table from the CSV contained in previously created temporary file
When I execute SQL query `
CREATE TABLE egg_miners AS SELECT * FROM CSVREAD('${egg-miners-csv-path}');
` against `in-memory-db-key`
----

+
[NOTE]
====
* See http://www.h2database.com/html/functions.html#csvread[CSVREAD] function description for more details.
* All columns read from CSV are of type VARCHAR.
* Use the http://www.h2database.com/html/grammar.html#cast_specification[CAST] function to adjust the column types (if applicable).
====

. Use the created table to execute SQL against
+
.Execute SQL against table created from CSV
[source,gherkin]
----
When I execute SQL query `
SELECT * FROM egg_miners WHERE race = 'Dark Elf';
` against `in-memory-db-key` and save result to scenario variable `egg-miners-records`
Then `${egg-miners-records}` is equal to `[{id=1, name=Daynila Valas, race=Dark Elf}]`
----
