== Configuration

=== Authentication

The plugin attempts to find AWS credentials by using https://docs.aws.amazon.com/sdk-for-java/v1/developer-guide/credentials.html#credentials-default[the default credential provider chain]. The provider chain looks for credentials using the provided below options one by one starting from the top. If credentials are found at some point, the search stops and further options are not evaluated.

. Environment variables: `AWS_ACCESS_KEY_ID` and `AWS_SECRET_ACCESS_KEY` (the optional variable for session token is `AWS_SESSION_TOKEN`).
. The properties: `system.aws.accessKeyId` and `system.aws.secretKey` (the optional property for session token is `system.aws.sessionToken`).
. Web Identity Token credentials from the environment or container.
. In the default credentials file (the location of this file varies by platform).
. Credentials delivered through the Amazon EC2 container service if the `AWS_CONTAINER_CREDENTIALS_RELATIVE_URI` environment variable is set and security manager has permission to access the variable.
. In the _instance profile credentials_, which exist within the instance metadata associated with the IAM role for the EC2 instance. This step is available only when running your application on an Amazon EC2 instance, but provides the greatest ease of use and best security when working with Amazon EC2 instances.
. If the plugin still hasn’t found credentials by this point, client creation fails with an exception.

See the official https://docs.aws.amazon.com/sdk-for-java/v1/developer-guide/credentials.html#credentials-default["Working with AWS Credentials"] guide to get more details.

=== Region Selection

The plugin attempts to find AWS region by using https://docs.aws.amazon.com/sdk-for-java/v1/developer-guide/java-dg-region-selection.html#default-region-provider-chain[the default region provider chain]. The provider chain looks for a region using the provided below options one by one starting from the top. If region is found at some point, the search stops and further options are not evaluated.

. Environment variable: `AWS_REGION`.
. The property: `system.aws.region`.
. AWS shared configuration file (usually located at `~/.aws/config`).
. Use the Amazon EC2 instance metadata service to determine the region of the currently running Amazon EC2 instance.
. If the plugin still hasn’t found a region by this point, client creation fails with an exception.

See the official https://docs.aws.amazon.com/sdk-for-java/v1/developer-guide/java-dg-region-selection.html["AWS Region Selection"] guide to get more details.
