== Configuration

=== Authentication

The plugin will search for credentials using https://docs.aws.amazon.com/sdk-for-java/v1/developer-guide/credentials.html#credentials-default[the default credential provider chain] in the following order:

. In system environment variables: `AWS_ACCESS_KEY_ID` and `AWS_SECRET_ACCESS_KEY`.
. In the properties: `system.aws.accessKeyId` and `system.aws.secretKey`.
. Web Identity Token credentials from the environment or container.
. In the default credentials file (the location of this file varies by platform).
. Credentials delivered through the Amazon EC2 container service if the `AWS_CONTAINER_CREDENTIALS_RELATIVE_URI` environment variable is set and security manager has permission to access the variable.
. In the _instance profile credentials_, which exist within the instance metadata associated with the IAM role for the EC2 instance. This step is available only when running your application on an Amazon EC2 instance, but provides the greatest ease of use and best security when working with Amazon EC2 instances.

See the official https://docs.aws.amazon.com/sdk-for-java/v1/developer-guide/credentials.html#credentials-default["Working with AWS Credentials"] guide to get more details.
