=== Compare date and current instant

Validates the difference between the current instant and the provided date in seconds.

[source,gherkin]
----
Then the date '$date' is $comparisonRule current for $seconds seconds
----

* `$date` - The date in the {iso-date-format-link} format.
* `$comparisonRule` - xref:parameters:comparison-rule.adoc[The comparison rule].
* `$seconds` - The expected number of seconds between the current instant and the provided date.

.Validate the date is less than current for 10 seconds
[source,gherkin]
----
Then the date '2020-06-16T15:25:29.516580Z' is less than current for 10 seconds
----

=== Compare two dates

Compares two dates according to the given comparison rule.

[source,gherkin]
----
Then the date '$date1' is $comparisonRule the date '$date2'
----

* `$date1` - The first date in the {iso-date-format-link} format.
* `$comparisonRule` - xref:parameters:comparison-rule.adoc[The comparison rule].
* `$date2` - The second date in the {iso-date-format-link} format.

.Compare dates
[source,gherkin]
----
Then the date '2021-04-20T01:02:03.004Z' is greater than the date '2021-04-20T01:02:03.003Z'
Then the date '2021-04-19' is less than the date '2021-04-20'
----

=== Compare date with custom format and current instant

Validates the difference between the current instant and the provided date in seconds using the custom date format.

[source,gherkin]
----
Then the date '$date' in the format '$format' is $comparisonRule current for $seconds seconds
----

* `$date` - The date to validate.
* `$format` - {java-date-time-formatter-link}.
* `$comparisonRule` - xref:parameters:comparison-rule.adoc[The comparison rule].
* `$seconds` - The expected number of seconds between the current instant and the provided date.

.Validate the date is greater than current for 10 seconds
[source,gherkin]
----
Then the date '2020-06-25T00:19:58.890007Z' in the format 'uuuu-MM-dd'T'HH:mm:ss.nnnX' is > current for 10 seconds
----