=== Context element rectangle

IMPORTANT: Context element rectangle dynamic variables are deprecated and will be removed in VIVIDUS 0.7.0, please use <<_save_size_and_coordinates_of_element>> step.

The set of dynamic variables provides ability to access context element
coordinates, width and height.

IMPORTANT: The variables rely on the contextual approach: it is necessary to switch context to the target element.

WARNING: In case of missing search context the error will be logged and `-1` will be returned as a result


==== *Variable name*

[cols="1,3", options="header"]
|===

|Variable name
|Description

|`context-height`
|the height of the context element

|`context-width`
|the width of the context element

|`context-x-coordinate`
|the absolute `X` coordinate of the context element

|`context-y-coordinate`
|the absolute `Y` coordinate of the context element

|===

.Check the size and the location of the image
[source,gherkin]
----
When I change context to element located by `id(userpic)`
Then `${context-height}` is > `0`
Then `${context-width}` is > `0`
Then `${context-x-coordinate}` is > `0`
Then `${context-y-coordinate}` is > `0`
----

=== Context source code

Variable provides source code of the current UI context of the application under test.

[source,gherkin]
----
${context-source-code}
----

.Firstly check frames on the entire page, and then links in the specified context
[source,gherkin]
----
Given I am on main application page
Then all resources by selector `frame,iframe` from ${context-source-code} are valid
When I change context to element located by `id(linksList)`
Then all resources by selector `a` from ${context-source-code} are valid
----

=== Source code

Variable provides source code of the UI of the application under test.

[WARNING]
====
The variable is deprecated and will be removed in VIVIDUS 0.7.0. Please use `$\{context-source-code}` dynamic variable instead.
====

==== *Variable name*

[source,gherkin]
----
${source-code}
----

.Check if element exists on UI
[source,gherkin]
----
Then `${source-code}` matches `.+Home.+`
----
