=== Taking screenshot steps
==== Take screenshot

Takes a screenshot and publish it to the report.

[source,gherkin]
----
When I take screenshot
----

==== Take screenshot and save it to the file

Takes a screenshot and saves it to the file at the specified path.

TIP: The full path to the file with the taken screenshot is posted to logs and report.

[source,gherkin]
----
When I take screenshot and save it to file at path `$screenshotFilePath`
----

_Deprecated syntax (will be removed in VIVIDUS 0.7.0)_:
[source,gherkin]
----
When I take screenshot and save it to folder `$screenshotFilePath`
----

* `$screenshotFilePath` - The path to the file to save the screenshot, the allowed values are:
+
** an absolute path to the file, e.g. `C:\Windows\screenshot.png`;
** a relative path (it is resolved from the current working directory, e.g. `screenshot.png`.

.Take a screenshot and save it to the file
[source,gherkin]
----
When I take screenshot and save it to file at path `${screenshot-directory}/start-page.png`
----

include::plugins:partial$ui-wait-element-state-steps.adoc[]

=== Wait for expected elements number

Waits for the expected number of elements located by locator.

TIP: In order to wait for invisible elements one rely on <<_visibility_types>>.

[source,gherkin]
----
When I wait until number of elements located by `$locator` is $comparisonRule $number
----

* `$locator` - <<_locator>>.
* `$comparisonRule` - xref:parameters:comparison-rule.adoc[The comparison rule].
* `$number` - The expected number of the elements.

.Wait for the visible elements
[source,gherkin]
----
When I wait until number of elements located by `tagName(img)` is equal to `5`
----

.Wait for the invisible elements
[source,gherkin]
----
When I wait until number of elements located by `tagName(img):1` is equal to `5`
----


=== Wait for element to stop moving

Waits for element with the specified locator to stop moving.

NOTE: An element is considered _moving_ when its coordinates (position) are changing. For example, an animated GIF is not a _moving_ element unless it changes position.

[source,gherkin]
----
When I wait until element located by `$locator` stops moving
----

* `$locator` - <<_locator>>.

.Wait for element with the specified id to stop moving
[source,gherkin]
----
When I wait until element located by `id(submitForm)` stops moving
----

=== Saves the attribute value of the context

Saves the attribute value of the context element into a variable.

[WARNING]
Step will throw an error if the context element is not set.

[source,gherkin]
----
When I save `$attributeName` attribute value of context element to $scopes variable `$variableName`
----

* `$attributeName` - The name of an element attribute.
* `$scopes` - xref:commons:variables.adoc#_scopes[The comma-separated set of the variables scopes].
* `$variableName` - The name of the variable to save the attribute value.

.Save the attribute value of the context element
[source,gherkin]
----
When I change context to element located by `id(username)`
When I save `innerText` attribute value of context element to SCENARIO variable `username`
----


=== Save the attribute value of the element

Saves the attribute value of the element located by locator into a variable.

[source,gherkin]
----
When I save `$attributeName` attribute value of element located by `$locator` to $scopes variable `$variableName`
----

_Deprecated syntax (will be removed in VIVIDUS 0.7.0)_:
[source,gherkin]
----
When I save `$attributeName` attribute value of element located `$locator` to $scopes variable `$variableName`
----

* `$attributeName` - The name of an element attribute.
* `$locator` - <<_locator>>.
* `$scopes` - xref:commons:variables.adoc#_scopes[The comma-separated set of the variables scopes].
* `$variableName` - The name of the variable to save the attribute value.

Save the attribute value of the element
[source,gherkin]
----
When I save `innerText` attribute value of element located by `id(username)` to SCENARIO variable `username`
----

include::plugins:partial$ui-elements-quantity-steps.adoc[]

include::plugins:partial$ui-size-and-coordinates-steps.adoc[]

=== Element existence during the time period

Validates the element located by the locator has existed for the period
specified by the duration.

The actions performed by the step:

* check the search context is set,
* search for the element to validate existence (this search may include wait for
  element appearance if it's configured),
* validate the element has presented for the period specified by the duration.

[source,gherkin]
----
Then element located by `$locator` exists for `$duration` duration
----

* `$locator` - The <<_locator>> to find an element.
* `$duration` - The period of time the element should have existed in {durations-format-link} format.

.The element should have existed for 5 second
[source,gherkin]
----
Then element located by `id(banner)` exists for `PT5S` duration
----

=== Verify elements order

Gets a collection of elements by locator and checks that they are sorted by
their text in the specified order. The collection should have at least one
element with not empty text, otherwise the step fails.

[source,gherkin]
----
Then elements located by `$locator` are sorted by text in $sortingOrder order
----

* `$locator` - <<_locator>>.
* `$sortingOrder`

[cols="2,2,2", options="header"]
|===

|Plain
|Readable
|Description

|ASCENDING
|ascending
|Verify that elements are sorted in https://www.computerhope.com/jargon/a/ascendin.htm[ascending] order

|DESCENDING
|descending
|Verify that elements are sorted in https://www.computerhope.com/jargon/d/descorde.htm[descending] order

|CASE_INSENSITIVE_ASCENDING
|case-insensitive ascending
|Verify that elements are sorted in https://www.yourdictionary.com/case-insensitive[case-insensitive] https://www.computerhope.com/jargon/a/ascendin.htm[ascending] order

|CASE_INSENSITIVE_DESCENDING
|case-insensitive descending
|Verify that elements are sorted in https://www.yourdictionary.com/case-insensitive[case-insensitive] https://www.computerhope.com/jargon/d/descorde.htm[descending] order

|===

.Check items are sorted
[source,gherkin]
----
Given I am on page with URL `https://grocery.by`
When I click on element located by `id(a-z)`
Then elements located by `xpath(//span[@id='item-to-purchase'])` are sorted by text in ascending order
----

=== Scan barcode

Scan a barcode and save its value to the variable with the specified name. Only the first founded barcode will be scanned.

Supported Code Formats

include::partial$code-formats.adoc[]

Actions performed at this step:

* Takes a viewport screenshot
* Scans a barcode from the screenshot and save its value to the variable

[source,gherkin]
----
When I scan barcode from screen and save result to $scopes variable `$variableName`
----

* `$scopes` - xref:commons:variables.adoc#_scopes[The comma-separated set of the variables scopes].
* `$variableName` - The name of the variable to save the value of the barcode.

.Scan a barcode
[source,gherkin]
----
When I scan barcode from screen and save result to scenario variable `qrCodeLink`
Then `${qrCodeLink}` is equal to `https://www.example.com`
----

include::plugins:partial$ui-elements-conditional-iteration-steps.adoc[]

:javascript-executor-link: https://www.selenium.dev/selenium/docs/api/java/org/openqa/selenium/JavascriptExecutor.html[JavascriptExecutor]

=== Execute JavaScript

Executes passed JavaScript code on the opened page via {javascript-executor-link}.

TIP: You can refer to search context element in JS code by using `arguments[0]` reference.

[source,gherkin]
----
When I execute javascript `$jsCode`
----
* `$jsCode` - The JavaScript code.

.Click on the link using JavaScript
[source,gherkin]
----
Given I am on page with URL `https://vividus-test-site-a92k.onrender.com`
When I execute javascript `document.querySelector('a').click()`
----

.Change color of context element using JavaScript
[source,gherkin]
----
Given I am on page with URL `https://vividus-test-site-a92k.onrender.com`
When I change context to element located by `tagName(body)`
When I execute javascript `arguments[0].style.color = 'red';`
----

=== Execute JavaScript with arguments

Executes JavaScript via {javascript-executor-link}. Step executes the script either without any arguments or with `String` or `Object` argument types.

[source,gherkin]
----
When I execute javascript `$script` with arguments:$arguments
----

* `$script` - The JavaScript code to execute.
* `$arguments` - The examples table with set of arguments and their type:
** [subs=+quotes]`*value*` -  The value of the argument.
** [subs=+quotes]`*type*` -  The type of the argument. Either `string` or `object`.

.Remove noisy assistant
[source,gherkin]
----
When I execute javascript `document.querySelector('#assistant').remove()` with arguments:
----

.Inject image
[source,gherkin]
----
When I execute javascript `sauce:inject-image` with arguments:
|value                                                                                       |type  |
|iVBORw0KGgoAAAANSUhEUgAAAAEAAAABCAQAAAC1HAwCAAAAC0lEQVR42mNk+A8AAQUBAScY42YAAAAASUVORK5CYII=|string|
----

.Throttle CPU
[source,gherkin]
----
When I execute javascript `sauce:throttleCPU` with arguments:
| value        | type   |
| {"rate" : 4} | object |
----

=== Execute JavaScript and save result.

https://www.selenium.dev/selenium/docs/api/java/org/openqa/selenium/JavascriptExecutor.html[Executes JavaScript] code and saves result into variable.

TIP: You can refer to search context element in JS code by using `arguments[0]` reference.

[source,gherkin]
----
When I execute javascript `$jsCode` and save result to $scopes variable `$variableName`
----
* `$jsCode` - Any JavaScript code. In order to save a result https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Statements/return[return] statement should be used.
* `$scopes` - xref:commons:variables.adoc#_scopes[The comma-separated set of the variables scopes].
* `$variableName` - The variable name to script execution result.

.Validate timings
[source,gherkin]
----
Given I am on page with URL `https://vividus-test-site-a92k.onrender.com/`
When I execute javascript `return JSON.stringify(window.performance.timing)` and save result to scenario variable `timings`
Then number of JSON elements from `${timings}` by JSON path `$.connectStart` is = 1
----

.Get size of context element using JavaScript
[source,gherkin]
----
Given I am on page with URL `https://vividus-test-site-a92k.onrender.com`
When I change context to element located by `tagName(body)`
When I execute javascript `return arguments[0].getBoundingClientRect();` and save result to scenario variable `clientRect`
----
