=== Taking screenshot steps
==== Take screenshot

Takes a screenshot and publish it to the report.

[source,gherkin]
----
When I take screenshot
----

==== Take screenshot and save it to the file

Takes a screenshot and saves it to the file at the specified path.

TIP: The full path to the file with the taken screenshot is posted to logs and report.

[source,gherkin]
----
When I take screenshot and save it to file at path `$screenshotFilePath`
----

_Deprecated syntax (will be removed in VIVIDUS 0.7.0)_:
[source,gherkin]
----
When I take screenshot and save it to folder `$screenshotFilePath`
----

* `$screenshotFilePath` - The path to the file to save the screenshot, the allowed values are:
+
** an absolute path to the file, e.g. `C:\Windows\screenshot.png`;
** a relative path (it is resolved from the current working directory, e.g. `screenshot.png`.

.Take a screenshot and save it to the file
[source,gherkin]
----
When I take screenshot and save it to file at path `${screenshot-directory}/start-page.png`
----

=== Wait for element appearance

Waits for appearance of the element by the locator.

WARNING: It's forbidden to use <<_visibility_types>> in the locator.

[source,gherkin]
----
When I wait until element located by `$locator` appears
----

* `$locator` - <<_locator>>.

.Wait for appearance of the element with the specified name
[source,gherkin]
----
When I wait until element located by `name(welcome-image)` appears
----


=== Wait for element disappearance

Waits for disappearance of the element by the locator.

NOTE: If the element doesn't exist on the page/context, the step will immediately complete successfully.
Checking the element on the page (if needed) should be done in a separate step (e.g. <<_wait_for_element_appearance>> or xref:plugin-html.adoc#_validate_elements[Validate elements]).

WARNING: It's forbidden to use <<_visibility_types>> in the locator.

[source,gherkin]
----
When I wait until element located by `$locator` disappears
----

* `$locator` - <<_locator>>.

.Wait for disappearance of the element with the specified name
[source,gherkin]
----
When I wait until element located by `name(welcome-image)` disappears
----


=== Wait for element with specified state using polling interval

Waits for an element with the specified state to be found using the specified timeout with polling interval.

[source,gherkin]
----
When I wait `$duration` with `$pollingDuration` polling until element located by `$locator` becomes $state
----

_Deprecated syntax (will be removed in VIVIDUS 0.6.0)_:
[source,gherkin]
----
When I wait `$duration` with `$pollingDuration` polling until element located `$locator` becomes $state
----

* `$duration` - Total duration to wait in the {iso-date-format-link} format.
* `$pollingDuration` - The duration to wait between search retries in the {iso-date-format-link} format.
* `$locator` - The <<_locator,locator>> of the element to wait for state change.
* `$state` - The element xref:parameters:state.adoc[state].

.Verify that the element become invisible up to 10 times
[source,gherkin]
----
When I wait `PT10S` with `PT1S` polling until element located by `id(element-to-hide)` becomes not visible
----


=== Wait for expected elements number

Waits for the expected number of elements located by locator.

TIP: In order to wait for invisible elements one rely on <<_visibility_types>>.

[source,gherkin]
----
When I wait until number of elements located by `$locator` is $comparisonRule $number
----

* `$locator` - <<_locator>>.
* `$comparisonRule` - xref:parameters:comparison-rule.adoc[The comparison rule].
* `$number` - The expected number of the elements.

.Wait for the visible elements
[source,gherkin]
----
When I wait until number of elements located by `tagName(img)` is equal to `5`
----

.Wait for the invisible elements
[source,gherkin]
----
When I wait until number of elements located by `tagName(img):1` is equal to `5`
----


=== Wait for element to stop moving

Waits for element with the specified locator to stop moving.

NOTE: An element is considered _moving_ when its coordinates (position) are changing. For example, an animated GIF is not a _moving_ element unless it changes position.

[source,gherkin]
----
When I wait until element located by `$locator` stops moving
----

* `$locator` - <<_locator>>.

.Wait for element with the specified id to stop moving
[source,gherkin]
----
When I wait until element located by `id(submitForm)` stops moving
----


=== Verify elements number

Verifies if the number of elements located by locator matches the desired number.

[source,gherkin]
----
Then number of elements found by `$locator` is $comparisonRule `$quantity`
----

* `$locator` - <<_locator>>.
* `$comparisonRule` - xref:parameters:comparison-rule.adoc[The comparison rule].
* `$quantity` - The expected number of the elements.

.Verify the number of elements
[source,gherkin]
----
Then number of elements found by `tagName(img)` is equal to `5`
----


=== Verify elements state

Verifies if the number of elements located by locator matches the number
condition and all of them are in the desired state.

[IMPORTANT]
If you describe number condition as equal to 5 in case if there are 10 elements by this locator and only 5 of them in the desired state. You will get two failed assertions.
The first one about number condition violation. The second one about state check failure.

[WARNING]
In case when <<_visibility_types>> are used and checked state are equal (For an example ':i' and 'NOT_VISIBLE') exception will be thrown. In such cases please use step: <<_verify_elements_number>>.
Contradictory visibility parameters (locator - ':i' and checked state - 'VISIBLE') are also not allowed.

[source,gherkin]
----
Then number of $state elements found by `$locator` is $comparisonRule `$quantity`
----

* `$state` - xref:parameters:state.adoc[State]
* `$locator` - <<_locator>>.
* `$comparisonRule` - xref:parameters:comparison-rule.adoc[The comparison rule].
* `$quantity` - The expected number of elements.

.Verify the number of elements in the state
[source,gherkin]
----
Then number of VISIBLE elements found by `tagName(img)` is = `1`
----


=== Save the text of the context

Saves the text of the context element into a variable.

[WARNING]
Step will throw an error if the context element is not set.

[source,gherkin]
----
When I save text of context element to $scopes variable `$variableName`
----

* `$scopes` - xref:commons:variables.adoc#_scopes[The comma-separated set of the variables scopes].
* `$variableName` - The name of the variable to save the text.

.Save the text of the context element
[source,gherkin]
----
When I change context to element located by `id(username)`
When I save text of context element to SCENARIO variable `username`
----


=== Saves the attribute value of the context

Saves the attribute value of the context element into a variable.

[WARNING]
Step will throw an error if the context element is not set.

[source,gherkin]
----
When I save `$attributeName` attribute value of context element to $scopes variable `$variableName`
----

* `$attributeName` - The name of an element attribute.
* `$scopes` - xref:commons:variables.adoc#_scopes[The comma-separated set of the variables scopes].
* `$variableName` - The name of the variable to save the attribute value.

.Save the attribute value of the context element
[source,gherkin]
----
When I change context to element located by `id(username)`
When I save `innerText` attribute value of context element to SCENARIO variable `username`
----


=== Save the attribute value of the element

Saves the attribute value of the element located by locator into a variable.

[source,gherkin]
----
When I save `$attributeName` attribute value of element located `$locator` to $scopes variable `$variableName`
----

* `$attributeName` - The name of an element attribute.
* `$locator` - <<_locator>>.
* `$scopes` - xref:commons:variables.adoc#_scopes[The comma-separated set of the variables scopes].
* `$variableName` - The name of the variable to save the attribute value.

Save the attribute value of the element
[source,gherkin]
----
When I save `innerText` attribute value of element located `By.id(username)` to SCENARIO variable `username`
----


=== Save number of elements

Saves number of elements located by locator into a variable.

[source,gherkin]
----
When I save number of elements located `$locator` to $scopes variable `$variableName`
----

* `$locator` - <<_locator>>.
* `$scopes` - xref:commons:variables.adoc#_scopes[The comma-separated set of the variables scopes].
* `$variableName` - The name of the variable to save the number of elements.

.Save number of elements
[source,gherkin]
----
When I save number of elements located `tagName(a)` to scenario variable `numberOfLinks`
Then `${numberOfLinks}` is equal to `1`
----


=== Change context

Changes the context to an element located by locator for limiting area of subsequent UI interactions.

[source,gherkin]
----
When I change context to element located by `$locator` in scope of current context
----

_Deprecated syntax (will be removed in VIVIDUS 0.7.0)_:
[source,gherkin]
----
When I change context to element located `$locator` in scope of current context
----

* `$locator` - <<_locator>>.

.Change context
[source,gherkin]
----
Then number of elements found by `By.xpath(html)` is equal to `1`
When I change context to element located by `xpath(//body)` in scope of current context
Then number of elements found by `By.xpath(html)` is equal to `0`
----

=== Reset and change context

Resets current context and changes the context to an element located by locator for limiting area of subsequent UI interactions.

[source,gherkin]
----
When I change context to element located by `$locator`
----

_Deprecated syntax (will be removed in VIVIDUS 0.7.0)_:
[source,gherkin]
----
When I change context to element located `$locator`
----

* `$locator` - <<_locator>>.

.Change context
[source,gherkin]
----
Then number of elements found by `By.xpath(html)` is equal to `1`
When I change context to element located by `xpath(//body)`
Then number of elements found by `By.xpath(html)` is equal to `0`
----


=== Reset context

Resets the context.

[source,gherkin]
----
When I reset context
----

.Reset context
[source,gherkin]
----
Then number of elements found by `By.xpath(html)` is equal to `1`
When I change context to element located by `xpath(//body)`
Then number of elements found by `By.xpath(html)` is equal to `0`
When I reset context
Then number of elements found by `By.xpath(html)` is equal to `1`
----


=== Element existence during the time period

Validates the element located by the locator has existed for the period
specified by the duration.

The actions performed by the step:

* check the search context is set,
* search for the element to validate existence (this search may include wait for
  element appearance if it's configured),
* validate the element has presented for the period specified by the duration.

[source,gherkin]
----
Then element located by `$locator` exists for `$duration` duration
----

* `$locator` - The <<_locator>> to find an element.
* `$duration` - The period of time the element should have existed in {durations-format-link} format.

.The element should have existed for 5 second
[source,gherkin]
----
Then element located by `id(banner)` exists for `PT5S` duration
----


=== Navigate back

Navigates back to the previous view.

[source,gherkin]
----
When I navigate back
----

.Navigate back
[source,gherkin]
----
Then number of elements found by `xpath(//*[@*='Welcome'])` is equal to `1`
When I navigate back
Then number of elements found by `xpath(//*[@*='Welcome'])` is equal to `0`
----


=== Verify elements order

Gets a collection of elements by locator and checks that they are sorted by
their text in the specified order. The collection should have more than 1
element with not empty text, otherwise the step fails.

[source,gherkin]
----
Then elements located by `$locator` are sorted by text in $sortingOrder order
----

* `$locator` - <<_locator>>.
* `$sortingOrder`

[cols="2,2,2", options="header"]
|===

|Plain
|Readable
|Description

|ASCENDING
|ascending
|Verify that elements are sorted in https://www.computerhope.com/jargon/a/ascendin.htm[ascending] order

|DESCENDING
|descending
|Verify that elements are sorted in https://www.computerhope.com/jargon/d/descorde.htm[descending] order

|CASE_INSENSITIVE_ASCENDING
|case-insensitive ascending
|Verify that elements are sorted in https://www.yourdictionary.com/case-insensitive[case-insensitive] https://www.computerhope.com/jargon/a/ascendin.htm[ascending] order

|CASE_INSENSITIVE_DESCENDING
|case-insensitive descending
|Verify that elements are sorted in https://www.yourdictionary.com/case-insensitive[case-insensitive] https://www.computerhope.com/jargon/d/descorde.htm[descending] order

|===

.Check items are sorted
[source,gherkin]
----
Given I am on page with URL `https://grocery.by`
When I click on element located by `id(a-z)`
Then elements located by `xpath(//span[@id='item-to-purchase'])` are sorted by text in ascending order
----

=== Scan barcode

Scan a barcode and save its value to the variable with the specified name. Only the first founded barcode will be scanned.

Supported Code Formats

include::partial$code-formats.adoc[]

Actions performed at this step:

* Takes a viewport screenshot
* Scans a barcode from the screenshot and save its value to the variable

[source,gherkin]
----
When I scan barcode from screen and save result to $scopes variable `$variableName`
----

* `$scopes` - xref:commons:variables.adoc#_scopes[The comma-separated set of the variables scopes].
* `$variableName` - The name of the variable to save the value of the barcode.

.Scan a barcode
[source,gherkin]
----
When I scan barcode from screen and save result to scenario variable `qrCodeLink`
Then `${qrCodeLink}` is equal to `https://www.example.com`
----

=== Perform steps while elements exist

Executes the steps while the found elements exist.

[IMPORTANT]
To avoid infinite loops the iterationLimit parameter is used. If iteration's limit reached the step will fail.

[source,gherkin]
----
When I find $comparisonRule `$number` elements `$locator` and while they exist do up to $iterationLimit iteration of$stepsToExecute
----

Alias:
[source,gherkin]
----
When I find $comparisonRule '$number' elements $locator and while they exist do up to $iterationLimit iteration of$stepsToExecute
----

* `$comparisonRule` - xref:parameters:comparison-rule.adoc[The comparison rule].
* `$number` - The number of elements to find.
* `$locator` - <<_locator>>.
* `$iterationLimit` - The maximum number of iterations to perform.
* `$stepsToExecute` - The xref:ROOT:glossary.adoc#_examplestable[ExamplesTable] with a single column containing the steps to execute.

.Disable menus
[source,gherkin]
----
When I find >= `0` elements `xpath(//*[@class='menu enabled'])` and while they exist do up to 10 iteration of
|step                                            |
|When I click on element located by `id(disable)`|
----

=== Execute JavaScript with arguments

Executes JavaScript via https://www.selenium.dev/selenium/docs/api/java/org/openqa/selenium/JavascriptExecutor.html[JavascriptExecutor]. Step executes the script either without any arguments or with `String` or `Object` argument types.

[source,gherkin]
----
When I execute javascript `$script` with arguments:$arguments
----

* `$script` - The JavaScript code to execute.
* `$arguments` - The examples table with set of arguments and their type:
** [subs=+quotes]`*value*` -  The value of the argument.
** [subs=+quotes]`*type*` -  The type of the argument. Either `string` or `object`.

.Remove noisy assistant
[source,gherkin]
----
When I execute javascript `document.querySelector('#assistant').remove()` with arguments:
----

.Inject image
[source,gherkin]
----
When I execute javascript `sauce:inject-image` with arguments:
|value                                                                                       |type  |
|iVBORw0KGgoAAAANSUhEUgAAAAEAAAABCAQAAAC1HAwCAAAAC0lEQVR42mNk+A8AAQUBAScY42YAAAAASUVORK5CYII=|string|
----

.Throttle CPU
[source,gherkin]
----
When I execute javascript `sauce:throttleCPU` with arguments:
|value                                                                                       |type  |
|{"rate" : 4}|object|
----

==== Execute JavaScript and save result.

https://www.selenium.dev/selenium/docs/api/java/org/openqa/selenium/JavascriptExecutor.html[Executes JavaScript] code and saves result into variable.

[source,gherkin]
----
When I execute javascript `$jsCode` and save result to $scopes variable `$variableName`
----
* `$jsCode` - Any JavaScript code. In order to save a result https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Statements/return[return] statement should be used.
* `$scopes` - xref:commons:variables.adoc#_scopes[The comma-separated set of the variables scopes].
* `$variableName` - The variable name to script execution result.

.Validate timings
[source,gherkin]
----
Given I am on page with URL `https://vividus-test-site-a92k.onrender.com/`
When I execute javascript `return JSON.stringify(window.performance.timing)` and save result to scenario variable `timings`
Then number of JSON elements from `${timings}` by JSON path `$.connectStart` is = 1
----
