=== Verify elements number

Verifies if the number of elements located by locator matches the desired number.

[source,gherkin]
----
Then number of elements found by `$locator` is $comparisonRule `$quantity`
----

* `$locator` - <<_locator>>.
* `$comparisonRule` - xref:parameters:comparison-rule.adoc[The comparison rule].
* `$quantity` - The expected number of the elements.

.Verify the number of elements
[source,gherkin]
----
Then number of elements found by `tagName(img)` is equal to `5`
----


=== Verify elements state

Verifies if the number of elements located by locator matches the number
condition and all of them are in the desired state.

[IMPORTANT]
If you describe number condition as equal to 5 in case if there are 10 elements by this locator and only 5 of them in the desired state. You will get two failed assertions.
The first one about number condition violation. The second one about state check failure.

[WARNING]
In case when locator's visibility and checked state are equal (For an example :i and NOT_VISIBLE) exception will be thrown. In such cases please use step: <<_verify_elements_number>>

[source,gherkin]
----
Then number of $state elements found by `$locator` is $comparisonRule `$quantity`
----

* `$state` - xref:parameters:state.adoc[State]
* `$locator` - <<_locator>>.
* `$comparisonRule` - xref:parameters:comparison-rule.adoc[The comparison rule].
* `$quantity` - The expected number of elements.

.Verify the number of elements in the state
[source,gherkin]
----
Then number of VISIBLE elements found by `tagName(img)` is = `1`
----


=== Wait for element appearance

Waits for appearance of an element by the locator.

[source,gherkin]
----
When I wait until element located `$locator` appears
----

* `$locator` - <<_locator>>.

.Wait for element appearance
[source,gherkin]
----
When I wait until element located `name(welcome-image)` appears
----


=== Wait for element disappearance

Waits for disappearance of an element by the locator.

[source,gherkin]
----
When I wait until element located `$locator` disappears
----

* `$locator` - <<_locator>>.

.Wait for element disappearance
[source,gherkin]
----
When I wait until element located `name(welcome-image)` disappears
----


=== Save the text of the context

Saves the text of the context element into a variable.

[WARNING]
Step will throw an error if the context element is not set.

[source,gherkin]
----
When I save text of context element to $scopes variable `$variableName`
----

* `$scopes` - xref:commons:variables.adoc#_scopes[The comma-separated set of the variables scopes].
* `$variableName` - The name of the variable to save the text.

.Save the text of the context element
[source,gherkin]
----
When I change context to element located `By.id(username)`
When I save text of context element to SCENARIO variable `username`
----


=== Saves the attribute value of the context

Saves the attribute value of the context element into a variable.

[WARNING]
Step will throw an error if the context element is not set.

[source,gherkin]
----
When I save `$attributeName` attribute value of context element to $scopes variable `$variableName`
----

* `$attributeName` - The name of an element attribute.
* `$scopes` - xref:commons:variables.adoc#_scopes[The comma-separated set of the variables scopes].
* `$variableName` - The name of the variable to save the attribute value.

.Save the attribute value of the context element
[source,gherkin]
----
When I change context to element located `By.id(username)`
When I save `innerText` attribute value of context element to SCENARIO variable `username`
----


=== Save the attribute value of the element

Saves the attribute value of the element located by locator into a variable.

[source,gherkin]
----
When I save `$attributeName` attribute value of element located `$locator` to $scopes variable `$variableName`
----

* `$attributeName` - The name of an element attribute.
* `$locator` - <<_locator>>.
* `$scopes` - xref:commons:variables.adoc#_scopes[The comma-separated set of the variables scopes].
* `$variableName` - The name of the variable to save the attribute value.

Save the attribute value of the element
[source,gherkin]
----
When I save `innerText` attribute value of element located `By.id(username)` to SCENARIO variable `username`
----


=== Save number of elements

Saves number of elements located by locator into a variable.

[source,gherkin]
----
When I save number of elements located `$locator` to $scopes variable `$variableName`
----

* `$locator` - <<_locator>>.
* `$scopes` - xref:commons:variables.adoc#_scopes[The comma-separated set of the variables scopes].
* `$variableName` - The name of the variable to save the number of elements.

.Save number of elements
[source,gherkin]
----
When I save number of elements located `tagName(a)` to scenario variable `numberOfLinks`
Then `${numberOfLinks}` is equal to `1`
----


=== Change context

Changes the context to an element located by locator for limiting area of subsequent UI interactions.

[source,gherkin]
----
When I change context to element located `$locator`
----

* `$locator` - <<_locator>>.

.Change context
[source,gherkin]
----
Then number of elements found by `By.xpath(html)` is equal to `1`
When I change context to element located `By.xpath(//body)`
Then number of elements found by `By.xpath(html)` is equal to `0`
----


=== Reset context

Resets the context.

[source,gherkin]
----
When I reset context
----

.Reset context
[source,gherkin]
----
Then number of elements found by `By.xpath(html)` is equal to `1`
When I change context to element located `By.xpath(//body)`
Then number of elements found by `By.xpath(html)` is equal to `0`
When I reset context
Then number of elements found by `By.xpath(html)` is equal to `1`
----


=== Element exists for duration

Verifies that an element located by locator exists for given duration.

[source,gherkin]
----
Then element located `$locator` exists for `$duration` duration
----

* `$locator` - <<_locator>>.
* `$duration` - The duration in {iso-date-format-link} format.

.Element should exists for 5 second
[source,gherkin]
----
Then element located `id(banner)` exists for `PT5S` duration
----


=== Navigate back

Navigates back to the previous view.

[source,gherkin]
----
When I navigate back
----

.Navigate back
[source,gherkin]
----
Then number of elements found by `xpath(//*[@*='Welcome'])` is equal to `1`
When I navigate back
Then number of elements found by `xpath(//*[@*='Welcome'])` is equal to `0`
----


=== Verify elements order

Gets a collection of elements by locator and checks that they are sorted by
their text in the specified order. The collection should have more than 1
element with not empty text, otherwise the step fails.

[source,gherkin]
----
Then elements located `$locator` are sorted by text in $sortingOrder order
----

* `$locator` - <<_locator>>.
* `$sortingOrder`

[cols="2,2,2", options="header"]
|===

|Plain
|Readable
|Description

|ASCENDING
|ascending
|Verify that elements are sorted in https://www.computerhope.com/jargon/a/ascendin.htm[ascending] order

|DESCENDING
|descending
|Verify that elements are sorted in https://www.computerhope.com/jargon/d/descorde.htm[descending] order

|CASE_INSENSITIVE_ASCENDING
|case-insensitive ascending
|Verify that elements are sorted in https://www.yourdictionary.com/case-insensitive[case-insensitive] https://www.computerhope.com/jargon/a/ascendin.htm[ascending] order

|CASE_INSENSITIVE_DESCENDING
|case-insensitive descending
|Verify that elements are sorted in https://www.yourdictionary.com/case-insensitive[case-insensitive] https://www.computerhope.com/jargon/d/descorde.htm[descending] order

|===

.Check items are sorted
[source,gherkin]
----
Given I am on a page with the URL 'https://grocery.by'
When I click on element located `By.id(a-z)`
Then elements located `By.xpath(//span[@id='item-to-purchase'])` are sorted by text in ascending order
----


=== Take a screenshot

Takes a screenshot and saves it to the default folder defined by the property `ui.screenshots.directory`.

TIP: The full path to the screenshot is posted to the logs and the report.

[source,gherkin]
----
When I take screenshot
----


=== Take a screenshot and save it to the folder

Takes a screenshot and saves it to the default folder defined by user.

TIP: The full path to a screenshot will be posted to logs and allure

[source,gherkin]
----
When I take screenshot and save it to folder `$path`
----

* `$path` - The absolute or relative path to the folder to save taken screenshot.

.Take a screenshot to a path
[source,gherkin]
----
When I take screenshot to path `${screenshot-directory}/#{generate(Ancient.god)}.png`
----

=== Scan QR code

Scan a QR code and save its value to the variable with the specified variable

Supported Code Formats

[cols="2,2,2", options="header"]
|===

|1D product
|1D industrial
|2D

a|
* UPC-A
* UPC-E
* EAN-8
* EAN-13
* UPC/EAN Extension 2/5
* RSS-14
* RSS-Expanded
a|
* Code 39
* Code 93
* Code 128
* Codabar
* ITF
a|
* QR Code
* Data Matrix
* Aztec
* PDF 417
* MaxiCode

|===

Actions performed at this step:

* Takes a viewport screenshot
* Scan a QR code and save its value to the variable

[source,gherkin]
----
When I scan a QR Code from screen and save result to $scopes variable `$variableName`
----

* `$scopes` - xref:commons:variables.adoc#_scopes[The comma-separated set of the variables scopes].
* `$variableName` - The name of the variable to save the number of elements.

.Scan a QR Code
[source,gherkin]
----
When I scan a QR Code from screen and save result to scenario variable `qrCodeLink`
Then `${qrCodeLink}` is equal to `https://www.example.com`
----

=== Perform steps while elements exist

Executes the steps while the found elements exist.

[IMPORTANT]
To avoid infinite loops the iterationLimit parameter is used. If iteration's limit reached the step will fail.

[source,gherkin]
----
When I find $comparisonRule `$number` elements `$locator` and while they exist do up to $iterationLimit iteration of$stepsToExecute
----

Alias:
[source,gherkin]
----
When I find $comparisonRule '$number' elements $locator and while they exist do up to $iterationLimit iteration of$stepsToExecute
----

* `$comparisonRule` - xref:parameters:comparison-rule.adoc[The comparison rule].
* `$number` - The number of elements to find.
* `$locator` - <<_locator>>.
* `$iterationLimit` - The maximum number of iterations to perform.
* `$stepsToExecute` - The `ExamplesTable` with a single column containing the steps to execute.

.Disable menus
[source,gherkin]
----
When I find >= `0` elements `xpath(//*[@class='menu enabled'])` and while they exist do up to 10 iteration of
|step                                         |
|When I click on element located `id(disable)`|
----
