:onbeforeunload-event: https://www.w3schools.com/jsref/event_onbeforeunload.asp[onbeforeunload]
:popup-alert: https://www.w3schools.com/js/js_popup.asp
:close-spec: https://w3c.github.io/webdriver/webdriver-spec.html#close-window[close]

=== Page steps

==== Open main application page

Loading the page which was associated with the main application page.

Main page can be set by the property `web-application.main-page-url` in the property file.

[source,gherkin]
----
Given I am on main application page
----

.Open page defined in the `web-application.main-page-url` variable
[source,gherkin]
----
Given I am on main application page
----

==== Open a page with defined URL

Loading the page with a given absolute URL, e.g. _https://example.com/_.

[source,gherkin]
----
Given I am on page with URL `$pageURL`
----

.Open 'https://docs.vividus.dev/' page
[source,gherkin]
----
Given I am on page with URL `https://docs.vividus.dev/`
----

==== Open page with relative URL

Navigates the browser to the specific path in the current host defined in the _relative URL_ step parameter.

A relative URL can point to a file within a web site (like `about.html` or `/products`).

- If the parameter starts with '/' char, navigation will be performed from the root of the host, see examples below.
- If the parameter starts without '/' char or with './', navigation will be performed from the current path directory.

.Examples
|===
|Current page |Relative URL parameter|Opened page

|https://mysite.com
|about.html
|https://mysite.com/about.html

|https://mysite.com
|/products/new
|https://mysite.com/products/new

|https://mysite.com/path/foo
|stats
|https://mysite.com/path/foo/stats

|https://mysite.com/path/foo
|./docs/info.html
|https://mysite.com/path/foo/docs/info.html

|https://mysite.com/path/foo
|/documents
|https://mysite.com/documents
|===

[source,gherkin]
----
When I go to relative URL `$relativeURL`
----

* `relativeURL` - A string value of the relative URL.

. Open main application page and then navigate to '/products/new' page on the application host
[source,gherkin]
----
Given I am on main application page
When I go to relative URL `/products/new`
----

==== Refresh the page

Refreshes the page: the step does the same as the reload button in the browser.

[source,gherkin]
----
When I refresh page
----

_Deprecated syntax (will be removed in VIVIDUS 0.6.0)_:
[source,gherkin]
----
When I refresh the page
----

==== Validate the page title

Checks the page title matches to the text according to the provided string validation rule

[source,gherkin]
----
Then page title $comparisonRule `$text`
----

_Deprecated syntax (will be removed in VIVIDUS 0.6.0)_:
[source,gherkin]
----
Then the page title $comparisonRule '$text'
----

* `$comparisonRule` - string validation rule. One of:
** `is equal to` - title should be equal to `text`
** `contains` - title should contain `text`
** `does not contain` - title should not contain `text`
* `text` - the text of the title to compare

.Validate 'https://docs.vividus.dev/' page title
[source,gherkin]
----
Then page title is equal to `What is VIVIDUS :: VIVIDUS`
----

.Validate the part of 'https://docs.vividus.dev/' page title
[source,gherkin]
----
Then page title contains `VIVIDUS`
----

=== Click on element

Clicks on the element found by the specified locator.

The atomic actions performed are:

* find the element by the locator;
* click on the element if it is found, otherwise the whole step is failed and its execution stops;
* the first two actions are retried once if the field becomes stale during actions execution in other
words if https://www.selenium.dev/exceptions/#stale_element_reference[StaleElementReferenceException]
is occurred at any atomic action.

[NOTE]
====
If element by the specified locator is not clickable (overlapped by another element, problems with page/context loading or the element is disabled) the step will fail with corresponding error:
[source]
----
Could not click on the element: org.openqa.selenium.ElementClickInterceptedException: element click intercepted:
Element <a href="#where-to-buy" data-tab-name="..." role="button">Where to Buy</a> is not clickable at point (1619, 275).
Other element would receive the click: <div class="content">...</div>
----
====

[source,gherkin]
----
When I click on element located by `$locator`
----

* `$locator` - The <<_locator,locator>> used to find element.

.Click on element
[source,gherkin]
----
When I click on element located by `name(Submit)`
----

=== Scrolling steps
==== Scroll context

Scrolls the context to an edge

[source,gherkin]
----
When I scroll context to $scrollDirection edge
----
* `$scrollDirection` - the direction of the scroll. One of:
** `LEFT` - start of a page/element horizontally
** `RIGHT` - end of a page/element horizontally
** `TOP` - start of a page/element vertically
** `BOTTOM` - end of a page/element vertically

[TIP]
If the context is not set, the whole page will be scrolled

.Scroll login to a bottom
[source,gherkin]
----
When I change context to element located by `id(login)`
When I scroll context to BOTTOM edge
----

==== Scroll element into view

Scrolls an element into the view.

[source,gherkin]
----
When I scroll element located by `$locator` into view
----
* `$locator` - The <<_locator,locator>> used to find element.

_Deprecated syntax (will be removed in VIVIDUS 0.7.0)_:
[source,gherkin]
----
When I scroll element located `$locator` into view
----
* `$locator` - The <<_locator,locator>> used to find element.

.Scroll button into view
[source,gherkin]
----
When I scroll element located by `id(way_down_button)` into view
----

==== Validate the page is scrolled to element

Checks if the page is scrolled to the specific element

[source,gherkin]
----
Then page is scrolled to element located by `$locator`
----
* `$locator` - The <<_locator,locator>> used to find element.

.Validate Contact link is scrolled into view
[source,gherkin]
----
Then page is scrolled to element located by `xpath(//a[text()="Contact"])`
----

=== Text validation steps

==== Validate the text exists

Validates that the text is presented in the current context. Expected text is *case sensitive*.

The context can be set by the <<_change_context,corresponding steps>>. If no context is set, the text will be searched on the whole page.

[source,gherkin]
----
Then text `$text` exists
----
* `$text` - Expected text.

.Check the text 'Contract Us' is presented on the page
[source,gherkin]
----
Given I am on page with URL `https://docs.vividus.dev/`
Then text `Contract Us` exists
----

==== Validate the text does not exists

Validates that the text is not presented in the current context.

The context can be set by the <<_change_context,corresponding steps>>. If no context is set, the text will be searched on the whole page.

[source,gherkin]
----
Then text `$text` does not exist
----
* `$text` - Text that should not exist.

.Check the text 'Deprecated' is not presented in the element
[source,gherkin]
----
When I change context to element located by `id(code)`
Then text `Deprecated` does not exist
----


=== Tab steps
==== Open a new tab

Opens a new browser tab and switches the focus for future commands to this tab.

[source,gherkin]
----
When I open new tab
----

.Open page in a new tab
[source,gherkin]
----
When I open new tab
Given I am on page with URL `https://docs.vividus.dev/`
----

==== Open URL in a new tab

Opens a new tab, switches the focus to this tab and loads the given URL.

[IMPORTANT]
====
The key difference of this step from the <<_open_a_new_tab,previous one opening a new tab>>
is that this step _inherits_ the state of the previous page, i.e.:

* new tab will have acces to the <<_web_storage_steps,session storage>> of the previous tab,
* it will be possible <<_close_current_tab_with_possibility_to_handle_alert,to handle alerts appearing on tab closing>>.
====

[source,gherkin]
----
When I open URL `$URL` in new tab
----

_Deprecated syntax (will be removed in VIVIDUS 0.7.0)_:
[source,gherkin]
----
When I open URL `$URL` in new window
----
* `$URL` - The URL to open.

.Open docs in a new tab
[source,gherkin]
----
When I open URL `https://docs.vividus.dev` in new tab
----

==== Close current tab

Closes the current tab and switches to the previous tab.

[source,gherkin]
----
When I close current tab
----

_Deprecated syntax (will be removed in VIVIDUS 0.7.0)_:
[source,gherkin]
----
When I close the current window
----

IMPORTANT: Handling {popup-alert}[alerts] displayed with '{onbeforeunload-event}' events is not implied by the WebDriver specification to {close-spec} window. For handling alerts use step based on JavaScript '<<_close_current_tab_with_possibility_to_handle_alert>>'.

NOTE: This step can only be applied to a session with multiple tabs open.

.Open URL in new tab, close it and switch to the previous page
[source,gherkin]
----
Given I am on page with URL `https://example.com/`
When I open URL `https://example.com/contact-us` in new tab
When I close current tab
----

==== Close current tab with possibility to handle alert

Trying to close the current tab with '{onbeforeunload-event}' events handling.

* If an {popup-alert}[alert] window is opened via '{onbeforeunload-event}' event, it must be checked and handled in the subsequent steps.
* If an {popup-alert}[alert] window is not opened, the step closes the current window and switches to the previous window.

[source,gherkin]
----
When I attempt to close current tab with possibility to handle alert
----

_Deprecated syntax (will be removed in VIVIDUS 0.7.0)_:
[source,gherkin]
----
When I attempt to close current window with possibility to handle alert
----

IMPORTANT: This step can only be used if the current tab was opened via the step <<_open_url_in_a_new_tab,``When I open URL \`$pageUrl` in new tab``>>.

NOTE: If you confirm window close in {popup-alert}[alert], the tab will be closed, and you will need to switch to current tab using the following step: `When I switch to tab with title that $stringComparisonRule `$windowName``.

.Checking for an alert when trying to close a window with form
[source,gherkin]
----
Given I am on page with URL `https://example.com/`
When I open URL `https://example.com/form` in new tab
When I click on element located by `xpath(//*[@id='form-edit'])`
When I execute sequence of actions:
|type      |argument    |
|ENTER_TEXT|changed text|
When I attempt to close current tab with possibility to handle alert
Then an alert is present
When I accept alert with message which matches `.*`
----

=== Execute sequence of actions

Executes the sequence of web actions

[source,gherkin]
----
When I execute sequence of actions: $actions
----
* `$actions` - table of actions to execute
+
.Possible actions
[cols="1,5,3", options="header"]
|===

|`type`
|`argument`
|Argument example

|DOUBLE_CLICK
|Element locator or empty.
|By.linkUrl(http://httpbin.org)

|CLICK_AND_HOLD
|Element locator or empty.
|By.linkText(Click me)

|MOVE_BY_OFFSET
|Point.
|(10, 15) where *x* is 10 and *y* is 15

|RELEASE
|Element locator or empty.
|By.tagName(div)

|ENTER_TEXT
|Text to type.
|Minsk City

|CLICK
|Element locator or empty.
|By.caseSensitiveText(Done)

|PRESS_KEYS
|Comma-separated https://selenium.dev/selenium/docs/api/java/org/openqa/selenium/Keys.html[keys] to press and release.
|BACK_SPACE

|KEY_DOWN
|Comma-separated https://selenium.dev/selenium/docs/api/java/org/openqa/selenium/Keys.html[keys] to press one by one.
|CONTROL,SHIFT,ALT

|KEY_UP
|Comma-separated https://selenium.dev/selenium/docs/api/java/org/openqa/selenium/Keys.html[keys] to release one by one.
|CONTROL,SHIFT,ALT

|MOVE_TO
|Element locator.
|By.id(username)

|===

[TIP]
====
Windows/Unix and macOS platforms have different keyboards. For example, kbd:[Ctrl+C] combination is used to copy text
on Windows and Unix, but kbd:[⌘ Command+C] should be used on macOS with default preferences.

In order to close this gap VIVIDUS offers unique key `OS_INDEPENDENT_CONTROL`: it is mapped to
https://en.wikipedia.org/wiki/Control_key[`CONTROL`] key on Windows/Unix and to
https://en.wikipedia.org/wiki/Command_key[`COMMAND`] key on macOS. Using this key it is possible to make tests fully
platform independent.
====

.Execute various web-actions
[source,gherkin]
----
When I execute sequence of actions:
|type          |argument                                |
|DOUBLE_CLICK  |By.fieldText(Hello World)               |
|DOUBLE_CLICK  |                                        |
|CLICK_AND_HOLD|By.xpath(//signature-pad-control/canvas)|
|CLICK_AND_HOLD|                                        |
|MOVE_BY_OFFSET|(-300, 0)                               |
|RELEASE       |By.xpath(//signature-pad-control/canvas)|
|RELEASE       |                                        |
|ENTER_TEXT    |Text                                    |
|CLICK         |By.placeholder(Enter your password)     |
|CLICK         |                                        |
|PRESS_KEYS    |BACK_SPACE                              |
|KEY_DOWN      |CONTROL,SHIFT                           |
|KEY_UP        |CONTROL,SHIFT                           |
|MOVE_TO       |By.id(name)                             |
----

[TIP]
====
This step can be used to perform clipboard interactions.

.Select all text in the focused field and copy it to the clipboard on Windows
[source,gherkin]
----
When I execute sequence of actions:
|type      |argument  |
|KEY_DOWN  |CONTROL, a|
|KEY_UP    |a, CONTROL|
|KEY_DOWN  |CONTROL, c|
|KEY_UP    |c, CONTROL|
----

.Paste text from the clipboard to the focused field on MacOS
[source,gherkin]
----
When I execute sequence of actions:
|type      |argument  |
|KEY_DOWN  |COMMAND, v|
|KEY_UP    |v, COMMAND|
----

.Select all text in the focused field and copy it to the clipboard on any OS
[source,gherkin]
----
When I execute sequence of actions:
|type      |argument                 |
|KEY_DOWN  |OS_INDEPENDENT_CONTROL, a|
|KEY_UP    |a, OS_INDEPENDENT_CONTROL|
|KEY_DOWN  |OS_INDEPENDENT_CONTROL, c|
|KEY_UP    |c, OS_INDEPENDENT_CONTROL|
----
====

=== Browser logs steps

This set of steps allows to validate the https://developer.mozilla.org/en-US/docs/Web/API/console[browser console logging messages].

:log-levels: List of the comma-separated messages levels. The supported levels are: ERRORS, WARNINGS, INFOS.

[TIP]
=====
In order to configure availability of the INFO level messages use following properties:
[cols="1,2"]
|===

|Browser
|Property to enable INFO logs

|Google Chrome
|`selenium.capabilities.goog\:loggingPrefs.browser=INFO`

|Microsoft Edge Chromium
|`selenium.capabilities.ms\:loggingPrefs.browser=INFO`
|===
=====

==== Validate log entries absence

Validates the absence of log entries of the desired level in the browser console.

[source,gherkin]
----
Then there are no browser console $logLevels
----
* `$logLevels` - {log-levels}

.Validate absence of JS errors
[source,gherkin]
----
Given I am on page with URL `https://vividus-test-site-a92k.onrender.com/`
Then there are no browser console ERRORS
----

==== Validate specific log entries absence

Validates the absence of specific log entries of the desired level in the browser console.

[source,gherkin]
----
Then there are no browser console $logLevels by regex `$regex`
----

_Deprecated syntax (will be removed in VIVIDUS 0.7.0)_:
[source,gherkin]
----
Then there are no browser console $logLevels by regex '$regex'
----

* `$logLevels` - {log-levels}
* `$regex` - The regular expression to match log entry messages.

.Validate absence of JS error referencing user
[source,gherkin]
----
Given I am on page with URL `https://vividus-test-site-a92k.onrender.com/`
Then there are no browser console ERRORS by regex `.*user.*`
----

==== Validate specific log entries presence

Validates the presence of specific log entries of the desired level in the browser console.

[source,gherkin]
----
Then there are browser console $logLevels by regex `$regex`
----
* `$logLevels` - {log-levels}
* `$regex` - The regular expression to match log entry messages.

.Validate presence of JS errors referencing user
[source,gherkin]
----
Given I am on page with URL `https://vividus-test-site-a92k.onrender.com/`
Then there are browser console ERRORS by regex `.*user.*`
----

==== Wait for console log entries and save them

Waits for the appearance of the console log entries with the expected level and which match regular expression and saves all the entries (including awaited ones) of the expected level gathered during the wait to the scoped variable.

NOTE: Wait uses generic UI timeouts specified by the properties `ui.wait.timeout` and `ui.wait.polling-period`. See <<_properties>> section for more details.

[source,gherkin]
----
When I wait until browser console $logEntries by regex `$regex` appear and save all entries into $scopes variable `$variableName`
----
* `$logLevels` - {log-levels}
* `$regex` - The regular expression to match log entry messages.
* `$scopes` - xref:commons:variables.adoc#_scopes[The comma-separated set of the variables scopes].
* `$variableName` - The name of the variable to save the value of the barcode.

.Wait for application readiness
----
Given I am on page with URL `https://vividus-test-site-a92k.onrender.com/`
When I wait until browser console infos by regex `.*Application ready.*` appear and save all entries into scenario variable `logs`
Then `${logs}` matches `.*Application ready in \d+ seconds.*`
----

=== Perform steps for each found element

Executes the steps against all elements found by locator. After a required number of elements is found,
search context switches in order for each found element and performs all steps on it.

[IMPORTANT]
If comparison rule mismatch steps will not be performed even if elements are found.

[source,gherkin]
----
When I find $comparisonRule `$number` elements by `$locator` and for each element do$stepsToExecute
----

Alias:
[source,gherkin]
----
When I find $comparisonRule '$number' elements by $locator and for each element do$stepsToExecute
----

* `$comparisonRule` - xref:parameters:comparison-rule.adoc[The comparison rule].
* `$number` - The number of elements to find.
* `$locator` - The <<_locator,locator>> used to find elements.
* `$stepsToExecute` - The xref:ROOT:glossary.adoc#_examplestable[ExamplesTable] with a single column containing the steps to execute.

.Script type check
[source,gherkin]
----
When I find = `5` elements by `By.xpath(//script):a` and for each element do
|step                                                                                      |
|When I set 'type' attribute value of the context element to the 'scenario' variable 'type'|
|Then `${type}` is equal to `text/javascript`                                              |
----

=== Context steps
==== Switch to the default context of page

Switches context to the root https://developer.mozilla.org/en-US/docs/Web/HTML/Element/html[<html>] element of the current page.

[source,gherkin]
----
When I switch back to the page
----

.Switch to user context and back to the default context of page
----
Given I am on page with URL `https://vividus-test-site-a92k.onrender.com/elementState.html`
When I change context to element located by `id(button-hide)`
Then text `Element to hide` does not exist
When I switch back to the page
Then text `Element to hide` exists
----

==== Switch context to a frame

Switches to https://developer.mozilla.org/en-US/docs/Web/HTML/Element/iframe[<iframe>] or https://developer.mozilla.org/en-US/docs/Web/HTML/Element/frame[<frame>] element using one of the supported locators.

[source,gherkin]
----
When I switch to frame located `$locator`
----
* `$locator` - <<_locator>>.

.Switch to frame
----
Given I am on page with URL `https://vividus-test-site-a92k.onrender.com/nestedFrames.html`
Then text `Modal Frame Example` does not exist
When I switch to frame located `id(parent)`
Then text `Modal Frame Example` exists
----

==== Switch context to new tab

Switch the focus of future browser commands to new tab.

This step gets the identifier of the currently active tab and then switches focus to the first available tab with a different identifier. For example, if tabs #1, #2, #3 are open and tab #2 is active, this step will switch focus to tab #3.

[NOTE]
A new tab should already be open for this step to function. After executing this step, the new tab will become the active tab.

[source,gherkin]
----
When I switch to new tab
----
_Deprecated syntax (will be removed in VIVIDUS 0.7.0)_:
[source,gherkin]
----
When I switch to a new window
----

.Open the new tab by link and switch to it
----
Given I am on page with URL `https://the-internet.herokuapp.com/windows`
When I click on element located by `linkUrlPart(/windows/new)`
Then text `New Window` does not exist
When I switch to new tab
Then text `New Window` exists
----

==== Switch context to new tab with specified title

Switch the focus of future browser commands to new tab with specified title.

[source,gherkin]
----
When I switch to tab with title that $stringComparisonRule `$tabName`
----
_Deprecated syntax (will be removed in VIVIDUS 0.7.0)_:
[source,gherkin]
----
When I switch to window with title that $stringComparisonRule `$windowName`
----
* `$stringComparisonRule` - xref:parameters:string-comparison-rule.adoc[String comparison rule].
* `$tabName` - The expected tab title.

.Open the new tab by link and switch to it using regex title pattern
----
Given I am on page with URL `https://the-internet.herokuapp.com/windows`
When I click on element located by `linkUrlPart(/windows/new)`
Then text `New Window` does not exist
When I switch to tab with title that matches `.*[wW]indow.*`
Then text `New Window` exists
----
