== Profiles

The xref:configuration:tests-configuration.adoc#_profiles[profiles] allow to choose and/or parameterize browser that tests run on.

=== Desktop

The following profiles running desktop browsers are available out of the box:

- `web/desktop/chrome`
- `web/desktop/edge`
- `web/desktop/firefox`
- `web/desktop/iexplore`
+
[WARNING]
====
Since Internet Explorer 11 https://blogs.windows.com/windowsexperience/2022/06/15/internet-explorer-11-has-retired-and-is-officially-out-of-support-what-you-need-to-know/[has retired and is officially out of support],
this profile is deprecated and will be removed in VIVIDUS 0.8.0.
====

- `web/desktop/opera`
+
NOTE: In order to run tests in Opera browser locally, it is required
to configure <<_configure_browser_path,browser path>>.

- `web/desktop/safari`


=== Headless

https://en.wikipedia.org/wiki/Headless_browser[Headless mode] is a functionality that allows the execution of a full
version of the browser while controlling it programmatically. It can be used without dedicated graphics or display,
meaning that it runs without its “head”, the Graphical User Interface (GUI). The following profiles running browsers in
headless mode are available:

- `web/headless/chrome`
+
[cols="2,1,1,2", options="header"]
|===
|Profile-specific properties
|Format
|Default value
|Description

|`web.headless.chrome.window-size`
|`width,height`
|`800,600`
a|Sets the initial window size.

NOTE: This property is ignored when custom CLI arguments are set using `web.driver.chrome.command-line-arguments` property.

|===

- `web/headless/firefox`
- `web/headless/edge`


==== Mobile emulation

. Built-in devices
+
Chrome allows to emulate view on mobile devices using https://developer.chrome.com/docs/devtools/device-mode/[Device mode]. Such feature is reflected in `mobile_emulation` subdirectory in Profiles. Use device-name property to mention target device:
+
[source, properties]
----
web.driver.chrome.mobile-emulation.device-name=DEVICE_NAME
----
Available for emulation devices you can find in the https://developer.chrome.com/docs/devtools/device-mode/#device[Dimensions list] in chrome.

. Custom devices
+
In case you need to use https://developer.chrome.com/docs/devtools/device-mode/#responsive[Responsive Viewport Mode] and set up your own device, update the screen resolution in the following properties:
+
[source, properties]
----
web.driver.chrome.mobile-emulation.width=1440
web.driver.chrome.mobile-emulation.height=900
----


=== Docker
This profile should be used in conjuction with other browser profile.

.Use Chrome browser running in a docker container
[source,properties]
----
configuraiton.profiles=web/docker,web/desktop/chrome
----

WARNING: Default Selenium grid URL is set to `selenium.grid.url=http://localhost:4444/wd/hub`. Don't forget to modify it if your grid is running in a different location.

=== Mobile web

The following profiles running mobile browsers are available out of the box:

- `web/phone/android`
- `web/phone/iphone`
- `web/tablet/ipad`
