:onbeforeunload-event: https://www.w3schools.com/jsref/event_onbeforeunload.asp[onbeforeunload]
:popup-alert: https://www.w3schools.com/js/js_popup.asp
:close-spec: https://w3c.github.io/webdriver/webdriver-spec.html#close-window[close]

include::plugins:partial$common-web-app-steps.adoc[]
include::plugins:partial$ui-context-management-steps.adoc[]

=== Mouse Actions
==== Click on the element

Clicks on the element found by the given locator.

The atomic actions performed are:

* find the element by the given locator;
* click on the element if it is found, otherwise the whole step is failed and its execution stops;
* the first two actions are retried once if the field becomes stale during actions execution in other
words if https://www.selenium.dev/exceptions/#stale_element_reference[StaleElementReferenceException]
is occurred at any atomic action.

[NOTE]
====
If the element by the given locator is not clickable (overlapped by another element, page or current context
is not loaded properly or the element is disabled) the step will fail with corresponding error:
[source]
----
Could not click on the element: org.openqa.selenium.ElementClickInterceptedException: element click intercepted:
Element <a href="#where-to-buy" data-tab-name="..." role="button">Where to Buy</a> is not clickable at point (1619, 275).
Other element would receive the click: <div class="content">...</div>
----
In this case extra steps might be needed to ensure element actionability, like, scrolling to the element, adding waits, etc.
====

[source,gherkin]
----
When I click on element located by `$locator`
----

* `$locator` - The <<_locator,locator>> used to find the element to click.

.Click on element with name `Submit`
[source,gherkin]
----
When I click on element located by `name(Submit)`
----

==== Validate page is not refreshed after click on element

Clicks on the element and checks that the page has not been refreshed after the click.

[source,gherkin]
----
When I click on element located by `$locator` then page does not refresh
----

_Deprecated syntax (will be removed in VIVIDUS 0.7.0)_:
[source,gherkin]
----
When I click on an element '$locator' then the page does not refresh
----

* `$locator` - The <<_locator,locator>> used to find the element to click.

.Click on the element with `id` attribute having value `send` and validate page is not refreshed after the action
[source,gherkin]
----
When I click on element located by `id(send)` then page does not refresh
----

include::plugins:partial$common-web-app-mouse-steps.adoc[]

include::plugins:partial$common-web-app-field-steps.adoc[]
==== Clear field

Finds the field by the given locator and clears it if it's found. The step does not trigger any keyboard or mouse
events on the field.

[source,gherkin]
----
When I clear field located by `$locator`
----
* `$locator` - The <<_locator,locator>> used to find the field to clear.

.Clear the field with attribute `id` having value `email`
[source,gherkin]
----
When I clear field located by `id(email)`
----

==== Clear field using keyboard

Finds the field by the given locator and clears it using keyboard if the field is found. The step simulates user action
by pressing buttons kbd:[Ctrl+A] or kbd:[Cmd+A] and then kbd:[Backspace] that allows to trigger keyboard events on
the field.

[source,gherkin]
----
When I clear field located by `$locator` using keyboard
----
* `$locator` - The <<_locator,locator>> used to find a field.

.Clear the field with attribute `id` having value `email` using keyboard
[source,gherkin]
----
When I clear field located by `id(email)` using keyboard
----

include::plugins:partial$ui-scrolling-steps.adoc[]

include::plugins:partial$ui-elements-validation-steps.adoc[]

include::plugins:partial$ui-selenium-text-content-steps.adoc[]

include::plugins:partial$common-web-app-text-steps.adoc[]

include::plugins:partial$common-web-app-wait-steps.adoc[]

=== Tab steps
==== Open a new tab

Opens a new browser tab and switches the focus for future commands to this tab.

[source,gherkin]
----
When I open new tab
----

.Open page in a new tab
[source,gherkin]
----
When I open new tab
Given I am on page with URL `https://docs.vividus.dev/`
----

==== Open URL in a new tab

Opens a new tab, switches the focus to this tab and loads the given URL.

[IMPORTANT]
====
The key difference of this step from the <<_open_a_new_tab,previous one opening a new tab>>
is that this step _inherits_ the state of the previous page, i.e.:

* new tab will have acces to the <<_web_storage_steps,session storage>> of the previous tab,
* it will be possible <<_close_current_tab_with_possibility_to_handle_alert,to handle alerts appearing on tab closing>>.
====

[source,gherkin]
----
When I open URL `$URL` in new tab
----

_Deprecated syntax (will be removed in VIVIDUS 0.7.0)_:
[source,gherkin]
----
When I open URL `$URL` in new window
----
* `$URL` - The URL to open.

.Open docs in a new tab
[source,gherkin]
----
When I open URL `https://docs.vividus.dev` in new tab
----

==== Close current tab

Closes the current tab and switches to the previous tab.

[source,gherkin]
----
When I close current tab
----

_Deprecated syntax (will be removed in VIVIDUS 0.7.0)_:
[source,gherkin]
----
When I close the current window
----

IMPORTANT: Handling {popup-alert}[alerts] displayed with '{onbeforeunload-event}' events is not implied by the WebDriver specification to {close-spec} window. For handling alerts use step based on JavaScript '<<_close_current_tab_with_possibility_to_handle_alert>>'.

NOTE: This step can only be applied to a session with multiple tabs open.

.Open URL in new tab, close it and switch to the previous page
[source,gherkin]
----
Given I am on page with URL `https://example.com/`
When I open URL `https://example.com/contact-us` in new tab
When I close current tab
----

==== Close current tab with possibility to handle alert

Trying to close the current tab with '{onbeforeunload-event}' events handling.

* If an {popup-alert}[alert] window is opened via '{onbeforeunload-event}' event, it must be checked and handled in the subsequent steps.
* If an {popup-alert}[alert] window is not opened, the step closes the current window and switches to the previous window.

[source,gherkin]
----
When I attempt to close current tab with possibility to handle alert
----

_Deprecated syntax (will be removed in VIVIDUS 0.7.0)_:
[source,gherkin]
----
When I attempt to close current window with possibility to handle alert
----

IMPORTANT: This step can only be used if the current tab was opened via the step <<_open_url_in_a_new_tab,``When I open URL \`$pageUrl` in new tab``>>.

NOTE: If you confirm window close in {popup-alert}[alert], the tab will be closed, and you will need to switch to current tab using the following step: `When I switch to tab with title that $stringComparisonRule `$windowName``.

.Checking for an alert when trying to close a window with form
[source,gherkin]
----
Given I am on page with URL `https://example.com/`
When I open URL `https://example.com/form` in new tab
When I click on element located by `xpath(//*[@id='form-edit'])`
When I execute sequence of actions:
|type      |argument    |
|ENTER_TEXT|changed text|
When I attempt to close current tab with possibility to handle alert
Then an alert is present
When I accept alert with message which matches `.*`
----

=== Execute sequence of actions

Executes the sequence of web actions

[source,gherkin]
----
When I execute sequence of actions: $actions
----
* `$actions` - table of actions to execute
+
.Possible actions
[cols="1,5,3", options="header"]
|===

|`type`
|`argument`
|Argument example

|DOUBLE_CLICK
|Element locator or empty.
|By.linkUrl(http://httpbin.org)

|CLICK_AND_HOLD
|Element locator or empty.
|By.linkText(Click me)

|MOVE_BY_OFFSET
|Point.
|(10, 15) where *x* is 10 and *y* is 15

|RELEASE
|Element locator or empty.
|By.tagName(div)

|ENTER_TEXT
|Text to type.
|Minsk City

|CLICK
|Element locator or empty.
|By.caseSensitiveText(Done)

|PRESS_KEYS
|Comma-separated https://selenium.dev/selenium/docs/api/java/org/openqa/selenium/Keys.html[keys] to press and release.
|BACK_SPACE

|KEY_DOWN
|Comma-separated https://selenium.dev/selenium/docs/api/java/org/openqa/selenium/Keys.html[keys] to press one by one.
|CONTROL,SHIFT,ALT

|KEY_UP
|Comma-separated https://selenium.dev/selenium/docs/api/java/org/openqa/selenium/Keys.html[keys] to release one by one.
|CONTROL,SHIFT,ALT

|MOVE_TO
|Element locator.
|By.id(username)

|===

[TIP]
====
Windows/Unix and macOS platforms have different keyboards. For example, kbd:[Ctrl+C] combination is used to copy text
on Windows and Unix, but kbd:[⌘ Command+C] should be used on macOS with default preferences.

In order to close this gap VIVIDUS offers unique key `OS_INDEPENDENT_CONTROL`: it is mapped to
https://en.wikipedia.org/wiki/Control_key[`CONTROL`] key on Windows/Unix and to
https://en.wikipedia.org/wiki/Command_key[`COMMAND`] key on macOS. Using this key it is possible to make tests fully
platform independent.
====

.Execute various web-actions
[source,gherkin]
----
When I execute sequence of actions:
|type          |argument                                |
|DOUBLE_CLICK  |By.fieldText(Hello World)               |
|DOUBLE_CLICK  |                                        |
|CLICK_AND_HOLD|By.xpath(//signature-pad-control/canvas)|
|CLICK_AND_HOLD|                                        |
|MOVE_BY_OFFSET|(-300, 0)                               |
|RELEASE       |By.xpath(//signature-pad-control/canvas)|
|RELEASE       |                                        |
|ENTER_TEXT    |Text                                    |
|CLICK         |By.placeholder(Enter your password)     |
|CLICK         |                                        |
|PRESS_KEYS    |BACK_SPACE                              |
|KEY_DOWN      |CONTROL,SHIFT                           |
|KEY_UP        |CONTROL,SHIFT                           |
|MOVE_TO       |By.id(name)                             |
----

[TIP]
====
This step can be used to perform clipboard interactions.

.Select all text in the focused field and copy it to the clipboard on Windows
[source,gherkin]
----
When I execute sequence of actions:
|type      |argument  |
|KEY_DOWN  |CONTROL, a|
|KEY_UP    |a, CONTROL|
|KEY_DOWN  |CONTROL, c|
|KEY_UP    |c, CONTROL|
----

.Paste text from the clipboard to the focused field on MacOS
[source,gherkin]
----
When I execute sequence of actions:
|type      |argument  |
|KEY_DOWN  |COMMAND, v|
|KEY_UP    |v, COMMAND|
----

.Select all text in the focused field and copy it to the clipboard on any OS
[source,gherkin]
----
When I execute sequence of actions:
|type      |argument                 |
|KEY_DOWN  |OS_INDEPENDENT_CONTROL, a|
|KEY_UP    |a, OS_INDEPENDENT_CONTROL|
|KEY_DOWN  |OS_INDEPENDENT_CONTROL, c|
|KEY_UP    |c, OS_INDEPENDENT_CONTROL|
----
====

=== Browser logs steps

This set of steps allows to validate the https://developer.mozilla.org/en-US/docs/Web/API/console[browser console logging messages].

:log-levels: List of the comma-separated messages levels. The supported levels are: ERRORS, WARNINGS, INFOS.

[TIP]
=====
In order to configure availability of the INFO level messages use following properties:
[cols="1,2"]
|===

|Browser
|Property to enable INFO logs

|Google Chrome
|`selenium.capabilities.goog\:loggingPrefs.browser=INFO`

|Microsoft Edge Chromium
|`selenium.capabilities.ms\:loggingPrefs.browser=INFO`
|===
=====

==== Validate log entries absence

Validates the absence of log entries of the desired level in the browser console.

[source,gherkin]
----
Then there are no browser console $logLevels
----
* `$logLevels` - {log-levels}

.Validate absence of JS errors
[source,gherkin]
----
Given I am on page with URL `https://vividus-test-site-a92k.onrender.com/`
Then there are no browser console ERRORS
----

==== Validate specific log entries absence

Validates the absence of specific log entries of the desired level in the browser console.

[source,gherkin]
----
Then there are no browser console $logLevels by regex `$regex`
----

_Deprecated syntax (will be removed in VIVIDUS 0.7.0)_:
[source,gherkin]
----
Then there are no browser console $logLevels by regex '$regex'
----

* `$logLevels` - {log-levels}
* `$regex` - The regular expression to match log entry messages.

.Validate absence of JS error referencing user
[source,gherkin]
----
Given I am on page with URL `https://vividus-test-site-a92k.onrender.com/`
Then there are no browser console ERRORS by regex `.*user.*`
----

==== Validate specific log entries presence

Validates the presence of specific log entries of the desired level in the browser console.

[source,gherkin]
----
Then there are browser console $logLevels by regex `$regex`
----
* `$logLevels` - {log-levels}
* `$regex` - The regular expression to match log entry messages.

.Validate presence of JS errors referencing user
[source,gherkin]
----
Given I am on page with URL `https://vividus-test-site-a92k.onrender.com/`
Then there are browser console ERRORS by regex `.*user.*`
----

==== Wait for console log entries and save them

Waits for the appearance of the console log entries with the expected level and which match regular expression and saves all the entries (including awaited ones) of the expected level gathered during the wait to the scoped variable.

NOTE: Wait uses generic UI timeouts specified by the properties `ui.wait.timeout` and `ui.wait.polling-period`. See <<_properties>> section for more details.

[source,gherkin]
----
When I wait until browser console $logEntries by regex `$regex` appear and save all entries into $scopes variable `$variableName`
----
* `$logLevels` - {log-levels}
* `$regex` - The regular expression to match log entry messages.
* `$scopes` - xref:commons:variables.adoc#_scopes[The comma-separated set of the variables scopes].
* `$variableName` - The name of the variable to save the value of the barcode.

.Wait for application readiness
----
Given I am on page with URL `https://vividus-test-site-a92k.onrender.com/`
When I wait until browser console infos by regex `.*Application ready.*` appear and save all entries into scenario variable `logs`
Then `${logs}` matches `.*Application ready in \d+ seconds.*`
----

==== Clear browser console logs

Clears browser console logs of all types.

NOTE: The `console.clear();` JS command doesn't affect the logs fetched by Selenium.

[source,gherkin]
----
When I clear browser console logs
----

.Clear browser console logs
----
Given I am on page with URL `https://vividus-test-site-a92k.onrender.com/`
When I clear browser console logs
Then there are browser console ERRORS by regex `.*`
----

include::plugins:partial$ui-execution-on-each-element-steps.adoc[]

=== Context steps
==== Switch to the default context of page

Switches context to the root https://developer.mozilla.org/en-US/docs/Web/HTML/Element/html[<html>] element of the current page.

[source,gherkin]
----
When I switch back to page
----

_Deprecated syntax (will be removed in VIVIDUS 0.7.0)_:
[source,gherkin]
----
When I switch back to the page
----

.Switch to user context and back to the default context of page
----
Given I am on page with URL `https://vividus-test-site-a92k.onrender.com/elementState.html`
When I change context to element located by `id(button-hide)`
Then text `Element to hide` does not exist
When I switch back to page
Then text `Element to hide` exists
----

==== Switch context to a frame

Switches to https://developer.mozilla.org/en-US/docs/Web/HTML/Element/iframe[<iframe>] or https://developer.mozilla.org/en-US/docs/Web/HTML/Element/frame[<frame>] element using one of the supported locators.

[source,gherkin]
----
When I switch to frame located by `$locator`
----

_Deprecated syntax (will be removed in VIVIDUS 0.7.0)_:
[source,gherkin]
----
When I switch to frame located `$locator`
----

* `$locator` - <<_locator>> of frame element.

.Switch to frame
----
Given I am on page with URL `https://vividus-test-site-a92k.onrender.com/nestedFrames.html`
Then text `Modal Frame Example` does not exist
When I switch to frame located by `id(parent)`
Then text `Modal Frame Example` exists
----

==== Switch context to new tab

Switch the focus of future browser commands to new tab.

This step gets the identifier of the currently active tab and then switches focus to the first available tab with a different identifier. For example, if tabs #1, #2, #3 are open and tab #2 is active, this step will switch focus to tab #3.

[NOTE]
A new tab should already be open for this step to function. After executing this step, the new tab will become the active tab.

[source,gherkin]
----
When I switch to new tab
----
_Deprecated syntax (will be removed in VIVIDUS 0.7.0)_:
[source,gherkin]
----
When I switch to a new window
----

.Open the new tab by link and switch to it
----
Given I am on page with URL `https://the-internet.herokuapp.com/windows`
When I click on element located by `linkUrlPart(/windows/new)`
Then text `New Window` does not exist
When I switch to new tab
Then text `New Window` exists
----

==== Switch context to new tab with specified title

Switch the focus of future browser commands to new tab with specified title.

[source,gherkin]
----
When I switch to tab with title that $stringComparisonRule `$tabName`
----
_Deprecated syntax (will be removed in VIVIDUS 0.7.0)_:
[source,gherkin]
----
When I switch to window with title that $stringComparisonRule `$windowName`
----
* `$stringComparisonRule` - xref:parameters:string-comparison-rule.adoc[String comparison rule].
* `$tabName` - The expected tab title.

.Open the new tab by link and switch to it using regex title pattern
----
Given I am on page with URL `https://the-internet.herokuapp.com/windows`
When I click on element located by `linkUrlPart(/windows/new)`
Then text `New Window` does not exist
When I switch to tab with title that matches `.*[wW]indow.*`
Then text `New Window` exists
----
