=== Proxy Steps
==== Check the number of HTTP requests
:proxy: This step requires proxy to be turned on. It can be done in properties or by switching on @proxy meta tag at the story level.

{proxy}

The actions preformed by the step:

* extract HTTP messages from the recorded proxy archive
* filter out the HTTP messages with the response status code `302 Moved Temporarily`
* find HTTP requests matching the provided HTTP methods and the URL regular expression
* check that the total number of the found HTTP messages satisfies the desired condition

{har-attached}

[source,gherkin]
----
Then number of HTTP $httpMethods requests with URL pattern `$urlPattern` is $comparisonRule `$number`
----
* `$httpMethods` - The comma-separated HTTP methods to filter by
* `$urlPattern` - The regular expression to match HTTP request URL
* `$comparisonRule` - xref:parameters:comparison-rule.adoc[Comparison Rule]
* `$number` - The number to compare with

.Check the number of HTTP GET and POST requests matching URL regurlar expression is equal to 1
[source,gherkin]
----
Then number of HTTP GET, POST requests with URL pattern `http://httpbin\.org/get` is equal to `1`
----

==== Capture HTTP message

Save the HTTP message part from the HTTP request with given URL-pattern into the variable with specified name and the scopes.

{proxy}

The actions preformed by the step:

* extract HTTP messages from the recorded proxy archive
* filter out the HTTP messages with the response status code `302 Moved Temporarily`
* find HTTP requests matching the provided HTTP methods and the URL regular expression
* check that total number of the found HTTP messages is equal to `1`
* save the HTTP message part to the specified variable

{har-attached}

[source,gherkin]
----
When I capture HTTP $httpMethods request with URL pattern `$urlPattern` and save $httpMessagePart to $scopes variable `$variableName`
----
* `$httpMethods` - The "or"-separated set of HTTP methods to filter by, e.g. `GET or POST or PUT`.
* `$urlPattern` - The regular expression to match HTTP request URL.
* `$httpMessagePart` - The HTTP message part to save. One of:
** `URL` - The request URL.
** `URL query` - The request URL query parameters.
** `request data` - The request data includes the following keys:
*** `query` - The URL query is stored as a collection of key and value pairs, where key is the name of the query parameter and value is the list of query parameter values. The query parameter values are accessible via zero-based index.
*** `requestBody.mimeType` - The MIME type of posted data, the variable will not be saved if MIME type is not present.
*** `requestBody.text` - The posted data as plain text, the variable will not be saved if the request body is not present.
*** `requestBodyParameters` - The form data parameters are stored as a collection of key and value pairs, where key is the name of the form parameter and value is the list of form parameter values. The form parameter values are accessible via zero-based index.
*** `responseStatus` - The response status, the variable will not be saved if the response is not present.
** `response data` - The response data includes the following keys:
*** `responseBody.mimeType` - The MIME type of response data, the variable will not be saved if MIME type is not present.
*** `responseBody.text` - The response data as plain text, the variable will not be saved if the response body is not present.
* `$scopes` - xref:commons:variables.adoc#_scopes[The comma-separated set of the variables scopes].
* `$variableName` - The variable name to save the HTTP message part.

.Validate the URL of the matching HTTP request
[source,gherkin,subs="attributes+"]
----
{given-step}
When I capture HTTP GET or POST request with URL pattern `.*/search.*=vividus` and save URL to scenario variable `URL`
Then `${URL}` is equal to `https://www.google.com/search?q=vividus`
----

.Validate the URL query of the matching HTTP request
[source,gherkin,subs="attributes+"]
----
{given-step}
When I capture HTTP GET request with URL pattern `.*/search.*=vividus` and save URL query to scenario variable `query`
Then `${query.q[0]}` is equal to `vividus`
Then `${query.q}` is equal to `[vividus]`
Then `${query}` is equal to `{q=[vividus]}`
----

.Validate the request data from the matching HTTP message
[source,gherkin,subs="attributes+"]
----
{given-step}
When I capture HTTP GET request with URL pattern `https://www.google.com/search?q=vividus` and save request data to scenario variable `data`
Then `${data.query}` is equal to `{}`
Then `${data.requestBodyParameters}` is equal to `{delivery=, custtel=, comments=, custemail=, custname=}`
Then `${data.requestBody}` is not equal to `null`
Then `${data.responseStatus}` is equal to `200`
----

.Validate the response data from the matching HTTP message
[source,gherkin,subs="attributes+"]
----
{given-step}
When I capture HTTP GET request with URL pattern `https://www.google.com/search?q=vividus` and save request data to scenario variable `data`
Then `${data.responseBody.text}` is equal to `{"status": "ok"}`
Then `${data.responseBody.mimeType}` is equal to `application/json`
----


==== Wait for the HTTP request

{proxy}
Waits for the HTTP requests matching the provided HTTP methods and URL regular expression.
If no HTTP request is sent and wait timeout is reached, then the step will fail.

[source,gherkin]
----
When I wait until HTTP $httpMethods request with URL pattern `$urlPattern` exists in proxy log
----
* `$httpMethods` - the "or"-separated HTTP methods to filter by, e.g. 'GET or POST or PUT'
* `$urlPattern` - the regular expression to match HTTP request URL

.Wait for the HTTP request
[source,gherkin,subs="attributes+"]
----
{given-step}
When I wait until HTTP GET or POST request with URL pattern `https://www.google.com/search?q=vividus` exists in proxy log
Then number of HTTP GET or POST requests with URL pattern `https://www.google.com/search?q=vividus` is equal to `1`
----


==== Add headers to the HTTP request

{proxy}
Add headers to the proxied HTTP request satisfying the desired condition

[source,gherkin]
----
When I add headers to proxied requests with URL pattern which $comparisonRule `$url`:$headers
----
* `$comparisonRule` - xref:parameters:string-comparison-rule.adoc[String comparison rule]
* `$url` - The input value of URL to filter by
* `$headers` - ExamplesTable representing the list of the headers with columns "name" and "value" specifying HTTP header names and values respectively

.Add headers to the proxied HTTP request
[source,gherkin,subs="attributes+"]
----
When I add headers to proxied requests with URL pattern which is equal to `https://www.google.com/search?q=vividus`:
|name     |value     |
|testName1|testValue1|
|testName2|testValue2|
{given-step}
Then a JSON element from '${response}' by the JSON path '$.headers' is equal to '
{
    "Testname1": "testValue1",
    "Testname2": "testValue2"
}
'ignoring extra fields
----


==== Clear the recordings

{proxy}
The step clears the HTTP requests and responses recorded by the proxy

[source,gherkin]
----
When I clear proxy log
----

.Clear the data recorded by the proxy
[source,gherkin,subs="attributes+"]
----
{given-step}
When I clear proxy log
Then number of HTTP GET requests with URL pattern 'https://www.google.com/search?q=vividus' is equal to `0`
----


==== Clear the mocks

{proxy}
The step clears previously created mocks

[source,gherkin]
----
When I clear proxy mocks
----

.Clear the proxy mocks
[source,gherkin,subs="attributes+"]
----
When I mock HTTP responses with request URL which CONTAINS `vividus` using response code `200`, content `#{loadResource(page.html)}` and headers:
|name        |value    |
|Content-Type|text/html|
When I clear proxy mocks
{given-step}
Then number of elements found by `id(sw)` is = `0`
----


==== Mock the HTTP response by methods with content

{proxy}
Mocks HTTP response by methods with a provided content

[IMPORTANT]
No actual request will be executed. Short-circuited response will be returned.

[source,gherkin]
----
When I mock HTTP $httpMethods responses with request URL which $comparisonRule `$url` using response code `$responseCode`, content `$payload` and headers:$headers
----
* `$httpMethods` - The "or"-separated set of HTTP methods to filter by, e.g. `GET or POST or PUT`.
* `$rule` - xref:parameters:string-comparison-rule.adoc[String comparison rule]
* `$url` - The input value of URL to filter by
* `$code` - The response status code
* `$content` - The content to send within a response
* `$headers` - ExamplesTable representing the list of the headers with columns "name" and "value" specifying HTTP header names and values respectively

.Hijack a page
[source,gherkin]
----
When I mock HTTP POST responses with request URL which CONTAINS `example` using response code `202`, content `#{loadResource(mocked-example.json)}` and headers:
|name        |value           |
|Content-Type|application/json|
----


==== Mock the HTTP response with content

{proxy}
Mocks HTTP response with a provided content

[IMPORTANT]
No actual request will be executed. Short-circuited response will be returned.

[source,gherkin]
----
When I mock HTTP responses with request URL which $comparisonRule `$url` using response code `$responseCode`, content `$payload` and headers:$headers
----

* `$rule` - xref:parameters:string-comparison-rule.adoc[String comparison rule]
* `$url` - The input value of URL to filter by
* `$code` - The response status code
* `$content` - The content to send within a response
* `$headers` - ExamplesTable representing the list of the headers with columns "name" and "value" specifying HTTP header names and values respectively

.Hijack a page
[source,gherkin]
----
When I mock HTTP responses with request URL which CONTAINS `example.com` using response code `200`, content `#{loadResourceAsByteArray(page.html)}` and headers:
|name        |value    |
|Content-Type|text/html|
----


==== Mock the HTTP response without content

{proxy}
Mocks HTTP response

[IMPORTANT]
No actual request will be executed. Short-circuited response will be returned.

[source,gherkin]
----
When I mock HTTP responses with request URL which $comparisonRule `$url` using response code `$responseCode` and headers:$headers
----

* `$rule` - xref:parameters:string-comparison-rule.adoc[String comparison rule]
* `$url` - The input value of URL to filter by
* `$code` - The response status code
* `$headers` - ExamplesTable representing the list of the headers with columns "name" and "value" specifying HTTP header names and values respectively

.404 page
[source,gherkin]
----
When I mock HTTP responses with request URL which CONTAINS `example.com` using response code `404` and headers:
|name          |value|
|Content-Length|0    |
----
