=== Elements validation

==== Validate elements number

Validates the context contains the number of elements matching the specified comparison rule.

[source,gherkin]
----
Then number of elements found by `$locator` is $comparisonRule `$quantity`
----

* `$locator` - The <<_locator,locator>> used to find elements.
* `$comparisonRule` - The xref:parameters:comparison-rule.adoc[comparison rule].
* `$quantity` - The expected number of the elements.

.Validate the number of elements
[source,gherkin]
----
Then number of elements found by `xpath(./a)` is equal to `5`
----

==== Verify elements state

Verifies if the number of elements located by locator matches the number
condition and all of them are in the desired state.

[IMPORTANT]
If you describe number condition as equal to 5 in case if there are 10 elements by this locator and only 5 of them in the desired state. You will get two failed assertions.
The first one about number condition violation. The second one about state check failure.

[WARNING]
In case when <<_visibility_types>> are used and checked state are equal (For an example ':v' and 'VISIBLE') exception will be thrown. In such cases please use step:
<<_validate_elements_number>>.
Contradictory visibility parameters (locator - ':v' and checked state - 'NOT_VISIBLE') are also not allowed.

[source,gherkin]
----
Then number of $state elements found by `$locator` is $comparisonRule `$quantity`
----

* `$state` - xref:parameters:state.adoc[State]
* `$locator` - <<_locator>>.
* `$comparisonRule` - xref:parameters:comparison-rule.adoc[The comparison rule].
* `$quantity` - The expected number of elements.

.Verify the number of elements in the state
[source,gherkin]
----
Then number of VISIBLE elements found by `id(img)` is = `1`
----
