=== Scrolling steps
==== Scroll context

Scrolls the context to an edge

[source,gherkin]
----
When I scroll context to $scrollDirection edge
----
* `$scrollDirection` - the direction of the scroll. One of:
** `LEFT` - start of a page/element horizontally
** `RIGHT` - end of a page/element horizontally
** `TOP` - start of a page/element vertically
** `BOTTOM` - end of a page/element vertically

[TIP]
If the context is not set, the whole page will be scrolled

.Scroll login to a bottom
[source,gherkin]
----
When I change context to element located by `id(login)`
When I scroll context to BOTTOM edge
----

==== Scroll element into view

Scrolls an element into the view with centred positioning.

NOTE: If the element to scroll is located inside an https://developer.mozilla.org/en-US/docs/Web/CSS/overflow[overflow] container then native https://developer.mozilla.org/en-US/docs/Web/API/Element/scrollIntoView[scrollIntoView] JS method with top alignment is used.

[source,gherkin]
----
When I scroll element located by `$locator` into view
----
* `$locator` - The <<_locator,locator>> used to find element.

_Deprecated syntax (will be removed in VIVIDUS 0.7.0)_:
[source,gherkin]
----
When I scroll element located `$locator` into view
----
* `$locator` - The <<_locator,locator>> used to find element.

.Scroll button into view
[source,gherkin]
----
When I scroll element located by `id(way_down_button)` into view
----

==== Validate the page is scrolled to element

Checks if the page is scrolled to the specific element

[WARNING]
====
This step is deprecated and will be removed in VIVIDUS 0.8.0.
Please see the replacement pattern below:
[source,gherkin]
----
Then element located by `$locator` is visible in viewport
----
====

[source,gherkin]
----
Then page is scrolled to element located by `$locator`
----
* `$locator` - The <<_locator,locator>> used to find element.

.Validate Contact link is scrolled into view
[source,gherkin]
----
Then page is scrolled to element located by `xpath(//a[text()="Contact"])`
----

==== Validate element presence in viewport

Checks if the element located by the specified locater is or is not presented in the browser viewport

[source,gherkin]
----
Then element located by `$locator` $presence visible in viewport
----
* `$locator` - The <<_locator,locator>> used to find element.
* `$presence` - The presence state of the element, either `is` or `is not`.

.Validate element presence in viewport
[source,gherkin]
----
Given I am on a page with the URL 'https://ui.com/long-page-with-image'
Then element located by `tagName(img)` is not visible in viewport
When I scroll element located `tagName(img)` into view
Then element located by `tagName(img)` is visible in viewport
----
