=== https://developer.mozilla.org/en-US/docs/Web/API/Web_Storage_API[Web Storage] steps
==== Get web storage item

Finds the web storage item by the key and saves its value to the variable.

[source,gherkin]
----
When I save $storageType storage item with key `$key` to $scopes variable `$variableName`
----
* `$storageType` - One of the web storage mechanisms: either `local` or `session`.
* `$key` - The name of the key to retrieve the value of.
* `$scopes` - xref:commons:variables.adoc#_scopes[The comma-separated set of the variables scopes].
* `$variableName` - The name of the variable to store the value of the web storage item.

.Get the value of the local storage item
[source,gherkin]
----
When I save local storage item with key `token` to scenario variable `application-token`
----

==== Set web storage item

Adds the item with the specified key-value pair to the web storage, or updates
that key's value if it already exists.

[source,gherkin]
----
When I set $storageType storage item with key `$key` and value `$value`
----
* `$storageType` - One of the web storage mechanisms: either `local` or `session`.
* `$key` - The name of the key to create/update.
* `$value` - The value to give the key that is creating/updating.

.Set the session storage item
[source,gherkin]
----
When I set session storage item with key `token` and value `session-token`
----

==== Validate web storage item presence

Validates the web storage item with the specified key exists.

[source,gherkin]
----
Then $storageType storage item with key `$key` exists
----
* `$storageType` - One of the web storage mechanisms: either `local` or `session`.
* `$key` - The name of the key to check presence.

.Check the session storage item is present
[source,gherkin]
----
Then session storage item with key `token` exists
----

==== Validate web storage item absence

Validates the web storage item with the specified key does not exist.

[source,gherkin]
----
Then $storageType storage item with key `$key` does not exist
----
* `$storageType` - One of the web storage mechanisms: either `local` or `session`.
* `$key` - The key of the local storage item to check absence.

.Check the local storage item is not present
[source,gherkin]
----
Then local storage item with key `token` does not exist
----

==== Remove web storage item

Removes an item with the key from web storage.

[source,gherkin]
----
When I remove item with key `$key` from $storageType storage
----

* `$key` - The key of the item to remove.
* `$storageType` - One of the web storage mechanisms: either `local` or `session`.

.Remove item with 'token' key from web storage
[source,gherkin]
----
When I remove item with key `token` from session storage
----

==== Clear web storage

Removes all items from web storage.

[source,gherkin]
----
When I clear $storageType storage
----

* `$storageType` - One of the web storage mechanisms: either `local` or `session`.

.Clear session storage
[source,gherkin]
----
When I clear session storage
----
