project.description = 'VIVIDUS plugin for WinRM (Windows Remote Management)'

dependencies {
    implementation project(':vividus-engine')
    implementation project(':vividus-reporter')
    implementation project(':vividus-soft-assert')

    implementation('org.metricshub:winrm-java:2.1.00')

    testImplementation platform(libs.junit.bom)
    testImplementation(libs.junit.jupiter)
    testRuntimeOnly(libs.junit.platformLauncher)
    testImplementation platform(libs.mockito.bom)
    testImplementation(libs.mockito.junitJupiter)
}
