= Tests Configuration

== `configuration.properties`

The Vividus configuration includes the following parts: profiles, environments and suites.

=== Suites

The property `configuration.suites` defines the suites set. It is a comma separated set of suite file addresses:

.configuration.properties
----
configuration.suites=testSuite,anotherDir/anotherTestSuite
----
The Vividus suite consists of the unlimited number of batches. In its turn the batch consists of any number of stories represented by the files with `*.story` extension. The batches are run sequentially, while the stories in the batch are run in parallel.

The suites are loaded one by one starting from the last one in the sequence, in other words, the values of the properties defined in the first suite will take precedence over the values of the same properties defined in all subsequent suites.

The following properties are used to configure batches (Vividus doesn't provide any default batch configuration out of the box). `batch-number` is one-based batch index.

NOTE: The properties marked with *bold* are mandatory.

[cols="2,1,2", options="header"]
|===
|Property
|Default value
|Description

|[subs=+quotes]`*bdd.story-loader.batch-<batch-number>.resource-location*`
|
|The test project path to the folder with story-files

|`bdd.story-loader.batch-<batch-number>.resource-include-patterns`
|`<empty>`
|The comma-separated set of https://ant.apache.org/manual/dirtasks.html#patterns[ant-patterns] to match the stories to be included in the batch

|`bdd.story-loader.batch-<batch-number>.resource-exclude-patterns`
|`<empty>`
|The comma-separated set of https://ant.apache.org/manual/dirtasks.html#patterns[ant-patterns] to match the stories to be excluded from the batch

|`bdd.batch-<batch-number>.name`
|`batch-<batch-number>`
|The name of the batch to display in the report

|`bdd.batch-<batch-number>.threads`
|`1`
|The number of parallel threads used to run stories

|`bdd.batch-<batch-number>.meta-filters`
|suite meta-filter
|The meta-filter used to filter the batch stories and scenarios

|`bdd.batch-<batch-number>.ignore-failure`
|`true`
|If `false` and any failure is occurred during the batch execution, the subsequent batches are not executed.

|`bdd.batch-<batch-number>.story-execution-timeout`
|`PT3H`
|The max duration of the single story in the batch.
|===

== Known Issues

Known issues mechanism allows to distinguish failures from known issues presented in the system under test.

[IMPORTANT]
JSON file should contain a valid JSON. If JSON is not valid known issues will be ignored and warning about invalid file will be printed.

=== Properties

[cols="2,1,2", options="header"]
|===
|Property
|Default value
|Description

|`known-issue-provider.fileName`
|`known-issues.json`
|Defines the location of the known issues file

|`known-issue-provider.detect-potentially-known-issues`
|`true`
|Defines are potentially known issues detected
|===

=== Known Issues file

The file represents a collection of JSON elements describing known issues.

.known-issues.json
[source,json,subs=attributes+]
----
 {
    "VVD-1": { <1>
        "type": "Internal",<2>
        "assertionPattern": "Expected: a value equal to 200, Actual: \\[404\\]" <3>
        "storyPattern": "Validate the Math", <4>
        "scenarioPattern": "Validate equality", <5>
        "stepPattern": "Then `1` is = `2`.+", <6>
        "variablePatterns": { <7>
            "var":  "value-.*"
        },
        "failScenarioFast": true, <8>
        "failStoryFast": true <9>
    }
}
----
<1> [Mandatory] *Identifier* (This could be an ID of the issue in your bug tracking system)
<2> [Mandatory] *Issue type.* One of: INTERNAL (application issue), EXTERNAL (3rd party issue), AUTOMATION (test automation issue)
<3> [Mandatory] *Assertion pattern* describes which failed assertions should be considered as known
<4> Story pattern to match failed story name
<5> Scenario pattern to match failed scenario name
<6> Step pattern to match failed step.
<7> Variable patterns. Patterns to match variables.
<8> Skip the rest of scenario in case of failure identified as this known issue
<9> Skip the rest of story in case of failure identified as this known issue

[IMPORTANT]
Use *\\* for escaping of special characters in regular expressions

=== Examples

* To consider failed assertion known or potentially-known *assertionPattern* should match assertion failure, if defined *variablePatterns* should match also.
* If *assertionPattern*/*variablePatterns* matched and you have *story/scenario/step/Pattern* defined, to consider issue known all of them should match.
* If *assertionPattern*/*variablePatterns* matched and you have *story/scenario/step/Pattern* defined, when at least one not matched issue is considered potentially known.
