= Tests Configuration

== `configuration.properties`

The Vividus configuration includes the following parts: profiles, environments and suites.

=== Suites

The property `configuration.suites` defines the suites set. It is a comma separated set of suite file addresses:

.configuration.properties
----
configuration.suites=testSuite,anotherDir/anotherTestSuite
----
The Vividus suite consists of the unlimited number of batches. In its turn the batch consists of any number of stories represented by the files with `*.story` extension. The batches are run sequentially, while the stories in the batch are run in parallel.

The suites are loaded one by one starting from the last one in the sequence, in other words, the values of the properties defined in the first suite will take precedence over the values of the same properties defined in all subsequent suites.

The following properties are used to configure batches (Vividus doesn't provide any default batch configuration out of the box). `batch-number` is one-based batch index.

NOTE: The properties marked with *bold* are mandatory.

[cols="2,1,2", options="header"]
|===
|Property
|Default value
|Description

|[subs=+quotes]`*bdd.story-loader.batch-<batch-number>.resource-location*`
|
|The test project path to the folder with story-files

|`bdd.story-loader.batch-<batch-number>.resource-include-patterns`
|`<empty>`
|The comma-separated set of https://ant.apache.org/manual/dirtasks.html#patterns[ant-patterns] to match the stories to be included in the batch

|`bdd.story-loader.batch-<batch-number>.resource-exclude-patterns`
|`<empty>`
|The comma-separated set of https://ant.apache.org/manual/dirtasks.html#patterns[ant-patterns] to match the stories to be excluded from the batch

|`bdd.batch-<batch-number>.name`
|`batch-<batch-number>`
|The name of the batch to display in the report

|`bdd.batch-<batch-number>.threads`
|`1`
|The number of parallel threads used to run stories

|`bdd.batch-<batch-number>.meta-filters`
|suite meta-filter
|The meta-filter used to filter the batch stories and scenarios

|`bdd.batch-<batch-number>.fail-fast`
|`false`
|If `true` and any failure is occurred during the batch execution, the subsequent batches are not executed.

|`bdd.batch-<batch-number>.story-execution-timeout`
|`PT3H`
|The max duration of the single story in the batch.

|`bdd.batch.fail-fast`
|`false`
|If set to `true` the subsequent batches execution will be stopped after first failed assertion

|`bdd.story.fail-fast`
|`false`
|If set to `true` the story execution will be stopped after first failed assertion

|`bdd.scenario.fail-fast`
|`false`
|If set to `true` the scenario execution will be stopped after first failed assertion
|===

== Known Issues

Known issues mechanism allows to distinguish failures from known issues presented in the system under test.

[IMPORTANT]
JSON file should contain a valid JSON. If JSON is not valid known issues will be ignored and warning about invalid file will be printed.

=== Properties

[cols="2,1,2", options="header"]
|===
|Property
|Default value
|Description

|`known-issue-provider.fileName`
|`known-issues.json`
|Defines the location of the known issues file

|`known-issue-provider.detect-potentially-known-issues`
|`true`
|Defines are potentially known issues detected
|===

=== Known Issues file

The file represents a collection of JSON elements describing known issues.

.known-issues.json
[source,json,subs=attributes+]
----
 {
    "VVD-1": { <1>
        "type": "Internal",<2>
        "assertionPattern": "Expected: a value equal to 200, Actual: \\[404\\]" <3>
        "storyPattern": "Validate the Math", <4>
        "scenarioPattern": "Validate equality", <5>
        "stepPattern": "Then `1` is = `2`.+", <6>
        "variablePatterns": { <7>
            "var":  "value-.*"
        },
        "failScenarioFast": true, <8>
        "failStoryFast": true <9>
    }
}
----
<1> [Mandatory] *Identifier* (This could be an ID of the issue in your bug tracking system)
<2> [Mandatory] *Issue type.* One of: INTERNAL (application issue), EXTERNAL (3rd party issue), AUTOMATION (test automation issue)
<3> [Mandatory] *Assertion pattern* describes which failed assertions should be considered as known
<4> Story pattern to match failed story name
<5> Scenario pattern to match failed scenario name
<6> Step pattern to match failed step.
<7> Variable patterns. Patterns to match variables.
<8> Skip the rest of scenario in case of failure identified as this known issue
<9> Skip the rest of story in case of failure identified as this known issue

[IMPORTANT]
Use *\\* for escaping of special characters in regular expressions

=== Examples

* To consider failed assertion known or potentially-known *assertionPattern* should match assertion failure, if defined *variablePatterns* should match also.
* If *assertionPattern*/*variablePatterns* matched and you have *story/scenario/step/Pattern* defined, to consider issue known all of them should match.
* If *assertionPattern*/*variablePatterns* matched and you have *story/scenario/step/Pattern* defined, when at least one not matched issue is considered potentially known.

== Meta tags

Meta tags can be used to reach several goals:

* Grouping of stories and scenarios in the report.
* Dynamic selection of tests to execute by meta tags.
* Management of capabilities for the particular tests.

=== Levels
Meta tags may be used at both story and scenario level. Meta tags specified at the story level are propagated to every scenario, if the same meta tag is used at the scenario level, then the scenario level value takes precedence.

.Levels of meta tags 
[source,gherkin]
----
!-- Story level
Meta:
     @group Login

Scenario: Open Epam main page
!-- Scenario level
Meta:
  @severity 1
  @layout desktop
Given I am on a page with the URL 'https://www.epam.com/'
Then the page title is equal to 'EPAM | Enterprise Software Development, Design & Consulting'

Scenario: Open Google main page
Meta:
  @severity 2
  @layout desktop
  @skip
Given I am on a page with the URL 'https://www.google.com/'
Then the page title is equal to 'Google'
----

=== Properties

The prorerty `bdd.all-meta-filters` is used to override values of the default meta filters based on the tags: `@skip`, `@layout`, `@browserWindowSize` and etc.

The property `bdd.meta-filters` relies on groovy synax can be used to filters tests to be executed.

.Execute stoies and scenarios marked with '@group Login' tag and without '@skip' tag
[source,properties]
----
bdd.meta-filters=groovy: (group == 'Login' && !skip)
----

The following meta tags are available out of the box.

=== 1D tags (@key)
[cols="1,4", options="header"]
|===
|Tag
|Description

|`@skip`
|Used to exclude particular scenarios from the test execution
|===


=== 2D tags (@key  value)
[cols="1,1,3,1", options="header"]
|===
|Tag Key
|Allowed values
|Description
|Example

|@severity
|Numeric values (range 1-5)
|Used to mark importance of the test where, most usually, the smallest number is the most important Test, the highest number is the least important.
|`@severity 1`

|@layout
|`desktop`, `phone`, `phone_portrait`, `phone_landscape`, `chrome_phone`, `chrome_responsive`, `chrome_tablet`, `tablet`, `tablet_landscape`, `tablet_portrait`
|Used to specify layout, using which marked story or scenario should be executed. In case if this meta tag is not specified, default (`desktop`) value is used for web applications.
|`@layout desktop`

|@browserWindowSize
|Any browser window size in pixels, e.g. `800x600`. Note: browser window size should be smaller than the current screen resolution.
|Used to specify browser window size. It can be applied on both story and scenario levels. In case, if browser size differs between adjacent scenarios, browser window will be simply resized to desired values, browser session will not be restarted. If the tag is not set for story or scenario, the browser window will be maximized to the screen size during local test execution.
|`@browserWindowSize 1024x768`
|===
