project.description = 'VIVIDUS extension for AWS Cloud'

dependencies {
    api platform(libs.awssdk.bom)
    api('software.amazon.awssdk:auth')
    api('software.amazon.awssdk:aws-core')
    api("org.vividus:jbehave-core:${versions.jbehave}")
    implementation project(':vividus-test-context')

    testImplementation platform(libs.junit.bom)
    testImplementation(libs.junit.jupiter)
    testRuntimeOnly(libs.junit.platformLauncher)
    testImplementation(libs.hamcrest)
    testImplementation platform(libs.mockito.bom)
    testImplementation(libs.mockito.junitJupiter)
}
