= Azure DevOps Exporter

Azure DevOps Exporter is a tool used to export test cases into https://azure.microsoft.com/en-us/services/devops/test-plans/[Azure Test Plans].

Features:

* Create and update Test Cases. VIVIDUS scenarios are mapped to Azure DevOps Test Cases by using `testCaseId` meta tags.
* Create automated Test Runs.

== Azure DevOps Export Properties

NOTE: The properties marked with *bold* are mandatory.

[cols="2,1,1,3", options="header"]
|===

|Property
|Default value
|Acceptable values
|Description

|`*azure-devops-exporter.json-results-directory*`
|
|string
a|Path to directory with test execution JSON results.

The path is managed by the `bdd.report-directory` property which default value is `output/reports/jbehave` relatively to the tests directory.

Please make sure that the `bdd.configuration.formats` property includes JSON value in order to generate test execution results.

|`*azure-devops-exporter.organization*`
|
|string
|The name of the Azure DevOps organization.

|`*azure-devops-exporter.project*`
|
|string
|Project ID or project name.

|`azure-devops-exporter.area`
|
|string
a|The area of the product which a test case is associated with.

If the Area name is inherited from the Project name in AzureDevOps this property should be empty. You can check this by making a request for any https://docs.microsoft.com/en-us/rest/api/azure/devops/wit/work-items/get-work-item?view=azure-devops-rest-7.1&tabs=HTTP[Work Item] within current Area and checking if the `System.AreaPath` contains any data besides the Project name.

|`azure-devops-exporter.section-mapping.steps`
|`AUTOMATED`
|`AUTOMATED` or `MANUAL`
|The scenario part to export into `Steps` section of `Test Case` work item, the remaining scenario part is exported into `Summary` section.

|`azure-devops-exporter.create-test-run`
|`false`
|`true` or `false`
a|Whether to create test run.

In Azure DevOps only Test Cases with https://docs.microsoft.com/en-us/azure/devops/test/associate-automated-test-with-test-case?view=azure-devops[associated automation] can be included into automated Test Run. The associated automation is automatically added by exported only for <<_automated_test_cases, Automated Test Cases>>. Attempts to include <<_manual_test_cases, Manual Test Case>> into automated Test Run will fail the execution process.

|`azure-devops-exporter.test-run.name`
|
|string
a|The test run name.

This property is mandatory when the test run creation is enabled, see `azure-devops-exporter.create-test-run` property for details.

|`azure-devops-exporter.test-run.test-plan-id`
|
|number
a|The ID of Azure DevOps Test Plan that the Azure DevOps Test Run belongs to.

In Azure DevOps Test Plan is used to group individual Test Cases and Test Suites, in their turn Test Suites are used to group Test Cases into separate testing scenarios within a single Test Plan and also may include child Test Suites. Azure DevOps allows to have an individual Test Case to be included into several Test Suites and into the Test Plan, *BUT* this is not supported by the exporter which requires the Test Case to be linked to either Test Plan or only one Test Suite, the export process fails if this condition is not met.

This property is mandatory when the test run creation is enabled, see `azure-devops-exporter.create-test-run` property for details.

The ID can be found by opening appropriate Azure DevOps Test Plan in "Test Plans" and copying number value of the `planId` query parameter in the page URL, e.g. having URL `https://dev.azure.com/organization/project/_testPlans/define?planId=911` the plan ID is 911.

|===

== Authentication properties

[cols="1,1,3", options="header"]
|===

|Property
|Acceptable values
|Description

|azure-devops.username
|`string`
|Username from Azure DevOps

|azure-devops.password
|`string`
|Personal access token

|===

== Scenario Meta Attributes

[cols="2,2,3", options="header"]
|===

|Name
|Example
|Description

|`testCaseId`
|`@testCaseId 911`
|Map scenario to Azure DevOps test case in 1 to 1 relation

|`azure-devops.skip-export`
|`@azure-devops.skip-export`
|Skip test case while exporting

|===

include::partial$test-case-types.adoc[]

:service-key: azure-devops
:gh-packages-url: https://github.com/vividus-framework/vividus/packages/929350

include::partial$export.adoc[]
