= Web Application Plugin
:proxy: This step requires proxy to be turned on: it can be done by setting the corresponding properties or by switching on @proxy meta tag at story level.
:har-attached: In case of failure the full HTTP archive (HAR) is attached to the report.

The plugin provides functionality to interact with Web applications.

== Installation

.build.gradle
[source,gradle,subs="attributes+"]
----
implementation(group: 'org.vividus', name: 'vividus-plugin-web-app', version: '{current-version}')
----


include::partial$locator-header.adoc[]


=== Filter Types

[cols="1,2,2", options="header"]
|===

|Type
|Description
|Examples

include::partial$common-filters.adoc[]

|===


=== Locator Types

[cols="1,2,1", options="header"]
|===

|Type
|Description
|Example

|linkText
|text of the link
|linkText(Google)

|linkUrl
|*href* attribute of the link element
|linkUrl(/faq)

|linkUrlPart
|part of a *href* attribute of the link element
|linkUrlPart(faq)

|caseSensitiveText
|case sensitive text of an element
|caseSensitiveText(Description)

|caseInsensitiveText
|case insensitive text of an element
|caseInsensitiveText(description)

|XPath
|https://developer.mozilla.org/en-US/docs/Web/XPath[Xpath to locate an element]
|xpath(//a)

|cssSelector
|CSS selector to an element
|cssSelector(.menu-item)

|tagName
|name of an element tagName
|tagName(a)

|imageSrc
|shortcut to a *.//img[@src='<value>>']*
|imgSrc(/images/kote.png)

|imageSrcPart
|shortcut to a *.//img[contains(@src,'<value>>')]']*
|imgSrcPart(kote.png)

|buttonName
|elements of type button or input with text or any attribute value
|buttonName(submit)

|fieldName
|input or textarea with text or any attribute value
|fieldName(editor)

|checkboxName
|input element with @type="checkbox" and text value
|checkboxName(allow)

|id
|id attribute of an element
|id(submitForm)

|className
|CSS class name
|className(bold)

|elementName
|Any attribute or text value
|elementName(OK)

|===

include::partial$visibility-types.adoc[]

=== Filter types

Filter are applied after elements search via locator. Elements not matching filter condition will be sorted out without additional notice.

[cols="1,2,3", options="header"]
|===

|Filter type
|Description
|Example

|state
|
element xref:parameters:state.adoc[State]
|id(v1)->filter.state(VISIBLE)

|caseSensitiveText
|element text should match case sensitively
|id(v1)->filter.caseSensitiveText(text)

|classAttributePart
|class attribute should contain part
|id(v1)->filter.classAttributePart(clazz)

|linkUrl
|*href* attribute of the link element
|id(v1)->filter.linkUrl(/url)

|linkUrlPart
|part of *href* attribute of the link element
|id(v1)->filter.linkUrlPart(/url)

|tooltip
|title attribute value
|id(v1)->filter.tooltip(title)

|imageSrcPart
|src attribute should contain value
|id(v1)->filter.imageSrcPart(part)

|textPart
|text of an element should contain value
|id(v1)->filter.textPart(part)

|placeholder
|Placeholder attribute should be equal to a value
|id(v1)->filter.placeholder(placeholder-value)

|validationIconSource
|CSS property background-image should match
|id(v1)->filter.validationIconSource(src)

|fieldText
|field text should match expected value
|id(v1)->filter.fieldText(value)

|fieldTextPart
|field text should contain expected value
|id(v1)->filter.fieldTextPart(value)

|dropDownText
|any of select options should be equal to a value
|id(v1)->filter.dropDownText(value)

|===


== Properties

:application-under-test: browser
:session-scope-property-base: web-application
[cols="3,1,1,3", options="header"]
|===
|Property Name
|Acceptable values
|Default
|Description

include::partial$selenium-properties.adoc[]
|screenshot.on-failure.debug-modes
|proxy
|empty
|Provides possibility to attach screenshot for failed proxy steps
|===

=== Meta Tags

`@proxy` - some steps require proxy to be turned on: it can be done by setting the corresponding properties or by switching on this meta tag at story level.


== Steps

=== Execute sequence of actions

Executes the sequence of web actions

[source,gherkin]
----
When I execute sequence of actions: $actions
----
* `$actions` - table of actions to execute

==== Possible actions

[cols="1,5,3", options="header"]
|===

|Type
|Argument
|Example

|DOUBLE_CLICK
|Search attribute or empty value
|By.linkUrl(http://httpbin.org)

|CLICK_AND_HOLD
|Search attribute or empty value
|By.linkText(Click me)

|MOVE_BY_OFFSET
|Point
|(10, 15) where *x* is 10 and *y* is 15

|RELEASE
|Search attribute or empty value
|By.tagName(div)

|ENTER_TEXT
|Text
|Minsk City

|CLICK
|Search attribute or empty value
|By.caseSensitiveText(Done)

|PRESS_KEYS
|Press xref:https://selenium.dev/selenium/docs/api/java/org/openqa/selenium/Keys.html[Keys]
|BACK_SPACE

|KEY_DOWN
|Press xref:https://selenium.dev/selenium/docs/api/java/org/openqa/selenium/Keys.html[Keys] SHIFT, ALT or CONTROL simultaneously
|CONTROL,SHIFT,ALT

|KEY_UP
|Release xref:https://selenium.dev/selenium/docs/api/java/org/openqa/selenium/Keys.html[Keys] SHIFT, ALT or CONTROL simultaneously
|CONTROL,SHIFT,ALT

|MOVE_TO
|Search attribute
|By.id(username)

|===

.ActionSteps.story
[source,gherkin]
----
When I execute sequence of actions:
|type          |argument                                |
|DOUBLE_CLICK  |By.fieldText(Hello World)               |
|DOUBLE_CLICK  |                                        |
|CLICK_AND_HOLD|By.xpath(//signature-pad-control/canvas)|
|CLICK_AND_HOLD|                                        |
|MOVE_BY_OFFSET|(-300, 0)                               |
|RELEASE       |By.xpath(//signature-pad-control/canvas)|
|RELEASE       |                                        |
|ENTER_TEXT    |Text                                    |
|CLICK         |By.placeholder(Enter your password)     |
|CLICK         |                                        |
|PRESS_KEYS    |BACK_SPACE                              |
|KEY_DOWN      |CONTROL,SHIFT                           |
|KEY_UP        |CONTROL,SHIFT                           |
|MOVE_TO       |By.id(name)                             |
----

include::partial$generic-ui-steps.adoc[]

=== Dropdown: verify available options.

Verifies if dropdown located by locator exists and has expected list of options

[source,gherkin]
----
Then dropdown located `$locator` contains options: $option
----
* `$locator` - <<_locator>>
* `$options` - examples table describing expected options

.Dropdown.story
[source,gherkin]
----
Then a drop down with the name 'colors' contains the items:
|state|item |
|false|Red  |
|false|Green|
|true |Blue |
----

[IMPORTANT]

Item - is an option. State - true/false describes if option selected


=== Dropdown: verify first selected option

Verifies if dropdown located by locator exists and first selected option.

[source,gherkin]
----
Then dropdown located `$locator` exists and selected option is `$option`
----
* `$locator` - <<_locator>>
* `$option` - first selected option

.Dropdown.story
[source,gherkin]
----
Then dropdown located `id(colors)` exists and selected option is `Blue`
----


=== Dropdown: add text to a mutli-select

Selects option in multi-select dropdown

[IMPORTANT]
Step will fail if target dropdown is not multi-select

[source,gherkin]
----
When I add `$option` to selection in dropdown located `$locator`
----
* `$option` - option to select
* `$locator` - <<_locator>>

.Dropdown.story
[source,gherkin]
----
When I add `Two` to selection in dropdown located `id(numbers)`
----


=== Dropdown: select option

Selects option in dropdown

[IMPORTANT]
Does not support multi-selection

[source,gherkin]
----
When I select `$option` in dropdown located `$locator``
----
* `$option` - option to select
* `$locator` - <<_locator>>

.Dropdown.story
[source,gherkin]
----
When I select `Red` in dropdown located `id(colors)`
----


=== Proxy - Check the number of HTTP requests

{proxy}
The actions preformed by the step:

* extract HTTP messages from the recorded proxy archive
* filter out the HTTP messages with response status code `302 Moved Temporarily`
* find HTTP requests matching the provided HTTP methods and URL regular expression
* check that total number of the found HTTP messages satisfies the desired condition

{har-attached}

[source,gherkin]
----
Then number of HTTP $httpMethods requests with URL pattern `$urlPattern` is $comparisonRule `$number`
----
* `$httpMethods` - the comma-separated HTTP methods to filter by
* `$urlPattern` - the regular expression to match HTTP request URL
* `$comparisonRule` - xref:parameters:comparison-rule.adoc[Comparison Rule]
* `$number` - The number to compare with

.Check the number of HTTP GET and POST requests matching URL regurlar expression is equal to 1
[source,gherkin]
----
Then number of HTTP GET, POST requests with URL pattern `http://httpbin\.org/get` is equal to `1`
----


=== Proxy - Save the HTTP request URL

{proxy}
The actions preformed by the step:

* extract HTTP messages from the recorded proxy archive
* filter out the HTTP messages with response status code `302 Moved Temporarily`
* find HTTP requests matching the provided HTTP methods and URL regular expression
* check that total number of the found HTTP messages is equal to 1
* save the HTTP request URL to the specified variable

{har-attached}

[source,gherkin]
----
When I capture HTTP $httpMethods request with URL pattern `$urlPattern` and save URL to $scopes variable `$variableName`
----
* `$httpMethods` - the "or"-separated HTTP methods to filter by, e.g. 'GET or POST or PUT'
* `$urlPattern` - the regular expression to match HTTP request URL
* `$scopes` - xref:parameters:variable-scope.adoc[The set of variable's scope]
* `$variableName` - the variable name

.Save the URL of the matching HTTP request to the variable
[source,gherkin]
----
Given I am on a page with the URL 'https://www.google.com/search?q=vividus'
When I capture HTTP GET or POST request with URL pattern `.*/search.*=vividus` and save URL to scenario variable `URL`
Then `${URL}` is equal to `https://www.google.com/search?q=vividus`
----


=== Proxy - Save the HTTP request URL query

{proxy}
The actions preformed by the step:

* extract HTTP messages from the recorded proxy archive
* filter out the HTTP messages with response status code `302 Moved Temporarily`
* find HTTP requests matching the provided HTTP methods and URL regular expression
* check that total number of the found HTTP messages is equal to 1
* save the HTTP request URL query to the specified variable

{har-attached}

[source,gherkin]
----
When I capture HTTP $httpMethods request with URL pattern `$urlPattern` and save URL query to $scopes variable `$variableName`
----
* `$httpMethods` - the "or"-separated HTTP methods to filter by, e.g. 'GET or POST or PUT'
* `$urlPattern` - the regular expression to match HTTP request URL
* `$scopes` - xref:parameters:variable-scope.adoc[The set of variable's scope]
* `$variableName` - the variable name

.Save the URL query of the matching HTTP request to the variable
[source,gherkin]
----
Given I am on a page with the URL 'http://httpbin.org/forms/post'
When I click on element located `By.xpath(//button)`
When I capture HTTP POST request with URL pattern `http://httpbin\.org/post` and save URL query to scenario variable `query`
Then `${query}` is equal to `{}`
----


=== Proxy - Save the HTTP message data

{proxy}
The actions preformed by the step:

* extract HTTP messages from the recorded proxy archive
* filter out the HTTP messages with response status code `302 Moved Temporarily`
* find HTTP requests matching the provided HTTP methods and URL regular expression
* check that total number of the found HTTP messages is equal to 1
* save the HTTP message data to the specified variable

{har-attached}

[source,gherkin]
----
When I capture HTTP $httpMethods request with URL pattern `$urlPattern` and save request data to $scopes variable `$variableName`
----
* `$httpMethods` - the "or"-separated HTTP methods to filter by, e.g. 'GET or POST or PUT'
* `$urlPattern` - the regular expression to match HTTP request URL
* `$scopes` - xref:parameters:variable-scope.adoc[The set of variable's scope]
* `$variableName` - the variable name

.Save the data from the matching HTTP message to the variable
[source,gherkin]
----
Given I am on a page with the URL 'http://httpbin.org/forms/post'
When I click on element located `By.xpath(//button)`
When I capture GET or HTTP POST request with URL pattern `http://httpbin\.org/post` and save request data to scenario variable `data`
Then `${data.query}` is equal to `{}`
Then `${data.requestBodyParameters}` is equal to `{delivery=, custtel=, comments=, custemail=, custname=}`
Then `${data.requestBody}` is not equal to `null`
Then `${data.responseStatus}` is equal to `200`
----


=== Proxy - Wait for the HTTP request

{proxy}
Waits for the HTTP requests matching the provided HTTP methods and URL regular expression.
If no HTTP request is sent and wait timeout is reached, then the step will fail.

[source,gherkin]
----
When I wait until HTTP $httpMethods request with URL pattern `$urlPattern` exists in proxy log
----
* `$httpMethods` - the "or"-separated HTTP methods to filter by, e.g. 'GET or POST or PUT'
* `$urlPattern` - the regular expression to match HTTP request URL

.Wait for the HTTP request
[source,gherkin]
----
Given I am on a page with the URL 'http://httpbin.org/get'
When I wait until HTTP GET or POST request with URL pattern `http://httpbin\.org/get` exists in proxy log
Then number of HTTP GET or POST requests with URL pattern `http://httpbin\.org/get` is equal to `1`
----


=== Proxy - Add headers to the HTTP request

{proxy}
Add headers to the proxied HTTP request satisfying the desired condition

[source,gherkin]
----
When I add headers to proxied requests with URL pattern which $comparisonRule `$url`:$headers
----
* `$comparisonRule` - xref:parameters:string-comparison-rule.adoc[String comparison rule]
* `$url` - the input value of URL to filter by
* `$headers` - ExamplesTable representing the list of the headers with columns "name" and "value" specifying HTTP header names and values respectively

.Add headers to the proxied HTTP request
[source,gherkin]
----
When I add headers to proxied requests with URL pattern which is equal to `http://httpbin.org/headers`:
|name     |value     |
|testName1|testValue1|
|testName2|testValue2|
Given I am on a page with the URL 'http://httpbin.org/headers'
When I change context to element located `xpath(//pre)`
When I set the text found in search context to the 'SCENARIO' variable 'response'
Then a JSON element from '${response}' by the JSON path '$.headers' is equal to '
{
    "Testname1": "testValue1",
    "Testname2": "testValue2"
}
'ignoring extra fields
----


=== Proxy - Clear

{proxy}
The step clears the HTTP requests and responses recorded by the proxy

[source,gherkin]
----
When I clear proxy log
----

.Clear the data recorded by the proxy
[source,gherkin]
----
Given I am on a page with the URL 'http:/httpbin.org/get'
When I clear proxy log
Then number of HTTP GET requests with URL pattern `http://httpbin\.org/get` is equal to `0`
----


== Dynamic variables

Dynamic variables is variables available out of the box using standard approach `$\{variable-name\}` Usually the data provided by dynamic variables calculated at runtime.


=== Context element rectangle

Provides possibility to access context element coordinates, width and height.

[IMPORTANT]

Variable uses contextual approach. So it is necessary to switch context to a target element.


==== *Variable name*

[cols="1,3", options="header"]
|===

|Variable name
|Description

|context-height
|provided context element height

|context-width
|provided context element width

|context-x-coordinate
|provided context element absolute X coordinate

|context-y-coordinate
|provided context element absolute Y coordinate

|===


==== *Usage example*

[source,gherkin]
----
When I change context to element located `tagName(img)`
Then `${context-height}` is > `0`
Then `${context-width}` is > `0`
Then `${context-x-coordinate}` is > `0`
Then `${context-y-coordinate}` is > `0`
----
