= Web Application Plugin: Playwright Engine

The plugin provides functionality to interact with Web applications with help of https://playwright.dev/java/[Playwright] engine.

:plugin-short-name: web-app-playwright
include::partial$plugin-installation.adoc[]

== Properties

NOTE: The properties marked with *bold* are mandatory.

[cols="3,2,2,3", options="header"]
|===
|Property Name
|Acceptable values
|Default
|Description

include::partial$common-web-app-properties.adoc[]

|`playwright.tracing.output-directory`
|A relative or absolute path of the directory on the file system
|`${output.report-directory}/playwright-traces`
|When any tracing option is enabled, the traces are recorded and saved to the specified directory. Every session
is stored in the own file, the full path to the file is printed in the logs.

|`playwright.tracing.screenshots-enabled`
a|`true` +
`false`
|`false`
|When tracing with the https://playwright.dev/java/docs/trace-viewer#screenshots[screenshots option] turned on,
each trace records a screencast and renders it as a film strip.

|`playwright.tracing.snapshots-enabled`
a|`true` +
`false`
|`false`
|When tracing with the https://playwright.dev/java/docs/trace-viewer#snapshots[snapshots option] turned on,
Playwright captures a set of complete DOM snapshots for each action.

|`ui.wait.timeout`
|{durations-format-link} format
|`PT1M`
|Total duration to wait for UI condition

|===

== Locator

----
By.<locatorType>(<locatorValue>):<visibility>
----

[IMPORTANT]

By. prefix is optional.

. `locatorType` - *[mandatory]* type of the locator
. `locatorValue` - *[mandatory]* value of the locator
. `visibility` - *[optional]* visibility of element (visible by default)


=== Locator Types

[cols="1,3,2", options="header"]
|===

|Type
|Description
|Example

|`id`
|Locates elements whose `id` attribute matches the search value
|id(submitBtn)

|`css`
|Locates elements matching a https://playwright.dev/java/docs/locators#locate-by-css-or-xpath[CSS selector]
|css(.menu-item)

|`xPath`
|Locates elements matching an https://playwright.dev/java/docs/locators#locate-by-css-or-xpath[xPath expression]
|xpath(//a)

|===

=== Visibility types

[cols="1,1,3", options="header"]
|===

|Visibility type
|Usage example
|Description

|VISIBLE
|xpath(//a)
|Default visibility option. Only visible elements will be found

|all
|xpath(//a):a
|Either visible and invisible elements will be found

|===

== Steps
include::plugins:partial$common-web-app-steps.adoc[]
include::plugins:partial$ui-context-management-steps.adoc[]

=== Tab steps
==== Open a new tab

Opens a new browser tab and switches the focus for future commands to this tab.

[source,gherkin]
----
When I open new tab
----

.Open page in a new tab
[source,gherkin]
----
When I open new tab
Given I am on page with URL `https://docs.vividus.dev`
----

==== Close current tab

Closes the current tab and switches to the last browser tab.

[source,gherkin]
----
When I close current tab
----

NOTE: This step can only be applied to a session with multiple tabs open.

.Open URL in new tab, close it and switch to the previous page
[source,gherkin]
----
Given I am on page with URL `https://example.com`
When I open new tab
Given I am on page with URL `https://example.com/contact-us`
When I close current tab
----

=== Mouse Actions
==== Click on the element

Finds the element by the given locator and performs a click in the center of the element if it's found
(at first moves mouse to the location of the element).

[source,gherkin]
----
When I click on element located by `$locator`
----

* `$locator` - The <<_locator,locator>> used to find the element to click.

.Click on element with name `Submit`
[source,gherkin]
----
When I click on element located by `name(Submit)`
----

include::plugins:partial$common-web-app-mouse-steps.adoc[]

include::plugins:partial$common-web-app-field-steps.adoc[]
==== Clear field

Finds the field by the given locator and clears it if it's found.

[source,gherkin]
----
When I clear field located by `$locator`
----
* `$locator` - The <<_locator,locator>> used to find the field to clear.

.Clear the field with attribute `id` having value `email`
[source,gherkin]
----
When I clear field located by `id(email)`
----

include::plugins:partial$ui-elements-validation-steps.adoc[]

include::plugins:partial$ui-text-content-steps.adoc[]

==== Save the text of the context

Saves the text of the context into a variable.

[source,gherkin]
----
When I save text of context to $scopes variable `$variableName`
----

* `$scopes` - The comma-separated set of the xref:commons:variables.adoc#_scopes[variables scopes].
* `$variableName` - The name of the variable to save the text content.

.Save the text of the context
[source,gherkin]
----
When I change context to element located by `id(username)`
When I save text of context element to scneario variable `username`
----

=== Saves the attribute value of the context

Saves the attribute value of the context element into a variable.

[source,gherkin]
----
When I save `$attributeName` attribute value of context element to $scopes variable `$variableName`
----

* `$attributeName` - The name of an element attribute.
* `$scopes` - xref:commons:variables.adoc#_scopes[The comma-separated set of the variables scopes].
* `$variableName` - The name of the variable to save the attribute value.

.Save the attribute value of the context element
[source,gherkin]
----
When I change context to element located by `id(username)`
When I save `innerText` attribute value of context element to SCENARIO variable `username`
----

=== Save the attribute value of the element

Saves the attribute value of the element located by locator into a variable.

[source,gherkin]
----
When I save `$attributeName` attribute value of element located by `$locator` to $scopes variable `$variableName`
----

* `$attributeName` - The name of an element attribute.
* `$locator` - <<_locator>>.
* `$scopes` - xref:commons:variables.adoc#_scopes[The comma-separated set of the variables scopes].
* `$variableName` - The name of the variable to save the attribute value.

Save the attribute value of the element
[source,gherkin]
----
When I save `innerText` attribute value of element located by `id(username)` to SCENARIO variable `username`
----

include::plugins:partial$ui-elements-quantity-steps.adoc[]

include::plugins:partial$ui-size-and-coordinates-steps.adoc[]

include::plugins:partial$common-web-app-text-steps.adoc[]

=== Wait for element appearance

Waits for appearance of the element by the locator.

[source,gherkin]
----
When I wait until element located by `$locator` appears
----

* `$locator` - <<_locator>>.

.Wait for appearance of the element with the specified id
[source,gherkin]
----
When I wait until element located by `id(welcome-image)` appears
----


=== Wait for element disappearance

Waits for disappearance of the element by the locator.

NOTE: If the element doesn't exist on the page/context, the step will immediately complete successfully.

[source,gherkin]
----
When I wait until element located by `$locator` disappears
----

* `$locator` - <<_locator>>.

.Wait for disappearance of the element with the specified id
[source,gherkin]
----
When I wait until element located by `id(welcome-image)` disappears
----

=== Wait for expected elements number

Waits for the expected number of elements located by locator.

[source,gherkin]
----
When I wait until number of elements located by `$locator` is $comparisonRule $number
----

* `$locator` - <<_locator>>.
* `$comparisonRule` - xref:parameters:comparison-rule.adoc[The comparison rule].
* `$number` - The expected number of the elements.

.Wait for the visible elements
[source,gherkin]
----
When I wait until number of elements located by `xpath(//a)` is equal to `5`
----

=== JavaScript steps
==== Execute JavaScript

Executes passed JavaScript code on the opened page.

[source,gherkin]
----
When I execute javascript `$jsCode`
----
* `$jsCode` - The JavaScript code.

.Click on the link using JavaScript
[source,gherkin]
----
Given I am on page with URL `https://vividus-test-site-a92k.onrender.com`
When I execute javascript `document.querySelector('a').click()`
----

==== Execute JavaScript and save result

Executes passed JavaScript code on the opened page and saves result into variable.

[source,gherkin]
----
When I execute javascript `$jsCode` and save result to $scopes variable `$variableName`
----
* `$jsCode` - The JavaScript code with return value.
* `$scopes` - xref:commons:variables.adoc#_scopes[The comma-separated set of the variables scopes].
* `$variableName` - The variable name to script execution result.

.Validate timings
[source,gherkin]
----
Given I am on page with URL `https://vividus-test-site-a92k.onrender.com/`
When I execute javascript `JSON.stringify(window.performance.timing)` and save result to scenario variable `timings`
Then number of JSON elements from `${timings}` by JSON path `$.connectStart` is = 1
----

=== Context steps
==== Switch to the default context of page

Switches context to the root https://developer.mozilla.org/en-US/docs/Web/HTML/Element/html[<html>] element of the current page.

[source,gherkin]
----
When I switch back to page
----

.Switch to user context and back to the default context of page
----
Given I am on page with URL `https://vividus-test-site-a92k.onrender.com/elementState.html`
When I change context to element located by `id(button-hide)`
Then text `Element to hide` does not exist
When I switch back to page
Then text `Element to hide` exists
----

==== Switch context to a frame

Switches to https://developer.mozilla.org/en-US/docs/Web/HTML/Element/iframe[<iframe>] or https://developer.mozilla.org/en-US/docs/Web/HTML/Element/frame[<frame>] element using one of the supported locators.

[source,gherkin]
----
When I switch to frame located by `$locator`
----

* `$locator` - <<_locator>> of frame element.

.Switch to frame
----
Given I am on page with URL `https://vividus-test-site-a92k.onrender.com/nestedFrames.html`
Then text `Modal Frame Example` does not exist
When I switch to frame located by `id(parent)`
Then text `Modal Frame Example` exists
----

=== Select an option in dropdown

Selects the first https://developer.mozilla.org/en-US/docs/Web/HTML/Element/option[option] in dropdown whose https://developer.mozilla.org/en-US/docs/Web/HTML/Element/option#value[value attribute] is equal to the provided value (case-insensitive).

[source,gherkin]
----
When I select `$option` in dropdown located by `$locator`
----

* `$option` - The option to select.
* `$locator` - The <<_locator,locator>> used to find dropdown.

.Select option with the value `Red` in dropdown
[source,gherkin]
----
When I select `Red` in dropdown located by `id(colors)`
----

include::plugins:partial$ui-element-css-property-steps.adoc[]

include::plugins:partial$ui-elements-conditional-iteration-steps.adoc[]

include::plugins:partial$ui-execution-on-each-element-steps.adoc[]

include::plugins:partial$web-cookie-steps.adoc[]

=== Upload file

Uploads the xref:ROOT:glossary.adoc#_resource[resource] or file via web interface.

[source,gherkin]
----
When I select element located by `$locator` and upload `$resourceNameOrFilePath`
----

* `$locator` - the <<_locator,locator>> of the web element with *input* tag and attribute *type=file*
* `$resourceNameOrFilePath` - relative path to the file to be uploaded

.Upload file_for_upload.png file
[source,gherkin]
----
When I select element located by `id(uploadfile)` and upload file `/folder/file_for_upload.png`
----
