= Azure Storage Account Plugin

The plugin provides functionality to interact with https://docs.microsoft.com/en-us/azure/storage/[Azure Storage Account].

== Installation

.build.gradle
[source,gradle,subs="attributes+"]
----
implementation(group: 'org.vividus', name: 'vividus-plugin-azure-storage-account', version: '{current-version}')
----

== Configuration

include::partial$azure-authentication.adoc[]

=== Properties

The storage accounts endpoints are configured with the following property format:

[source,properties]
----
azure.storage-account.<key>=<endpoint>
----

where:

. `key` - The logical key used to refer storage account in the steps.
. `endpoint` - The storage account endpoint, e.g. `https://storageaccount.blob.core.windows.net/`

== Steps

=== Download blob

Downloads a blob text content

[source,gherkin]
----
When I download blob with name `$blobName` from container `$containerName` in storage account `$storageAccountKey` and save its content to $scopes variable `$variableName`
----

* `$blobName` - The full path to a blob in the container.
* `$containerName` - The name of the container.
* `$storageAccountKey` - The key of storage account from the configuration.
* `$scopes` - xref:parameters:variable-scope.adoc[The comma-separated set of the variables scopes].
* `$variableName` - The variable name to store the blob.

.Download a blob
[source,gherkin]
----
When I download blob with name `raw/test.json` from container `vividus` in storage account `test-account` and save its content to scenario variable `blob`
----

=== Download blob to a temporary file

Downloads a blob to a local temporary file

[source,gherkin]
----
When I download blob located at `$blobName` from container `$containerName` in storage account `$storageAccountKey` to temporary file with name `$baseFileName` and save path to $scopes variable `$variableName`
----

* `$blobName` - The full path to a blob in the container.
* `$containerName` - The name of the container.
* `$storageAccountKey` - The key of storage account from the configuration.
* `$baseFileName` - The base file name used to generate the prefix and the suffix for the creating temporary file.
* `$scopes` - xref:parameters:variable-scope.adoc[The comma-separated set of the variables scopes].
* `$variableName` - The variable name to store the path to the temporary file with the blob content.

.Download a blob to a temporary file
[source,gherkin]
----
When I download blob located at `raw/test.json` from container `vividus` in storage account `test-account` to temporary file with name `test.json` and save blobName to scenario variable `pathToABlob`
----

=== Delete blob

Deletes a blob by the path

[source,gherkin]
----
When I delete blob located at `$blobName` from container `$containerName` in storage account `$storageAccountKey`
----

* `$blobName` - The full path to a blob in the container.
* `$containerName` - The name of the container.
* `$storageAccountKey` - The key of storage account from the configuration.

.Delete a blob
[source,gherkin]
----
When I delete blob located at `raw/test.json` from container `vividus` in storage account `test-account`
----

=== Find blobs

Finds the blobs with names matching the specified comparison rule.

[source,gherkin]
----
When I find all blobs with name which $comparisonRule `$blobNameToMatch` from container `$containerName` in storage account `$storageAccountKey` and save result to $scopes variable `$variableName`
----

* `$comparisonRule` - xref:parameters:string-comparison-rule.adoc[The blob name comparison rule].
* `$blobNameToMatch` - The full or partial blob name to be matched.
* `$containerName` - The name of the container.
* `$storageAccountKey` - The key of storage account from the configuration.
* `$scopes` - xref:parameters:variable-scope.adoc[The comma-separated set of the variables scopes].
* `$variableName` - The variable name to store the list of found blob names.

.Find blobs
[source,gherkin]
----
When I find all blobs with name which contains `json` from container `vividus` in storage account `test-account` and save result to scenario variable `blobsCollection`
----
