= Plugin Web App
:proxy: This step requires proxy to be turned on. It can be done via setting properties or switching on @proxy metatag.

== General Info

The plugin provides functionality to interact with Web applications.

== Installation

.build.gradle
[source,gradle]
----
implementation(group: 'org.vividus', name: 'vividus-plugin-web-app', version: '0.2.4')
----


== Properties

=== Required

There are no required properties for the plugin.

=== Optional

@proxy - Some steps requires proxy to be turned on. It can be done via setting properties or switching on @proxy metatag.

== Steps

=== Clear proxy log

==== *_Info_*

Clears the proxy log

==== *_Wording_*

[source,gherkin]
----
When I clear proxy log
----

==== *_Usage_*

.ProxyStepsTests.story
[source,gherkin]
----
Scenario: Verify step When I clear proxy log
Given I am on a page with the URL 'http:/httpbin.org/get'
When I clear proxy log
Then number of HTTP GET requests with URL pattern `http://httpbin.org/get` is EQUAL TO `0`
----


=== Check if the number of requests with given URL-pattern exist

==== *_Info_*

{proxy}
Step gets proxies log, extract from contained requests URLs and match them with URL-pattern
If URLs are the same, there were calls with given URL-pattern, otherwise - weren't.
If there weren't any calls matching requirements, HAR file with all calls will be attached to report.
If response contains status code 302 - corresponding request will be filtered out.

==== *_Wording_*

[source,gherkin]
----
Then number of HTTP $httpMethod requests with URL pattern `$urlPattern` is $comparisonRule `$number`
----

==== *_Parameters_*

. `$httpMethod` - HTTP method to filter by
. `$urlPattern` - the string value of URL-pattern to filter by
. `$comparisonRule` - xref:parameters:comparison-rule.adoc[Comparison Rule]
. `$number` - The number to compare with

==== *_Usage_*

.ProxyStepsTests.story
[source,gherkin]
----
Scenario: Verify step When I clear proxy log
Given I am on a page with the URL 'http:/httpbin.org/get'
When I clear proxy log
Then number of HTTP GET requests with URL pattern `http://httpbin.org/get` is EQUAL TO `0`
----


=== Execute sequence of actions

==== *_Info_*

Executes the sequence of web actions

==== *_Wording_*

[source,gherkin]
----
When I execute sequence of actions: $actions
----

==== *_Parameters_*

. `$actions` - xref:parameters:action-scope.adoc[table of actions to execute]

==== *_Usage_*

.ActionSteps.story
[source,gherkin]
----
Scenario: Action verification CLICK with no argument
Given I am on a page with the URL '${vividus-test-site-url}/mouseEvents.html'
When I initialize the scenario variable `expectedText` with value `Good day!`
Then the text '${expectedText}' does not exist
When I execute sequence of actions:
|type   |argument                             |
|MOVE_TO|By.xpath(//button[text()='Click me'])|
|CLICK  |                                     |
Then the text '${expectedText}' exists
----


=== Saves the query string into the variable with specified name and scopes.

==== *_Info_*

{proxy}
Step gets proxies log, extract from contained requests URLs and match them with URL-pattern
If there is one entry, it saves the query string from request as Map of keys and values into the variable with specified name and scopes.
If there weren't any calls or more than one matching requirements, HAR file with all
calls will be attached to report.

==== *_Wording_*

[source,gherkin]
----
When I capture HTTP $httpMethod request with URL pattern `$urlPattern` and save URL query to $scopes variable `$variableName`
----

==== *_Parameters_*

. `$httpMethod` - HTTP method to filter by
. `$urlPattern` - the string value of URL-pattern to filter by
. `$scopes` - xref:parameters:variable-scope.adoc[The set of variable's scope]
. `$variableName` - A variable name

==== *_Usage_*

.ProxyStepsTests.story
[source,gherkin]
----
Scenario: Verify step When I capture HTTP $httpMethod request with URL pattern `$urlPattern` and save URL query to $scopes variable `$variableName`
Given I am on a page with the URL 'http://httpbin.org/forms/post'
When I click on element located `By.xpath(//button)`
When I capture HTTP POST request with URL pattern `http://httpbin.org/post` and save URL query to SCENARIO variable `query`
Then `${query}` is equal to `{}`
----


=== Saves the request data into the variable with specified name and scopes.

==== *_Info_*

{proxy}
Step gets proxies log, extract from contained requests URLs and match them with URL-pattern
If there is one entry, it saves the query string from request as Map of keys and values into the variable with specified name and scopes.
If there weren't any calls or more than one matching requirements, HAR file with all calls will be attached to report.

==== *_Wording_*

[source,gherkin]
----
When I capture HTTP $httpMethod request with URL pattern `$urlPattern` and save request data to $scopes variable `$variableName`
----

==== *_Parameters_*

. `$httpMethod` - HTTP method to filter by
. `$urlPattern` - the string value of URL-pattern to filter by
. `$scopes` - xref:parameters:variable-scope.adoc[The set of variable's scope]
. `$variableName` - A variable name

==== *_Usage_*

.ProxyStepsTests.story
[source,gherkin]
----
Scenario: Verify step When I capture HTTP $httpMethod request with URL pattern `$urlPattern` and save request data to $scopes variable `$variableName`
Given I am on a page with the URL 'http://httpbin.org/forms/post'
When I click on element located `By.xpath(//button)`
When I capture HTTP POST request with URL pattern `http://httpbin.org/post` and save request data to SCENARIO variable `requestData`
Then `${requestData.query}` is equal to `{}`
Then `${requestData.requestBodyParameters}` is equal to `{delivery=, custtel=, comments=, custemail=, custname=}`
Then `${requestData.requestBody}` is not equal to `null`
Then `${requestData.responseStatus}` is equal to `200`
----


=== Waits for appearance of HTTP request matched httpMethod and urlPattern in proxy log

==== *_Info_*

Waits for appearance of HTTP request matched httpMethod and urlPattern in proxy log

==== *_Wording_*

[source,gherkin]
----
When I wait until HTTP $httpMethod request with URL pattern `$urlPattern` exists in proxy log
----

==== *_Parameters_*

. `$httpMethod` - HTTP method to filter by
. `$urlPattern` - The string value of URL-pattern to filter by

==== *_Usage_*

.ProxyStepsTests.story
[source,gherkin]
----
Scenario: Verify step When I wait until HTTP $httpMethod request with URL pattern `$urlPattern` exists in proxy log
Given I am on a page with the URL 'http://httpbin.org/get'
When I wait until HTTP GET request with URL pattern `http://httpbin.org/get` exists in proxy log
Then number of HTTP GET requests with URL pattern `http://httpbin.org/get` is EQUAL TO `1`
----


=== Verify elements state

==== *_Info_*

Verifies if the number of elements located by locator matches number condition and all of them are in desired state

[IMPORTANT]

If you describer number condition as equal to 5 in case if there are 10 elements by this locator and only 5 of them in the desired state. You will get two failed assertions.
The first one about number condition violation. The second one about state check failure.

==== *_Wording_*

[source,gherkin]
----
Then number of $state elements found by `$locator` is $comparisonRule `$quantity`
----

==== *_Parameters_*

. `$state` - xref:parameters:state.adoc[State]
. `$locator` - xref:parameters:locator.adoc[Locator]
. `$comparisonRule` - xref:parameters:comparison-rule.adoc[Comparison rule]
. `$quantity` - expected number of elements

==== *_Usage_*

.VerifyState.story
[source,gherkin]
----
Scenario: Step verification 'Then number of $state elements found by `$locator` is $comparisonRule `$quantity`'
Given I am on a page with the URL '${vividus-test-site-url}'
Then number of VISIBLE elements found by `tagName(img)` is = `1`
----


== Dynamic variables

Dynamic variables is variables available out of the box using standard approach `$\{variable-name\}` Usually the data provided by dynamic variables calculated at runtime.


=== Context element rectangle

Provides possibility to access context element coordinates, width and height.

[IMPORTANT]

Variable uses contextual approach. So it is necessary to switch context to a target element.


==== *Variable name*

[cols="1,3", options="header"]
|===

|Variable name
|Description

|context-height
|provided context element height

|context-width
|provided context element width

|context-x-coordinate
|provided context element absolute X coordinate

|context-y-coordinate
|provided context element absolute Y coordinate

|===


==== *Usage example*

[source,gherkin]
----
When I change context to element located `tagName(img)`
Then `${context-height}` is > `0`
Then `${context-width}` is > `0`
Then `${context-x-coordinate}` is > `0`
Then `${context-y-coordinate}` is > `0`
----
