= Relational Database Plugin

The plugin provides capabilities to work with relational databases via
https://en.wikipedia.org/wiki/Java_Database_Connectivity[JDBC] and contains
a set of the steps for comparison of data tables.

== Installation

.build.gradle
[source,gradle,subs="attributes+"]
----
implementation(group: 'org.vividus', name: 'vividus-plugin-db', version: '{current-version}')
----

== Configuration

=== Data Comparison

[cols="4,2,1,4", options="header"]
|===
|Property name
|Acceptable values
|Default
|Description


|`db.duplicate-keys-strategy`
a|`NOOP`

`DISTINCT`
|`NOOP`
a|The strategy defining how records with duplicate keys should be handled:

* `NOOP` - the records with duplicate keys are compared in the order they are returned by the query or presented in the expected data
* `DISTINCT` - only 1 top record from left and right sides are compared, other records with duplicate keys are ignored

|`db.diff-limit`
|integer
|`100`
|The max number of records in the comparison result output

|`db.query-timeout`
|{iso-date-format-link} duration
|`PT30M`
|The maximum time to wait for DB query completion

|===


== Table Transformers

NOTE: The table transformers properties marked with *bold* are mandatory.

=== FROM_DB

`FROM_DB` transformer generates table based on the data retirved from the
specified database using SQL query.

[cols="1,3", options="header"]
|===
|Parameter
|Description

|`*dbKey*`
|Database key

|`*sqlQuery*`
|SQL `SELECT` query to retrieve the data from DB

|`nullReplacement`
|The value to put in the generating table instead of `NULL`-s contained in the DB data set
|===

.Generate ExampleTable using data from H2 database
[source,gherkin]
----
{transformer=FROM_DB, dbKey=testh2db, sqlQuery=SELECT * FROM students, nullReplacement= }
----
