= REST API Plugin

The plugin provides the following abilities:

* build and send HTTP requests
* validate HTTP responses (headers, status code, body)
* validate JSON content of HTTP response bodies

== Installation

.build.gradle
[source,gradle,subs="attributes+"]
----
implementation(group: 'org.vividus', name: 'vividus-plugin-rest-api', version: '{page-component-version}')
----


== Properties

[WARNING]
To be implemented

== Steps

=== Verify secure protocols supported by server

==== *_Info_*

Checks that a server defined by the `hostname` supports secure protocols listed in the `protocols` parameter.

==== *_Wording_*

[source,gherkin]
----
Then server `$hostname` supports secure protocols that $rule `$protocols`
----

==== *_Parameters_*

. `$hostname` - server hostname.
. `$rule` - xref:parameters:collection-comparison-rule.adoc[Collection Comparison Rule]
. `$protocols` - secure protocols that are expected to match specified `$rule`

==== *_Usage_*

.Sample.story
[source,gherkin]
----
Scenario: Verify that the server supports TLSv1.3 and TLSv1.2 protocols
Then server `vividus-test-site.herokuapp.com` supports secure protocols that contain `TLSv1.3,TLSv1.2`
----

=== Wait for JSON element to be returned in HTTP response

==== *_Info_*

Execute the provided sub-steps until the HTTP response body contains an element by the specified JSON path or until the maximum number of retries is reached. The maximum duration of the step execution is not limited. The actions of the step:
. execute sub-steps
. wait for the polling interval
. if the required JSON element exists or the maximum number of retries is reached, then execution stops, otherwise the step actions are repeated

==== *_Wording_*

[source,gherkin]
----
When I wait for presence of element by `$jsonPath` with `$pollingInterval` polling interval retrying $retryTimes times$stepsToExecute
----

==== *_Parameters_*

. `jsonPath` - the JSON path of the element to find
. `pollingInterval` - the duration to wait between retries
. `retryTimes` - the maximum number of the retries
. `stepsToExecute` - the sub-steps to execute at each iteration

==== *_Usage_*

.Sample.story
[source,gherkin]
----
Scenario: Wait for presence of element by JSON path $.data.testData
When I wait for presence of element by `$.data.testData` with `PT5S` polling interval retrying 10 times
|step                                  |
|When I set request headers:           |
|{headerSeparator=!,valueSeparator=!}  |
|!name          !value                !|
|!Authorization !${accessToken}       !|
|When I issue a HTTP GET request for a resource with the URL '${requestUrl}'|
----

=== Adding headers to HTTP request

==== *_Info_*

Adds headers to HTTP request. See https://en.wikipedia.org/wiki/List_of_HTTP_header_fields#Request_fields[standard request fields].

==== *_Wording_*

[source,gherkin]
----
When I add request headers:$headers
----

==== *_Parameters_*

. `headers` - ExamplesTable representing list of headers with columns `name` and `value` specifying HTTP header

==== *_Usage_*

.Sample.story
[source,gherkin]
----
Scenario: Verify possibility to add request header with name Accept-Language and value en-ru
When I add request headers:
|name           |value |
|Accept-Language|en-ru |
When I send HTTP GET to the relative URL '/get?name=Content'
Then a JSON element by the JSON path '$.headers.Accept-Language' is equal to '"en-ru"'
----

== Expressions


=== URI Encoding

`${encodeUriXyz(..)}` is a family of expressions that encode specific URI components (e.g. path, query)
by percent encoding illegal characters, which includes non-US-ASCII characters, and also characters that
are otherwise illegal within the given URI component type, as defined in
https://www.ietf.org/rfc/rfc3986.txt[RFC 3986].

[cols="3,2", options="header"]
|===
|Syntax
|Description

|`#{encodeUriUserInfo($userInfo)}`
|Encode the given URI user info

|`#{encodeUriHost($host)}`
|Encode the given URI host

|`#{encodeUriPath($path)}`
|Encode the given URI path

|`#{encodeUriPathSegment($segment)}`
|Encode the given URI path segment

|`#{encodeUriQuery($query)}`
|Encode the given URI query

|`#{encodeUriQueryParameter($queryParameter)}`
|Encode the given URI query parameter

|`#{encodeUriFragment($fragment)}`
|Encode the given URI fragment
|===

==== Examples

|===
|Expression |Result

|`#{encodeUriUserInfo(user@vividus.dev:pass)}`
|user%40vividus.dev:pass

|`#{encodeUriHost(vividus.бел)}`
|vividus.%D0%B1%D0%B5%D0%BB

|`#{encodeUriPath(/path/with spaces/)}`
|/path/with%20spaces/

|`#{encodeUriPathSegment(path/segment)}`
|path%2Fsegment

|`#{encodeUriQuery(a&b=c d)}`
|a&b=c%20d

|`#{encodeUriQueryParameter(a&b)}`
|a%26b

|`#{encodeUriFragment(frag ment)}`
|frag%20ment

|===
