:azure-service-name: event-grid

= Azure Event Grid Plugin

The plugin provides functionality to interact with https://azure.microsoft.com/en-us/services/event-grid/[Event Grid]

== Installation

.build.gradle
[source,gradle,subs="attributes+"]
----
implementation(group: 'org.vividus', name: 'vividus-plugin-azure-event-grid', version: '{current-version}')
----

== Interaction with topics

=== Topics configuration

Topics are configured with a set of properties with the following format:

[source,properties]
----
azure.event-grid.{topic-name}.{property-name}=property value
----

Where:

. `topic-name` - The name of the topic which will be used as a step parameter
. `property-name` - The name of the topic property. One of:
.. `key` - The topic access key
.. `event-schema` - The kind of https://docs.microsoft.com/en-us/azure/event-grid/event-schema[schema] (GRID, CLOUD or CUSTOM)
.. `endpoint` - The topic endpoint

=== Steps

==== Publish event

Publishes an event to a topic

[source,gherkin]
----
When I send event to `$topicName` topic with payload:$payload
----

* `$topicName` - The name of the topic, will be used to find required properties values
* `$payload` - The JSON payload to send to a topic

.Send an event
[source,gherkin]
----
When I send event to `create-user` topic with payload:
{
  "id": "1807",
  "eventType": "RegisterVehicle",
  "subject": "myapp/vehicles/motorcycles",
  "eventTime": "2017-08-10T21:03:07+00:00",
  "data": {
    "make": "Ducati",
    "model": "Monster"
  },
  "dataVersion": "1.0"
}
----

== Topic management

=== Configuration

include::partial$azure-authentication.adoc[leveloffset=+1]

include::partial$azure-profile-and-subscription.adoc[leveloffset=+1]

=== Steps

==== Collect system topics info

Collects system topics info in the specified resource group and saves it as
JSON to a variable.

[source,gherkin]
----
When I collect system topics in resource group `$resourceGroupName` and save them as JSON to $scopes variable `$variableName`
----

* `$resourceGroupName` - The name of the resource group to list the system topics from.
* `$scopes` - xref:commons:variables.adoc#_scopes[The comma-separated set of the variables scopes].
* `$variableName` - The variable name to store the info about system topics as JSON.

[IMPORTANT]
====
The client should have permission to run action `Microsoft.EventGrid/systemTopics/read`
over scope `/subscriptions/{subscription ID}/resourceGroups/{resource group name}/providers/Microsoft.EventGrid`.
====

.Collect system topics info
[source,gherkin]
----
When I collect system topics in resource group `TEST-SA` and save them as JSON to scenario variable `system-topics`
----
