= Web Application Plugin
:grid-default-hostname: empty
:given-step: Given I am on a page with the URL 'https://www.google.com/search?q=vividus'

The plugin provides functionality to interact with Web applications.

== Installation

.build.gradle
[source,gradle,subs="attributes+"]
----
implementation(group: 'org.vividus', name: 'vividus-plugin-web-app', version: '{current-version}')
----


include::partial$locator-header.adoc[]


=== Locator Types

[cols="2,3,3", options="header"]
|===

|Type
|Description
|Example


|`id`
|id attribute of an element
|id(submitForm)

|`cssSelector`
|CSS selector to an element
|cssSelector(.menu-item)

|`xPath`
|https://developer.mozilla.org/en-US/docs/Web/XPath[Xpath to locate an element]
|xpath(//a)

|`tagName`
|name of an element tagName
|tagName(a)

|`className`
|CSS class name
|className(bold)

|`linkText`
|text of the link
|linkText(Google)

|`linkUrl`
|*href* attribute of the link element
|linkUrl(/faq)

|`linkUrlPart`
|part of a *href* attribute of the link element
|linkUrlPart(faq)

|`caseSensitiveText`
|case sensitive text of an element
|caseSensitiveText(Description)

|`caseInsensitiveText`
|case insensitive text of an element
|caseInsensitiveText(description)

|`imageSrc`
|shortcut to a *.//img[@src='<value>>']*
|imgSrc(/images/kote.png)

|`imageSrcPart`
|shortcut to a *.//img[contains(@src,'<value>>')]']*
|imgSrcPart(kote.png)

|`buttonName`
|elements of type button or input with text or any attribute value
|buttonName(submit)

|`fieldName`
|input or textarea with text or any attribute value
|fieldName(editor)

|`checkboxName`
|input element with @type="checkbox" and text value
|checkboxName(allow)

|`elementName`
|any attribute or text value
|elementName(OK)

|`shadowCssSelector`
|chain of css selectors, separated by `;`, where first value - selector for upper shadow host, last value - target element selector
|shadowCssSelector(.upperHost; #innerHost1; #innerHost2; .targetValue)

|===

include::partial$visibility-types.adoc[]

=== Filter types

The filters are applied after elements search using of the locators specified above.
The elements not matching the filter condition are sorted out without any notice.

[cols="1,2,3", options="header"]
|===

|Filter type
|Description
|Example

include::partial$common-filters.adoc[]

|`state`
|element xref:parameters:state.adoc[State]
|id(v1)->filter.state(VISIBLE)

|`caseSensitiveText`
|element text should match case sensitively
|id(v1)->filter.caseSensitiveText(text)

|`classAttributePart`
|class attribute should contain part
|id(v1)->filter.classAttributePart(clazz)

|`linkUrl`
|*href* attribute of the link element
|id(v1)->filter.linkUrl(/url)

|`linkUrlPart`
|part of *href* attribute of the link element
|id(v1)->filter.linkUrlPart(/url)

|`tooltip`
|title attribute value
|id(v1)->filter.tooltip(title)

|`imageSrcPart`
|src attribute should contain value
|id(v1)->filter.imageSrcPart(part)

|`placeholder`
|Placeholder attribute should be equal to a value
|id(v1)->filter.placeholder(placeholder-value)

|`validationIconSource`
|CSS property background-image should match
|id(v1)->filter.validationIconSource(src)

|`fieldText`
|field text should match expected value
|id(v1)->filter.fieldText(value)

|`fieldTextPart`
|field text should contain expected value
|id(v1)->filter.fieldTextPart(value)

|`dropDownText`
|any of select options should be equal to a value
|id(v1)->filter.dropDownText(value)

|===


== Properties

:application-under-test: browser
:session-scope-property-base: web-application
[cols="3,1,1,3", options="header"]
|===
|Property Name
|Acceptable values
|Default
|Description

include::partial$selenium-properties.adoc[]
include::partial$selenium-grid-properties.adoc[]
|screenshot.on-failure.debug-modes
include::partial$proxy-properties.adoc[]

|web.driver.<browser-name>.command-line-arguments
|string with arguments
|empty
a|The command line arguments to use when starting browser.

`<browser-name>` is one supported browsers:

* https://peter.sh/experiments/chromium-command-line-switches/[`CHROME`]
* https://www-archive.mozilla.org/docs/command-line-args/[`FIREFOX`],
* https://docs.microsoft.com/en-us/previous-versions/windows/internet-explorer/ie-developer/general-info/hh826025(v=vs.85)?redirectedfrom=MSDN/[`IEXPLORE`].

|===

include::partial$proxy-meta-tags.adoc[]

== xref:commons:variables.adoc[Dynamic variables]

include::partial$dynamic-variables-ui.adoc[]

== Steps

=== Open URL in a new tab

Opens a new tab, switches to the opened tab and loads the given URL

[source,gherkin]
----
When I open URL `$URL` in new window
----
* `$URL` - The URL to open

.Open docs in a new tab.story
[source,gherkin]
----
When I open URL `https://docs.vividus.dev` in new window
----

=== Stop page loading

Stops page loading

[source,gherkin]
----
When I stop page loading
----

[TIP]
Could be useful in combination with Selenium's https://www.selenium.dev/documentation/en/webdriver/page_loading_strategy/[page load strategy]

.Stop page loading.story
[source,gherkin]
----
When I open URL `https://delayed.vividus.dev` in new window
When I stop page loading
----

=== Configure page load timeout

Sets a custom page load timeout for a part of the story

[source,gherkin]
----
When I set page load timeout to `$duration`
----

* `$duration` - total duration to wait for page load completion in {iso-date-format-link} format

.Before loading a heavy page set an increased timeout
[source,gherkin]
----
Given I am on a page with the URL 'https://example.com/'
When I set page load timeout to `PT20S`
When I open URL `https://example.com/super-heavy-page` in new window
When I set page load timeout to `PT10S`
----

=== Scroll context

Scrolls the context to an edge

[source,gherkin]
----
When I scroll context to $scrollDirection edge
----
* `$scrollDirection` - the direction of the scroll. One of:
** `LEFT` - start of a page/element horizontally
** `RIGHT` - end of a page/element horizontally
** `TOP` - start of a page/element vertically
** `BOTTOM` - end of a page/element vertically

[TIP]
If the context is not set, the whole page will be scrolled

.Scroll login to a bottom
[source,gherkin]
----
When I change context to element located `id(login)`
When I scroll context to BOTTOM edge
----

=== Scroll element into view

Scrolls an element into the view.

[source,gherkin]
----
When I scroll element located `$locator` into view
----
* `$locator` - <<_locator>>

.Scroll button into view
[source,gherkin]
----
When I scroll element located `id(way_down_button)` into view
----

=== Performance metrics

Checks web performance metrics.

[source,gherkin]
----
Then metric $webPerformanceMetric is $comparisonRule `$duration`
----

:navigation-timing: https://www.w3.org/TR/navigation-timing/#dom-performancetiming-

* `$webPerformanceMetric` - The web performance metric. Where:
** [subs=+quotes]`*TIME_TO_FIRST_BYTE*` -  The time between {navigation-timing}navigationstart[the navigation start] and {navigation-timing}responsestart[the response start].
** [subs=+quotes]`*DNS_LOOKUP_TIME*` -  The time between {navigation-timing}domainlookupstart[the domain lookup start] and {navigation-timing}domainlookupend[the domain lookup end].
** [subs=+quotes]`*DOM_CONTENT_LOAD_TIME*` -  The time between {navigation-timing}domloading[the DOM loading] and the {navigation-timing}domcomplete[the DOM complete].
** [subs=+quotes]`*PAGE_LOAD_TIME*` -  The time between {navigation-timing}navigationstart[the navgation start] and {navigation-timing}loadeventend[the load event end].
* `$comparisonRule` - xref:parameters:comparison-rule.adoc[The duration comparison rule].
* `$duration` - The duration to compare against in {iso-date-format-link} format.

.Check page load
[source,gherkin]
----
Given I am on a page with the URL 'https://example.com'
Then metric PAGE_LOAD_TIME is less than `PT5S`
----

=== Execute sequence of actions

Executes the sequence of web actions

[source,gherkin]
----
When I execute sequence of actions: $actions
----
* `$actions` - table of actions to execute

==== Possible actions

[cols="1,5,3", options="header"]
|===

|Type
|Argument
|Example

|DOUBLE_CLICK
|Search attribute or empty value
|By.linkUrl(http://httpbin.org)

|CLICK_AND_HOLD
|Search attribute or empty value
|By.linkText(Click me)

|MOVE_BY_OFFSET
|Point
|(10, 15) where *x* is 10 and *y* is 15

|RELEASE
|Search attribute or empty value
|By.tagName(div)

|ENTER_TEXT
|Text
|Minsk City

|CLICK
|Search attribute or empty value
|By.caseSensitiveText(Done)

|PRESS_KEYS
|Press xref:https://selenium.dev/selenium/docs/api/java/org/openqa/selenium/Keys.html[Keys]
|BACK_SPACE

|KEY_DOWN
|Press xref:https://selenium.dev/selenium/docs/api/java/org/openqa/selenium/Keys.html[Keys] SHIFT, ALT or CONTROL simultaneously
|CONTROL,SHIFT,ALT

|KEY_UP
|Release xref:https://selenium.dev/selenium/docs/api/java/org/openqa/selenium/Keys.html[Keys] SHIFT, ALT or CONTROL simultaneously
|CONTROL,SHIFT,ALT

|MOVE_TO
|Search attribute
|By.id(username)

|===

.ActionSteps.story
[source,gherkin]
----
When I execute sequence of actions:
|type          |argument                                |
|DOUBLE_CLICK  |By.fieldText(Hello World)               |
|DOUBLE_CLICK  |                                        |
|CLICK_AND_HOLD|By.xpath(//signature-pad-control/canvas)|
|CLICK_AND_HOLD|                                        |
|MOVE_BY_OFFSET|(-300, 0)                               |
|RELEASE       |By.xpath(//signature-pad-control/canvas)|
|RELEASE       |                                        |
|ENTER_TEXT    |Text                                    |
|CLICK         |By.placeholder(Enter your password)     |
|CLICK         |                                        |
|PRESS_KEYS    |BACK_SPACE                              |
|KEY_DOWN      |CONTROL,SHIFT                           |
|KEY_UP        |CONTROL,SHIFT                           |
|MOVE_TO       |By.id(name)                             |
----

include::partial$generic-ui-steps.adoc[]

=== Dropdown Steps
==== Validate available options

Validates whether the dropdown located by locator exists and contains the list
of the expected options.

[source,gherkin]
----
Then dropdown located `$locator` contains options: $option
----
* `$locator` - <<_locator>>
* `$options` - examples table describing expected options

.Validate dropdown contains a set of colors
[source,gherkin]
----
Then a drop down with the name 'colors' contains the items:
|state|item |
|false|Red  |
|false|Green|
|true |Blue |
----

IMPORTANT: The item is an option. The state (`true` or `false`) specifies whether the item is selected.


==== Validate the first selected option

Verifies if dropdown located by locator exists and first selected option.

[source,gherkin]
----
Then dropdown located `$locator` exists and selected option is `$option`
----
* `$locator` - <<_locator>>
* `$option` - first selected option

.Dropdown.story
[source,gherkin]
----
Then dropdown located `id(colors)` exists and selected option is `Blue`
----


==== Add an option to the mutli-select dropdown

Selects option in multi-select dropdown

[IMPORTANT]
Step will fail if target dropdown is not multi-select

[source,gherkin]
----
When I add `$option` to selection in dropdown located `$locator`
----
* `$option` - option to select
* `$locator` - <<_locator>>

.Dropdown.story
[source,gherkin]
----
When I add `Two` to selection in dropdown located `id(numbers)`
----


==== Select the option

Selects option in dropdown

[IMPORTANT]
Does not support multi-selection

[source,gherkin]
----
When I select `$option` in dropdown located `$locator``
----
* `$option` - option to select
* `$locator` - <<_locator>>

.Dropdown.story
[source,gherkin]
----
When I select `Red` in dropdown located `id(colors)`
----


=== Cookie Steps

==== Validate cookie presence

Validates whether the certain cookie is set.

[source,gherkin]
----
Then cookie with name `$cookieName` is set
----
* `$cookieName` - The name of the cookie to check presence.

.Check the session cookie is present
[source,gherkin]
----
Then cookie with name `JSESSIONID` is set
----

==== Validate cookie absence

Validates whether the certain cookie is not set.

[source,gherkin]
----
Then cookie with name `$cookieName` is not set
----
* `$cookieName` - The name of the cookie to check absence.

.Check the session cookie is not present
[source,gherkin]
----
Then cookie with name `JSESSIONID` is not set
----

==== Set cookies

Adds the cookies provided in the input ExamplesTable. It's allowed to add the
cookies for the current domain only: make sure the web browser is opened at the
expected domain. The actions performed by the step:

* add the cookies;
* refresh the current page (this action is required to apply the changes in cookies).

[source,gherkin]
----
When I set all cookies for current domain:$parameters
----
* `$parameters` - The parameters of the cookies to set as ExamplesTable:
+
[cols="1,2", options="header"]
|===

|Column Name
|Description

|`cookieName`
|the name of the cookie to set

|`cookieValue`
|the value of the cookie to set

|`path`
|the path of the cookie to set

|===

.Set the cookie for the current domain
[source,gherkin]
----
When I set all cookies for current domain:
|cookieName   |cookieValue |path |
|cookieAgreed |2           |/    |
----

==== Get cookie value

Finds the cookie by the name and saves its value to a variable.

[source,gherkin]
----
When I save value of cookie with name `$cookieName` to $scopes variable `$variableName`
----
* `$cookieName` - The name of the cookie to save the value.
* `$scopes` - xref:commons:variables.adoc#_scopes[The comma-separated set of the variables scopes].
* `$variableName` - The variable name to save the cookie value.

.Get the value of the session cookie
[source,gherkin]
----
When I save value of cookie with name `JSESSIONID` to scenario variable `session-id`
----

==== Get cookie

Finds the cookie by the name and saves all its parameters as JSON to a variable.

[source,gherkin]
----
When I save cookie with name `$cookieName` as JSON to $scopes variable `$variableName`
----
* `$cookieName` - The name of the cookie to save.
* `$scopes` - xref:commons:variables.adoc#_scopes[The comma-separated set of the variables scopes].
* `$variableName` - The variable name to save the cookie.

.Get the session cookie
[source,gherkin]
----
When I save cookie with name `JSESSIONID` as JSON to scenario variable `session-id`
----

==== Remove cookie

Removes the certain cookie from the current domain. The actions performed by the step:

* remove the certain cookie the from current domain;
* refresh the current page (this action is required to apply the changes in cookies).

[source,gherkin]
----
When I remove cookie with name `$cookieName` from current domain
----
* `$cookieName` - The name of the cookie to remove.

.Remove the session cookie
[source,gherkin]
----
When I remove cookie with name `JSESSIONID` from current domain
----

==== Remove cookie without apply

Removes the certain cookie from the current domain, but does not apply the
changes in cookies. The current page must be refreshed or the navigation must
be performed to apply the cookie changes.

[source,gherkin]
----
When I remove cookie with name `$cookieName` from current domain without applying changes
----
* `$cookieName` - The name of the cookie to remove.

.Remove the session cookie
[source,gherkin]
----
When I remove cookie with name `JSESSIONID` from current domain without applying changes
When I refresh the page
----

==== Remove all cookies

Removes all cookies from the current domain. The actions performed by the step:

* remove all cookies from the current domain;
* refresh the current page (this action is required to apply the changes in cookies).

[source,gherkin]
----
When I remove all cookies from current domain
----

==== Remove all cookies without apply

Removes all cookies from the current domain, but does not apply the changes in
cookies. The current page must be refreshed or the navigation must be performed
to apply the cookie changes.

[source,gherkin]
----
When I remove all cookies from current domain without applying changes
----

include::partial$proxy-steps.adoc[]
