= Web Application Plugin
:proxy: This step requires proxy to be turned on. It can be done via setting properties or switching on @proxy metatag.

The plugin provides functionality to interact with Web applications.

== Installation

.build.gradle
[source,gradle,subs="attributes+"]
----
implementation(group: 'org.vividus', name: 'vividus-plugin-web-app', version: '{page-component-version}')
----


include::partial$locator-header.adoc[]

=== Types

[cols="1,2,1", options="header"]
|===

|Locator type
|Description
|Example

|linkText
|text of the link
|linkText(Google)

|linkUrl
|*href* attribute of the link element
|linkUrl(/faq)

|linkUrlPart
|part of a *href* attribute of the link element
|linkUrlPart(faq)

|caseSensitiveText
|case sensitive text of an element
|caseSensitiveText(Description)

|caseInsensitiveText
|case insensitive text of an element
|caseInsensitiveText(description)

|XPath
|https://developer.mozilla.org/en-US/docs/Web/XPath[Xpath to locate an element]
|xpath(//a)

|cssSelector
|CSS selector to an element
|cssSelector(.menu-item)

|tagName
|name of an element tagName
|tagName(a)

|imageSrc
|shortcut to a *.//img[@src='<value>>']*
|imgSrc(/images/kote.png)

|imageSrcPart
|shortcut to a *.//img[contains(@src,'<value>>')]']*
|imgSrcPart(kote.png)

|buttonName
|elements of type button or input with text or any attribute value
|buttonName(submit)

|fieldName
|input or textarea with text or any attribute value
|fieldName(editor)

|checkboxName
|input element with @type="checkbox" and text value
|checkboxName(allow)

|id
|id attribute of an element
|id(submitForm)

|className
|CSS class name
|className(bold)

|elementName
|Any attribute or text value
|elementName(OK)

|===

include::partial$visibility-types.adoc[]

=== Filter types

Filter are applied after elements search via locator. Elements not matching filter condition will be sorted out without additional notice.

[cols="1,2,3", options="header"]
|===

|Filter type
|Description
|Example

|state
|
element xref:parameters:state.adoc[State]
|id(v1)->filter.state(VISIBLE)

|caseSensitiveText
|element text should match case sensitively
|id(v1)->filter.caseSensitiveText(text)

|classAttributePart
|class attribute should contain part
|id(v1)->filter.classAttributePart(clazz)

|linkUrl
|*href* attribute of the link element
|id(v1)->filter.linkUrl(/url)

|linkUrlPart
|part of *href* attribute of the link element
|id(v1)->filter.linkUrlPart(/url)

|tooltip
|title attribute value
|id(v1)->filter.tooltip(title)

|imageSrcPart
|src attribute should contain value
|id(v1)->filter.imageSrcPart(part)

|textPart
|text of an element should contain value
|id(v1)->filter.textPart(part)

|placeholder
|Placeholder attribute should be equal to a value
|id(v1)->filter.placeholder(placeholder-value)

|validationIconSource
|CSS property background-image should match
|id(v1)->filter.validationIconSource(src)

|fieldText
|field text should match expected value
|id(v1)->filter.fieldText(value)

|fieldTextPart
|field text should contain expected value
|id(v1)->filter.fieldTextPart(value)

|dropDownText
|any of select options should be equal to a value
|id(v1)->filter.dropDownText(value)

|===


== Properties

:application-under-test: browser
:session-scope-property-base: web-application
[cols="3,1,1,3", options="header"]
|===
|Property Name
|Acceptable values
|Default
|Description

include::partial$selenium-properties.adoc[]
|===

=== Meta Tags

@proxy - Some steps requires proxy to be turned on. It can be done via setting properties or switching on @proxy metatag.

== Steps

=== Clear proxy log

==== *_Info_*

Clears the proxy log

==== *_Wording_*

[source,gherkin]
----
When I clear proxy log
----

==== *_Usage_*

.ProxyStepsTests.story
[source,gherkin]
----
Scenario: Verify step When I clear proxy log
Given I am on a page with the URL 'http:/httpbin.org/get'
When I clear proxy log
Then number of HTTP GET requests with URL pattern `http://httpbin.org/get` is EQUAL TO `0`
----


=== Check if the number of requests with given URL-pattern exist

==== *_Info_*

{proxy}
Step gets proxies log, extract from contained requests URLs and match them with URL-pattern
If URLs are the same, there were calls with given URL-pattern, otherwise - weren't.
If there weren't any calls matching requirements, HAR file with all calls will be attached to report.
If response contains status code 302 - corresponding request will be filtered out.

==== *_Wording_*

[source,gherkin]
----
Then number of HTTP $httpMethod requests with URL pattern `$urlPattern` is $comparisonRule `$number`
----

==== *_Parameters_*

. `$httpMethod` - HTTP method to filter by
. `$urlPattern` - the string value of URL-pattern to filter by
. `$comparisonRule` - xref:parameters:comparison-rule.adoc[Comparison Rule]
. `$number` - The number to compare with

==== *_Usage_*

.ProxyStepsTests.story
[source,gherkin]
----
Scenario: Verify step When I clear proxy log
Given I am on a page with the URL 'http:/httpbin.org/get'
When I clear proxy log
Then number of HTTP GET requests with URL pattern `http://httpbin.org/get` is EQUAL TO `0`
----


=== Execute sequence of actions

==== *_Info_*

Executes the sequence of web actions

==== *_Wording_*

[source,gherkin]
----
When I execute sequence of actions: $actions
----

==== *_Parameters_*

. `$actions` - table of actions to execute

==== Possible actions

[cols="1,5,3", options="header"]
|===

|Type
|Argument
|Example

|DOUBLE_CLICK
|Search attribute or empty value
|By.linkUrl(http://httpbin.org)

|CLICK_AND_HOLD
|Search attribute or empty value
|By.linkText(Click me)

|MOVE_BY_OFFSET
|Point
|(10, 15) where *x* is 10 and *y* is 15

|RELEASE
|Search attribute or empty value
|By.tagName(div)

|ENTER_TEXT
|Text
|Minsk City

|CLICK
|Search attribute or empty value
|By.caseSensitiveText(Done)

|PRESS_KEYS
|Press xref:https://selenium.dev/selenium/docs/api/java/org/openqa/selenium/Keys.html[Keys]
|BACK_SPACE

|KEY_DOWN
|Press xref:https://selenium.dev/selenium/docs/api/java/org/openqa/selenium/Keys.html[Keys] SHIFT, ALT or CONTROL simultaneously
|CONTROL,SHIFT,ALT

|KEY_UP
|Release xref:https://selenium.dev/selenium/docs/api/java/org/openqa/selenium/Keys.html[Keys] SHIFT, ALT or CONTROL simultaneously
|CONTROL,SHIFT,ALT

|MOVE_TO
|Search attribute
|By.id(username)

|===

==== *_Usage_*

.ActionSteps.story
[source,gherkin]
----
When I execute sequence of actions:
|type          |argument                                |
|DOUBLE_CLICK  |By.fieldText(Hello World)               |
|DOUBLE_CLICK  |                                        |
|CLICK_AND_HOLD|By.xpath(//signature-pad-control/canvas)|
|CLICK_AND_HOLD|                                        |
|MOVE_BY_OFFSET|(-300, 0)                               |
|RELEASE       |By.xpath(//signature-pad-control/canvas)|
|RELEASE       |                                        |
|ENTER_TEXT    |Text                                    |
|CLICK         |By.placeholder(Enter your password)     |
|CLICK         |                                        |
|PRESS_KEYS    |BACK_SPACE                              |
|KEY_DOWN      |CONTROL,SHIFT                           |
|KEY_UP        |CONTROL,SHIFT                           |
|MOVE_TO       |By.id(name)                             |
----

=== Save the request URL

==== *_Info_*

{proxy}

Saves the captured request URL into scoped variable.

==== *_Wording_*

[source,gherkin]
----
When I capture HTTP $httpMethod request with URL pattern `$urlPattern` and save URL to $scopes variable `$variableName`
----

==== *_Parameters_*

. `$httpMethod` - HTTP method to filter by
. `$urlPattern` - the string value of URL-pattern to filter by
. `$scopes` - xref:parameters:variable-scope.adoc[The set of variable's scope]
. `$variableName` - A variable name

==== *_Usage_*

.ProxyStepsTests.story
[source,gherkin]
----
Scenario: Verify step When I capture HTTP $httpMethod request with URL pattern `$urlPattern` and save URL to $scopes variable `$variableName`
Given I am on a page with the URL 'https://www.google.com/search?q=vividus'
When I capture HTTP GET request with URL pattern `.*/search.*=vividus` and save URL to SCENARIO variable `URL`
Then `${URL}` is equal to `https://www.google.com/search?q=vividus`
----


=== Saves the query string into the variable with specified name and scopes.

==== *_Info_*

{proxy}
Step gets proxies log, extract from contained requests URLs and match them with URL-pattern
If there is one entry, it saves the query string from request as Map of keys and values into the variable with specified name and scopes.
If there weren't any calls or more than one matching requirements, HAR file with all
calls will be attached to report.

==== *_Wording_*

[source,gherkin]
----
When I capture HTTP $httpMethod request with URL pattern `$urlPattern` and save URL query to $scopes variable `$variableName`
----

==== *_Parameters_*

. `$httpMethod` - HTTP method to filter by
. `$urlPattern` - the string value of URL-pattern to filter by
. `$scopes` - xref:parameters:variable-scope.adoc[The set of variable's scope]
. `$variableName` - A variable name

==== *_Usage_*

.ProxyStepsTests.story
[source,gherkin]
----
Scenario: Verify step When I capture HTTP $httpMethod request with URL pattern `$urlPattern` and save URL query to $scopes variable `$variableName`
Given I am on a page with the URL 'http://httpbin.org/forms/post'
When I click on element located `By.xpath(//button)`
When I capture HTTP POST request with URL pattern `http://httpbin.org/post` and save URL query to SCENARIO variable `query`
Then `${query}` is equal to `{}`
----


=== Saves the request data into the variable with specified name and scopes.

==== *_Info_*

{proxy}
Step gets proxies log, extract from contained requests URLs and match them with URL-pattern
If there is one entry, it saves the query string from request as Map of keys and values into the variable with specified name and scopes.
If there weren't any calls or more than one matching requirements, HAR file with all calls will be attached to report.

==== *_Wording_*

[source,gherkin]
----
When I capture HTTP $httpMethod request with URL pattern `$urlPattern` and save request data to $scopes variable `$variableName`
----

==== *_Parameters_*

. `$httpMethod` - HTTP method to filter by
. `$urlPattern` - the string value of URL-pattern to filter by
. `$scopes` - xref:parameters:variable-scope.adoc[The set of variable's scope]
. `$variableName` - A variable name

==== *_Usage_*

.ProxyStepsTests.story
[source,gherkin]
----
Scenario: Verify step When I capture HTTP $httpMethod request with URL pattern `$urlPattern` and save request data to $scopes variable `$variableName`
Given I am on a page with the URL 'http://httpbin.org/forms/post'
When I click on element located `By.xpath(//button)`
When I capture HTTP POST request with URL pattern `http://httpbin.org/post` and save request data to SCENARIO variable `requestData`
Then `${requestData.query}` is equal to `{}`
Then `${requestData.requestBodyParameters}` is equal to `{delivery=, custtel=, comments=, custemail=, custname=}`
Then `${requestData.requestBody}` is not equal to `null`
Then `${requestData.responseStatus}` is equal to `200`
----


=== Waits for appearance of HTTP request matched httpMethod and urlPattern in proxy log

==== *_Info_*

Waits for appearance of HTTP request matched httpMethod and urlPattern in proxy log

==== *_Wording_*

[source,gherkin]
----
When I wait until HTTP $httpMethod request with URL pattern `$urlPattern` exists in proxy log
----

==== *_Parameters_*

. `$httpMethod` - HTTP method to filter by
. `$urlPattern` - The string value of URL-pattern to filter by

==== *_Usage_*

.ProxyStepsTests.story
[source,gherkin]
----
Scenario: Verify step When I wait until HTTP $httpMethod request with URL pattern `$urlPattern` exists in proxy log
Given I am on a page with the URL 'http://httpbin.org/get'
When I wait until HTTP GET request with URL pattern `http://httpbin.org/get` exists in proxy log
Then number of HTTP GET requests with URL pattern `http://httpbin.org/get` is EQUAL TO `1`
----

include::partial$generic-ui-steps.adoc[]

=== Dropdown: verify available options.

==== *_Info_*

Verifies if dropdown located by locator exists and has expected list of options

==== *_Wording_*

[source,gherkin]
----
Then dropdown located `$locator` contains options: $option
----

==== *_Parameters_*

. `$locator` - <<_locator>>
. `$options` - examples table describing expected options

==== *_Usage_*

.Dropdown.story
[source,gherkin]
----
Then a drop down with the name 'colors' contains the items:
|state|item |
|false|Red  |
|false|Green|
|true |Blue |
----

[IMPORTANT]

Item - is an option. State - true/false describes if option selected


=== Dropdown: verify first selected option

==== *_Info_*

Verifies if dropdown located by locator exists and first selected option.

==== *_Wording_*

[source,gherkin]
----
Then dropdown located `$locator` exists and selected option is `$option`
----

==== *_Parameters_*

. `$locator` - <<_locator>>
. `$option` - first selected option

==== *_Usage_*

.Dropdown.story
[source,gherkin]
----
Then dropdown located `id(colors)` exists and selected option is `Blue`
----


=== Dropdown: add text to a mutli-select

==== *_Info_*

Selects option in multi-select dropdown

[IMPORTANT]
Step will fail if target dropdown is not multi-select

==== *_Wording_*

[source,gherkin]
----
When I add `$option` to selection in dropdown located `$locator`
----

==== *_Parameters_*

. `$option` - option to select
. `$locator` - <<_locator>>

==== *_Usage_*

.Dropdown.story
[source,gherkin]
----
When I add `Two` to selection in dropdown located `id(numbers)`
----


=== Dropdown: select option

==== *_Info_*

Selects option in dropdown

[IMPORTANT]
Does not support multi-selection

==== *_Wording_*

[source,gherkin]
----
When I select `$option` in dropdown located `$locator``
----

==== *_Parameters_*

. `$option` - option to select
. `$locator` - <<_locator>>

==== *_Usage_*

.Dropdown.story
[source,gherkin]
----
When I select `Red` in dropdown located `id(colors)`
----


== Dynamic variables

Dynamic variables is variables available out of the box using standard approach `$\{variable-name\}` Usually the data provided by dynamic variables calculated at runtime.


=== Context element rectangle

Provides possibility to access context element coordinates, width and height.

[IMPORTANT]

Variable uses contextual approach. So it is necessary to switch context to a target element.


==== *Variable name*

[cols="1,3", options="header"]
|===

|Variable name
|Description

|context-height
|provided context element height

|context-width
|provided context element width

|context-x-coordinate
|provided context element absolute X coordinate

|context-y-coordinate
|provided context element absolute Y coordinate

|===


==== *Usage example*

[source,gherkin]
----
When I change context to element located `tagName(img)`
Then `${context-height}` is > `0`
Then `${context-width}` is > `0`
Then `${context-x-coordinate}` is > `0`
Then `${context-y-coordinate}` is > `0`
----


=== Adds headers to proxy request

==== *_Info_*

Add headers to proxy request that will be used while sending request with given urlPattern

==== *_Wording_*

[source,gherkin]
----
When I add headers to proxied requests with URL pattern which $comparisonRule `$urlPattern`:$headers
----

==== *_Parameters_*

. `$comparisonRule` - xref:parameters:string-comparison-rule.adoc[String comparison Rule]
. `$urlPattern` - The string value of URL-pattern to filter by
. `$headers` - ExamplesTable representing list of headers with columns "name" and "value" specifying HTTP header names and values respectively

==== *_Usage_*

.ProxyStepsTests.story
[source,gherkin]
----
Scenario: Verify step When I add headers to proxied requests with URL pattern which $comparisonRule `$urlPattern`:$headers
When I add headers to proxied requests with URL pattern which is equal to `http://httpbin.org/headers`:
|name     |value     |
|testName1|testValue1|
|testName2|testValue2|
Given I am on a page with the URL 'http://httpbin.org/headers'
When I change context to element located `xpath(//pre)`
When I set the text found in search context to the 'SCENARIO' variable 'response'
Then a JSON element from '${response}' by the JSON path '$.headers' is equal to '
{
    "Testname1": "testValue1",
    "Testname2": "testValue2"
}
'IGNORING_EXTRA
----
