= CSV Plugin

The plugin provides the ability to work with CSV files.

:plugin-short-name: csv
include::partial$plugin-installation.adoc[]

== Properties
[cols="2,1,2,3", options="header"]
|===
|Property Name
|Acceptable values
|Default
|Description

|`csv.delimiter-char`
|<char>
|`,`
|The char used for value separation, must not be a line break character

|`csv.escape-char`
|<char>
|`<disabled: no escape char>`
|The char used to escape special characters in values, may be disabled

|===

== xref:ROOT:glossary.adoc#_table_transformer[Table Transformers]

NOTE: The table transformers properties marked with *bold* are mandatory.

=== FROM_CSV

`FROM_CSV` transformer generates table from the given CSV file.

[cols="1,3", options="header"]
|===
|Parameter
|Description

|`path`
a|The relative path of the CSV file

IMPORTANT: The `path` parameter can not be used together with the `variableName` or `csvPath` parameter.

|`variableName`
a|The name of the variable containing source CSV, only variables of scopes `global` and `next_batches` are allowed.
Exceptions are cases when the transformer using in xref:commons:vividus-steps.adoc#_initialize_variable_with_a_table[step]
which initializes a variable with a table.

IMPORTANT: The `variableName` parameter can not be used together with the `path` or `csvPath` parameter.

|`csvPath`
a|The relative path of the CSV file

WARNING: The `csvPath` parameter is deprecated and will be removed in VIVIDUS 0.7.0, please use `path` instead.

IMPORTANT: The `csvPath` parameter can not be used together with the `variableName` or `path` parameter.

|`delimiterChar`
|The char used for value separation, must not be a line break character
|===

If `delimiterChar` is not set, then the corresponding property will be used during parsing.

.The transformer based on the default configuration
[source,gherkin]
----
{transformer=FROM_CSV, path=/data/example.csv}
----

.The transformer based on the default configuration with variable CSV source
[source,gherkin]
----
{transformer=FROM_CSV, variableName=csvVariable}
----

.The transformer with custom inlined configuration
[source,gherkin]
----
{transformer=FROM_CSV, path=/data/another-example.csv, delimiterChar=;}
----

== Steps

=== Save CSV into variable

Saves CSV string to indexed zero-based variable with column name mappings, e.g. var[0].key2, var[1].key1 etc. Please see the xref:commons:variables.adoc#_complex_types_variables[documentation] for more information about complex variables.

[source,gherkin]
----
When I save CSV `$csv` to $scopes variable `$variableName`
----

. `$csv` - CSV string.
. `$scopes` - The comma-separated set of the xref:commons:variables.adoc#_scopes[variables scopes].
. `$variableName` - The name of the variable to save CSV string.

.Validate CSV data
[source,gherkin]
----
Given I initialize scenario variable `csv` with value `key1,key2,key3
val1-1,val1-2,val1-3
val2-1,val2-2,val2-3`
When I save CSV `${csv}` to scenario variable `expected-csv`
When I save CSV `#{loadResource(/data/simple-csv.csv)}` to scenario variable `actual-csv`
Then `${expected-csv}` is equal to `${actual-csv}`
Then `${csv-from-file[1].key2}` is equal to `val2-2`
----
