= HTML Plugin

The plugin provides the ability to work with HTML documents: data extraction and validation.

:plugin-short-name: html
include::partial$plugin-installation.adoc[]

== xref:ROOT:glossary.adoc#_table_transformer[Table Transformers]

=== FROM_HTML

`FROM_HTML` transformer generates a table based on the text content, HTML content or attributes of HTML elements found in the requested HTML page.

[cols="1,3", options="header"]
|===

|Parameter Name
|Description

|`pageUrl`
a|The URL of the page to build the table upon.

WARNING: The `pageUrl` parameter is deprecated and will be removed in VIVIDUS 0.7.0, please use `variableName` instead.

IMPORTANT: The `pageUrl` parameter can not be used together with the `variableName` or `path` parameter.

|`variableName`
a|The name of the variable containing source HTML, only variables of scopes `global` and `next_batches` are allowed.
Exceptions are cases when the transformer using in xref:commons:vividus-steps.adoc#_initialize_variable_with_a_table[step]
which initializes a variable with a table.

IMPORTANT: The `variableName` parameter can not be used together with the `pageUrl` or `path` parameter.

|`path`
a|The xref:ROOT:glossary.adoc#_resource[HTML resource name] or the HTML file path.

IMPORTANT: The `path` parameter can not be used together with the `variableName` or `pageUrl` parameter.

|`column`
|The column name in the generated table.

|`xpathSelector`
a|The XPath selector to select HTML elements in the HTML page.

By using XPath selector we can extract element's HTML content, attributes and text content like its shown in the following example:

* `//a` - extract the link HTML content, e.g. `<a href="/hello">Say Hello</a>`
* `//a/text()` - extract the link text, e.g. `Say Hello`
* `//a/@href` - extract the link `href` attribute, e.g. `/hello`

|`baseUri`
|The base URI  can be used to get an absolute URL from an attribute that may be a relative URL: make sure to add the prefix `abs:` before the attribute name to https://jsoup.org/cookbook/extracting-data/working-with-urls[xPath selector], e.g. `//a/@abs:href`. If defined `pageUrl` parameter as the base URI implicitly using value of this parameter.

|===

[cols="3,1,1,3", options="header"]
|===

|Property Name
|Acceptable values
|Default
|Description

|`transformer.from-html.headers.<header name>=<header value>`
|
|
a|Set of headers to set when requesting the page.

[source,properties]
----
transformer.from-html.headers.x-vercel-protection-bypass=1fac2b25014d35e5103b
----

|===

.Given the following HTML page
[source,html]
----
<!DOCTYPE html>
<html>
    <body>
        <a href="/r">R</a>
        <a href="/g">G</a>
        <a href="/b">B</a>
    </body>
</html>
----

.Applyng FROM_HTML to the page
----
Examples:
{transformer=FROM_HTML, column=relative-url, pageUrl=https://mypage.com, xpathSelector=//a/@href}
----

.Output table
----
|relative-url|
|/r          |
|/g          |
|/b          |
----

.The transformer configuration based on local HTML file
[source,gherkin]
----
transformer=FROM_HTML, column=relative-url, path=data/index.html, xpathSelector=//a/@href
----

== Steps

=== Validate elements

Validates the number of elements found by the locator matches the specified rules.

[source,gherkin]
----
Then number of elements found by $htmlLocatorType `$htmlLocator` in HTML `$html` is $comparisonRule `$number`
----

include::partial$html-locator.adoc[]
- `$html` - The HTML document to validate.
- `$comparisonRule` - xref:parameters:comparison-rule.adoc[The comparison rule].
- `$quantity` -  The expected number of elements.

.Validate starfield release date
[source,gherkin]
----
When I execute HTTP GET request for resource with URL `https://bethesda.net/en/game/starfield`
Then number of elements found by XPath `//h3[contains(., '111122')]` in HTML `${response}` is = `1`
----

=== Validate element text

Validates whether the element found by the locator contains the expected text.

[source,gherkin]
----
Then element found by $htmlLocatorType `$htmlLocator` in HTML `$html` contains text `$expectedText`
----

include::partial$html-locator.adoc[]
- `$html` - The HTML document to validate.
- `$expectedText` - The expected element text.

.Validate starfield release date
[source,gherkin]
----
When I execute HTTP GET request for resource with URL `https://bethesda.net/en/game/starfield`
Then element found by XPath `//h3` in HTML `${response}` contains text `111122`
----

=== Save attribute value

Saves the attribute value into the variable.

[source,gherkin]
----
When I save `$attributeName` attribute value of element found by $htmlLocatorType `$htmlLocator` in HTML `$html` to $scopes variable `$variableName`
----

- `$attributeName` - The name of the attribute.
include::partial$html-locator.adoc[]
- `$html` - The HTML document to find element.
- `$scopes` - xref:commons:variables.adoc#_scopes[The comma-separated set of the variables scopes].
- `$variableName` - The name of the variable to save the attribute value.

.Validate paragraph title
[source,gherkin]
----
Given I initialize story variable `html` with value
`
<html>
  <head>
    <title>Page Title</title>
    <script>//<![CDATA[Here comes the data//]]></script>
  </head>
  <body>
    <h1>This is a Heading</h1>
    <p title="paragraph">This is a paragraph.</p>
  </body>
</html>
`
When I save `title` attribute value of element found by CSS selector `p` in HTML `${html}` to scenario variable `title`
Then `${title}` is = `paragraph`
----

=== Save data/text of element

Saves the data or the text of element. Where the *data* is characters between the start-tag and end-tag of the element and the *text* is the textual content of the element  without any inner element.
[source,gherkin]
----
When I save $dataType of element found by $htmlLocatorType `$htmlLocator` in HTML `$html` to $scopes variable `variableName`
----

- `$dataType` - Either `data` or `text`
- `$html` - The HTML document to find element.
include::partial$html-locator.adoc[]
* `$scopes` - xref:commons:variables.adoc#_scopes[The comma-separated set of the variables scopes].
* `$variableName` - The name of the variable to save the data or text.

.Validate data/text
[source,gherkin]
----
Given I initialize story variable `html` with value
`
<html>
  <head>
    <title>Page Title</title>
    <script>//<![CDATA[Here comes the data//]]></script>
  </head>
  <body>
    <h1>This is a Heading</h1>
    <p title="paragraph">This is a paragraph.</p>
  </body>
</html>
`
When I save data of element found by <locatorType> `<script>` in HTML `${html}` to scenario variable `data`
When I save text of element found by <locatorType> `<header>` in HTML `${html}` to scenario variable `text`
Then `${data}` is equal to `//<![CDATA[Here comes the data//]]>`
Then `${text}` is equal to `This is a Heading`
Examples:
|locatorType |script  |header|
|CSS selector|script  |h1    |
|XPath       |//script|//h1  |
----

=== Save number of elements

Saves the number of elements contained in HTML document.

[source,gherkin]
----
When I save number of elements found by $htmlLocatorType `$htmlLocator` in HTML `$html` to $scopes variable `$variableName`
----

include::partial$html-locator.adoc[]
- `$html` - The HTML document.
- `$scopes` - xref:commons:variables.adoc#_scopes[The comma-separated set of the variables scopes].
- `$variableName` - The name of the variable to save the number of elements.

.Validate number of Heading 1 elements
[source,gherkin]
----
Given I initialize story variable `html` with value
`
<html>
  <body>
    <h1>This is a Heading</h1>
    <p title="paragraph">This is a paragraph.</p>
  </body>
</html>
`
When I save number of elements found by XPath `//h1` in HTML `${html}` to scenario variable `heading1`
Then `${heading1}` is equal to `1`
----
