= Azure Storage Account Plugin

The plugin provides functionality to interact with https://docs.microsoft.com/en-us/azure/storage/[Azure Storage Account].

== Installation

.build.gradle
[source,gradle,subs="attributes+"]
----
implementation(group: 'org.vividus', name: 'vividus-plugin-azure-storage-account', version: '{current-version}')
----

== Configuration

include::partial$azure-authentication.adoc[]

=== Properties

Storage accounts are configured with a set of properties with the following format:

[source,properties]
----
azure.storage.account.{account-name}.{property-name}=property value
----

Where:

. `account-name` - The name of the storage account
. `property-name` - The name of the account property. One of:
.. `endoint` - The storage account  endpoint

== Steps

=== Download blob

Downloads a blob text content

[source,gherkin]
----
When I download blob with name `$blobName` from container `$containerName` in storage account `$storageAccountKey` and save its content to $scopes variable `$variableName`
----

* `$blobName` - The blob name
* `$containerName` - The name of the container
* `$storageAccountKey` - The key of storage account configuraiton
* `$scopes` - xref:parameters:variable-scope.adoc[The comma-separated set of the variables scopes].
* `$variableName` - The variable name to store the blob

.Download a blob
[source,gherkin]
----
When I download blob with name `test.json` from container `vividus` in storage account `testAccount` and save its content to scenario variable `blob`
----

=== Download to temp file

Downloads blob to a local filesystem temp folder

[source,gherkin]
----
When I download blob located at `$blobName` from container `$containerName` in storage account `$storageAccountKey` to temporary file with name `$baseFileName` and save blobName to $scopes variable `$variableName`
----

* `$blobName` - The name of the blob
* `$containerName` - The name of the container
* `$storageAccountKey` - The key of storage account configuraiton
* `$baseFileName` - The temp file base name
* `$scopes` - xref:parameters:variable-scope.adoc[The comma-separated set of the variables scopes].
* `$variableName` - The variable name to store the blob

.Download a blob to a temp folder
[source,gherkin]
----
When I download blob located at `test.json` from container `vividus` in storage account `testAccount` to temporary file with name `test.json` and save blobName to scenario variable `pathToABlob`
----

=== Delete blob

Deletes a blob by the path

[source,gherkin]
----
When I delete blob located at `$blobName` from container `$containerName` in storage account `$storageAccountKey`
----

* `$blobName` - The name of the blob
* `$containerName` - The name of the container
* `$storageAccountKey` - The key of storage account configuraiton

.Delete a blob
[source,gherkin]
----
When I delete blob `test.json` from `vividus-private` blob container
When I delete blob located at `test.json` from container `vividus` in storage account `testAccount`
----

=== Find blobs

Finds blobs with the path matching desired condition

[source,gherkin]
----
When I find all blobs with name which $comparisonRule `$blobNameToMatch` from container `$containerName` in storage account `$storageAccountKey` and save result to $scopes variable `$variableName`
----

* `$comparisonRule` - xref:parameters:string-comparison-rule.adoc[String comparison rule]
* `$blobNameToMatch` - The expected blob name
* `$containerName` - The name of the container
* `$storageAccountKey` - The key of storage account configuraiton
* `$scopes` - xref:parameters:variable-scope.adoc[The comma-separated set of the variables scopes].
* `$variableName` - The variable name to store the blob

.Find blobs
[source,gherkin]
----
When I find all blobs with name which contains `json` from container `vividus` in storage account `testAccount` and save result to scenario variable `blobsCollection`
----
