= Mobile Application Plugin

The plugin provides functionality to test mobile application on real devices, Android Emulators and iOS Simulators

== Installation

.build.gradle
[source,gradle,subs="attributes+"]
----
implementation(group: 'org.vividus', name: 'vividus-plugin-mobile-app', version: '{page-component-version}')
----


include::partial$locator-header.adoc[]

=== Types
:locator-strategy: https://appium.io/docs/en/commands/element/find-elements/index.html#selector-strategies

[cols="1,2,2", options="header"]
|===

|Locator type
|Description
|Examples

|XPath
|Search the app XML source using xpath (not recommended, has {locator-strategy}[performance issues])
|xpath(//android.widget.TextView[@text='Home']) or By.xpath(//XCUIElementTypeStaticText[@value='Home'])

|Accessibility ID
|See {locator-strategy}[Accessibility ID] selector strategy
|accessibilityId(menu-toggler) or By.accessibilityId(menu-toggler)

|===

include::partial$visibility-types.adoc[]



== Properties

See xref:ROOT:tests-configuration.adoc[Selenium Grid] properties to configure remote grid

:application-under-test: mobile application
:session-scope-property-base: mobile-application
[cols="6,3,2,6", options="header"]
|===
|Property Name
|Acceptable values
|Default
|Description

include::partial$selenium-properties.adoc[]

|`selenium.grid.platform-name`
a|`Android`

`iOS`
|Depends on the set profile
|Defines the mobile OS to use

|`selenium.grid.automation-name`
a|`UIAutomator2`
`XCUITest`
|Depends on the set profile
a|Defines automation engine to use
[cols="1,2", options="header"]
!===

!Platform
!Recommended engine

!`Android`
!http://appium.io/docs/en/drivers/android-uiautomator2/[UIAutomator2]

!`iOS`
!http://appium.io/docs/en/drivers/ios-xcuitest/[XCUITest]
!===

|===

== Profiles

=== iOS
:ios-profile: mobile_app/ios

The profile can be enabled by adding `{ios-profile}` to `configuration.profiles` property

Default profile configuration
[source,properties]
----
selenium.grid.platform-name=iOS
selenium.grid.automation-name=XCUITest
----

=== Android
:android-profile: mobile_app/android

The profile can be enabled by adding `{android-profile}` to `configuration.profiles` property

Default profile configuration
[source,properties]
----
selenium.grid.platform-name=Android
selenium.grid.automation-name=UIAutomator2
----

=== BrowserStack

==== Info

* The profile can be enabled by adding `browserstack/mobile_app` to `configuration.profiles` property
* The profile must be used together with either `{ios-profile}` or `{android-profile}` profiles
* BrowserStack specific properties must be prepended with `selenium.grid.capabilities.bstack\:options.` prefix, meaning given a property `projectName` with a value `My Project` the resulting property will be `selenium.grid.capabilities.bstack\:options.projectName=My Project`
* Appium specific properties in BrowserStack must be prepended with `selenium.grid.capabilities.appium\:options.` prefix, meaning given a property `clearSystemFiles` with a value `true` the resulting property will be `selenium.grid.capabilities.appium\:options.clearSystemFiles=true`
* See https://www.browserstack.com/app-automate/capabilities?tag=w3c[Capabilities Builder] to setup configuration

==== Required properties
* `selenium.grid.device-name` - defines device name to run tests on

=== SauceLabs

==== Info

* The profile can be enabled by adding `saucelabs/mobile_app` to `configuration.profiles` property
* The profile must be used together with either `{ios-profile}` or `{android-profile}` profiles
* See https://wiki.saucelabs.com/display/DOCS/Platform+Configurator#/[Platform Configurator] to setup configuration

==== Required properties

* `selenium.grid.device-name` - defines device name
* `selenium.grid.appium-version` - defines appium version
* `selenium.grid.platform-version` - defines platform version

== Steps

=== Start mobile application

==== *_Info_*

Starts mobile application with capabilities from user's `*.properties` files and profiles set by a user

==== *_Wording_*

[source,gherkin]
----
Given I start mobile application
----

==== *_Usage_*

.Sample.story
[source,gherkin]
----
Scenario: Start mobile application
Given I start mobile application
----

=== Start mobile application with capabilities

==== *_Info_*

Starts mobile application with capabilities from user's `*.properties` files and profiles set by a user, additionally step takes list of capabilities as an argument that override previously defined capabilities

==== *_Wording_*

[source,gherkin]
----
Given I start mobile application with capabilities:$capabilities
----

==== *_Parameters_*

. `$capabilities` - capabilities to start application with, these capabilies have higher priority than capabilities defined in `*.properties` files and in profiles

==== *_Usage_*

.Sample.story
[source,gherkin]
----
Scenario: Start mobile application with capabilities
Given I start mobile application with capabilities:
|name                           |value|
|bstack:options.networkLogs     |true |
|appium:options.clearSystemFiles|false|
----

=== Tap on element with duration

==== *_Info_*

Taps on the element located by the locator with the specified duration.

The atomic actions performed are:
* press on the element
* wait for the duration
* release

==== *_Wording_*

[source,gherkin]
----
When I tap on element located `$locator` with duration `$duration`
----

==== *_Parameters_*

. `$locator` - <<_locator>>
. `$duration` - duration between an element is pressed and released in {iso-date-format-link} format

==== *_Usage_*

.Sample.story
[source,gherkin]
----
Scenario: Tap on element with duration
When I tap on element located `accessibilityId(menu-toggler)` with duration `PT0.5S`
----

=== Tap on element

==== *_Info_*

Taps on the element located by the locator.

The atomic actions performed are:
* press on the element
* release

==== *_Wording_*

[source,gherkin]
----
When I tap on element located `$locator`
----

==== *_Parameters_*

. `$locator` - <<_locator>>

==== *_Usage_*

.Sample.story
[source,gherkin]
----
Scenario: Tap on element
When I tap on element located `accessibilityId(menu-toggler)`
----

=== Type text

==== *_Info_*

Types the text into the element located by the locator.

[WARNING]
Existing text is re-written by the text passed into the step

The atomic actions performed are:
* type text into the element
* hide keyboard

==== *_Wording_*

[source,gherkin]
----
When I type `$text` in field located `$locator`
----

==== *_Parameters_*

. `$text` - text to type into the element
. `$locator` - <<_locator>>

==== *_Usage_*

.Keyboard.story
[source,gherkin]
----
Scenario: Type text
When I type `Bob` in field located `accessibilityId(username)`
----


include::partial$generic-ui-steps.adoc[]
