= WinRM Plugin

The plugin provides functionality to execute commands via https://docs.microsoft.com/en-us/windows/win32/winrm/portal[WinRM].

:plugin-short-name: winrm
include::partial$plugin-installation.adoc[]

== Properties

It is allowed to configure an unlimited number of WinRM connections via the dynamic properties mechanism. The properties prefix example is:
```properties
winrm.server.my-server
```
where `my-server` is a key used to refer to a WinRM connection in the steps. The key is defined by users, must be unique and cannot contain dots.

:connection-parameters-prefix: winrm.server.<key>.
:parameters-name: properties
include::partial$winrm-connection-parameters.adoc[]

== Steps

=== Configure dynamic WinRM connection

Creates a new dynamic WinRM connection from the provided parameters. The connection is available only within the story that creates the connection.

[source,gherkin]
----
When I configure WinRM connection with key `$connectionKey` and parameters:$connectionParameters
----

* `$connectionKey` - The key to assign to the created WinRM connection. If the key conflicts with a global connection key, the dynamic connection takes precedence within the story.
* `$connectionParameters` - The xref:ROOT:glossary.adoc#_examplestable[ExamplesTable] with WinRM connection parameters.
+
:connection-parameters-prefix:
:parameters-name: parameters
include::partial$winrm-connection-parameters.adoc[]

.Configure WinRM connection dynamically
[source,gherkin]
----
When I configure WinRM connection with key `my-connection` and parameters:
|address         |username |password|authentication-scheme|
|10.10.10.10:5985|admin    |Pa$$w0rd|Basic                |
----

=== Execute batch command

Executes a https://en.wikibooks.org/wiki/Windows_Batch_Scripting[native Windows command]. A new session is created on the destination host for each step invocation.

[source,gherkin]
----
When I execute batch command `$command` on server `$connectionKey` using WinRM and save result to $scopes variable `$variableName`
----

* `$command` - The batch command limited to 8096 bytes. The maximum length of the command can be even less depending on the https://support.microsoft.com/en-us/kb/830473[platform].
* `$connectionKey` - The WinRM connection key matching any of configured ones.
* `$scopes` - xref:commons:variables.adoc#_scopes[The comma-separated set of the variables scopes].
* `$variableName` - The variable name to store the command execution results. The data will be stored under the following keys:
+
  - `$variableName.stdout` - the content of the https://en.wikipedia.org/wiki/Standard_streams#Standard_output_(stdout)[command standard output stream];
  - `$variableName.stderr` - the content of the https://en.wikipedia.org/wiki/Standard_streams#Standard_error_(stderr)[command standard error stream];
  - `$variableName.exit-status` - the https://en.wikipedia.org/wiki/Exit_status[exit status (a.k.a exit code)] of the command.

.Check batch command result
[source,gherkin]
----
When I execute batch command `echo hello cmd` on server `my-server` using WinRM and save result as JSON to scenario variable `cmd-result`
Then `${cmd-result.stdout}` is equal to `hello cmd`
Then `${cmd-result.stderr}` is equal to ``
Then `${cmd-result.exit-status}` is equal to `0`
----

=== Execute PowerShell command

Executes a PowerShell[https://docs.microsoft.com/en-us/powershell/scripting/overview] command. A new session is created on the destination host for each step invocation.

[source,gherkin]
----
When I execute PowerShell command `$command` on server `$connectionKey` using WinRM and save result to $scopes variable `$variableName`
----

* `$command` - The PowerShell command.
* `$connectionKey` - The WinRM connection key matching any of configured ones.
* `$scopes` - xref:commons:variables.adoc#_scopes[The comma-separated set of the variables scopes].
* `$variableName` - The variable name to store the command execution results. The data will be stored under the following keys:
+
  - `$variableName.stdout` - the content of the https://en.wikipedia.org/wiki/Standard_streams#Standard_output_(stdout)[command standard output stream];
  - `$variableName.stderr` - the content of the https://en.wikipedia.org/wiki/Standard_streams#Standard_error_(stderr)[command standard error stream];
  - `$variableName.exit-status` - the https://en.wikipedia.org/wiki/Exit_status[exit status (a.k.a exit code)] of the command.

.Check PowerShell command result
[source,gherkin]
----
When I execute PowerShell command `echo hello ps` on server `my-server` using WinRM and save result to scenario variable `ps-result`
Then `${ps-result.stdout}` is equal to `hello ps`
Then `${ps-result.stderr}` is equal to ``
Then `${ps-result.exit-status}` is equal to `0`
----
