= REST API Plugin

The plugin provides the following abilities:

* build and send HTTP requests
* validate HTTP responses (headers, status code, body)
* validate JSON content of HTTP response bodies

:plugin-short-name: rest-api
include::partial$plugin-installation.adoc[]

== Properties

include::plugins:partial$plugin-rest-api-properties.adoc[]

See xref:ROOT:tests-configuration.adoc#_http_configuration[HTTP configuration] for more fine-grained control over the HTTP interactions.

== Expressions

NOTE: The expression parameters marked with *bold* are mandatory.

=== `removeWrappingDoubleQuotes`

When REST API providing the data in JSON format is used it may be required to extract some values from JSON messages.
String values are usually wrapped into double quotes, but sometimes only the value without quotes is needed.
This expression allows to remove wrapping double quotes and use the value as is.

[source, subs="+quotes"]
----
#{removeWrappingDoubleQuotes(*$input*)}
----

* *`$input`* - any string to remove wrapping double quotes

.Extracting ID from JSON data and using it in HTTP GET
[source,gherkin]
----
When I save a JSON element from '${response}' by JSON path '$.id' to story variable 'id'
When I send HTTP GET to the relative URL 'rest/#{removeWrappingDoubleQuotes(${id})}'
----

.Examples of the expressions removing wrapping double quotes
|===
|Expression |Result

|`#{removeWrappingDoubleQuotes("value")}`  |`value`
|`#{removeWrappingDoubleQuotes(value)}`    |`value`
|`#{removeWrappingDoubleQuotes()}`         |`<empty>`
|`#{removeWrappingDoubleQuotes("")}`       |`<empty>`
|`#{removeWrappingDoubleQuotes(""")}`      |`"`
|`#{removeWrappingDoubleQuotes("value)}`   |`"value`
|`#{removeWrappingDoubleQuotes(v"alu"e)}`  |`v"alu"e`
|`#{removeWrappingDoubleQuotes("va"lu"e")}`|`va"lu"e`
|`#{removeWrappingDoubleQuotes("va"lu"e)}` |`"va"lu"e`
|`#{removeWrappingDoubleQuotes("va"lue)}`  |`"va"lue`
|`#{removeWrappingDoubleQuotes(va"lue")}`  |`va"lue"`
|===

=== `encodeUriXyz`

`#{encodeUriXyz(..)}` is a family of expressions that encode specific URI components (e.g. path, query)
by percent encoding illegal characters, which includes non-US-ASCII characters, and also characters that
are otherwise illegal within the given URI component type, as defined in
https://www.ietf.org/rfc/rfc3986.txt[RFC 3986].

[cols="3,2", options="header", subs="+quotes"]
|===
|Syntax
|Description

|`#{encodeUriUserInfo(*$userInfo*)}`
|encodes the given URI user info

|`#{encodeUriHost(*$host*)}`
|encodes the given URI host

|`#{encodeUriPath(*$path*)}`
|encodes the given URI path

|`#{encodeUriPathSegment(*$segment*)}`
|encodes the given URI path segment

|`#{encodeUriQuery(*$query*)}`
|encodes the given URI query

|`#{encodeUriQueryParameter(*$queryParameter*)}`
|encodes the given URI query parameter

|`#{encodeUriFragment(*$fragment*)}`
|encode the given URI fragment
|===

.Examples of the expressions encoding URI parts
|===
|Expression |Result

|`#{encodeUriUserInfo(user@vividus.dev:pass)}`
|user%40vividus.dev:pass

|`#{encodeUriHost(vividus.бел)}`
|vividus.%D0%B1%D0%B5%D0%BB

|`#{encodeUriPath(/path/with spaces/)}`
|/path/with%20spaces/

|`#{encodeUriPathSegment(path/segment)}`
|path%2Fsegment

|`#{encodeUriQuery(a&b=c d)}`
|a&b=c%20d

|`#{encodeUriQueryParameter(a&b)}`
|a%26b

|`#{encodeUriFragment(frag ment)}`
|frag%20ment

|===

== xref:commons:variables.adoc[Dynamic variables]

=== HTTP response as text
The variable provides the HTTP response body of the latest executed HTTP call as
string.

[source,gherkin]
----
${response}
----

.Validate the HTTP response matches the regular expression
[source,gherkin]
----
When I send HTTP GET to the relative URL '/get?name=Content'
Then `${response}` matches `.+Home.+`
----

=== HTTP response as binary data
The variable provides the HTTP response body of the latest executed HTTP call as
binary data.

[source,gherkin]
----
${response-as-bytes}
----

.Save the received Excel document into the temporary folder
[source,gherkin]
----
When I execute HTTP GET request for resource with URL `https://github.com/vividus-framework/vividus/blob/master/vividus-plugin-excel/src/test/resources/TestTemplate.xlsx?raw=true`
When I create temporary file with name `excel` and content `${response-as-bytes}` and put path to scenario variable `excelPath`
----

=== HTTP response code

:http-status-code: https://developer.mozilla.org/en-US/docs/Web/HTTP/Status[HTTP response status code]

The variable provides the {http-status-code} of the latest executed HTTP call.

[source,gherkin]
----
${response-code}
----

.Validate the HTTP response code
[source,gherkin]
----
When I send HTTP GET to the relative URL '/get?name=Content'
Then `${response-code}` is equal to `200`
----

== xref:ROOT:glossary.adoc#_table_transformer[Table Transformers]

=== FROM_JSON

:json-paths: https://github.com/json-path/JsonPath#path-examples[JSON Paths]

`FROM_JSON` transformer constructs a table by mapping table columns to values found by {json-paths} in the source JSON.

[cols="1,3", options="header"]
|===
|Parameter
|Description

|`variable`
|The name of the variable containing source JSON, only variables of scopes `global` and `next_batches` are allowed.

|`url`
a| WARNING: This parameter is deprecated and will be removed in VIVIDUS 0.6.0. `variable` parameter must be used instead.

The URL of the JSON resource that can be retrieved using the https://developer.mozilla.org/en-US/docs/Web/HTTP/Methods/GET[HTTP GET] call.

|columns
a|The semicolon-separated list of mappings between column names and {json-paths} used to get column values.

.Columns parameter format
[source]
----
columns=column_name_1=json_path_1;column_name_2=json_path_2;column_name_N=json_path_N
----

* `column_name` - The user-defined column name in the resulting table.
* `json_path` - The json path used to retrieve a value from the source JSON for a particular column name.

IMPORTANT: The number of elements found by the {json-paths} for each column must be the same.

|===

[IMPORTANT]
`variable` and `url` are competing parameters and only one can be specified at the same time.

.Source JSON
[source,json]
----
[
    {
        "firstName": "Cheryl",
        "lastName": "Wilkerson",
        "age": 36,
        "address": {
            "streetAddress": "690 Selah Way",
            "city": "Waitsfield",
            "postalCode": "05673"
        }
    },
    {
        "firstName": "Zachary",
        "lastName": "Harrington",
        "age": 63,
        "address": {
            "streetAddress": "4803 Duncan Avenue",
            "city": "New York",
            "postalCode": "10014"
        }
    }
]
----

.Usage of FROM_JSON transformer
[source,gherkin]
----
Given request body: {
  "fullName": "<fname> <lname>"
}
When I execute HTTP POST request for resource with URL `https://service-under-test.com/register`
Examples:
{transformer=FROM_JSON, url=https://data-provider/users, columns=fname=$..firstName;lname=$..lastName}
----

== HTTP Steps

=== Set HTTP request configuration

Set up custom request configuration.

[source,gherkin]
----
When I set HTTP request configuration:$configItems
----

* `$configItems` - Table representing list of configuration items with columns "name" and "value" specifying their names and values respectively.
+
.Available configs
|===
|Config |Acceptable values |Request config default value |Description

|`expectContinueEnabled`
|Boolean
|`false`
|Whether the 'https://developer.mozilla.org/en-US/docs/Web/HTTP/Status/100[Expect: 100-Continue]' handshake is enabled

|`staleConnectionCheckEnabled`
|Boolean
|`false`
|Whether stale connection check is to be used

|`redirectsEnabled`
|Boolean
|`true`
|Whether redirects should be handled automatically

|`relativeRedirectsAllowed`
|Boolean
|`true`
|Whether relative redirects should be rejected

|`circularRedirectsAllowed`
|Boolean
|`false`
|Whether "circular redirects" (redirects to the same location) should be allowed

|`authenticationEnabled`
|Boolean
|`true`
|Whether authentication should be handled automatically

|`contentCompressionEnabled`
|Boolean
|`true`
|Whether the target server is requested to compress content

|`normalizeUri`
|Boolean
|`true`
|Whether client should normalize URIs in requests or not

|`maxRedirects`
|Integer
|`50`
|The maximum number of redirects to be followed

|`connectionRequestTimeout`
|Integer
|`-1`
|The timeout in milliseconds used when requesting a connection from the connection manager

|`socketTimeout`
|Integer
|`-1`
|The socket timeout in milliseconds

|`socketTimeout`
|Integer
|`-1`
|The socket timeout in milliseconds, which is the timeout for waiting for data or, put differently, a maximum period inactivity between two consecutive data packets

|`cookieSpec`
|String
|`null`
|The name of the cookie specification to be used for HTTP state management

|===

pass:[*] `-1` means "infinity"

.Load a page with slow connection and with the property `http.socket-timeout` set to `15000`
[source,gherkin]
----
When I set HTTP request configuration:
|socketTimeout |
|25000         |
When I execute HTTP GET request for resource with URL `https://vividus-test-site.onrender.com/?pageTimeout=20000`
Then '${responseStatusCode}' is = '200'
----

=== Set HTTP request body

Sets HTTP request body that will be used while executing the request. In the case of textual content the default HTTP
request header with name `Content-Type` and value `text/plain; charset=UTF-8` is set.

WARNING: No HTTP request header is set in the case of binary content.

[source,gherkin]
----
Given request body: $content
----

* `$content` - HTTP request body.

.Set textual HTTP request body
[source,gherkin]
----
Given request body: Hello!
----

.Set binary HTTP request body
[source,gherkin]
----
Given request body: #{loadBinaryResource(/data/image.png)}
When I set request headers:
|name        |value    |
|Content-Type|image/png|
When I send HTTP POST to the relative URL '/upload/png'
----

=== Prepare multipart HTTP request

Sets https://tools.ietf.org/html/rfc7578[multipart] request entity that will be used while executing HTTP requests.

[source,gherkin]
----
Given multipart request:$requestParts
----

where `requestParts` is xref:ROOT:glossary.adoc#_examplestable[ExamplesTable] representing the list of the request parts with the following columns:

* `type` - One of request part types: `STRING`, `FILE`, `BINARY`.
* `name` - The request part name.
* `value` -
** For `FILE` part type - the xref:ROOT:glossary.adoc#_resource[resource name] or the file path.
** For `STRING` or `BINARY` part type - the actual content.
* `contentType` - The https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/Content-Type[content type].
* `fileName` - The name of the file contained in this request part. The
parameter is not allowed for `STRING` part type, but it's required for `BINARY` one and optional for `FILE` part type.

.Init HTTP request consisting of 4 different parts
[source,gherkin]
----
Given I initialize scenario variable `temp-file-content` with value `Your first and last stop for No-Code Test Automation!`
When I create temporary file with name `abc.txt` and content `${temp-file-content}` and put path to scenario variable `temp-file-path`
Given multipart request:
|type  |name      |value            |contentType|fileName       |
|file  |file-key  |/data/file.txt   |           |anotherName.txt|
|file  |file-key2 |${temp-file-path}|text/plain |               |
|string|string-key|string1          |text/plain |               |
|binary|binary-key|raw              |text/plain |raw.txt        |
----

=== Set form data HTTP request

Sets https://www.w3.org/TR/html401/interact/forms.html#h-17.13.4.1[URL-encoded form data] request entity that will be used while executing HTTP requests.
Default HTTP request header with name `Content-Type` and value `application/x-www-form-urlencoded; charset=UTF-8` is set.
In case if `Content-Type` is `text/plain` <<Set HTTP request body>> should be used

[source,gherkin]
----
Given form data request:$parameters
----

* `$parameters` -  The xref:ROOT:glossary.adoc#_examplestable[ExamplesTable] representing list of parameters with columns `name` and `value` specifying form data request.

.Set form data HTTP request body
[source,gherkin]
----
Given form data request:
|name     |value  |
|firstName|Ivan   |
|lastName |Ivanov |
|password |!@3qwer|
----


=== Add HTTP headers to the request

include::plugins:partial$plugin-rest-api-http-headers-to-request.adoc[]

=== Execute HTTP request with absolute URL

include::plugins:partial$plugin-rest-api-execute-http-request-with-absolute-url-step.adoc[]

=== Execute HTTP request with relative URL

Executes the HTTP request for a resource identified by the URL relative to the base URL specified by the `rest-api.http.endpoint`
property. The step uses previously set HTTP headers and request body. The HTTP response headers, status code and body can be
accessed via the corresponding steps and dynamic variables.

[source,gherkin]
----
When I execute HTTP $httpMethod request for resource with relative URL `$relativeURL`
----

* `$httpMethod` - The https://developer.mozilla.org/en-US/docs/Web/HTTP/Methods[HTTP method].
* `$relativeURL` - The relative URL of the resource on the server.

.Configuration
[source,properties]
----
rest-api.http.endpoint=https://httpbin.org
----

.Execute HTTP GET request
[source,gherkin]
----
When I execute HTTP GET request for resource with relative URL `/image/jpeg`
----

=== Compare HTTP response body against resource

Compares the HTTP response body against the xref:ROOT:glossary.adoc#_resource[resource] data according to the provided rule.

[source,gherkin]
----
Then response body $validationRule resource at `$resourcePath`
----

* `$validationRule` - The validation rule, either `is equal to` or `is not equal to`.
* `$resourcePath` - The xref:ROOT:glossary.adoc#_resource[resource] path.

.Compare images
[source,gherkin]
----
When I execute HTTP GET request for resource with URL `https://httpbin.org/image/png`
Then response body is equal to resource at `/images/pig.png`
----

=== Validate HTTP response code

include::plugins:partial$plugin-rest-api-validate-http-response-code-step.adoc[]

=== Validate HTTP response time

Compares the HTTP response time against the expected number in milliseconds.

[source,gherkin]
----
Then response time is $comparisonRule `$responseTime` milliseconds
----

* `$comparisonRule` - xref:parameters:comparison-rule.adoc[The comparison rule].
* `$responseTime` - The expected response time in milliseconds.

.Check HTTP response time
[source,gherkin]
----
When I execute HTTP GET request for resource with URL `https://example.com`
Then response time is less than `1000` milliseconds
----

=== Valdate number of HTTP response headers

:http-response-header: https://en.wikipedia.org/wiki/List_of_HTTP_header_fields#Response_fields[HTTP response header]

Validates the number of HTTP response headers filtered by the specified name.

[source,gherkin]
----
Then number of response headers with name `$headerName` is $comparisonRule $number
----

* `$headerName` - The {http-response-header} name.
* `$comparisonRule` - xref:parameters:comparison-rule.adoc[The comparison rule].
* `$number` - The expected number of headers.

.Check the browser is forced to use a secure web connection
[source,gherkin]
----
Then number of response headers with name `Strict-Transport-Security` is equal to 1
----

=== Validate HTTP response header value

Compares the header value against the expected value according to the comparison rule.

[source,gherkin]
----
Then value of response header `$headerName` $comparisonRule `$value`
----

* `$headerName` - The {http-response-header} name.
* `$comparisonRule` - xref:parameters:string-comparison-rule.adoc[The string comparison rule].
* `$number` - The expected HTTP header value.

.Check HTTP response content type
[source,gherkin]
----
When I execute HTTP GET request for resource with URL `https://httpbin.org/robots.txt`
Then value of response header `Content-Type` is equal to `text/plain`
----

=== Validate HTTP response header elements

Validates that the response header with the specified name contains elements. Might be useful to verify such HTTP
headers as `Set-Cookie` that have values that can be decomposed into multiple elements.

.HTTP header with elements format
[source]
----
header = [ element ] *( "," [ element ] )
----

[source,gherkin]
----
Then response header `$headerName` contains elements:$elements
----

* `$headerName` - The {http-response-header} name.
* `$attributes` - The xref:ROOT:glossary.adoc#_examplestable[ExamplesTable] with expected elements.

.Check attributes of Set-Cookie header
[source,gherkin]
----
When I execute HTTP GET request for resource with URL `https://httpbin.org/authenticate`
Then response header `Set-Cookie` contains elements:
|element |
|JSESSION|
|clientId|
----

=== Save HTTP response header value

Saves the HTTP response header value into a variable.

[source,gherkin]
----
When I save response header `$headerName` value to $scopes variable `$variableName`
----

* `$headerName` - The {http-response-header} name.
* `$scopes` - xref:commons:variables.adoc#_scopes[The comma-separated set of the variables scopes].
* `$variableName` - The variable name to store the header value.

.Save Content-Length header value
[source,gherkin]
----
When I execute HTTP GET request for resource with URL `https://httpbin.org/brotli`
When I save response header `Content-Length` value to scenario variable `length`
----

=== Validate connection security

Validates that the HTTP connection is secured with the defined security protocol.

[source,gherkin]
----
Then connection is secured using $securityProtocol protocol
----

* `$securityProtocol` - The expected security protocol, e.g. `TLSv1.2`, `TLSv1.3`

.Check that the httpbin is secured
[source,gherkin]
----
When I execute HTTP GET request for resource with URL `https://httpbin.org/`
Then connection is secured using TLSv1.2 protocol
----

=== Validate secure protocols supported by server

include::plugins:partial$plugin-rest-api-validate-secure-protocols-supported-by-server-step.adoc[]

include::plugins:partial$plugin-rest-api-waiting-steps.adoc[]


=== Validate content type of response body

:content-type: https://www.iana.org/assignments/media-types/media-types.xhtml[content type]

Checks content type of HTTP response body matches to the specified expected {content-type} according to the provided string validation rule.

[source,gherkin]
----
Then content type of response body $comparisonRule `$contentType`
----

* `$comparisonRule` - xref:parameters:string-comparison-rule.adoc[String validation rule].
* `$contentType` – Expected {content-type}, e.g. `text/html`, `application/xml`, `application/json`.

.Submit a GET request and check that response body type is `application/json`
[source,gherkin]
----
When I execute HTTP GET request for resource with URL `https://httpbin.org/json`
Then content type of response body is equal to `application/json`
----

=== Validate absence of response body

Validates that the HTTP response does not contain a body.

[source,gherkin]
----
Then response does not contain body
----

.Submit a POST request and check that response body is absent
[source,gherkin]
----
When I execute HTTP POST request for resource with URL `https://httpbin.org/json`
Then response does not contain body
----

=== Validate size of response body

include::plugins:partial$plugin-rest-api-validate-size-of-response-body-step.adoc[]

=== Save ZIP archive entries

[WARNING]
====
The step xref:commons:vividus-steps.adoc#_save_zip_archive_entries[is moved] to core package
i.e. it's not required to install any plugin to use this step - it's available out of the box.
====

=== Validate ZIP archive

[WARNING]
====
The step xref:commons:vividus-steps.adoc#_validate_zip_archive[is moved] to core package
i.e. it's not required to install any plugin to use this step - it's available out of the box.
====

=== Validate HTTP resources

Validates the defined HTTP resources

Actions performed by step:

* executes https://developer.mozilla.org/en-US/docs/Web/HTTP/Methods/HEAD[HTTP HEAD] request against the passed URL
* if the status code is `200` then the check is considered as `passed`
* if the status code falls under any of `404`, `405`, `501`, `503` then the https://developer.mozilla.org/en-US/docs/Web/HTTP/Methods/GET[HTTP GET] request will be sent
* if the GET status code is `200` then check is considered as `passed`, otherwise `failed`
* if the target URL has already been checked then the check is considered as `skipped`

[source,gherkin]
----
Then HTTP resources are valid:$resources
----

* `resources` - The URLs of HTTP resources to validate

.Verify HTTP resources
[source,gherkin]
----
Then HTTP resources are valid:
|url                                                   |
|https://saucelabs.com                                 |
|https://vividus-test-site.onrender.com/img/vividus.png|
----


== HTTP cookie steps

include::plugins:partial$plugin-rest-api-cookie-steps.adoc[]

== JSON Steps

:json-path: https://github.com/json-path/JsonPath#path-examples[JSON Path]
:json-unit-options: https://github.com/lukas-krecan/JsonUnit/blob/master/README.md#options[options]

include::plugins:partial$plugin-rest-api-json-steps.adoc[]


== Tips & Tricks

=== Validate HTTP response body

In order to validate the body of the latest HTTP response use the <<_http_response_as_text,response>> dynamic variable to access the body
data in conjunction with any step responsible for data validation like data comparison, JSON, XML and other steps.

.Validate response body
[source,gherkin]
----
When I execute HTTP GET request for resource with URL `https://httpbin.org/json`
Then JSON element from `${response}` by JSON path `$.slideshow` is equal to `
{
  "author": "Yours Truly",
  "date": "date of publication",
  "slides": [
    {
      "title": "Wake up to WonderWidgets!",
      "type": "all"
    },
    {
      "items": [
        "Why <em>WonderWidgets</em> are great",
        "Who <em>buys</em> WonderWidgets"
      ],
      "title": "Overview",
      "type": "all"
    }
  ],
  "title": "Sample Slide Show"
}
`
----

=== Save HTTP response body into variable

The HTTP response body can be saved into static variable by using the xref:commons:vividus-steps.adoc#_initialize_variable[init variable step]
in conjunction with the <<_http_response_as_text,response>> dynamic variable, it might be useful if you want to preserve the data for further computations since each
subsequent HTTP call rewrites previously received response data.

.Save response body into variable
[source,gherkin]
----
When I execute HTTP GET request for resource with URL `https://httpbin.org/json`
When I initialize the scenario variable `json` with value `${response}`
----
