= AWS S3 Plugin

The plugin provides functionality to interact with https://aws.amazon.com/s3/[Amazon Simple Storage Service (Amazon S3)].

== Installation

.build.gradle
[source,gradle,subs="attributes+"]
----
implementation(group: 'org.vividus', name: 'vividus-plugin-aws-s3', version: '{current-version}')
----

== Configuration

=== Authentication

The plugin will search for credentials using https://docs.aws.amazon.com/sdk-for-java/v1/developer-guide/credentials.html#credentials-default[the default credential provider chain] in the following order:

. In system environment variables: `AWS_ACCESS_KEY_ID` and `AWS_SECRET_ACCESS_KEY`.
. In the properties: `system.aws.accessKeyId` and `system.aws.secretKey`.
. Web Identity Token credentials from the environment or container.
. In the default credentials file (the location of this file varies by platform).
. Credentials delivered through the Amazon EC2 container service if the `AWS_CONTAINER_CREDENTIALS_RELATIVE_URI` environment variable is set and security manager has permission to access the variable.
. In the _instance profile credentials_, which exist within the instance metadata associated with the IAM role for the EC2 instance. This step is available only when running your application on an Amazon EC2 instance, but provides the greatest ease of use and best security when working with Amazon EC2 instances.

See the official https://docs.aws.amazon.com/sdk-for-java/v1/developer-guide/credentials.html#credentials-default["Working with AWS Credentials"] guide to get more details.

== Steps

=== Download S3 object

Retrieve the object by key from the provided S3 bucket and save its content to a variable. The specified bucket and object key must exist, or an error will result.


[source,gherkin]
----
When I fetch object with key `$objectKey` from S3 bucket `$bucketName` and save result to $scopes variable `$variableName`
----

- `$objectKey` - the key under which the desired object is stored
- `$bucketName` - the name of the bucket containing the desired object
- `$scopes` - xref:parameters:variable-scope.adoc[the comma-separated set of the variables scopes]
- `$variableName` - the variable name

.Download S3 object
[source,gherkin]
----
When I fetch object with key `/path/file.json` from S3 bucket `some-bucket-name` and save result to scenario variable `my-json-var`
----
