:grid-default-hostname: empty
:keys: https://github.com/appium/appium-xcuitest-driver#mobile-pressbutton[iOS keys] or https://appium.github.io/java-client/io/appium/java_client/android/nativekey/AndroidKey.html[Android keys]
:given-step: Given I start mobile application

= Mobile Application Plugin

The plugin provides functionality to test mobile application on real devices, Android Emulators and iOS Simulators.

== Installation

.build.gradle
[source,gradle,subs="attributes+"]
----
implementation(group: 'org.vividus', name: 'vividus-plugin-mobile-app', version: '{current-version}')
----


include::partial$locator-header.adoc[]


=== Filter Types

[cols="1,2,2", options="header"]
|===

|Type
|Description
|Examples

include::partial$common-filters.adoc[]

|text
|Filter elements by their exact text.
|tagName(android.widget.EditText)->filter.text(Welcome)

|attribute
|Filter elements by their attribute values
a|`tagName(android.widget.TextView)->filter.attribute(text=Hi)` - `android.widget.TextView` element has the `text` attribute with `Hi` value
`tagName(android.widget.TextView)->filter.attribute(text)` - `android.widget.TextView` element has the `text` attribute with any value
`tagName(android.widget.TextView)->filter.attribute(text=)` - `android.widget.TextView` element has the `text` attribute with an empty value

|===


=== Locator Types
:locator-strategy: https://appium.io/docs/en/commands/element/find-elements/index.html#selector-strategies

[cols="1,1,2,2", options="header"]
|===

|Type
|Platform
|Description
|Examples

|XPath
|any
|Search the app XML source using xpath (not recommended, has {locator-strategy}[performance issues])
|xpath(//android.widget.TextView[@text='Home']) or By.xpath(//XCUIElementTypeStaticText[@value='Home'])

|Accessibility ID
|any
|See {locator-strategy}[Accessibility ID] selector strategy
|accessibilityId(menu-toggler) or By.accessibilityId(menu-toggler)

|ID
|any
|See {locator-strategy}[ID] selector strategy
|id(org.vividus:id/menu-toggler) or By.id(menu-toggler)

|iOS Class Chain
|`iOS`
|See https://github.com/facebookarchive/WebDriverAgent/wiki/Class-Chain-Queries-Construction-Rules[Class Chain Queries] for more details
|+iosClassChain(**/XCUIElementTypeCell[$name BEGINSWITH "A"$])+ or +By.iosClassChain(**/XCUIElementTypeCell[$name BEGINSWITH "B"$])+

|===

include::partial$visibility-types.adoc[]



== Properties

:application-under-test: mobile application
:session-scope-property-base: mobile-application
[cols="6,3,2,6", options="header"]
|===
|Property Name
|Acceptable values
|Default
|Description

include::partial$selenium-properties.adoc[]
include::partial$selenium-grid-properties.adoc[]

|`selenium.grid.platform-name`
a|`Android`

`iOS`
|Depends on the set profile
|Defines the mobile OS to use

|`selenium.grid.automation-name`
a|`UIAutomator2`
`XCUITest`
|Depends on the set profile
a|Defines automation engine to use
[cols="1,2", options="header"]
!===

!Platform
!Recommended engine

!`Android`
!http://appium.io/docs/en/drivers/android-uiautomator2/[UIAutomator2]

!`iOS`
!http://appium.io/docs/en/drivers/ios-xcuitest/[XCUITest]
!===

|`mobile-environment.real-device`
a|`true`

`false`

|Depends on the set profile

a|Defines whether the tests run on real device
[cols="2,1", options="header"]
!===

!Profile
!Value

!`browserstack/mobile_app`
!`true`

!`mobile_app/ios`
!`false`

!`mobile_app/android`
!`false`

!===

|`mobile-environment.device.folder-for-file-upload`
|`string`

|Depends on the set profile

a|Defines a destination folder on a device for a file being uploaded
[cols="1,1", options="header"]
!===

!Profile
!Value

!`mobile_app/ios`
!`/private/var/mobile/Media/DCIM/`

!`mobile_app/android`
!`/sdcard/Pictures`

!===
include::partial$proxy-properties.adoc[]
|===

include::partial$proxy-meta-tags.adoc[]

IMPORTANT: For device configuration, we need to perform the following steps: install CA certificate(download https://github.com/browserup/browserup-proxy/blob/master/browserup-proxy-core/src/main/resources/sslSupport/ca-certificate-rsa.cer[CA certificate] from a browserup repository), configure device proxy, and configure the test app to allow proxy in cases of necessity.

== Profiles

=== iOS
:ios-profile: mobile_app/ios

The profile can be enabled by adding `{ios-profile}` to `configuration.profiles` property

Default profile configuration
[source,properties]
----
selenium.grid.platform-name=iOS
selenium.grid.automation-name=XCUITest
----

=== tvOS
:tvos-profile: mobile_app/tvos

The profile can be enabled by adding `{tvos-profile}` to `configuration.profiles` property

Default profile configuration
[source,properties]
----
selenium.grid.platform-name=tvOS
selenium.grid.automation-name=XCUITest
----

=== Android
:android-profile: mobile_app/android

The profile can be enabled by adding `{android-profile}` to `configuration.profiles` property

Default profile configuration
[source,properties]
----
selenium.grid.platform-name=Android
selenium.grid.automation-name=UIAutomator2
----

=== Local
:local-profile: mobile_app/local

The profile simplifies execution of tests against the local Appium server. It could be used in conjunction with: `{android-profile}`, `{ios-profile}`, `{tvos-profile}`
The profile can be enabled by adding `{local-profile}` to `configuration.profiles` property

Default profile configuration
[source,properties]
----
selenium.grid.url=http://127.0.0.1:4723/wd/hub
selenium.grid.platformName=${selenium.grid.platform-name}
selenium.grid.automationName=${selenium.grid.automation-name}
----

include::partial$dynamic-variables-header.adoc[]

=== Get clipboard text

Gets the text of the system clipboard of simulator or real device

==== Properties

[cols="1,1,3", options="header"]

|===

|Property Name
|Default
|Description

|`mobile-environment.wda-bundle-id`
|`empty`
|The property is for iOS real devices only and it specifies the WebDriverAgent bundle ID used to http://appium.io/docs/en/commands/device/clipboard/get-clipboard/#description[get clipboard text]. The property value may vary depending on test cloud providers and can be found in the XCode logs.

|===

[source]
----
${clipboard-text}
----

.Verify clipboard content
[source,gherkin]
----
Then `${clipboard-text}` is equal to `uarlouski@gmail.com`
----

include::partial$dynamic-variables-ui.adoc[]

== Steps

=== Start mobile application

Starts mobile application with capabilities from user's `*.properties` files and profiles set by a user.

[source,gherkin]
----
Given I start mobile application
----

=== Start mobile application with capabilities

Starts mobile application with capabilities from user's `*.properties` files and profiles set by a user.
Additionally the step takes a list of capabilities as an argument that overrides gloablly-defined capabilities.

[source,gherkin]
----
Given I start mobile application with capabilities:$capabilities
----

* `$capabilities` - The capabilities to start application with, these capabilies
have higher priority than capabilities defined in `*.properties` files and profiles.

.Start mobile application with 2 custom capabilities
[source,gherkin]
----
Given I start mobile application with capabilities:
|name                           |value|
|bstack:options.networkLogs     |true |
|appium:options.clearSystemFiles|false|
----


=== Activate mobile application

Activates the existing application on the device/emulator/simulator and moves
it to the foreground. The application should be already running in order to
activate it.

[source,gherkin]
----
When I activate application with bundle identifier `$bundleId`
----

* `$bundleId` - `Package name` for Android or `Bundle identifier` from `Plist.info` for iOS

.Switch to Safari browser application
[source,gherkin]
----
When I activate application with bundle identifier `com.apple.mobilesafari`
----


=== Reinstall mobile application

Removes the mobile application from device/emulator/simulator and installs it again.

[source,gherkin]
----
When I reinstall mobile application with bundle identifier `$bundleId`
----

* `$bundleId` - `Package name` for Android or `Bundle identifier` from `Plist.info` for iOS.

The key benefit is that instead of the full remote session recreation (which
includes device re-allocation in testing clouds, like SauceLabs, BrowserStack,
etc.) achivable via the following example:

[source,gherkin]
----
When I close mobile application
Given I start mobile application with capabilities:
|name     |value|
|fullReset|true |
----

the step re-uses the current session which significantly improves performance.

.Reinstall mobile application
[source,gherkin]
----
When I reinstall mobile application with bundle identifier `vividus-mobile.app`
----


=== Terminate mobile application

Terminates the running application on the device/emulator/simulator and
navigates to the home device screen. The remote session will not be closed.

[source,gherkin]
----
When I terminate application with bundle identifier `$bundleId`
----

* `$bundleId` - `Package name` for Android or `Bundle identifier` from `Plist.info` for iOS

.Terminates Safari browser application
[source,gherkin]
----
When I terminate application with bundle identifier `com.apple.mobilesafari`
----


=== Close mobile application

Closes the mobile application and quits the remote session.

[source,gherkin]
----
When I close mobile application
----


=== Change session settings

Changes the behavior of the Appium session.

[source,gherkin]
----
When I change Appium session settings:$settings
----

* `$settings` - https://appium.io/docs/en/advanced-concepts/settings/#settings[The settings] to set.

.Configure to show invisible elements
[source,gherkin]
----
When I change Appium session settings:
|name                  |value|
|allowInvisibleElements|true |
----


=== Upload a file to the device

Uploads a file to the device/emulator/simulator.

[source,gherkin]
----
When I upload file `$filePath` to device
----

* `$filePath` - The path of the file to upload to the device.

.Upload file
[source,gherkin]
----
When I upload file `images/avatar.png` to device
Then the avatar icon is displayed with the uploaded image
----

:web-view-info: See http://appium.io/docs/en/writing-running-appium/web/hybrid/[Automating hybrid apps] for more information.

=== Switch to Web view by index

[WARNING]
This step is deprecated and will be removed in VIVIDUS 0.5.0. The replacement is <<_switch_to_web_view_by_name>>.

Switches context to a web view by the index, it starts from 1. {web-view-info}

[source,gherkin]
----
When I switch to web view with index `$index`
----

* `$index` - The index of the web view.

.Switch to web view by index
[source,gherkin]
----
Then number of elements found by `xpath(html)` is equal to `0`
When I switch to web view with index `1`
Then number of elements found by `xpath(html)` is equal to `1`
----


=== Switch to Web view by name

Switches context to a web view with name that matches the rule. {web-view-info}

[source,gherkin]
----
When I switch to web view with name that $comparisonRule `$value`
----

* `$comparisonRule` - xref:parameters:string-comparison-rule.adoc[The web view name comparison rule].
* `$value` - The value to find the target web view.

.Switch to web view by name
[source,gherkin]
----
Then number of elements found by `xpath(html)` is equal to `0`
When I switch to web view with name that contains `vividustestapp`
Then number of elements found by `xpath(html)` is equal to `1`
----


=== Switch to native context

Switches context to a mobile native context. See http://appium.io/docs/en/writing-running-appium/web/hybrid/[Automating hybrid apps] for more information.

[source,gherkin]
----
When I switch to native context
----

.Switch to native context
[source,gherkin]
----
Then number of elements found by `xpath(html)` is equal to `1`
When I switch to native context
Then number of elements found by `xpath(html)` is equal to `0`
----


=== Tap on element

Taps on the element located by the locator.

The atomic actions performed are:
* press on the element;
* release.

[source,gherkin]
----
When I tap on element located `$locator`
----

* `$locator` - <<_locator>>.

.Tap on element
[source,gherkin]
----
When I tap on element located `accessibilityId(menu-toggler)`
----


=== Tap on element with duration

Taps on the element located by the locator with the specified duration.

The atomic actions performed are:
* press on the element;
* wait for the duration;
* release.

[source,gherkin]
----
When I tap on element located `$locator` with duration `$duration`
----

* `$locator` - <<_locator>>.
* `$duration` - The duration between an element is pressed and released in {iso-date-format-link} format.

.Tap on element with duration
[source,gherkin]
----
When I tap on element located `accessibilityId(menu-toggler)` with duration `PT0.5S`
----


=== Press key

Presses {keys}.

[source,gherkin]
----
When I press $key key
----

* `$key` - The key to press.

.Go to Home screen
[source,gherkin]
----
When I press Home key
----


=== Long press key

Performs long press of {keys}.

TIP: to modify long press duration for `iOS` and `tvOS` you could use `mobile-application.long-press-duration` property.

[source,gherkin]
----
When I long press $key key
----

* `$key` - The key to perform long press action.

.Go to Home screen
[source,gherkin]
----
When I long press Home key
----


=== Press keys

Presses a sequence of {keys}.

[source,gherkin]
----
When I press keys:$keys
----

* `$keys` - The keys to press.

.Enter password
[source,gherkin]
----
When I press keys:
|key|
|P  |
|a  |
|s  |
|1  |
|$  |
----


=== Type text sequentially

Types the provided text

[WARNING]
All the characters will be treated as is and passed sequentially. To send special key like `HOME` please use <<_press_keys>>.

[source,gherkin]
----
When I type text `$text`
----

* `$text` - The text to type.

.Enter password
[source,gherkin]
----
When I type text `pas1$`
----


=== Type text in a field

Types the text into the element located by the locator.

WARNING: The existing text is re-written by the text passed into the step.

The atomic actions performed are:
* type text into the element;
* hide keyboard.

[WARNING]
For `iOS` real devices the hide keyboard action works only for
`XCUIElementTypeTextField` elements and skipped for `XCUIElementTypeTextView`
elements, in case of `XCUIElementTypeTextView` element tap outside the text view
is performed to close the keyboard.

[source,gherkin]
----
When I type `$text` in field located `$locator`
----

* `$text` - The text to type into the element.
* `$locator` - <<_locator>>.

.Type text
[source,gherkin]
----
When I type `Bob` in field located `accessibilityId(username)`
----


=== Type text and keep keyboard opened

Only types text into the element. The keyboard hiding is skipped.

[source,gherkin]
----
When I type `$text` in field located `$locator` and keep keyboard opened
----

* `$text` - The text to type into the element.
* `$locator` - <<_locator>>.

.Type text and keep keyboard opened
[source,gherkin]
----
When I type `Bob` in field located `accessibilityId(username)` and keep keyboard opened
----


=== Clear field

Clears the field located by the locator.

The atomic actions performed are:
* clear the field;
* hide keyboard.

[WARNING]
For `iOS` real devices the hide keyboard action works only for
`XCUIElementTypeTextField` elements and skipped for `XCUIElementTypeTextView`
elements, in case of `XCUIElementTypeTextView` element tap outside the text view
is performed to close the keyboard.

[source,gherkin]
----
When I clear field located `$locator`
----

* `$locator` - <<_locator>>.

.Clear the field
[source,gherkin]
----
When I clear field located `accessibilityId(username)`
----


=== Swipe to an element

Swipes to an element in either `UP`, `DOWN`, `LEFT` or `RIGHT` direction with
the specified swipe duration.

[NOTE]
The step takes into account the current context. If you need to perform swipe on
the element, you need to switch the context to this element.

==== Properties

* `mobile-application.swipe.limit` - defines max numbers of swipes to perform (if it's reached the swipe process is stopped and the error is thrown)
* `mobile-application.swipe.stabilization-duration` - defines a duration to wait after swipe until view becomes stable
* `mobile-application.swipe.vertical.x-position` - defines a vertical swipe `x` axis position in percentage from `0` to `100`, where `0` corresponds to `x=1` and `100` corresponds to `x = mobile screen width - 1`, default value is `0`
* `mobile-application.swipe.horizontal.y-position` - defines a horizontal swipe `y` axis position in percentage from `0` to `100`, where `0` corresponds to `y=1` and `100` corresponds to `y = mobile screen height - 1`, default value is `50`

[source,gherkin]
----
When I swipe $direction to element located `$locator` with duration $swipeDuration
----

* `$direction` - The direction to swipe: `UP`, `DOWN`, `LEFT` or `RIGHT`.
* `$locator` - <<_locator>>.
* `$swipeDuration` - The swipe duration in {iso-date-format-link} format.

.Swipe to an element
[source,gherkin]
----
Then number of elements found by `accessibilityId(end-of-screen)` is equal to `0`
When I swipe UP to element located `accessibilityId(end-of-screen)` with duration PT1S
Then number of elements found by `accessibilityId(end-of-screen)` is equal to `1`
----

.Swipe the context element
[source,gherkin]
----
Scenario: Switch slides
When I change context to element located `accessibilityId(carousel)`
Then number of elements found by `accessibilityId(slide 2)` is equal to `0`
When I swipe LEFT to element located `accessibilityId(slide 2)` with duration PT1S
Then number of elements found by `accessibilityId(slide 2)` is equal to `1`
----


=== Select date in date picker

Selects a next or previous picker wheel value in date picker

[WARNING]
* Only `iOS` platform is supported.
* The target element must be of type `XCUIElementTypePickerWheel`.

[source,gherkin]
----
When I select $direction value with `$offset` offset in picker wheel located `$locator`
----

* `$direction` - The direction to search the value: `NEXT` or `PREVIOUS`.
* `$offset` - The ofset to pick from a middle of the wheel, see https://appium.io/docs/en/writing-running-appium/ios/ios-xctest-mobile-gestures/index.html#mobile-selectpickerwheelvalue[Select Picker Wheel Value guide].
* `$locator` - The locator to find `XCUIElementTypePickerWheel` element.

.Select next item in the picker wheel
[source,gherkin]
----
When I select next value with `0.1` offset in picker wheel located `xpath(//XCUIElementTypePickerWheel)->filter.index(3)`
----


=== Recording iOS Performance metrics

Records performance metrics of iOS application. It is based on the Instruments utility distributed by Xcode which provides a number of built-in analyses and measurements.
See https://appiumpro.com/editions/12-capturing-performance-data-for-native-ios-apps[Capturing Performance Data for Native iOS Apps] and https://developer.apple.com/videos/play/wwdc2019/411/[Getting Started with Instruments] for more information.

[NOTE]
Appium server should be started with the *--relaxed-security* flag. This is because Instruments can gather data from the system as a whole, not just the AUT. (It's thus a security risk to expose potentially sensitive system information to Appium sessions running from a remote client).

[NOTE]
Archive with results contains *.trace file which could be opened by XCode. There is possibility to parse this file using XCode's utility https://keith.github.io/xcode-man-pages/xctrace.1.html[xctrace] and use generated data in tests

[source,gherkin]
----
When I start recording `$instrument` metrics
When I stop recording `$instrument` metrics and save results to file `$path`
----

. `$instrument` - The instrument of Xcode Instruments utility. Some useful instruments: Time Profiler, Leaks, File Activity, etc.
. `$path` - The path to the file to save an archive with collected data.

.Perform profiling during application usage
[source,gherkin]
----
When I start recording `Time Profiler` metrics
!-- set of actions to measure performance
When I stop recording `Time Profiler` metrics and save results to file `${outputDirectory}/time_profiler.zip`
----


include::partial$generic-ui-steps.adoc[]

include::partial$proxy-steps.adoc[]

=== Change network condition

Turn ON/OFF network condition.

[source,gherkin]
----
When I turn $toggle `$mode` network connection
----
* `$toggle` - The modes of the toggle: `ON` or `OFF`.
* `$mode` - The name of the network connect to toggle.

[cols="2,2,2", options="header"]
|===

|Mode
|Platform
|Description

|`WIFI`
|Android, iOS and emulators
|Turn ON/OFF Wi-Fi connection state only.

|`MOBILE_DATA`
|Android, iOS and emulators
|Turn ON/OFF Mobile Data connection state only.

|`AIRPLANE`
|Android and emulators
|Turn ON/OFF Airplane Mode only.

|`WIFI_AND_MOBILE_DATA`
|Android and emulators
|Turn ON/OFF Mobile Data and Wi-Fi state.

|===

TIP: For IOS devices: to return to the application you must use the step:
[source,gherkin]
----
When I activate application with bundle identifier `$bundleId`.
----

WARNING: To be able to use this step in the cloud testing platform, review the documentation related to simulating the mobile network conditions of the selected platform.

.Turn OFF Wi-Fi for Android
[source,gherkin]
----
When I turn OFF `WIFI` network connection
----

.Turn OFF Wi-Fi for iOS
[source,gherkin]
----
When I turn OFF `WIFI` network connection
When I activate application with bundle identifier `$bundleId`
----
