:test-cloud-name: SauceLabs
:test-cloud-key: saucelabs
:test-cloud-link: https://saucelabs.com/
:test-cloud-capabilities: https://wiki.saucelabs.com/display/DOCS/Platform+Configurator#/

include::partial$test-cloud-header.adoc[]

== Profiles

The plugin defines profiles with a set of the preconfigured properties.

[cols="1,2"]
|===

|`saucelabs/web`
|Use in conjunction with xref:plugins:plugin-web-app.adoc#_desktop[desktop web application profiles].

|`saucelabs/web/phone/iphone`
a|Use in conjunction with xref:plugins:plugin-web-app.adoc#_mobile_web[mobile web application profiles].

Required properties:

* `selenium.grid.device-name`
* `selenium.grid.platform-version`

|`saucelabs/web/phone/android`
a|Use in conjunction with xref:plugins:plugin-web-app.adoc#_mobile_web[mobile web application profiles].

Required properties:

* `selenium.grid.device-name`
* `selenium.grid.platform-version`

|`saucelabs/mobile_app`
a|Use in conjunction with xref:plugins:plugin-mobile-app.adoc#_profiles[native mobile application profiles].

Required properties:

* `selenium.grid.device-name`
* `selenium.grid.appium-version`
* `selenium.grid.platform-version`
|===

include::partial$test-cloud-usage.adoc[]

== Properties

NOTE: The properties marked with *bold* are mandatory.

[cols="3,2,1,3", options="header"]
|===
|Property Name
|Acceptable values
|Default
|Description

|[subs=+quotes]`*selenium.grid.host*`
|hostname
|`<empty>`
|https://wiki.saucelabs.com/display/DOCS/Data+Center+Endpoints[Sauce Labs OnDemand host] to be used to create a new session

|[subs=+quotes]`*selenium.grid.username*`
|username
|`<empty>`
|https://docs.saucelabs.com/basics/data-center-endpoints/#authorization-credentials[Sauce Labs username]

|[subs=+quotes]`*selenium.grid.password*`
|password
|`<empty>`
|https://docs.saucelabs.com/basics/data-center-endpoints/#authorization-credentials[Sauce Labs access key]

|[subs=+quotes]`*saucelabs.data-center*`
a|
* `US_WEST` +
* `US_EAST` +
* `EU_CENTRAL` +
|
|https://wiki.saucelabs.com/display/DOCS/Data+Center+Endpoints[Sauce Labs data center] to use

|`saucelabs.free-device-wait-timeout`
|{durations-format-link} format
|`PT0S`
|When the https://docs.saucelabs.com/dev/error-messages/#youve-exceeded-your-sauce-labs-concurrency-limit[Sauce Labs concurrency limit is exceeded],
the error message will be "Could not start a new session. Response code 400. Message: CCYAbuse - too many jobs".
This means all devices are busy. This property sets the maximum wait time for a free device before throwing an exception.
If set to zero, waiting is disabled.

|`saucelabs.sauce-connect.enabled`
a|`true` +
`false`
|`false`
a|Enables https://wiki.saucelabs.com/display/DOCS/Sauce+Connect+Proxy[Sauce Connect Proxy]

The https://wiki.saucelabs.com/display/DOCS/Sauce+Connect+Proxy[Sauce Connect Proxy] can also be enabled at story level by using `@tunnel` meta tag.

|`saucelabs.sauce-connect.use-latest-version`
a|`true` +
`false`
|`true`
|If `false`, then use embedded Sauce Connect (https://changelog.saucelabs.com/en?category=sauce%20connect[4.8.2]), otherwise check and download newer version if available.

|`saucelabs.sauce-connect.command-line-arguments`
|String line with CLI flags
|
|Used to provide set of custom https://wiki.saucelabs.com/display/DOCS/Sauce+Connect+Proxy+Command-Line+Quick+Reference+Guide[Sauce Connect command line arguments]

|`saucelabs.sauce-connect.skip-host-glob-patterns`
|Comma (,) separated list of host https://developer.mozilla.org/en-US/docs/Web/HTTP/Proxy_servers_and_tunneling/Proxy_Auto-Configuration_PAC_file#shexpmatch[glob patterns]
|
a|This property comes into effect only if proxy is used, otherwise its value is ignored. The property specifies
the list of glob patterns for hosts that are connected-to directly, others are connected through the proxy. By default
the list inicludes

* `*.miso.saucelabs.com`
* `*.api.testobject.com`
* `*.saucelabs.com`
* `saucelabs.com`

host patterns to avoid sending of status information by SauceConnect to SauceLabs REST API throughout the lifetime of
a tunnel via proxy used by tests.

|===

.Configuration snippet to run tests in Chrome browser on Sauce Labs US West data center
[source,properties]
----
configuration.profiles=saucelabs/web,web/desktop/chrome

include::partial$sauce-labs-common-confguration.adoc[]
----

.Configuration snippet to run mobile app tests using iOS Sumulator on Sauce Labs US West data center
[source,properties]
----
configuration.profiles=saucelabs/mobile_app,mobile_app/ios

include::partial$sauce-labs-common-confguration.adoc[]

selenium.grid.device-name=iPhone Simulator
selenium.grid.appium-version=2.0.0
selenium.grid.platform-version=16.2

# https://docs.saucelabs.com/mobile-apps/app-storage/
selenium.grid.capabilities.app=myapp.app
----

.Configuration snippet to run mobile app tests using Android Emulator on Sauce Labs US West data center
[source,properties]
----
configuration.profiles=saucelabs/mobile_app,mobile_app/android

include::partial$sauce-labs-common-confguration.adoc[]

selenium.grid.device-name=Android GoogleAPI Emulator
selenium.grid.appium-version=2.0.0
selenium.grid.platform-version=13.0

# https://docs.saucelabs.com/mobile-apps/app-storage/
selenium.grid.capabilities.app=myapp.apk
----

== Sauce Orchestrate

The https://docs.saucelabs.com/orchestrate/[Sauce Orchestrate] is a new and unique approach to web and mobile application testing that increases test execution speed and enables end-to-end test orchestration.

Prerequisites to install:

* https://docs.saucelabs.com/dev/cli/saucectl/[saucectl]
* https://www.docker.com/get-started/[Docker]

How to run VIVIDUS steps using Sauce Orchestrate:

. Go to the project root directory.
. Build a docker image with tests and push it to a docker registry as described in this xref:integrations:docker.adoc#_how_to_build_an_image_with_tests_and_publish_it_to_docker_registry[article].
. Create a `.sauce/config.yml` file in the project root with the following content:
+
[source,yml]
----
apiVersion: v1alpha
kind: imagerunner
sauce:
  region: us-west-1
suites:
  - name: VIVIDUS test suite
    workload: webdriver
    resourceProfile: c2m2
    # replace the image value with the actual one
    image: vividus.jfrog.io/tests-docker-release/vividus-sample-tests:0.1.0-SNAPSHOT
    imagePullAuth:
      user: $DOCKER_REGISTRY_USERNAME
      token: $DOCKER_REGISTRY_PASSWORD
    artifacts:
      - '/vividus/output/reports/*'

artifacts:
  cleanup: true
  download:
    when: always
    match:
      - "*"
    directory: ./report
----
+
[TIP]
====
* Please see https://docs.saucelabs.com/orchestrate/saucectl-configuration/[saucectl configuration] for more details.
* Make sure `region` configuration value corresponds to the region specified by the `saucelabs.data-center` property, please see https://docs.saucelabs.com/orchestrate/saucectl-configuration/#region[region] docs for mapping.
* The `DOCKER_REGISTRY_USERNAME` and `DOCKER_REGISTRY_PASSWORD` are expected to be set during the 2nd step of the guide.
====
. Start tests by using `saucectl`:
+
[source,bash]
----
saucectl run
----
. Wait until the tests run is finished and see `report` folder in the project root for reports.
