= WinRM Plugin

The plugin provides functionality to execute commands via https://docs.microsoft.com/en-us/windows/win32/winrm/portal[WinRM].

== Installation

.build.gradle
[source,gradle,subs="attributes+"]
----
implementation(group: 'org.vividus', name: 'vividus-plugin-winrm', version: '{current-version}')
----

== Properties

It's allowed to configure unlimited number of WinRM connections via mechanism of the dynamic properties. The properties prefix example is:
```properties
winrm.server.my-server
```
where `my-server` is a key used to refer WinRm connection in the steps. The key is defined by users, must be unique and can't contain dots.

NOTE: The properties marked with *bold* are mandatory.

[cols="3,1,1,3", options="header"]
|===
|Property Name
|Acceptable values
|Default
|Description

|[subs=+quotes]`*winrm.server.<key>.address*`
|<string>
|
|Either full endpoint URL (e.g. `https://10.240.1.1:5986/wsman`) or hostname and port separated by colon (e.g. `10.240.1.1:5986`)

|[subs=+quotes]`*winrm.server.<key>.username*`
|<string>
|
|The name of the user logging in

|[subs=+quotes]`*winrm.server.<key>.password*`
|<string>
|
|The password of the user logging in


|`winrm.server.<key>.authentication-scheme`
a|`Basic` +
`Digest` +
`NTLM` +
`Negotiate` +
`Kerberos` +
`CredSSP`
|`NTLM`
|Authentication scheme

|`winrm.server.<key>.disable-certificate-checks`
a|`true` +
`false`
|`false`
|Disable/enable HTTPS certificates validation

|===

== Steps

=== Execute batch command

Executes a https://en.wikibooks.org/wiki/Windows_Batch_Scripting[native Windows command]. A new session is created on the destination host for each step invocation.

[source,gherkin]
----
When I execute batch command `$command` on server `$server` using WinRM and save result to $scopes variable `$variableName`
----

* `$command` - The batch command limited to 8096 bytes. The maximum length of the command can be even less depending on the https://support.microsoft.com/en-us/kb/830473[platform].
* `$server` - The WinRM server key matching one configured in the properties.
* `$scopes` - xref:commons:variables.adoc#_scopes[The comma-separated set of the variables scopes].
* `$variableName` - The variable name to store the command execution results. The the data will be stored under the following keys:
+
  - `$variableName.stdout` - the content of the https://en.wikipedia.org/wiki/Standard_streams#Standard_output_(stdout)[command standard output stream];
  - `$variableName.stderr` - the content of the https://en.wikipedia.org/wiki/Standard_streams#Standard_error_(stderr)[command standard error stream];
  - `$variableName.exit-status` - the https://en.wikipedia.org/wiki/Exit_status[exit status (a.k.a exit code)] of the command.

.Check batch command result
[source,gherkin]
----
When I execute batch command `echo hello cmd` on server `my-server` using WinRM and save result as JSON to scenario variable `cmd-result`
Then `${cmd-result.stdout}` is equal to `hello cmd`
Then `${cmd-result.stderr}` is equal to ``
Then `${cmd-result.exit-status}` is equal to `0`
----

=== Execute PowerShell command

Executes a PowerShell[https://docs.microsoft.com/en-us/powershell/scripting/overview] command. A new session is created on the destination host for each step invocation.

[source,gherkin]
----
When I execute PowerShell command `$command` on server `$server` using WinRM and save result to $scopes variable `$variableName`
----

* `$command` - The PowerShell command.
* `$server` - The WinRM server key matching one configured in the properties.
* `$scopes` - xref:commons:variables.adoc#_scopes[The comma-separated set of the variables scopes].
* `$variableName` - The variable name to store the command execution results. The the data will be stored under the following keys:
+
  - `$variableName.stdout` - the content of the https://en.wikipedia.org/wiki/Standard_streams#Standard_output_(stdout)[command standard output stream];
  - `$variableName.stderr` - the content of the https://en.wikipedia.org/wiki/Standard_streams#Standard_error_(stderr)[command standard error stream];
  - `$variableName.exit-status` - the https://en.wikipedia.org/wiki/Exit_status[exit status (a.k.a exit code)] of the command.

.Check PowerShell command result
[source,gherkin]
----
When I execute PowerShell command `echo hello ps` on server `my-server` using WinRM and save result to scenario variable `ps-result`
Then `${ps-result.stdout}` is equal to `hello ps`
Then `${ps-result.stderr}` is equal to ``
Then `${ps-result.exit-status}` is equal to `0`
----
