:azure-service-name: event-hub

= Azure Event Hub Plugin

The plugin provides functionality to interact with https://docs.microsoft.com/en-us/azure/event-hubs/[Event Hub].

:plugin-short-name: azure-event-hub
include::partial$plugin-installation.adoc[]

== Event Hub management

=== Configuration

include::partial$azure-authentication.adoc[leveloffset=+1]

include::partial$azure-profile-and-subscription.adoc[leveloffset=+1]

=== Steps

==== Manage data capturing

Toggles https://docs.microsoft.com/en-us/azure/event-hubs/event-hubs-capture-overview[data capturing option]
(enables or disables it) for the specified Azure Event Hub.

[source,gherkin]
----
When I $toggle data capturing for event hub `$eventHubName` in namespace `$namespaceName` from resource group `$resourceGroupName`
----

* `$toggle` - The data capturing toggle: either `ENABLE` or `DISABLE`.
* `$eventHubName` - The event hub name.
* `$namespaceName` - The name of the namespace the event hub belongs to.
* `$resourceGroupName` - The resource group name.

[IMPORTANT]
====
The client should have permission to run action `Microsoft.EventHub/namespaces/eventhubs/write`
over scope `/subscriptions/{subscription ID}/resourceGroups/{resource group name}/providers/Microsoft.EventHub/namespaces/{event hub namespace}/eventhubs/{event hub name}`.
====

.Restart data capturing
[source,gherkin]
----
When I disable data capturing for event hub `sample_event_hub` in namespace `NS-EH` from resource group `RG-EH`
When I enable data capturing for event hub `sample_event_hub` in namespace `NS-EH` from resource group `RG-EH`
----

== Event Hub for Kafka

Azure Event Hubs provides an Apache Kafka endpoint on an event hub, which allows users to connect to the event hub using the Kafka protocol.
During publishing or consuming events, your client is trying to access the Event Hubs resources. These resources can be accessed using an authorized entity.
Azure Event Hubs provides 2 options for authorizing access to secure resources:
* OAuth 2.0
* Shared access signature (SAS)

For configuration access to Azure Event Hubs with Kafka protocol needed:

. Add the Event Hub and Kafka dependencies to the project `build.gradle`
+
[source,gradle,subs="attributes+"]
----
implementation(group: 'org.vividus', name: 'vividus-plugin-azure-event-hub', version: '{current-version}')
implementation(group: 'org.vividus', name: 'vividus-plugin-kafka', version: '{current-version}')
----

. Configure xref:plugin-kafka.adoc[Kafka Consumer and Producer] and mechanism of authentication

.Setup for consumer or produces with OAuth 2.0
[source,properties]
----
kafka.<consumer/producer>.<consumer-or-producer-key>.security.protocol=SASL_SSL
kafka.<consumer/producer>.<consumer-or-producer-key>.sasl.mechanism=OAUTHBEARER
kafka.<consumer/producer>.<consumer-or-producer-key>.sasl.login.callback.handler.class=org.apache.kafka.common.security.oauthbearer.secured.OAuthBearerLoginCallbackHandler
kafka.<consumer/producer>.<consumer-or-producer-key>.sasl.oauthbearer.token.endpoint.url=https://login.microsoftonline.com/<azure-tenant-id>/oauth2/v2.0/token
kafka.<consumer/producer>.<consumer-or-producer-key>.sasl.jaas.config= \
  org.apache.kafka.common.security.oauthbearer.OAuthBearerLoginModule required \
    clientId='<azure-client-id>' \
    scope='https://<azure-event-hub-namespace>.servicebus.windows.net/.default' \
    clientSecret='<azure-client-secret>';
----

.Setup for consumer or produces with SAS
[source,properties]
----
kafka.<consumer/producer>.<consumer-or-producer-key>.security.protocol=SASL_SSL
kafka.<consumer/producer>.<consumer-or-producer-key>.sasl.mechanism=PLAIN
kafka.<consumer/producer>.<consumer-or-producer-key>.sasl.jaas.config=org.apache.kafka.common.security.plain.PlainLoginModule required username="$ConnectionString" password="Endpoint=sb://<azure-event-hub-url>/;SharedAccessKeyName=<shared-access-key-name>;SharedAccessKey=<shared-access-key>";
----
