:azure-service-name: data-factory

= Azure Data Factory Plugin

The plugin provides functionality to interact with https://docs.microsoft.com/en-us/azure/data-factory/[Azure Data Factory]

== Installation

.build.gradle
[source,gradle,subs="attributes+"]
----
implementation(group: 'org.vividus', name: 'vividus-plugin-azure-data-factory', version: '{current-version}')
----

== Configuration

include::partial$azure-authentication.adoc[]

include::partial$azure-profile-and-subscription.adoc[]

== Steps

=== Run Pipeline with expected status

Creates a run of a pipeline in Data Factory, waits for its completion or until
the timeout is reached and validates the run status is equal to the expected one.

[source,gherkin]
----
When I run pipeline `$pipelineName` in Data Factory `$factoryName` from resource group `$resourceGroupName` with wait timeout `$waitTimeout` and expect run status to be equal to `$expectedPipelineRunStatus`
----

* `$pipelineName` - The name of the pipeline to run.
* `$factoryName` - The name of the factory.
* `$resourceGroupName` - The name of the resource group of the factory.
* `$waitTimeout` - The maximum duration of time to wait for the pipeline completion in {iso-date-format-link} format.
* `$expectedPipelineRunStatus` - The expected pipeline run status, e.g. `Succeeded`.

.Run pipeline
[source,gherkin]
----
When I run pipeline `vividus-pipeline` in Data Factory `vividus-data-factory` from resource group `vividus-resource-group-ingestion` with wait timeout `PT30S` and expect run status to be equal to `Succeeded`
----

=== Run Pipeline

[WARNING]
This step is deprecated and will be removed in VIVIDUS 0.4.0. The replacement is
<<_run_pipeline_with_expected_status,the step accepting an expected status as input parameter>>.

Creates a run of a pipeline in Data Factory, waits for its completion or until
the timeout is reached and validates the run status is `Succeeded`.

[source,gherkin]
----
When I run pipeline `$pipelineName` in Data Factory `$factoryName` from resource group `$resourceGroupName` with wait timeout `$waitTimeout`
----

* `$pipelineName` - The name of the pipeline to run.
* `$factoryName` - The name of the factory.
* `$resourceGroupName` - The name of the resource group of the factory.
* `$waitTimeout` - The maximum duration of time to wait for the pipeline completion in {iso-date-format-link} format.

.Run pipeline
[source,gherkin]
----
When I run pipeline `vividus-pipeline` in Data Factory `vividus-data-factory` from resource group `vividus-resource-group-ingestion` with wait timeout `PT30S`
----
