= YAML Plugin

The plugin provides a set of actions for validation of YAML data.

:plugin-short-name: yaml
include::partial$plugin-installation.adoc[]

== Steps

:yaml-path: https://github.com/yaml-path/YamlPath#usage[YAML Path]

The steps syntax uses internal (VIVIDUS-only) term:

 * "YAML element value" or "value of YAML element" - scalar values like
   `string`, `integer`, `float`, `boolean` (`true` or `false`) and `null`.

=== Save YAML element value from input

Saves a value of YAML element found in the given YAML into the variable with
the specified name and scope.

[source,gherkin]
----
When I save YAML element value from `$yaml` by YAML path `$yamlPath` to $scopes variable `$variableName`
----

* `$yaml` - The YAML used to find YAML element value.
* `$yamlPath` - The {yaml-path} used to find YAML element value.
* `$scopes` - xref:commons:variables.adoc#_scopes[The comma-separated set of the variables scopes].
* `$variableName` - The name of the variable to save the found YAML element value.

.Validate the title of the second book
[source,gherkin]
----
When I save YAML element value from `${response}` by YAML path `store.book[1].title` to scenario variable `title-of-second-book`
Then `${title-of-second-book}` is equal to `Sword of Honour`
----

=== Save number of YAML elements

Saves the number of YAML elements found by the YAML path into the variable with
the specified name and scope.

[source,gherkin]
----
When I save number of elements from `$yaml` by YAML path `$yamlPath` to $scopes variable `$variableName`
----

* `$yaml` - The YAML used to find YAML elements.
* `$yamlPath` - The {yaml-path} used to find YAML elements.
* `$scopes` - xref:commons:variables.adoc#_scopes[The comma-separated set of the variables scopes].
* `$variableName` - The name of the variable to save the number of found YAML elements.

.Check address field exists in YAML response
[source,gherkin]
----
When I save number of elements from `${response}` by YAML path `store.address` to scenario variable `address`
Then `${address}` is equal to `1`
----
