:azure-service-name: key-vault

= Azure Key Vault Plugin

The plugin provides functionality to interact with https://docs.microsoft.com/en-us/azure/key-vault/[Azure Key Vault].

== Installation

.build.gradle
[source,gradle,subs="attributes+"]
----
implementation(group: 'org.vividus', name: 'vividus-plugin-azure-key-vault', version: '{current-version}')
----

== Key Vault management

=== Configuration

include::partial$azure-authentication.adoc[leveloffset=+1]

include::partial$azure-profile-and-subscription.adoc[leveloffset=+1]

=== Steps

==== Retrieve the Key Vault properties

Retrieves the properties of the specified Azure key vault and saves them as JSON
to a variable. For more information, see the
https://docs.microsoft.com/en-us/rest/api/keyvault/keyvault/vaults/get[Azure Docs].

[source,gherkin]
----
When I retrieve properties of key vault with name `$keyVaultName` from resource group `$resourceGroupName` and save them as JSON to $scopes variable `$variableName`
----

* `$keyVaultName` - The name of the key vault within the specified resource group.
* `$resourceGroupName` - The name of the resource group within the user's subscription to retrieve the key vault from. The name is case-insensitive.
* `$scopes` - xref:commons:variables.adoc#_scopes[The comma-separated set of the variables scopes].
* `$variableName` - The variable name to store the key vault properties as JSON.

.Retrieve the Key Vault properties
[source,gherkin]
----
When I retrieve properties of key vault with name `KEY-VAULT-NAME` from resource group `TEST-SA` and save them as JSON to scenario variable `key-vault-properties`
----
