= Web Application Plugin
:given-step: Given I am on a page with the URL 'https://www.google.com/search?q=vividus'

The plugin provides functionality to interact with Web applications.

:plugin-short-name: web-app
include::partial$plugin-installation.adoc[]

include::partial$locator-header.adoc[]

include::plugins:partial$web-locators.adoc[]

== Properties

NOTE: The properties marked with *bold* are mandatory.

:application-under-test: browser
:session-scope-property-base: web-application
[cols="6,3,2,6", options="header"]
|===
|Property Name
|Acceptable values
|Default
|Description

|`selenium.grid.platform-name`
|Valid target platform name
|empty
|Identifies the operating system for the testing. e.g. `Windows`

|`selenium.grid.platform-version`
|Valid target platform version
|empty
|Identifies the operating system version for the testing. e.g. `10`

include::partial$selenium-properties.adoc[]
include::partial$proxy-properties.adoc[]

|`screenshot.on-failure.debug-modes`
|`proxy`
|`<empty>`
|Provides possibility to attach screenshot for failed proxy steps

|`web.driver.<browser-name>.command-line-arguments`
|string with arguments
|`<empty>`
a|The command line (CLI) arguments to use when starting browser.

`<browser-name>` is one of the browsers supporting CLI arguments:

* https://peter.sh/experiments/chromium-command-line-switches/[`CHROME`]
* https://www-archive.mozilla.org/docs/command-line-args/[`FIREFOX`],
* https://docs.microsoft.com/en-us/previous-versions/windows/internet-explorer/ie-developer/general-info/hh826025(v=vs.85)?redirectedfrom=MSDN/[`IEXPLORE`].

|`web-application.sticky-header-size-percentage`
|header size as a viewport size percent
|`25`
|Before the click VIVIDUS scrolls element into the viewport, the property defines top edge indent in viewport percent for the scroll

|===

=== How to configure user preferences for Chrome browser?
In addition to the command line arguments, user preferences (see the _Preferences_ file in Chrome's user data directory or open `chrome://prefs-internals/` link in Chrome browser for examples) can be customised.

Here is an example how to configure third-party cookies behaviour.

.Add the following property to allow all cookies
[source,properties]
----
web.driver.CHROME.experimental-options={"prefs": {"profile": {"cookie_controls_mode": 0}}}
----
The allowed values for the preference from the example are:

* `0` - allow all cookies;
* `1` - block third-party cookies;
* `2` - block third-party cookies in Incognito mode only.

include::partial$proxy-meta-tags.adoc[]

== xref:commons:variables.adoc[Dynamic variables]

=== Browser window dimension

The set of dynamic variables provides ability to access height and width of the browser window.

==== *Variable name*

[cols="1,3", options="header"]
|===

|Variable name
|Description

|`browser-window-height`
|the height of the browser window

|`browser-window-width`
|the width of the browser window

|===

.Check the dimension of the browser window
[source,gherkin]
----
When I change window size to `800x600`
Then `${browser-window-width}` is = `800`
Then `${browser-window-height}` is = `600`
----

include::partial$dynamic-variables-ui.adoc[]

include::plugins:partial$tutorial-web-profiles.adoc[]

== Steps

include::plugins:partial$tutorial-web-steps.adoc[]

=== Click on element without retry

[WARNING]
====
The step is deprecated and will be removed in VIVIDUS 0.6.0.
The replacement is <<_click_on_element>>.
The replacement pattern is:
[source,gherkin]
----
When I click on element located by `<locator>`
----
====

Clicks on an element found by the locator.

[source,gherkin]
----
When I click on element located `$locator`
----

* `$locator` - The <<_locator,locator>> used to find element.

.Click on element
[source,gherkin]
----
When I click on element located `name(Submit)`
----

=== Open a new tab

Opens a new browser tab and switches the focus for future commands to this tab.

[source,gherkin]
----
When I open new tab
----

.Open page in a new tab
[source,gherkin]
----
When I open new tab
Given I am on a page with the URL 'https://docs.vividus.dev/'
----

=== Open URL in a new tab

Opens a new tab, switches the focus to this tab and loads the given URL.

[IMPORTANT]
====
The key difference of this step from the <<_open_a_new_tab,previous one openning a new tab>>
is that this step _inherits_ the state of the previous page, i.e.:

* new tab will have acces to the <<_web_storage_steps,session storage>> of the previous tab,
* it will be possible <<_close_current_window_with_possibility_to_handle_alert,to handle alerts appearing on tab closing>>.
====

[source,gherkin]
----
When I open URL `$URL` in new window
----
* `$URL` - The URL to open.

.Open docs in a new tab
[source,gherkin]
----
When I open URL `https://docs.vividus.dev` in new window
----

=== Wait for window and switch

Waits for the windows with desired title and switches to it.

[source,gherkin]
----
When I wait `$duration` until window with title that $comparisonRule `$windowTitile` appears and switch to it
----

* `$duration` - The timeout duration to wait for a window in {iso-date-format-link} format.
* `$comparisonRule` - The window title xref:parameters:string-comparison-rule.adoc[comparison rule].
* `$windowTitle` - The expected window title.

.Wait for window and switch to it
[source,gherkin]
----
Given I am on a page with the URL 'https://vividus-test-site.onrender.com/windows.html'
When I click on element located by `id(timeout)`
When I wait `PT3S` until window with title that is equal to `Vividus test site` appears and switch to it
----

=== Close current window

Closes the current window and switches to the previous window.

[source,gherkin]
----
When I close the current window
----

IMPORTANT: Handling {popup-alert}[alerts] displayed with '{onbeforeunload-event}' events is not implied by the WebDriver specification to {close-spec} window. For handling alerts use step based on JavaScript '<<_close_current_window_with_possibility_to_handle_alert>>'.

WARNING: This step can only be applied to a session with multiple windows open.

.Open URL in new tab, close it and switch to the previous page
[source,gherkin]
----
Given I am on a page with the URL 'https://example.com/'
When I open URL `https://example.com/contact-us` in new window
When I close the current window
----

=== Close current window with possibility to handle alert

Trying to close the current window with '{onbeforeunload-event}' events handling.

* If an {popup-alert}[alert] window is opened via '{onbeforeunload-event}' event, it must be checked and handled in the subsequent steps.
* If an {popup-alert}[alert] window is not opened, the step closes the current window and switches to the previous window.

[source,gherkin]
----
When I attempt to close current window with possibility to handle alert
----

IMPORTANT: This step can only be used if the current window was opened via the step ``When I open URL \`$pageUrl` in new window``.

NOTE: If you confirm window close in {popup-alert}[alert], the window will be closed, and you will need to switch to current window using the following step: `When I switch to window with title that $stringComparisonRule `$windowName``.

.Checking for an alert when trying to close a window with form
[source,gherkin]
----
Given I am on a page with the URL 'https://example.com/'
When I open URL `https://example.com/form` in new window
When I click on element located by `xpath(//*[@id='form-edit'])`
When I execute sequence of actions:
|type      |argument    |
|ENTER_TEXT|changed text|
When I attempt to close current window with possibility to handle alert
Then an alert is present
When I accept alert with message which matches `.*`
----

=== Stop page loading

Stops page loading

[source,gherkin]
----
When I stop page loading
----

[TIP]
Could be useful in combination with Selenium's https://www.selenium.dev/documentation/en/webdriver/page_loading_strategy/[page load strategy]

.Stop page loading.story
[source,gherkin]
----
When I open URL `https://delayed.vividus.dev` in new window
When I stop page loading
----

=== Configure page load timeout

Sets a custom page load timeout for a part of the story

[source,gherkin]
----
When I set page load timeout to `$duration`
----

* `$duration` - total duration to wait for page load completion in {iso-date-format-link} format

.Before loading a heavy page set an increased timeout
[source,gherkin]
----
Given I am on a page with the URL 'https://example.com/'
When I set page load timeout to `PT20S`
When I open URL `https://example.com/super-heavy-page` in new window
When I set page load timeout to `PT10S`
----

=== Scroll context

Scrolls the context to an edge

[source,gherkin]
----
When I scroll context to $scrollDirection edge
----
* `$scrollDirection` - the direction of the scroll. One of:
** `LEFT` - start of a page/element horizontally
** `RIGHT` - end of a page/element horizontally
** `TOP` - start of a page/element vertically
** `BOTTOM` - end of a page/element vertically

[TIP]
If the context is not set, the whole page will be scrolled

.Scroll login to a bottom
[source,gherkin]
----
When I change context to element located `id(login)`
When I scroll context to BOTTOM edge
----

=== Scroll element into view

Scrolls an element into the view.

[source,gherkin]
----
When I scroll element located `$locator` into view
----
* `$locator` - The <<_locator,locator>> used to find element.

.Scroll button into view
[source,gherkin]
----
When I scroll element located `id(way_down_button)` into view
----

=== Performance metrics

Checks web performance metrics.

[source,gherkin]
----
Then metric $webPerformanceMetric is $comparisonRule `$duration`
----

:navigation-timing: https://www.w3.org/TR/navigation-timing/#dom-performancetiming-

* `$webPerformanceMetric` - The web performance metric. Where:
** [subs=+quotes]`*TIME_TO_FIRST_BYTE*` -  The time between {navigation-timing}navigationstart[the navigation start] and {navigation-timing}responsestart[the response start].
** [subs=+quotes]`*DNS_LOOKUP_TIME*` -  The time between {navigation-timing}domainlookupstart[the domain lookup start] and {navigation-timing}domainlookupend[the domain lookup end].
** [subs=+quotes]`*DOM_CONTENT_LOAD_TIME*` -  The time between {navigation-timing}domloading[the DOM loading] and the {navigation-timing}domcomplete[the DOM complete].
** [subs=+quotes]`*PAGE_LOAD_TIME*` -  The time between {navigation-timing}navigationstart[the navgation start] and {navigation-timing}loadeventend[the load event end].
* `$comparisonRule` - xref:parameters:comparison-rule.adoc[The duration comparison rule].
* `$duration` - The duration to compare against in {iso-date-format-link} format.

.Check page load
[source,gherkin]
----
Given I am on a page with the URL 'https://example.com'
Then metric PAGE_LOAD_TIME is less than `PT5S`
----

=== Execute sequence of actions

Executes the sequence of web actions

[source,gherkin]
----
When I execute sequence of actions: $actions
----
* `$actions` - table of actions to execute
+
.Possible actions
[cols="1,5,3", options="header"]
|===

|`type`
|`argument`
|Argument example

|DOUBLE_CLICK
|Element locator or empty
|By.linkUrl(http://httpbin.org)

|CLICK_AND_HOLD
|Element locator or empty
|By.linkText(Click me)

|MOVE_BY_OFFSET
|Point
|(10, 15) where *x* is 10 and *y* is 15

|RELEASE
|Element locator or empty
|By.tagName(div)

|ENTER_TEXT
|Text to type
|Minsk City

|CLICK
|Element locator or empty
|By.caseSensitiveText(Done)

|PRESS_KEYS
|Press and release any of https://selenium.dev/selenium/docs/api/java/org/openqa/selenium/Keys.html[Keys]
|BACK_SPACE

|KEY_DOWN
|Press any of https://selenium.dev/selenium/docs/api/java/org/openqa/selenium/Keys.html[Keys] one by one
|CONTROL,SHIFT,ALT

|KEY_UP
|Release any of https://selenium.dev/selenium/docs/api/java/org/openqa/selenium/Keys.html[Keys] one by one
|CONTROL,SHIFT,ALT

|MOVE_TO
|Element locator
|By.id(username)

|===

.Execute various web-actions
[source,gherkin]
----
When I execute sequence of actions:
|type          |argument                                |
|DOUBLE_CLICK  |By.fieldText(Hello World)               |
|DOUBLE_CLICK  |                                        |
|CLICK_AND_HOLD|By.xpath(//signature-pad-control/canvas)|
|CLICK_AND_HOLD|                                        |
|MOVE_BY_OFFSET|(-300, 0)                               |
|RELEASE       |By.xpath(//signature-pad-control/canvas)|
|RELEASE       |                                        |
|ENTER_TEXT    |Text                                    |
|CLICK         |By.placeholder(Enter your password)     |
|CLICK         |                                        |
|PRESS_KEYS    |BACK_SPACE                              |
|KEY_DOWN      |CONTROL,SHIFT                           |
|KEY_UP        |CONTROL,SHIFT                           |
|MOVE_TO       |By.id(name)                             |
----

[TIP]
====
This step can be used to perform clipboard interactions.

.Select all text in the focused field and copy it to the clipboard on Windows
[source,gherkin]
----
When I execute sequence of actions:
|type      |argument  |
|KEY_DOWN  |CONTROL, a|
|KEY_UP    |a, CONTROL|
|KEY_DOWN  |CONTROL, c|
|KEY_UP    |c, CONTROL|
----

.Paste text from the clipboard to the focused field on MacOS
[source,gherkin]
----
When I execute sequence of actions:
|type      |argument  |
|KEY_DOWN  |COMMAND, v|
|KEY_UP    |v, COMMAND|
----
====

include::partial$generic-ui-steps.adoc[]

=== Scan barcode from context

Scan a barcode from the specified context and save its value to the variable with the specified name.
If context not set - takes a screenshot of the entire page. Only the first found barcode will be scanned.

Supported Code Formats

include::partial$code-formats.adoc[]

Actions performed at this step:

* Takes a screenshot of the specified context. If it's not set - takes a screenshot of the entire page
* Scans a barcode from the screenshot and save its value to the variable

[source,gherkin]
----
When I scan barcode from context and save result to $scopes variable `$variableName`
----

* `$scopes` - xref:commons:variables.adoc#_scopes[The comma-separated set of the variables scopes].
* `$variableName` - The name of the variable to save the value of the barcode.

.Scan the barcode
[source,gherkin]
----
When I change context to element located `By.xpath(//div[@id='qrCode'])`
When I scan barcode from context and save result to scenario variable `qrCodeLink`
Then `${qrCodeLink}` is equal to `https://www.example.com`
----

=== Field Steps

Fields are elements where users can enter data. The most typical fields are:

* https://www.w3schools.com/tags/tag_input.asp[`input`],
* https://www.w3schools.com/tags/tag_textarea.asp[`textarea`],
* CKE editor (it usually should be located via `body` tag, that is contained in a frame as a separate HTML document).

==== Enter text in field

Enters the text in a field found by the specified locator.

The atomic actions performed are:

* find the field by the locator;
* clear the field if it is found, otherwise the whole step is failed and its execution stops;
* type the text in the field;
* the first three actions are retried once if the field becomes stale during actions execution in other
words if https://www.selenium.dev/exceptions/#stale_element_reference[StaleElementReferenceException]
is thrown at any atomic action.

[source,gherkin]
----
When I enter `$text` in field located by `$locator`
----
* `$text` - The text to enter in the field.
* `$locator` - The <<_locator,locator>> used to find field.

.Add text 'pa$$w0rd' in password field
[source,gherkin]
----
When I enter `pa$$w0rd` in field located by `id(password)`
----

==== Add text to field

Enters the text in the field found by the specified locator without clearing of
the previous content.

[source,gherkin]
----
When I add `$text` to field located by `$locator`
----
* `$text` - The text to add to the field.
* `$locator` - The <<_locator,locator>> used to find field.

.Add text 'name' to username field
[source,gherkin]
----
When I add `name` to field located by `id(username)`
----

==== Clear field

Clears the field found by the specified locator. The step does not trigger any
keyboard or mouse events on the field.

[source,gherkin]
----
When I clear field located by `$locator`
----
* `$locator` - The <<_locator,locator>> used to find field.

.Clear username field
[source,gherkin]
----
When I clear field located by `id(username)`
----

==== Clear field using keyboard

Clears the field found by the specified locator using keyboard. The step
simulates user action by pressing buttons kbd:[Ctrl+A] and then kbd:[Backspace]
that allows to trigger keyboard events on the field.

[source,gherkin]
----
When I clear field located by `$locator` using keyboard
----
* `$locator` - The <<_locator,locator>> used to find field.

.Clear password field using keyboard
[source,gherkin]
----
When I clear field located by `id(password)` using keyboard
----

=== Dropdown Steps
==== Validate available options

Validates whether the dropdown located by locator exists and contains the list
of the expected options.

[source,gherkin]
----
Then dropdown located `$locator` contains options: $option
----
* `$locator` - The <<_locator,locator>> used to find dropdown.
* `$options` - examples table describing expected options

.Validate dropdown contains a set of colors
[source,gherkin]
----
Then a drop down with the name 'colors' contains the items:
|state|item |
|false|Red  |
|false|Green|
|true |Blue |
----

IMPORTANT: The item is an option. The state (`true` or `false`) specifies whether the item is selected.


==== Validate the first selected option

Verifies if dropdown located by locator exists and first selected option.

[source,gherkin]
----
Then dropdown located `$locator` exists and selected option is `$option`
----
* `$locator` - The <<_locator,locator>> used to find dropdown.
* `$option` - first selected option

.Dropdown.story
[source,gherkin]
----
Then dropdown located `id(colors)` exists and selected option is `Blue`
----


==== Add an option to the mutli-select dropdown

Selects option in multi-select dropdown

[IMPORTANT]
Step will fail if target dropdown is not multi-select

[source,gherkin]
----
When I add `$option` to selection in dropdown located `$locator`
----
* `$option` - option to select
* `$locator` - The <<_locator,locator>> used to find dropdown.

.Dropdown.story
[source,gherkin]
----
When I add `Two` to selection in dropdown located `id(numbers)`
----


==== Select the option

Selects option in dropdown

[IMPORTANT]
Does not support multi-selection

[source,gherkin]
----
When I select `$option` in dropdown located `$locator``
----
* `$option` - option to select
* `$locator` - The <<_locator,locator>> used to find dropdown.

.Dropdown.story
[source,gherkin]
----
When I select `Red` in dropdown located `id(colors)`
----


=== Cookie Steps

==== Validate cookie presence

Validates whether the certain cookie is set.

[source,gherkin]
----
Then cookie with name `$cookieName` is set
----
* `$cookieName` - The name of the cookie to check presence.

.Check the session cookie is present
[source,gherkin]
----
Then cookie with name `JSESSIONID` is set
----

==== Validate cookie absence

Validates whether the certain cookie is not set.

[source,gherkin]
----
Then cookie with name `$cookieName` is not set
----
* `$cookieName` - The name of the cookie to check absence.

.Check the session cookie is not present
[source,gherkin]
----
Then cookie with name `JSESSIONID` is not set
----

==== Set cookies

Adds the cookies provided in the input xref:ROOT:glossary.adoc#_examplestable[ExamplesTable]. It's allowed to add the
cookies for the current domain only: make sure the web browser is opened at the
expected domain. The actions performed by the step:

* add the cookies;
* refresh the current page (this action is required to apply the changes in cookies).

[source,gherkin]
----
When I set all cookies for current domain:$parameters
----
* `$parameters` - The parameters of the cookies to set as xref:ROOT:glossary.adoc#_examplestable[ExamplesTable]:
+
[cols="1,2", options="header"]
|===

|Column Name
|Description

|`cookieName`
|the name of the cookie to set

|`cookieValue`
|the value of the cookie to set

|`path`
|the path of the cookie to set

|===

.Set the cookie for the current domain
[source,gherkin]
----
When I set all cookies for current domain:
|cookieName   |cookieValue |path |
|cookieAgreed |2           |/    |
----

==== Get cookie value

Finds the cookie by the name and saves its value to a variable.

[source,gherkin]
----
When I save value of cookie with name `$cookieName` to $scopes variable `$variableName`
----
* `$cookieName` - The name of the cookie to save the value.
* `$scopes` - xref:commons:variables.adoc#_scopes[The comma-separated set of the variables scopes].
* `$variableName` - The variable name to save the cookie value.

.Get the value of the session cookie
[source,gherkin]
----
When I save value of cookie with name `JSESSIONID` to scenario variable `session-id`
----

==== Get cookie

Finds the cookie by the name and saves all its parameters as JSON to a variable.

[source,gherkin]
----
When I save cookie with name `$cookieName` as JSON to $scopes variable `$variableName`
----
* `$cookieName` - The name of the cookie to save.
* `$scopes` - xref:commons:variables.adoc#_scopes[The comma-separated set of the variables scopes].
* `$variableName` - The variable name to save the cookie.

.Get the session cookie
[source,gherkin]
----
When I save cookie with name `JSESSIONID` as JSON to scenario variable `session-id`
----

==== Remove cookie

Removes the certain cookie from the current domain. The actions performed by the step:

* remove the certain cookie the from current domain;
* refresh the current page (this action is required to apply the changes in cookies).

[source,gherkin]
----
When I remove cookie with name `$cookieName` from current domain
----
* `$cookieName` - The name of the cookie to remove.

.Remove the session cookie
[source,gherkin]
----
When I remove cookie with name `JSESSIONID` from current domain
----

==== Remove cookie without apply

Removes the certain cookie from the current domain, but does not apply the
changes in cookies. The current page must be refreshed or the navigation must
be performed to apply the cookie changes.

[source,gherkin]
----
When I remove cookie with name `$cookieName` from current domain without applying changes
----
* `$cookieName` - The name of the cookie to remove.

.Remove the session cookie
[source,gherkin]
----
When I remove cookie with name `JSESSIONID` from current domain without applying changes
When I refresh the page
----

==== Remove all cookies

Removes all cookies from the current domain. The actions performed by the step:

* remove all cookies from the current domain;
* refresh the current page (this action is required to apply the changes in cookies).

[source,gherkin]
----
When I remove all cookies from current domain
----

==== Remove all cookies without apply

Removes all cookies from the current domain, but does not apply the changes in
cookies. The current page must be refreshed or the navigation must be performed
to apply the cookie changes.

[source,gherkin]
----
When I remove all cookies from current domain without applying changes
----


=== https://developer.mozilla.org/en-US/docs/Web/API/Web_Storage_API[Web Storage] steps
==== Get web storage item

Finds the web storage item by the key and saves its value to the variable.

[source,gherkin]
----
When I save $storageType storage item with key `$key` to $scopes variable `$variableName`
----
* `$storageType` - One of the web storage mechanisms: either `local` or `session`.
* `$key` - The name of the key to retrieve the value of.
* `$scopes` - xref:commons:variables.adoc#_scopes[The comma-separated set of the variables scopes].
* `$variableName` - The name of the variable to store the value of the web storage item.

.Get the value of the local storage item
[source,gherkin]
----
When I save local storage item with key `token` to scenario variable `application-token`
----

==== Set web storage item

Adds the item with the specified key-value pair to the web storage, or updates
that key's value if it already exists.

[source,gherkin]
----
When I set $storageType storage item with key `$key` and value `$value`
----
* `$storageType` - One of the web storage mechanisms: either `local` or `session`.
* `$key` - The name of the key to create/update.
* `$value` - The value to give the key that is creating/updating.

.Set the session storage item
[source,gherkin]
----
When I set session storage item with key `token` and value `session-token`
----

==== Validate web storage item presence

Validates the web storage item with the specified key exists.

[source,gherkin]
----
Then $storageType storage item with key `$key` exists
----
* `$storageType` - One of the web storage mechanisms: either `local` or `session`.
* `$key` - The name of the key to check presence.

.Check the session storage item is present
[source,gherkin]
----
Then session storage item with key `token` exists
----

==== Validate web storage item absence

Validates the web storage item with the specified key does not exist.

[source,gherkin]
----
Then $storageType storage item with key `$key` does not exist
----
* `$storageType` - One of the web storage mechanisms: either `local` or `session`.
* `$key` - The key of the local storage item to check absence.

.Check the local storage item is not present
[source,gherkin]
----
Then local storage item with key `token` does not exist
----


include::partial$proxy-steps.adoc[]

=== Window Steps
==== Resize the current browser window

Changes the current browser window size to the specified one.

IMPORTANT: The specified browser window size should be smaller than the current screen resolution.

[source,gherkin]
----
When I change window size to `$targetSize`
----

* `$targetSize` - The desired browser window size in pixels, e.g. `800x600`,
where the first measure is window width, the last one is window height.

.Resize the browser window
[source,gherkin]
----
Given I am on a page with the URL 'https://example.com/'
When I change window size to `640x320`
----

=== Video steps

Steps allow to interact with https://www.w3schools.com/html/html5_video.asp[video] elements.

==== Play Video

Starts video playback.

[source,gherkin]
----
When I play video in video player located `$locator`
----
* `$locator` - The <<_locator,locator>> used to find video player.

==== Pause Video

Pauses video playback.

[source,gherkin]
----
When I pause video in video player located `$locator`
----
* `$locator` - The <<_locator,locator>> used to find video player.

==== Rewind Video

Rewinds video to the desired mark in seconds.

[source,gherkin]
----
When I rewind time to `$number` seconds in video player located `$locator`
----
* `$number` - time mark in seconds
* `$locator` - The <<_locator,locator>> used to find video player.

==== Get info
Saves video player info: *duration*, *currentTime*, *src*, *networkState*.
For more information about the properties see https://www.w3schools.com/tags/ref_av_dom.asp[HTML Audio/Video Properties]

[source,gherkin]
----
When I save info from video player located `$locator` to $scopes variable `$variableName`
----

* `$locator` - The <<_locator,locator>> used to find video player.
* `$scopes` - xref:commons:variables.adoc#_scopes[The comma-separated set of the variables scopes].
* `$variableName` - The variable name to save the info. If the variable name is *info*, the following variables will be created:
** `${info.src}`- The current source of the audio/video element
** `${info.duration}` - The length of the current audio/video (in seconds)
** `${info.currentTime}` - The current playback position in the audio/video(in seconds)
** `${info.networkState}` - The current network state of the audio/video. For more information see: https://www.w3schools.com/tags/av_prop_networkstate.asp[Network State]

.Video player verifications
[source,gherkin]
----
Given I am on a page with the URL 'https://www.youtube.com/watch?v=pYqyVpCV-3c'
When I pause video in video player located `cssSelector(video)`
When I rewind time to `777` seconds in video player located `cssSelector(video)`
When I play video in video player located `cssSelector(video)`
When I save info from video player located `cssSelector(video)` to SCENARIO variable `info`
Then `${info.currentTime}` is > `0`
Then `${info.duration}` is > `1000`
Then `${info.networkState}` is = `2`
Then `${info.src}` matches `.+youtube.+`
----

=== Perform steps for each found element

Executes the steps against all elements found by locator. After a required number of elements is found,
search context switches in order for each found element and performs all steps on it.

[IMPORTANT]
If comparison rule mismatch steps will not be performed even if elements are found.

[source,gherkin]
----
When I find $comparisonRule `$number` elements by `$locator` and for each element do$stepsToExecute
----

Alias:
[source,gherkin]
----
When I find $comparisonRule '$number' elements by $locator and for each element do$stepsToExecute
----

* `$comparisonRule` - xref:parameters:comparison-rule.adoc[The comparison rule].
* `$number` - The number of elements to find.
* `$locator` - The <<_locator,locator>> used to find elements.
* `$stepsToExecute` - The xref:ROOT:glossary.adoc#_examplestable[ExamplesTable] with a single column containing the steps to execute.

.Script type check
[source,gherkin]
----
When I find = `5` elements by `By.xpath(//script):a` and for each element do
|step                                                                                      |
|When I set 'type' attribute value of the context element to the 'scenario' variable 'type'|
|Then `${type}` is equal to `text/javascript`                                              |
----

=== Browser Configuration Steps
==== Set the browser command line arguments

Allows to set command line arguments for browsers.
This step works similar to the property
```properties
web.driver.<browser-name>.command-line-arguments
```
In case both property and step are used - arguments from property will be ignored.
Step will take effect for all new browser sessions created in the current story. It will not affect the current sessions.

List of supported command line arguments for popular browsers:
. https://peter.sh/experiments/chromium-command-line-switches/[Chrome]
. https://www-archive.mozilla.org/docs/command-line-args[Firefox]
. https://docs.microsoft.com/en-us/previous-versions/windows/internet-explorer/ie-developer/general-info/hh826025(v=vs.85)[Internet Explorer]

Not supported browsers:
. Safari
. Edge

[source,gherkin]
----
When I set browser command line arguments to `$argsString`
----

* `$argsString` - Sequence of command line arguments, separated by space.

.Set the browser to use the mocked camera stream
[source,gherkin]
----
When I set browser command line arguments to `--use-fake-ui-for-media-stream --use-file-for-fake-video-capture=${videoStorage}/${video1}.y4m --use-fake-device-for-media-stream`
Given I am on the main application page
----

=== Code steps

==== Execute async JavaScript and save result.

https://www.selenium.dev/selenium/docs/api/java/org/openqa/selenium/JavascriptExecutor.html[Executes async JavaScript] code and saves result into variable.

[source,gherkin]
----
When I execute async javascript `$jsCode` and save result to $scopes variable `$variableName`
----
* `$jsCode` - Any JavaScript code. In order to save a result https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Statements/return[return] statement should be used.
* `$scopes` - xref:commons:variables.adoc#_scopes[The comma-separated set of the variables scopes].
* `$variableName` - The variable name to save the cookie value.

.Validate response
[source,gherkin]
----
When I execute async javascript `
var callback = arguments[arguments.length - 1];
var xhr = new XMLHttpRequest();
xhr.open('GET', '/resource/data.json', true);
xhr.onreadystatechange = function() {
  if (xhr.readyState == 4) {
    callback(xhr.responseText);
  }
};
xhr.send();` and save result to scenario variable `response`
Then `${response}` matcher `.+`
----

=== Browser logs steps

This set of steps allows to validate the https://developer.mozilla.org/en-US/docs/Web/API/console[browser console logging messages].

:log-levels: List of the comma-separated messages levels. The supported levels are: ERRORS, WARNINGS, INFOS.

[TIP]
=====
In order to configure availability of the INFO level messages use following properties:
[cols="1,2"]
|===

|Browser
|Property to enable INFO logs

|Google Chrome
|`selenium.capabilities.goog\:loggingPrefs.browser=INFO`

|Microsoft Edge Chromium
|`selenium.capabilities.ms\:loggingPrefs.browser=INFO`
|===
=====

==== Validate log entries absence

Validates the absence of log entries of the desired level in the browser console.

[source,gherkin]
----
Then there are no browser console $logLevels
----
* `$logLevels` - {log-levels}

.Validate absence of JS errors
[source,gherkin]
----
Given I am on a page with the URL 'https://vividus-test-site.onrender.com/'
Then there are no browser console ERRORS
----

==== Validate specific log entries absence

Validates the absence of specific log entries of the desired level in the browser console.

[source,gherkin]
----
Then there are no browser console $logLevels by regex '$pattern'
----
* `$logLevels` - {log-levels}
* `$pattern` - The regular expression to match log entry messages.

.Validate absence of JS error referencing user
[source,gherkin]
----
Given I am on a page with the URL 'https://vividus-test-site.onrender.com/'
Then there are no browser console ERRORS by regex '.*user.*'
----

==== Validate specific log entries presence

Validates the presence of specific log entries of the desired level in the browser console.

[source,gherkin]
----
Then there are browser console $logLevels by regex '$pattern'
----
* `$logLevels` - {log-levels}
* `$pattern` - The regular expression to match log entry messages.

.Validate presence of JS errors referencing user
[source,gherkin]
----
Given I am on a page with the URL 'https://vividus-test-site.onrender.com/'
Then there are browser console ERRORS by regex '.*user.*'
----

==== Wait for console log entries and save them

Waits for the appearance of the console log entries with the expected level and which match regular expression and saves all the entries (including awaited ones) of the expected level gathered during the wait to the scoped variable.

NOTE: Wait uses generic UI timeouts specified by the properties `ui.wait.timeout` and `ui.wait.polling-period`. See <<_properties>> section for more details.

[source,gherkin]
----
When I wait until browser console $logEntries by regex `$regex` appear and save all entries into $scopes variable `$variableName`
----
* `$logLevels` - {log-levels}
* `$pattern` - The regular expression to match log entry messages.
* `$scopes` - xref:commons:variables.adoc#_scopes[The comma-separated set of the variables scopes].
* `$variableName` - The name of the variable to save the value of the barcode.

.Wait for application readiness
----
Given I am on a page with the URL 'https://vividus-test-site.onrender.com/'
When I wait until browser console infos by regex `.*Application ready.*` appear and save all entries into scenario variable `logs`
Then `${logs}` matches `.*Application ready in \d+ seconds.*`
----

=== Element wait steps

:disappearance-check-note: If the element doesn't exist on the page/context, the step will immediately complete successfully. Checking the element on the page (if needed) should be done in a separate step (e.g. <<_wait_for_element_appearance>> or xref:plugin-html.adoc#_validate_elements[Validate elements]).

=== Wait for disappearance of an element with a tag

[WARNING]
====
The step is deprecated and will be removed in VIVIDUS 0.6.0.
The replacement is a <<_wait_for_element_disappearance,generic step waiting for element disappearance>>.
====

Waits for an element with the specified tag, attribute type and value disappearance.

Actions performed by step:

* Searches for an element with the specified attribute and tag within search context
* If there are no elements by specified attribute and tag, step provides passed assertion and don't check disappearance of an element
* If there are elements by specified attribute and tag, waits until this element becomes not visible

NOTE: {disappearance-check-note}

[source,gherkin]
----
When I wait until an element with the tag '$elementTag' and attribute '$attributeType'='$attributeValue' disappears
----

* `$elementTag` - Type of the https://www.w3schools.com/TAgs/default.asp[html tag] (e.g. `div` or `iframe`).
* `$attributeType` - Type of the https://www.w3schools.com/html/html_attributes.asp[tag attribute] (e.g. `name` or `id`).
* `$attributeValue` - Value of the attribute.

.Click on the button and waiting for disappearance of the `div` element with a certain attribute and value
[source,gherkin]
----
When I click on a button with the name 'Toggle element visibility with delay'
When I wait until an element with the tag 'div' and attribute 'id'='delayed' disappears
----

=== Wait for element disappearance with timeout

Waits for element disappearance with desired timeout.

NOTE: {disappearance-check-note}

[source,gherkin]
----
Then element located by `$locator` disappears in `$timeout`
----

_Deprecated syntax (will be removed in VIVIDUS 0.6.0)_:
[source,gherkin]
----
Then element located '$locator' disappears in '$timeout'
----

* `$locator` - The <<_locator,locator>> used to element.
* `$timeout` - The maximum time to wait for the element disappearance in {iso-date-format-link} format.

.Click on the button and waiting for disappearance of the element for 3 seconds
[source,gherkin]
----
When I click on a button with the name 'Toggle element visibility with delay'
Then element located 'By.xpath(//div[@id='delayed'])' disappears in 'PT3S'
----
