:grid-default-hostname: empty

= Mobile Application Plugin

The plugin provides functionality to test mobile application on real devices, Android Emulators and iOS Simulators

== Installation

.build.gradle
[source,gradle,subs="attributes+"]
----
implementation(group: 'org.vividus', name: 'vividus-plugin-mobile-app', version: '{current-version}')
----


include::partial$locator-header.adoc[]


=== Filter Types

[cols="1,2,2", options="header"]
|===

|Type
|Description
|Examples

include::partial$common-filters.adoc[]

|text
|Filter elements by their exact text.
|tagName(android.widget.EditText)->filter.text(Welcome)

|attribute
|Filter elements by their attribute values
a|`tagName(android.widget.TextView)->filter.attribute(text=Hi)` - `android.widget.TextView` element has the `text` attribute with `Hi` value
`tagName(android.widget.TextView)->filter.attribute(text)` - `android.widget.TextView` element has the `text` attribute with any value
`tagName(android.widget.TextView)->filter.attribute(text=)` - `android.widget.TextView` element has the `text` attribute with an empty value

|===


=== Locator Types
:locator-strategy: https://appium.io/docs/en/commands/element/find-elements/index.html#selector-strategies

[cols="1,1,2,2", options="header"]
|===

|Type
|Platform
|Description
|Examples

|XPath
|any
|Search the app XML source using xpath (not recommended, has {locator-strategy}[performance issues])
|xpath(//android.widget.TextView[@text='Home']) or By.xpath(//XCUIElementTypeStaticText[@value='Home'])

|Accessibility ID
|any
|See {locator-strategy}[Accessibility ID] selector strategy
|accessibilityId(menu-toggler) or By.accessibilityId(menu-toggler)

|ID
|any
|See {locator-strategy}[ID] selector strategy
|id(org.vividus:id/menu-toggler) or By.id(menu-toggler)

|iOS Class Chain
|`iOS`
|See https://github.com/facebookarchive/WebDriverAgent/wiki/Class-Chain-Queries-Construction-Rules[Class Chain Queries] for more details
|+iosClassChain(**/XCUIElementTypeCell[$name BEGINSWITH "A"$])+ or +By.iosClassChain(**/XCUIElementTypeCell[$name BEGINSWITH "B"$])+

|===

include::partial$visibility-types.adoc[]



== Properties

:application-under-test: mobile application
:session-scope-property-base: mobile-application
[cols="6,3,2,6", options="header"]
|===
|Property Name
|Acceptable values
|Default
|Description

include::partial$selenium-properties.adoc[]
include::partial$selenium-grid-properties.adoc[]

|`selenium.grid.platform-name`
a|`Android`

`iOS`
|Depends on the set profile
|Defines the mobile OS to use

|`selenium.grid.automation-name`
a|`UIAutomator2`
`XCUITest`
|Depends on the set profile
a|Defines automation engine to use
[cols="1,2", options="header"]
!===

!Platform
!Recommended engine

!`Android`
!http://appium.io/docs/en/drivers/android-uiautomator2/[UIAutomator2]

!`iOS`
!http://appium.io/docs/en/drivers/ios-xcuitest/[XCUITest]
!===

|`mobile-environment.real-device`
a|`true`

`false`

|Depends on the set profile

a|Defines whether the tests run on real device
[cols="2,1", options="header"]
!===

!Profile
!Value

!`browserstack/mobile_app`
!`true`

!`mobile_app/ios`
!`false`

!`mobile_app/android`
!`false`

!===

|`mobile-environment.device.folder-for-file-upload`
|`string`

|Depends on the set profile

a|Defines a destination folder on a device for a file being uploaded
[cols="1,1", options="header"]
!===

!Profile
!Value

!`mobile_app/ios`
!`/private/var/mobile/Media/DCIM/`

!`mobile_app/android`
!`/sdcard/Pictures`

!===

|===

== Profiles

=== iOS
:ios-profile: mobile_app/ios

The profile can be enabled by adding `{ios-profile}` to `configuration.profiles` property

Default profile configuration
[source,properties]
----
selenium.grid.platform-name=iOS
selenium.grid.automation-name=XCUITest
----

=== tvOS
:tvos-profile: mobile_app/tvos

The profile can be enabled by adding `{tvos-profile}` to `configuration.profiles` property

Default profile configuration
[source,properties]
----
selenium.grid.platform-name=tvOS
selenium.grid.automation-name=XCUITest
----

=== Android
:android-profile: mobile_app/android

The profile can be enabled by adding `{android-profile}` to `configuration.profiles` property

Default profile configuration
[source,properties]
----
selenium.grid.platform-name=Android
selenium.grid.automation-name=UIAutomator2
----

=== Local
:local-profile: mobile_app/local

The profile simplifies execution of tests against the local Appium server. It could be used in conjunction with: `{android-profile}`, `{ios-profile}`, `{tvos-profile}`
The profile can be enabled by adding `{local-profile}` to `configuration.profiles` property

Default profile configuration
[source,properties]
----
selenium.grid.url=http://127.0.0.1:4723/wd/hub
selenium.grid.platformName=${selenium.grid.platform-name}
selenium.grid.automationName=${selenium.grid.automation-name}
----

include::partial$dynamic-variables-header.adoc[]

=== Get clipboard text

Gets the text of the system clipboard of simulator or real device

==== Properties

[cols="1,1,3", options="header"]

|===

|Property Name
|Default
|Description

|`mobile-environment.wda-bundle-id`
|`empty`
|The property is for iOS real devices only and it specifies the WebDriverAgent bundle ID used to http://appium.io/docs/en/commands/device/clipboard/get-clipboard/#description[get clipboard text]. The property value may vary depending on test cloud providers and can be found in the XCode logs.

|===

[source]
----
${clipboard-text}
----

.Verify clipboard content
[source,gherkin]
---- 
Then `${clipboard-text}` is equal to `uarlouski@gmail.com`
----

include::partial$dynamic-variables-ui.adoc[]

== Steps

=== Start mobile application

==== *_Info_*

Starts mobile application with capabilities from user's `*.properties` files and profiles set by a user

==== *_Wording_*

[source,gherkin]
----
Given I start mobile application
----

==== *_Usage_*

.Sample.story
[source,gherkin]
----
Scenario: Start mobile application
Given I start mobile application
----

=== Start mobile application with capabilities

==== *_Info_*

Starts mobile application with capabilities from user's `*.properties` files and profiles set by a user, additionally step takes list of capabilities as an argument that override previously defined capabilities

==== *_Wording_*

[source,gherkin]
----
Given I start mobile application with capabilities:$capabilities
----

==== *_Parameters_*

. `$capabilities` - capabilities to start application with, these capabilies have higher priority than capabilities defined in `*.properties` files and in profiles

==== *_Usage_*

.Sample.story
[source,gherkin]
----
Scenario: Start mobile application with capabilities
Given I start mobile application with capabilities:
|name                           |value|
|bstack:options.networkLogs     |true |
|appium:options.clearSystemFiles|false|
----

=== Restart mobile application

==== *_Info_*

Closes a mobile application and launch it again with the same capabilities

==== *_Wording_*

[source,gherkin]
----
When I restart mobile application
----

==== *_Usage_*

.Restart mobile application
[source,gherkin]
----
When I restart mobile application
----

One of the key benefit of usage the restart step instead of
[source,gherkin]
----
When I close mobile application
Given I start mobile application
----

steps pair is ability to avoid device re-allocation on SauceLabs or BrowserStack in case of application re-installation within story run (e.g. in case usage ExamplesTable)

.Re-install mobile application in Sauce Labs
[source,gherkin]
----
Given I start mobile application with capabilities:
|name   |value|
|noReset|false|
!-- Some test steps

When I restart mobile application
!-- Some test steps after application re-installation
----

.Re-install mobile application in Browser Stack
[source,gherkin]
----
Given I start mobile application with capabilities:
|name     |value|
|fullReset|true |
!-- Some test steps

When I restart mobile application
!-- Some test steps after application re-installation
----

=== Close mobile application

==== *_Info_*

Closes a mobile application and quits the session

==== *_Wording_*

[source,gherkin]
----
When I close mobile application
----

==== *_Usage_*

.Close mobile application
[source,gherkin]
----
When I close mobile application
----

=== Tap on element with duration

==== *_Info_*

Taps on the element located by the locator with the specified duration.

The atomic actions performed are:
* press on the element
* wait for the duration
* release

==== *_Wording_*

[source,gherkin]
----
When I tap on element located `$locator` with duration `$duration`
----

==== *_Parameters_*

. `$locator` - <<_locator>>
. `$duration` - duration between an element is pressed and released in {iso-date-format-link} format

==== *_Usage_*

.Sample.story
[source,gherkin]
----
Scenario: Tap on element with duration
When I tap on element located `accessibilityId(menu-toggler)` with duration `PT0.5S`
----

=== Tap on element

==== *_Info_*

Taps on the element located by the locator.

The atomic actions performed are:
* press on the element
* release

==== *_Wording_*

[source,gherkin]
----
When I tap on element located `$locator`
----

==== *_Parameters_*

. `$locator` - <<_locator>>

==== *_Usage_*

.Sample.story
[source,gherkin]
----
Scenario: Tap on element
When I tap on element located `accessibilityId(menu-toggler)`
----

=== Type text

==== *_Info_*

Types the text into the element located by the locator.

[WARNING]
Existing text is re-written by the text passed into the step

The atomic actions performed are:
* type text into the element
* hide keyboard

[WARNING]
For `iOS` real devices the hide keyboard action works only for `XCUIElementTypeTextField` elements and skipped for `XCUIElementTypeTextView` elements, in case of `XCUIElementTypeTextView` element tap outside the text view to close the keyboard.

==== *_Wording_*

[source,gherkin]
----
When I type `$text` in field located `$locator`
----

==== *_Parameters_*

. `$text` - text to type into the element
. `$locator` - <<_locator>>

==== *_Usage_*

.Keyboard.story
[source,gherkin]
----
Scenario: Type text
When I type `Bob` in field located `accessibilityId(username)`
----

==== *_Wording_*

[source,gherkin]
----
When I type `$text` in field located `$locator` and keep keyboard opened
----

==== *_Info_*

The only type text into the element action is performed.

Keyboard hiding is skipped.

==== *_Parameters_*

. `$text` - text to type into the element
. `$locator` - <<_locator>>

==== *_Usage_*

.Keyboard.story
[source,gherkin]
----
Scenario: Type text
When I type `Bob` in field located `accessibilityId(username)` and keep keyboard opened
----

=== Clear field

==== *_Info_*

Clears a field located by the locator.

The atomic actions performed are:
* clear the field
* hide keyboard

[WARNING]
For `iOS` real devices the hide keyboard action works only for `XCUIElementTypeTextField` elements and skipped for `XCUIElementTypeTextView` elements, in case of `XCUIElementTypeTextView` element tap outside the text view to close the keyboard.

==== *_Wording_*

[source,gherkin]
----
When I clear field located `$locator`
----

==== *_Parameters_*

. `$locator` - <<_locator>>

==== *_Usage_*

.Keyboard.story
[source,gherkin]
----
Scenario: Type text
When I clear field located `accessibilityId(username)`
----

=== Swipe to an element

==== *_Info_*

Swipes to an element in either UP, DOWN, LEFT, or RIGHT direction with the specified swipe duration

[NOTE]
The step takes into account current context. If you need to perform swipe on the element, you need to switch the context to this element.

==== *_Wording_*

[source,gherkin]
----
When I swipe $direction to element located `$locator` with duration $swipeDuration
----

==== Properties

* `mobile-application.swipe.limit` - defines max numbers of swipes to perform (if it's reached the swipe process is stopped and the error is thrown)
* `mobile-application.swipe.stabilization-duration` - defines a duration to wait after swipe until view becomes stable
* `mobile-application.swipe.vertical.x-position` - defines a vertical swipe `x` axis position in percentage from `0` to `100`, where `0` corresponds to `x=1` and `100` corresponds to `x = mobile screen width - 1`, default value is `0`
* `mobile-application.swipe.horizontal.y-position` - defines a horizontal swipe `y` axis position in percentage from `0` to `100`, where `0` corresponds to `y=1` and `100` corresponds to `y = mobile screen height - 1`, default value is `50`

==== *_Parameters_*

. `$direction` - direction to swipe - UP, DOWN, LEFT, or RIGHT
. `$locator` - <<_locator>>
. `$swipeDuration` - swipe duration in {iso-date-format-link} format

==== *_Usage_*

.Swipe.story
[source,gherkin]
----
Scenario: Swipe to element
Then number of elements found by `accessibilityId(end-of-screen)` is equal to `0`
When I swipe UP to element located `accessibilityId(end-of-screen)` with duration PT1S
Then number of elements found by `accessibilityId(end-of-screen)` is equal to `1`
----

.Swipe context element.story
[source,gherkin]
----
Scenario: Switch slides
When I change context to element located `accessibilityId(carousel)`
Then number of elements found by `accessibilityId(slide 2)` is equal to `0`
When I swipe LEFT to element located `accessibilityId(slide 2)` with duration PT1S
Then number of elements found by `accessibilityId(slide 2)` is equal to `1`
----

=== Upload a file to a device

==== *_Info_*

Uploads a file to a device

==== *_Wording_*

[source,gherkin]
----
When I upload file `$filePath` to device
----

==== *_Parameters_*

. `$filePath` - path of the file to upload to a device

==== *_Usage_*

.Upload.story
[source,gherkin]
----
Scenario: Upload file
When I upload file `images/avatar.png` to device
Then the avatar icon is displayed with the uploaded image
----

=== Activate mobile application

==== *_Info_*

Activates an existing application on the device and moves it to the foreground. The application should be already running in order to activate it.

==== *_Wording_*

[source,gherkin]
----
When I activate application with bundle identifier `$bundleId`
----

==== *_Parameters_*

. `$bundleId` - `Package name` for Android or `Bundle identifier` from `Plist.info` for iOS

==== *_Usage_*

.GoToSafari.story
[source,gherkin]
----
Scenario: Open safari
When I activate application with bundle identifier `com.apple.mobilesafari`
----


=== Terminate mobile application

==== *_Info_*

Terminates a running application on the device and navigates to the home device screen. The session will not be closed.

==== *_Wording_*

[source,gherkin]
----
When I terminate application with bundle identifier `$bundleId`
----

==== *_Parameters_*

. `$bundleId` - `Package name` for Android or `Bundle identifier` from `Plist.info` for iOS

==== *_Usage_*

.ColseSafari.story
[source,gherkin]
----
Scenario: Close safari
When I terminate application with bundle identifier `com.apple.mobilesafari`
----

include::partial$generic-ui-steps.adoc[]


=== Change session settings

==== *_Info_*

Changes the behavior of the Appium session

==== *_Wording_*

[source,gherkin]
----
When I change Appium session settings:$settings
----

==== *_Parameters_*

. `$settings` - https://appium.io/docs/en/advanced-concepts/settings/#settings[Settings]

==== *_Usage_*

.Settings.story
[source,gherkin]
----
Scenario: Show invisible elements
When I change Appium session settings:
|name                  |value|
|allowInvisibleElements|true |
----

=== Select date in date picker

==== *_Info_*

Selects a next or previous picker wheel value in date picker

[WARNING]
* Only `iOS` platform is supported
* Target element must be of type `XCUIElementTypePickerWheel`

==== *_Wording_*

[source,gherkin]
----
When I select $direction value with `$offset` offset in picker wheel located `$locator`
----

==== *_Parameters_*

. `$direction` - next value to select, either `NEXT` or `PREVIOUS`
. `$offset` - offset for pick from a middle of a wheel, see https://appium.io/docs/en/writing-running-appium/ios/ios-xctest-mobile-gestures/index.html#mobile-selectpickerwheelvalue[Select Picker Wheel Value]
. `$locator` - locator to locate `XCUIElementTypePickerWheel` element

==== *_Usage_*

.Select next item in the picker wheel
[source,gherkin]
----
When I select next value with `0.1` offset in picker wheel located `xpath(//XCUIElementTypePickerWheel)->filter.index(3)`
----

=== Switch to web view

Switches context to a web view by the index, it starts from 1.

See http://appium.io/docs/en/writing-running-appium/web/hybrid/[Automating hybrid apps] for more information.

[source,gherkin]
----
When I switch to web view with index `$index`
----

. `$index` - index of a web view

.Switch to web view
[source,gherkin]
----
Then number of elements found by `xpath(html)` is equal to `0`
When I switch to web view with index `1`
Then number of elements found by `xpath(html)` is equal to `1`
----

=== Switch to native context

Switches context to a mobile native context.

See http://appium.io/docs/en/writing-running-appium/web/hybrid/[Automating hybrid apps] for more information.

[source,gherkin]
----
When I switch to native context
----

.Switch to native context
[source,gherkin]
----
Then number of elements found by `xpath(html)` is equal to `1`
When I switch to native context
Then number of elements found by `xpath(html)` is equal to `0`
----

=== Press key

Presses an https://github.com/appium/appium-xcuitest-driver#mobile-pressbutton[iOS key] or https://appium.github.io/java-client/io/appium/java_client/android/nativekey/AndroidKey.html[Android key]

[source,gherkin]
----
When I press $key key
----

. `$key` - The key to press

.Go to home
[source,gherkin]
----
When I press Home key
----

=== Long press key

Performs long press of the https://appium.github.io/java-client/io/appium/java_client/android/nativekey/AndroidKey.html[Android key]

WARNING: Only Android supported

[source,gherkin]
----
When I long press $key key
----

. `$key` - The key to press

.Go to home
[source,gherkin]
----
When I long press Home key
----

=== Press keys

Presses a sequence of https://github.com/appium/appium-xcuitest-driver#mobile-pressbutton[iOS keys] or https://appium.github.io/java-client/io/appium/java_client/android/nativekey/AndroidKey.html[Android keys]

[source,gherkin]
----
When I press keys:$keys
----

. `$keys` - The keys to press

.Enter password
[source,gherkin]
----
When I press keys:
|key|
|P  |
|a  |
|s  |
|1  |
|$  |
----

=== Type text sequentially

Types the provided text

[WARNING]
All the characters will be treated as is and passed sequentially. To send special key like `HOME` please use <<_press_keys>>

[source,gherkin]
----
When I type text `$text`
----

. `$text` - The text to type

.Enter password
[source,gherkin]
----
When I type text `pas1$`
----

include::partial$generic-ui-steps.adoc[]
