= AWS S3 Plugin

The plugin provides functionality to interact with https://aws.amazon.com/s3/[Amazon Simple Storage Service (Amazon S3)].

== Installation

.build.gradle
[source,gradle,subs="attributes+"]
----
implementation(group: 'org.vividus', name: 'vividus-plugin-aws-s3', version: '{current-version}')
----

include::partial$aws.adoc[]

== Steps

=== Upload data

Upload the specified data to Amazon S3 under the specified bucket and key name.

[source,gherkin]
----
When I upload data `$data` with key `$objectKey` and content type `$contentType` to S3 bucket `$bucketName`
----

- `$data` - the data to be uploaded
- `$objectKey` - the key under which to store the specified data
- `$contentType` - the MIME type of data
- `$bucketName` - the name of an existing bucket

.Upload data to Amazon S3
[source,gherkin]
----
When I upload data `{"my":"json"}` with key `folder/name.json` and content type `application/json` to S3 bucket `testBucket`
----

=== Download S3 object

Retrieve the object by key from the provided S3 bucket and save its content to a variable. The specified bucket and object key must exist, or an error will result.


[source,gherkin]
----
When I fetch object with key `$objectKey` from S3 bucket `$bucketName` and save result to $scopes variable `$variableName`
----

- `$objectKey` - the key under which the desired object is stored
- `$bucketName` - the name of the bucket containing the desired object
- `$scopes` - xref:parameters:variable-scope.adoc[the comma-separated set of the variables scopes]
- `$variableName` - the variable name

.Download S3 object
[source,gherkin]
----
When I fetch object with key `/path/file.json` from S3 bucket `some-bucket-name` and save result to scenario variable `my-json-var`
----
