:grid-default-hostname: hub-cloud.browserstack.com

= Browser Stack Plugin

The plugin provides integration with continuous testing cloud https://www.browserstack.com/[BrowserStack].

== Installation

.build.gradle
[source,gradle,subs="attributes+"]
----
implementation(group: 'org.vividus', name: 'vividus-plugin-browserstack', version: '{current-version}')
----

== Profiles

The plugin defines profiles with a set of the preconfigured properties.

[cols="1,2"]
|===

|`browserstack/web`
|Use in conjunction with web application profiles.

|`browserstack/mobile_app`
a|Use in conjunction with xref:plugins:plugin-mobile-app.adoc#_profiles[native mobile application profiles].

Required properties:

* `selenium.grid.device-name`
|===

Browser Stack profiles can be enabled by adding the corresponding entry to `configuration.profiles` property.

.Configure Chrome on Browser Labs
[source,properties,subs="attributes+"]
----
configuration.profiles=browserstack/web,web/desktop/chrome
----

[IMPORTANT]
Browser Stack profile must be first.

Explore https://www.browserstack.com/app-automate/capabilities?tag=w3c[Capabilities Builder] for more fine-grained Browser Stack configuration.

TIP: Links to BrowserStack test runs can be found in Allure report

== Properties

* Browser Stack specific properties must be prepended with `selenium.grid.capabilities.bstack\:options.` prefix, meaning given a property `projectName` with a value `My Project` the resulting property will be `selenium.grid.capabilities.bstack\:options.projectName=My Project`
* Appium specific properties in Browser Stack must be prepended with `selenium.grid.capabilities.appium\:options.` prefix, meaning given a property `clearSystemFiles` with a value `true` the resulting property will be `selenium.grid.capabilities.appium\:options.clearSystemFiles=true`

[cols="3,1,1,3", options="header"]

|===

|Property Name
|Acceptable values
|Default
|Description

include::partial$selenium-grid-properties.adoc[]

|`browserstack.browserstack-local.enabled`
a|`true`
`false`
|`false`
|Enables https://www.browserstack.com/local-testing[Browser Stack Local]

|===

== Enable network capturing

The following options are available to enable network logs capturing on BrowserStack side:

* Add `selenium.grid.capabilities.bstack:options.networkLogs=true` property into tests configuration, this will enable network logs capturing for all stories in suite.
* Add `@capability.bstack:options.networkLogs true` meta for a story being run
* Pass the capability with name `bstack:options.networkLogs` and value `true` as parameter to the step starting native mobile application.
.Enable network logs in the step starting application
[source,gherkin]
----
Given I start mobile application with capabilities:
|name                      |value|
|bstack:options.networkLogs|true |
----

== Steps

=== Save network logs into variable

Saves network traffic captured during application run into variable. The network traffic data is in HAR format. The application session must be closed before network logs can be saved.

[source,gherkin]
----
When I save BrowserStack network logs to $scopes variable `$variableName`
----

. `$scopes` - xref:parameters:variable-scope.adoc[variable scopes]
. `$variableName` - name of variable to save network logs

See <<_enable_network_capturing>>

.Save network logs into variable
[source,gherkin]
----
When I close mobile application
When I save BrowserStack network logs to SCENARIO variable `networkLogs`
Then number of JSON elements from `${networkLogs}` by JSON path `$..*[?(@.url == 'https://graph.example.com/v8.0')]` is equal to 1
----

=== Save network logs into context

Saves network traffic captured during application run into JSON context. The network traffic data is in HAR format. The application session must be closed before network logs can be saved.

[source,gherkin]
----
When I save BrowserStack network logs to JSON context
----

See <<_enable_network_capturing>>

To interact with the saved network logs see xref:plugins:plugin-rest-api.adoc#_json_steps[JSON steps] that work with the JSON context

.Save network logs into variable
[source,gherkin]
----
When I close mobile application
When I save BrowserStack network logs to JSON context
Then number of JSON elements from `${networkLogs}` by JSON path `$..*[?(@.url == 'https://graph.example.com/v8.0')]` is equal to 1
----
