[tabs]
======
macOS / Linux::
+
[source,shell,subs="attributes+"]
----
./gradlew {task-name}
----

Windows::
+
[source,shell,subs="attributes+"]
----
gradlew {task-name}
----
======

=== Treat known issues only as a positive result

Any known issues detected during stories run fail the overall execution with the corresponding
xref:configuration:tests-configuration.adoc#_exit_codes[exit code]. The following command-line option can be used to not treat
known issues as failures:
[tabs]
======
macOS / Linux::
+
[source,shell,subs="attributes+"]
----
./gradlew {task-name} --treat-known-issues-only-as-passed
----

Windows::
+
[source,shell,subs="attributes+"]
----
gradlew {task-name} --treat-known-issues-only-as-passed
----
======

The treating of known issues as a positive result can be enabled globally at the project level by adding the following
line into the `build.gradle` file of the tests project:

[source,gradle,subs="attributes+"]
----
{task-name}.treatKnownIssuesOnlyAsPassed = true
----

[IMPORTANT]
====
Make sure to put the configuration below the line configuring the project tasks, namely:
[source,gradle]
----
apply from: "$\{buildSystemPath\}/vividus-test-project.gradle"
...
----
====


=== Write exit code to a file

The following command-line option can be used to write an exit code to a file:

[tabs]
======
macOS / Linux::
+
[source,shell,subs="attributes+"]
----
./gradlew {task-name} -PfileToSaveExitCode='/user/dir/exitCode.txt'
----

Windows::
+
[source,shell,subs="attributes+"]
----
gradlew {task-name} -PfileToSaveExitCode='/user/dir/exitCode.txt'
----
======

Also, it is possible to specify option to resolve a file path to write an exit code against the project build directory:

[tabs]
======
macOS / Linux::
+
[source,shell,subs="attributes+"]
----
./gradlew {task-name} -PfileToSaveExitCode='/exitCode.txt' -PresolvePathAgainstProjectBuildDir=true
----

Windows::
+
[source,shell,subs="attributes+"]
----
gradlew {task-name} -PfileToSaveExitCode='/exitCode.txt' -PresolvePathAgainstProjectBuildDir=true
----
======

Writing of the exit code can be enabled globally for the project by adding the following lines into the
`build.gradle` file of the test project:

.Write the exit code to a file by an absolute path via the project property
[source,gradle,subs="attributes+"]
----
{task-name}.fileToSaveExitCode ='/user/dir/exitCode.txt'
----

.Write an exit code to file with a path related to the project build directory via project property
[source,gradle,subs="attributes+"]
----
{task-name}.fileToSaveExitCode = '/exitCode.txt'
{task-name}.resolvePathAgainstProjectBuildDir = true
----
