project.description = 'VIVIDUS plugin for AWS Lambda'

dependencies {
    api project(':vividus-engine')
    implementation platform(libs.awssdk.bom)
    implementation('software.amazon.awssdk:lambda')
    implementation project(':vividus-extension-aws')

    testImplementation platform(libs.junit.bom)
    testImplementation(libs.junit.jupiter)
    testRuntimeOnly(libs.junit.platformLauncher)
    testImplementation platform(libs.mockito.bom)
    testImplementation(libs.mockito.junitJupiter)
}
