project.description = 'VIVIDUS utilities'

dependencies {
    api('org.freemarker:freemarker:2.3.35')

    api platform(libs.jackson.bom)
    api(libs.jackson.core)
    api(libs.jackson.databind)
    api('com.fasterxml.jackson.datatype:jackson-datatype-jdk8')

    api platform(libs.jackson3.bom)
    api(libs.jackson3.core)
    api(libs.jackson3.databind)

    api(libs.apache.commons.lang3)
    api("com.github.vividus-framework.JsonPath:json-path:${versions.jsonPath}")

    implementation('com.fasterxml.jackson.datatype:jackson-datatype-jsr310')

    implementation(libs.apache.commons.collections4)
    implementation(libs.apache.commons.io)
    implementation('com.fasterxml.jackson.dataformat:jackson-dataformat-properties')

    testImplementation platform(libs.junit.bom)
    testImplementation(libs.junit.jupiter)
    testRuntimeOnly(libs.junit.platformLauncher)
    testImplementation(libs.hamcrest)
    testImplementation platform(libs.mockito.bom)
    testImplementation(libs.mockito.junitJupiter)
    testCompileOnly("com.github.spotbugs:spotbugs-annotations:${spotbugsVersion}")
}
