:tabs-sync-option:

= CLI

In scope of this article the `task` term is a piece of work that is done on stories, scenarios, steps and other entities
and that produces some output based on the work done.

.The format of a task
[source,shell]
----
./gradlew <task to perform>
----

.The format of a task with arguments
[source,shell]
----
./gradlew <task to perform> --args='<arguments to pass into the task>'
----

NOTE: The tasks are available only through the `gradlew` command.

== Run stories

The task runs test stories based on current xref:configuration:tests-configuration.adoc[tests configuration] and tests state
on the file system:

:task-name: runStories
include::partial$stories-exec.adoc[]

== Debug stories

The task runs test stories omitting VIVIDUS initialization check based on current xref:configuration:tests-configuration.adoc[tests configuration]
and tests state on the file system.

:task-name: debugStories
include::partial$stories-exec.adoc[]

== Print available steps

The task prints all the steps that are available for the xref:configuration:tests-configuration.adoc[configured] profiles, environments and suites in the alphabetical order.

.Options
[cols="3,1,1,1", options="header"]
|===

|Description
|Short notation
|Full notation
|Default value

|Path to a file to save the list of the available steps
|f
|file
|by default steps are printed into the console

|===

[tabs]
======
macOS / Linux::
+
[source,shell]
----
./gradlew printSteps --args='-f my-steps.txt'
----

Windows::
+
[source,shell]
----
gradlew printSteps --args='-f my-steps.txt'
----
======

.Output
[source,gherkin]
----
vividus                                             Then `$value` matches `$regex`
vividus-plugin-web-app                              When I switch back to page
vividus-plugin-web-app                              When I press $keys on keyboard
                            COMPOSITE IN STEPS FILE Then an element with the name '$elementName' exists
                            COMPOSITE IN STEPS FILE When I click on an image with the name '$imageName'

----

== Count steps

The task counts steps in the specified tests folder and prints them in the descending order.

.Options
[cols="3,1,1,1", options="header"]
|===

|Description
|Short notation
|Full notation
|Default value

|Directory to count steps
|d
|dir
|story

|Number of steps to print
|t
|top
|<no limits by default>

|===

[tabs]
======
macOS / Linux::
+
[source,shell]
----
./gradlew countSteps --args='-t 5 -d story/uat'
----

Windows::
+
[source,shell]
----
gradlew countSteps --args='-t 5 -d story/uat'
----
======

.Output
[source,gherkin]
----
Top of the most used steps:                                                                  occurrence(s)
Then `$variable1` is $comparisonRule `$variable2`                                                      330
Given I am on page with URL `$pageURL`                                                                 127
Then number of elements found by `$locator` is $comparisonRule `$quantity`                             110
Given I initialize $scopes variable `$variableName` with value `$variableValue`                         83
When I change context to element located `$locator`                                                     59
----

== Count scenario

The task counts and prints stories, scenarios and scenarios containing examples found in the specified tests folder.

.Options
[cols="3,1,1,1", options="header"]
|===

|Description
|Short notation
|Full notation
|Default value

|Directory to count stories and scenarios
|d
|dir
|story

|===

[tabs]
======
macOS / Linux::
+
[source,shell]
----
./gradlew countScenarios --args='-d story/uat'
----

Windows::
+
[source,shell]
----
gradlew countScenarios --args='-d story/uat'
----
======

.Output
[source]
----
5  | Stories
13 | Scenarios
6  | Scenarios with Examples
----

== Validate known issues configuration

The task validates known issues format and prints the validated known issues into the console.

[tabs]
======
macOS / Linux::
+
[source,shell]
----
./gradlew validateKnownIssues
----

Windows::
+
[source,shell]
----
gradlew validateKnownIssues
----
======

.Output
[source]
----
Known issues found:
VVD-5
VVD-6
VVD-7
VVD-8
----

== Find known issues by assertion pattern

The task used to find known issues contained in the test project by one or more assertion patterns.

.Options
[cols="3,1,1,1", options="header"]
|===

|Description
|Short notation
|Full notation
|Default value

|Required path to a file that contains new-line-separated list of assertion patterns
|f
|file
|<no default value>

|===

IMPORTANT: If you miss the file argument into the task it will behave as described per <<_validate_known_issues_configuration>>

.assertion-patterns.txt
[source]
----
.*Doctor Who.*
----

[tabs]
======
macOS / Linux::
+
[source,shell]
----
./gradlew validateKnownIssues --args='-f ./assertion-failures.txt'
----

Windows::
+
[source,shell]
----
gradlew validateKnownIssues --args='-f assertion-failures.txt'
----
======

.Output
[source]
----
Known Issue | Assertion Error
VVD-6       | .*Doctor Who.*
----

== Replace deprecated steps

The task replaces deprecated steps with actual ones in all stories(`\*.story` files) and composite steps (`*.steps` files) along the path `<project-name>/src/main/resources`.
Please note that some deprecated steps (for example which should be replaced with two steps) cannot be replaced automatically and must be refactored manually.

[tabs]
======
macOS / Linux::
+
[source,shell]
----
./gradlew replaceDeprecatedSteps
----

Windows::
+
[source,shell]
----
gradlew replaceDeprecatedSteps
----
======

.Output (for cases when found steps which cannot be replaced automatically)
[source]
----
The step "When I check all checkboxes located by `xpath(.//input)`" from "CheckboxStepsTests.story - Scenario: Validation of step 'When I $checkboxState all checkboxes located by `$checkboxesLocator`'" is deprecated but cannot be replaced automatically, please replace it manually.
The step "When I check all checkboxes located by `xpath(.//input)`" from "composite.steps - Composite: When I run composite step with table:$table" is deprecated but cannot be replaced automatically, please replace it manually.
----

== Replace deprecated properties

The task replaces deprecated properties with actual ones in all properties files along the path `<project-name>/src/main/resources/properties`.

[tabs]
======
macOS / Linux::
+
[source,shell]
----
./gradlew replaceDeprecatedProperties
----

Windows::
+
[source,shell]
----
gradlew replaceDeprecatedProperties
----
======

The examples below demonstrate property file with deprecated properties before and after applying the `replaceDeprecatedProperties` task.

.Property file with deprecated entries before running the task `replaceDeprecatedProperties`
[source]
----
ui.visual.applitools.server-uri=https://eyes.applitools.com/
ui.visual.applitools.app-name=name
web.driver.CHROME.experimental-options={"prefs": {"profile": {"cookie_controls_mode": 0}}}
batch-6.story-execution-timeout=PT15M
----

.Property file with replaced entries after running the task `replaceDeprecatedProperties`
[source]
----
applitools.server-uri=https://eyes.applitools.com/
applitools.app-name=name
web.driver.chrome.experimental-options={"prefs": {"profile": {"cookie_controls_mode": 0}}}
batch-6.story.execution-timeout=PT15M
----

== VIVIDUS initialization

The task performs VIVIDUS initialization.

Within the folder containing your *tests*, this means all configuration properties will be checked,
including suites, profiles, environments, known issues, etc.

[tabs]
======
macOS / Linux::
+
[source,shell]
----
./gradlew testVividusInitialization
----

Windows::
+
[source,shell]
----
gradlew testVividusInitialization
----
======

== Verification

=== Check

This task run all checks.

NOTE: For VIVIDUS tests this task will test VIVIDUS initialization and validate configuration of known issues.

[tabs]
======
macOS / Linux::
+
[source,shell]
----
./gradlew check
----

Windows::
+
[source,shell]
----
gradlew check
----
======

== Find and fix formatting issues
https://github.com/diffplug/spotless[Spotless] checks refer to formatting and linting validations to enforce consistent
code quality standards. Spotless automates the formatting of files based on predefined rules and integrates with linting
tools. It offers a number of generic formatters (indentation correction, normalize line endings, enforce consistent EOF
files, enforce file encoding, etc.) that help keep test files clean, readable, and consistent, reducing noise in version
control and making collaboration easier.

For files like `\*.story`, `*.steps`, `*.table`, commonly used in VIVIDUS, the following Spotless rules are applied by default:

.Spotless rules
[cols="1,2", options="header"]
|===
|Rule
|Description

|Trimming Trailing Whitespace
|Removes any spaces or tabs at the end of lines.

|Ensuring Newline at End of File
|Guarantees that each file ends with a single newline.

|Consistent Indentation
|Enforces 4 spaces for indentation.

|Normalizing Line Endings
|Converts all line endings to LF (\n) for consistency across platforms.

|===

=== Spotless tasks

The task validates that all files comply with the specified formatting rules.

NOTE: This task is executed automatically during the build process and does not require manual invocation.

[tabs]
======
macOS / Linux::
+
[source,shell]
----
./gradlew spotlessCheck
----

Windows::
+
[source,shell]
----
gradlew spotlessCheck
----
======

The task automatically formats files to conform to the defined rules.

[tabs]
======
macOS / Linux::
+
[source,shell]
----
./gradlew spotlessApply
----

Windows::
+
[source,shell]
----
gradlew spotlessApply
----
======

=== Fixing Spotless violations

If the <<build>> task is failed and the result like the following is shown in the console output, it means that some files
do not comply with the Spotless rules.

[source,shell]
----
> Task :spotlessVividusCheck FAILED

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':spotlessVividusCheck'.
> The following files had format violations:
      src/main/resources/story/web_app/Google Search.story
          @@ -13,8 +13,6 @@
           |·step··········································|
           |·When·I·click·on·element·located·by·`xpath(.)`·|
           When·I·enter·`VIVIDUS·test·automation`·in·field·located·by·`<search-input-field>`
          -When·I·wait·until·element·located·by·`<search-button>`·appears·
          -When·I·click·on·element·located·by·`<search-button>`\t
          +When·I·wait·until·element·located·by·`<search-button>`·appears
          +When·I·click·on·element·located·by·`<search-button>`
           Then·number·of·elements·found·by·`linkUrlPart(https://docs.vividus.dev/vividus/)->filter.textPart(What·is·VIVIDUS·::·VIVIDUS)`·is·equal·to·`1`
          -
          -
  Run './gradlew :spotlessApply' to fix these violations.
----

You can fix the violations manually or automatically by running the `spotlessApply` task. After fixing, review
the changes and commit them to your repository. Following these steps will help keep your build stable and successful.

=== Git hook

You can run

[tabs]
======
macOS / Linux::
+
[source,shell]
----
./gradlew spotlessInstallGitPrePushHook
----

Windows::
+
[source,shell]
----
gradlew spotlessInstallGitPrePushHook
----
======

and it will install a hook such that

. When you perform Git push, it runs `spotlessCheck`
. If formatting issues are found:
    - It automatically runs `spotlessApply` to fix them
    - Aborts the push with a message
    - You can then commit the changes and push again

This ensures your code is always clean before it leaves your machine.

== Build the project

[id=build]
=== Build

Assembles the current project with tests.

Run the build task to compile and assemble all project components.
This will process source files, resolve dependencies, and generate build artifacts.

NOTE: Ensure all prerequisites are installed before running the build process.

[tabs]
======
macOS / Linux::
+
[source,shell]
----
./gradlew build
----

Windows::
+
[source,shell]
----
gradlew build
----
======

=== Clean

Deletes the build directory.

Run the clean task to remove all files and folders generated during the build process.
This helps ensure a fresh build environment by deleting any previous build artifacts.

[tabs]
======
macOS / Linux::
+
[source,shell]
----
./gradlew clean
----

Windows::
+
[source,shell]
----
gradlew clean
----
======

NOTE: Use this command before starting a new build to avoid issues caused by leftover files from previous builds.

[tabs]
======
macOS / Linux::
+
[source,shell]
----
./gradlew clean build
----

Windows::
+
[source,shell]
----
gradlew clean build
----
======

== IDE configuration

To use certain IDEs for test development, you’ll need to generate configuration files.

=== Eclipse

==== Generate Eclipse configuration files

This task will generate the necessary configuration files for Eclipse IDE.

[tabs]
======
macOS / Linux::
+
[source,shell]
----
./gradlew eclipse
----

Windows::
+
[source,shell]
----
gradlew eclipse
----
======

==== Clean Eclipse configuration files

This task cleans (removes) all Eclipse IDE configuration files.

[tabs]
======
macOS / Linux::
+
[source,shell]
----
./gradlew cleanEclipse
----

Windows::
+
[source,shell]
----
gradlew cleanEclipse
----
======

=== IDEA

==== Generate IntelliJ IDEA configuration files

This task will generate the necessary configuration files for IntelliJ IDEA.

[tabs]
======
macOS / Linux::
+
[source,shell]
----
./gradlew idea
----

Windows::
+
[source,shell]
----
gradlew idea
----
======

==== Clean IntelliJ IDEA configuration files

This task cleans (removes) all IntelliJ IDEA configuration files.

[tabs]
======
macOS / Linux::
+
[source,shell]
----
./gradlew cleanIdea
----

Windows::
+
[source,shell]
----
gradlew cleanIdea
----
======

==== Open in IntelliJ IDEA

Opens the configured project with your tests in IntelliJ IDEA.

[tabs]
======
macOS / Linux::
+
[source,shell]
----
./gradlew openIdea
----

Windows::
+
[source,shell]
----
gradlew openIdea
----
======
