= Expressions available out of the box

Here one could find description of the expressions that are delivered with Vividus itself without any plugins required.

NOTE: The expression parameters marked with *bold* are mandatory.

== Data generation

=== `randomInt`

Generates a random integer value between the specified origin (`minInclusive`) and the specified bound (`maxInclusive`).

[source, subs="+quotes"]
----
#{randomInt(*$minInclusive*, *$maxInclusive*)}
----

* *`$minInclusive`* - the least value
* *`$maxInclusive`* - the upper bound

.Examples of the expressions generating random integer value
|===
|Expression |Result

|`#{randomInt(1, 10)}`
|An integer between 1 and 10

|`#{randomInt(100, 999)}`
|An integer between 100 and 999

|`#{randomInt(-5, 5)}`
|An integer between -5 and 5

|`#{randomInt(-5, -2)}`
|An integer between -5 and -2

|`#{randomInt(1, 1)}`
|`1`
|===

== String manipulations

=== `toLowerCase`

Converts an input string to lower case.

[source, subs="+quotes"]
----
#{toLowerCase(*$input*)}
----

* *`$input`* - any string to be converted lower case

.Examples of the expressions converting strings to lower case
|===
|Expression |Result

|`#{toLowerCase(aBc)}`
|`abc`
|===

=== `toUpperCase`

Converts an input string to upper case.

[source, subs="+quotes"]
----
#{toUpperCase(*$input*)}
----

* *`$input`* - any string to be converted upper case

.Examples of the expressions converting strings to upper case
|===
|Expression |Result

|`#{toUpperCase(aBc)}`
|`ABC`
|===

=== `capitalizeFirstWord`

Capitalizes an input string, changing the first character to title case. No other characters are changed.

[source, subs="+quotes"]
----
#{capitalizeFirstWord(*$input*)}
----

* *`$input`* - any string to be capitalized

.Examples of the expressions capitalizing strings
|===
|Expression |Result

|`#{capitalizeFirstWord(aBc)}`
|`ABc`
|===

=== `capitalizeWords`

Capitalizes all the whitespace separated words in the input string. Only the first character of each word is changed.

[source, subs="+quotes"]
----
#{capitalizeWords(*$input*)}
----

* *`$input`* - any string to be capitalized

.Examples of the expressions capitalizing words in the string
|===
|Expression |Result

|`#{capitalizeWords(aBc dEf)}`
|`ABc DEf`
|===

=== `capitalizeWordsFully`

Converts all the whitespace separated words in a String into capitalized words, that is each word is made up of a titlecase character and then a series of lowercase characters.

[source, subs="+quotes"]
----
#{capitalizeWordsFully(*$input*)}
----

* *`$input`* - any string to be capitalized

.Examples of the expressions capitalizing strings
|===
|Expression |Result

|`#{capitalizeWordsFully(aBc dEf)}`
|`Abc Def`
|===

=== `uncapitalizeFirstWord`

Uncapitalizes an input string, changing the first character to title case. No other characters are changed.

[source, subs="+quotes"]
----
#{uncapitalizeFirstWord(*$input*)}
----

* *`$input`* - any string to be capitalized

.Examples of the expressions capitalizing strings
|===
|Expression |Result

|`#{uncapitalizeFirstWord(ABc)}`
|`aBc`
|===

=== `uncapitalizeWords`

Uncapitalizes all the whitespace separated words in the input string. Only the first character of each word is changed.

[source, subs="+quotes"]
----
#{uncapitalizeWords(*$input*)}
----

* *`$input`* - any string to be capitalized

.Examples of the expressions capitalizing words in the string
|===
|Expression |Result

|`#{uncapitalizeWords(ABc DEf)}`
|`aBc eEf`
|===

=== `trim`

Trims an input string (removes control characters (chars with code less than or equal to 32) from both ends).

[source, subs="+quotes"]
----
#{trim(*$input*)}
----

* *`$input`* - any string to be trimmed

.Examples of the expressions trimming strings
|===
|Expression |Result

|`#{trim( a b c )}`
|`a b c`
|===

=== `encodeToBase64`

Encode the input string to Base64 format

[source, subs="+quotes"]
----
#{encodeToBase64(*$input*)}
----

* *`$input`* - any string to be encoded to Base64 format

.Examples of the expressions encoding to Base64
|===
|Expression |Result

|`#{encodeToBase64(vividus)}`
|`dml2aWR1cw==`
|===

=== `decodeFromBase64`

Decodes the input string from Base64 format to the regular string

[source, subs="+quotes"]
----
#{decodeFromBase64(*$input*)}
----

* *`$input`* - Base64 string to decode

.Examples of the expressions decoding Base64
|===
|Expression |Result

|`#{decodeFromBase64(dml2aWR1cw==)}`
|`vividus`
|===


=== `toBase64Gzip`

Compress the input string to GZip and encode compressed bytes to Base64 format

[source, subs="+quotes"]
----
#{toBase64Gzip(*$input*)}
----

* *`$input`* - any string to be compressed and encoded

.Examples of the expressions compressing and encoding to Base64 GZip
|===
|Expression |Result

|`#{toBase64Gzip(vividus)}`
|`H4sIAAAAAAAAACvLLMtMKS0GANIHCdkHAAAA`
|===

== Hash calculations

:algorithm-summary: hash algorithm (can use https://datatracker.ietf.org/doc/rfc1319[MD2], https://datatracker.ietf.org/doc/rfc1321[MD5], https://datatracker.ietf.org/doc/rfc3174[SHA-1], https://datatracker.ietf.org/doc/rfc6234[SHA-256], https://datatracker.ietf.org/doc/rfc6234[SHA-384], https://datatracker.ietf.org/doc/rfc6234[SHA-512])

=== `calculateHash`

Calculates the hash using the specified hashing algorithm

[source, subs="+quotes"]
----
#{calculateHash($algorithm, $input)}
----

* *`$algorithm`* - {algorithm-summary}
* *`$input`* - any string to calculate hash

.Example of hash calculating for string using MD5
|===
|Expression |Result

|`#{calculateHash(MD5, vividus)}`
|`0a05ba6064ae7e5d6ee9818f85b666ad`
|===

=== `calculateFileHash`

:resource-info: xref:ROOT:glossary.adoc#_resource

Calculates the {resource-info}[resource] or file hash using the specified hashing algorithm

[source, subs="+quotes"]
----
#{calculateFileHash($algorithm, $resourceNameOrFilePath)}
----

* *`$algorithm`* - {algorithm-summary}
* *`$resourceNameOrFilePath`* - the {resource-info}[resource name] or the file path

.Example of hash calculating for file using SHA-1
|===
|Expression |Result

|`#{calculateFileHash(SHA-1, data/file.txt)}`
|`0a05ba6064ae7e5d6ee9818f85b666ad`
|===

== Resources
:resource-name-parameter: pass:quotes[*`$resourceName`* - the name of the xref:ROOT:glossary.adoc#_resource[resource] to load]

=== `loadResource`

Loads the resource by its name and replaces the expression with the content of the resource.

[source, subs="+quotes"]
----
#{loadResource(*$resourceName*)}
----

* {resource-name-parameter}

.Load data from the project resource
[source,gherkin]
----
When I initialize the scenario variable `my-data` with value `#{loadResource(/data/body.txt)}`
----

=== `loadBinaryResource`

Loads the resource by its name as bytes. It could be useful for the steps that accepting raw binary data.

[source, subs="+quotes"]
----
#{loadBinaryResource(*$resourceName*)}
----

* {resource-name-parameter}

.Load data from the project resource as bytes
[source,gherkin]
----
When I mock HTTP responses with request URL which CONTAINS `frames.html` using response code `200`, content `#{loadBinaryResource(page.html)}` and headers:
|name        |value    |
|Content-Type|text/html|
----

=== `resourceToBase64`

Finds the resource by its name and replaces the expression with the content of the resource in Base64 format.

[source, subs="+quotes"]
----
#{resourceToBase64(*$resourceName*)}
----

[subs="specialchars,attributes,quotes,replacements,macros,post_replacements"]
* {resource-name-parameter}

.Load data as Base64 from the project resource
[source,gherkin]
----
When I initialize the scenario variable `my-data` with value `#{resourceToBase64(/data/body.txt)}`
----

== Script evaluation

=== `eval`

Evaluates https://commons.apache.org/proper/commons-jexl/[JEXL] script and converts result to a string.

[source, subs="+quotes"]
----
#{eval(*$script*)}
----

* *`$script`* - valid https://commons.apache.org/proper/commons-jexl/reference/syntax.html[JEXL] script to be evaluated

[TIP]
* Any Vividus variable is accessible in the JEXL script by its name


.Evaluate JEXL script
[source,gherkin]
----
Scenario: Verify eval expression
Then `#{<expression>}` is = `<expected>`
Examples:
|expected          |expression                                                        |
|null              |eval(null)                                                        |
|28                |eval(16 + 2 * 6)                                                  |
|10                |eval(math:abs(-10))                                               |
|here              |eval(stringUtils:substringAfterLast('namescpaces are %here', '%'))|
|108               |eval((16 + 2) * 6)                                                |
|-6                |eval(100 / 5 - 16 * 2 + 6)                                        |
|true              |eval(`string\n1` == `string\n1`)                                  |
|false             |eval(`string\n1` == `string1`)                                    |
|I Am FINE         |eval(wordUtils:capitalize('i am FINE'))                           |
|i am fINE         |eval(wordUtils:uncapitalize('I Am FINE'))                         |
|tHE DOG HAS A bone|eval(wordUtils:swapCase('The dog has a BONE'))                    |
|FRD               |eval(wordUtils:initials('Fus Ro Dah'))                            |
----

=== `evalGroovy`

Evaluates groovy script and converts result to a string.

[source, subs="+quotes"]
----
#{evalGroovy(*$script*)}
----

* *`$script`* - valid https://groovy-lang.org/index.html[Groovy] script to be evaluated

[TIP]
====
* Any Vividus variable is accessible in the groovy script by its name
* One could use any of online groovy evaluators to verify the script. For example see: https://groovy-playground.appspot.com/[Evaluator]
====


.Evaluate Groovy script
[source,gherkin]
----
When I initialize Scenario variable `listOfMaps` with values:
|key|
|2  |
|1  |
|3  |
Then `1-2-3` is = `#{evalGroovy(return listOfMaps.collect{it['key']}.sort().join('-'))}`
----

== Null value

=== `null`

Represents `null` (a.k.a. `NULL`). In most case `null` means no value (see https://www.w3schools.com/sql/sql_null_values.asp[`NULL` in SQL] and https://www.json.org/json-en.html[`null` in JSON]).

[source, subs="+quotes"]
----
#{null}
----

NOTE: Null expression can only be evaluated separately. Strings or other expressions with the nested null expression will be completely ignored and not executed.

.Validation of JSON element with `null` value
[source,gherkin]
----
When I initialize the scenario variable `json` with value `
{
    "persons": {
        "nemo": null
    }
}
`
Then JSON element value from `${json}` by JSON path `$.persons.nemo` is equal to `#{null}`
----
