= Expressions

VIVIDUS provides a set of pre-defined expressions. Also plugins may define own
xref:ROOT:glossary.adoc#_expression[expressions] (they are documented in the
corresponding plugins articles).

NOTE: The expression arguments marked with *bold* are mandatory.

== Data generation

=== generate

Generates random data from various domain areas.

[source, subs="+quotes"]
----
`#{generate(*$data-provider-and-its-arguments*)}`
----

* *`$data-provider-and-its-arguments`* - one of the https://www.datafaker.net/documentation/providers/[data providers],
its dot-separated method and space separated arguments wrapped into single
quotes (for majority of cases arguments are not needed, their number and
possible values depend on the chosen data provider method).

Below you can find a complete list of the supported expressions with results
examples. Descriptions of the data providers and their arguments can be found
https://www.datafaker.net/documentation/providers/[in DataFaker documentation]:
click on the data provider name to find details.

[%collapsible]
.#Click here to view the complete list of the supported expressions#
====
include::partial$data-generating.adoc[]
====

Let's see the structure of the expression for the following example:
[source, subs="+quotes"]
----
`#{generate(Internet.password '5', '10', 'true')}`
----

[source,expression]
----
#{generate                                       <1>
          (Internet                              <2>
                   .password                     <3>
                             '5',                <4>
                                  '10',          <4>
                                        'true')} <4>
----
<1> Generate expression itself.
<2> Data provider from the https://www.datafaker.net/documentation/providers/[list]. In this case - `Internet`. Click on its name to see the methods it contains.
<3> One of the available https://javadoc.io/doc/net.datafaker/datafaker/1.9.0/net/datafaker/providers/base/Internet.html[methods] within `Internet` data provider - `password`. There are multiple choices, we picked the fourth one.
<4> Available arguments for the chosen https://javadoc.io/doc/net.datafaker/datafaker/1.9.0/net/datafaker/providers/base/Internet.html#password-int-int-boolean-[method].
+
There are three of them:

 - int minimumLength - minimum number of symbols;
 - int maximumLength - maximum number of symbols;
 - boolean includeUppercase - `true` or `false` for Uppercase usage;

In this way we created an *expression* that *generates* a *password* from *5* to *10* characters length *including* uppercase letters. +
Possible output is `51gVj5aLZY`


=== letterify

Replaces `?` symbols with latin letters.
[source, subs="+quotes"]
----
`#{generate(letterify '*$input*', '$isUpperCase')}`
----

* *`$input`* - any string containing `?` symbols to be replaced with letters
* `$isUpperCase` - boolean, set it to `true` for uppercase option

.letterify examples
[cols="a,a"]
|===
|Expression |Result

|
[source, expression]
----
#{generate(letterify 'test????test')}
----
.^|testnjmytest

|
[source, expression"]
----
#{generate(letterify 'test????test', 'true')}
----
.^|testXQBMtest
|===

=== numerify

Replaces `#` symbols with numbers.

[source, subs="+quotes"]
----
`#{generate(numerify '*$input*')}`
----

* *`$input`* - any string containing `#` symbols to be replaced with numbers

.numerify example
[cols="a,a"]
|===
|Expression |Result

|
[source, expression]
----
#{generate(numerify 'test####test')}
----
.^|test5862test
|===

=== bothify

Combination of letterify and numerify.

[source, subs="+quotes"]
----
`#{generate(bothify '*$input*')}`
----

* *`$input`* - any string containing `#` and `?` symbols to be replaced with numbers and letters accordingly

.bothify example
[cols="a,a"]
|===
|Expression |Result

|
[source, expression]
----
#{generate(bothify 'test#?#?#?#test')}
----
.^|test2o7v0g9test
|===

=== templatify

Replaces symbol mentioned in the second argument with one of the symbols mentioned after it.

[source, subs="+quotes"]
----
`#{generate(templatify '*$input*', '*$whatToReplace*', '*$replacement1*', '$replacement2', '$replacement3')}`
----

* *`$input`* - any string to process
* *`$whatToReplace`* - part of the string to be replaced
* *`$replacement`* - replacement to use. Possible to use multiple options

.templatify example
[cols="a,a"]
|===
|Expression |Result

.4+.^|
[source, expression]
----
#{generate(templatify 'VIVIDUS', 'I', 'X', 'P')}`
----
|VPVPDUS

|VXVPDUS

|VPVXDUS

|VXVXDUS
|===

=== examplify

Replaces symbols by example: uppercase with uppercase, digit with digit, lowercase with lowercase.

[source, subs="+quotes"]
----
`#{generate(examplify '*$input*')}`
----

* *`$input`* - any string to process

.examplify example
[cols="a,a"]
|===
|Expression |Result

|
[source, expression]
----
#{generate(examplify 'V1V1DUs')}
----
.^|R9Q7VTq
|===

=== regexify

Allows generating output based on https://en.wikipedia.org/wiki/Regular_expression[regular expression].

[source, subs="+quotes"]
----
`#{generate(regexify '*$regularExpression*')}`
----

* *`$regularExpression`* - regular expression that describes desired output

.regexify example
[cols="a,a"]
|===
|Expression |Result

|
[source, expression]
----
#{generate(regexify '\d{3}\w{1}')}
----
.^|409Y

|
[source, expression]
----
#{generate(regexify '[A-Z]{3}[a-z]{4}[2-8]{5}')}
----
.^|PQUlxdq66436
|===

=== options

Returns any of provided items.

[source, subs="+quotes"]
----
`#{generate(options.option '*$item1*', '*$item2*', '$item3')}`
----

* *`$item`* - option to choose from

.options example
[cols="6a,1a"]
|===
|Expression |Result

|
[source, expression]
----
#{generate(options.option 'V','I','V','I','D','U','S')}
----
.^|S
|===

=== generate JSON

Generates JSON based on key-value pairs input.

[source, subs="+quotes"]
----
`#{generate(json '*$key1*', '*$value1*', '$key2', '$value2')}`
----

.generate JSON example
[%autowidth.stretch]
[cols="~a,a"]
|===
|Expression |Result

.^|
[source, expression]
----
#{generate(json 'first_name','Bob','last_name','Dylan','profession','singer')}
----
|[source,JSON]
----
{"first_name": "Bob", "last_name": "Dylan", "profession": "singer"}
----
|===

=== generate CSV

Generates comma-separated values based on input.

[source, subs="+quotes"]
----
`#{generate(csv, '*$rowsNumber*' '*$columnName1*', '*$value1*', '$columnName2', '$value2')}`
----

* *`$rowsNumber`* - number of rows to fill in
* *`$columnName1`* - name of the first column
* *`$value1`* - data to enter the first column
* *`$columnName2`* - name of the second column
* *`$value2`* - data to enter the second column

.generate CSV example
[%autowidth.stretch]
[cols="~a,a"]
|===
|Expression |Result

.^|
[source, expression]
----
#{generate(csv '3', 'first_name','Bob','last_name','Dylan')}
----
|
[source,CSV]
----
"first_name","last_name"
"Bob","Dylan"
"Bob","Dylan"
"Bob","Dylan"
----
|===

=== `randomInt`

Generates a random integer value between the specified origin (`minInclusive`) and the specified bound (`maxInclusive`).

[source, subs="+quotes"]
----
#{randomInt(*$minInclusive*, *$maxInclusive*)}
----

* *`$minInclusive`* - the least value
* *`$maxInclusive`* - the upper bound

.Examples of the expressions generating random integer value
|===
|Expression |Result

|`#{randomInt(1, 10)}`
|An integer between 1 and 10

|`#{randomInt(100, 999)}`
|An integer between 100 and 999

|`#{randomInt(-5, 5)}`
|An integer between -5 and 5

|`#{randomInt(-5, -2)}`
|An integer between -5 and -2

|`#{randomInt(1, 1)}`
|`1`
|===

== Math calculations

=== `round`

Rounds a number with an approximate value based on specific rounding definitions.

[source, subs="+quotes"]
----
#{round(*$value*, $maxFractionDigits, $roundingMode)}
----

* *`$value`* - any number to be processed
* `$maxFractionDigits` - maximum number of digits after the decimal separator
* `$roundingMode` - specifies a rounding behavior for numerical operations (more information {java-api-docs-base-url}/docs/api/java.base/java/math/RoundingMode.html[here]):
+
[cols="1, 1, 4", options="header"]
|===
|Rouding Mode |Readable |Description

|UP
|up
|Rounds away from zero.

|DOWN
|down
|Rounds towards zero.

|CEILING
|ceiling
|Rounds towards positive infinity.

|FLOOR
|floor
|Rounds towards negative infinity.

|HALF_UP
|half up
|Rounds towards "nearest neighbor" unless both neighbors are equidistant, in which case round up.

|HALF_DOWN
|half down
|Rounds towards "nearest neighbor" unless both neighbors are equidistant, in which case round down.

|HALF_EVEN
|half even
|Rounds towards the "nearest neighbor" unless both neighbors are equidistant, in which case, round towards the even neighbor.

|UNNECESSARY
|unnecessary
|Asserts that the requested operation has an exact result, hence no rounding is necessary.
|===

.Examples of rounding operations with different arguments
|===
|Expression |Result

|`#{round(5.0)}`
|`5`

|`#{round(-5.9, 0)}`
|`-6`

|`#{round(5.551, 2)}`
|`5.55`

|`#{round(1.4, 0, ceiling)}`
|`2`

|`#{round(-1.4, 0, floor)}`
|`-2`

|`#{round(-5.5555, 3, half up)}`
|`-5.556`

|`#{round(-5.555, 2, half down)}`
|`-5.55`

|`#{round(-5.5, 0, half even)}`
|`-6`

|`#{round(-1.1, 2, unnecessary)}`
|`-1.1`
|===

== String manipulations

=== `replaceFirstByRegExp` / `replaceAllByRegExp`

Replaces the first / every substring of the input that matches the regular
expression with the given replacement string.

[TIP]
====
Online tools like https://www.regexplanet.com/advanced/java/index.html[RegexPlanet] or
https://regex101.com/[Regex101] can be used to test and debug regular expressions
====

[source, subs="+quotes"]
----
#{replaceFirstByRegExp(*$regularExpression*, *$replacement*, *$input*)}
----
[source, subs="+quotes"]
----
#{replaceAllByRegExp(*$regularExpression*, *$replacement*, *$input*)}
----

* *$regularExpression* - the regular expression to match substring(s)
* *$replacement* - the replacement string
+
[NOTE]
====
Backslashes (`\`) and dollar signs (`$`) in the replacement string may cause the results to be different than if it were
being treated as a literal replacement string. Dollar signs may be treated as references to captured substrings (e.g.
`$1` is a reference to the first group) and backslashes are used to escape literal characters in the replacement string.
====
* *$input* - any string to be processed

[cols="1, 2,1", options="header"]
|===
|Description |Expression |Result

|Extract ID from the string
|`#{replaceFirstByRegExp(product-(\d+), $1, product-86)}`
|`86`

|Extract ID and build new string with it
|`#{replaceFirstByRegExp(/user/(\d+), author/$1, /user/21)}`
|`author/21`

|Extract password from the string with comma
|`#{replaceFirstByRegExp(.\*new password is (.*), $1, """Updated, new password is qwe123""")}`
|`qwe123`

|Replace whitespaces with dashes
|`#{replaceAllByRegExp(\s, -, convert spaces to dashes)}`
|`convert-spaces-to-dashes`

|Remove all numbers from the string
|`#{replaceAllByRegExp(\d, , a1b2c3d)}`
|`abcd`

|Replace all whitespaces with commas
|`#{replaceAllByRegExp(\s, """,""", string with spaces)}`
|`string,with,spaces`

|Replace all whitespaces with commas
|`#{replaceAllByRegExp(\s, \,, string with spaces)}`
|`string,with,spaces`

|Replace all commas with underscores
|`#{replaceAllByRegExp(\,, _, string,with,commas)}`
|`string_with_commas`

|Replace all commas with underscores
|`#{replaceAllByRegExp(""",""", _, string,with,commas)}`
|`string_with_commas`

|Replace all commas with underscores
|`#{replaceAllByRegExp(\,, _, """string,with,commas""")}`
|`string_with_commas`

|Replace all commas with underscores
|`#{replaceAllByRegExp(\,, _, string\,with\,commas)}`
|`string_with_commas`

|Replace the first whitespace with comma
|`#{replaceFirstByRegExp(\s, """,""", string with spaces)}`
|`string,with spaces`

|Replace the first whitespace with comma
|`#{replaceFirstByRegExp(\s, \,, string with spaces)}`
|`string,with spaces`

|Replace the first comma with underscore
|`#{replaceFirstByRegExp(\,, _, string,with,commas)}`
|`string_with,commas`

|Replace the first comma with underscore
|`#{replaceFirstByRegExp(""",""", _, string,with,commas)}`
|`string_with,commas`

|Replace the first comma with underscore
|`#{replaceFirstByRegExp(\,, _, """string,with,commas""")}`
|`string_with,commas`

|Replace the first comma with underscore
|`#{replaceFirstByRegExp(\,, _, string\,with\,commas)}`
|`string_with,commas`

|===

=== `toLowerCase`

Converts an input string to lower case.

[source, subs="+quotes"]
----
#{toLowerCase(*$input*)}
----

* *`$input`* - any string to be converted lower case

.Examples of the expressions converting strings to lower case
|===
|Expression |Result

|`#{toLowerCase(aBc)}`
|`abc`
|===

=== `toUpperCase`

Converts an input string to upper case.

[source, subs="+quotes"]
----
#{toUpperCase(*$input*)}
----

* *`$input`* - any string to be converted upper case

.Examples of the expressions converting strings to upper case
|===
|Expression |Result

|`#{toUpperCase(aBc)}`
|`ABC`
|===

=== `capitalizeFirstWord`

Capitalizes an input string, changing the first character to title case. No other characters are changed.

[source, subs="+quotes"]
----
#{capitalizeFirstWord(*$input*)}
----

* *`$input`* - any string to be capitalized

.Examples of the expressions capitalizing strings
|===
|Expression |Result

|`#{capitalizeFirstWord(aBc)}`
|`ABc`
|===

=== `capitalizeWords`

Capitalizes all the whitespace separated words in the input string. Only the first character of each word is changed.

[source, subs="+quotes"]
----
#{capitalizeWords(*$input*)}
----

* *`$input`* - any string to be capitalized

.Examples of the expressions capitalizing words in the string
|===
|Expression |Result

|`#{capitalizeWords(aBc dEf)}`
|`ABc DEf`
|===

=== `capitalizeWordsFully`

Converts all the whitespace separated words in a String into capitalized words, that is each word is made up of a titlecase character and then a series of lowercase characters.

[source, subs="+quotes"]
----
#{capitalizeWordsFully(*$input*)}
----

* *`$input`* - any string to be capitalized

.Examples of the expressions capitalizing strings
|===
|Expression |Result

|`#{capitalizeWordsFully(aBc dEf)}`
|`Abc Def`
|===

=== `uncapitalizeFirstWord`

Uncapitalizes an input string, changing the first character to title case. No other characters are changed.

[source, subs="+quotes"]
----
#{uncapitalizeFirstWord(*$input*)}
----

* *`$input`* - any string to be capitalized

.Examples of the expressions capitalizing strings
|===
|Expression |Result

|`#{uncapitalizeFirstWord(ABc)}`
|`aBc`
|===

=== `uncapitalizeWords`

Uncapitalizes all the whitespace separated words in the input string. Only the first character of each word is changed.

[source, subs="+quotes"]
----
#{uncapitalizeWords(*$input*)}
----

* *`$input`* - any string to be capitalized

.Examples of the expressions capitalizing words in the string
|===
|Expression |Result

|`#{uncapitalizeWords(ABc DEf)}`
|`aBc eEf`
|===

=== `trim`

Trims an input string (removes control characters (chars with code less than or equal to 32) from both ends).

[source, subs="+quotes"]
----
#{trim(*$input*)}
----

* *`$input`* - any string to be trimmed

.Examples of the expressions trimming strings
|===
|Expression |Result

|`#{trim( a b c )}`
|`a b c`
|===

=== `substringBefore`

Gets the substring before the first occurrence of a separator. The separator is not included in the result.

[source, subs="+quotes"]
----
#{substringBefore(*$input*, *$separator*)}
----

* *`$input`* - any string to get a substring from
* *`$separator`* - the string to search for

.Examples of the expressions getting the substring
|===
|Expression                               |Result

|`#{substringBefore(, a)}`                |
|`#{substringBefore(abc, a)}`             |
|`#{substringBefore(abcba, b)}`           |`a`
|`#{substringBefore(abcba,b)}`            |`a`
|`#{substringBefore(abc, c)}`             |`ab`
|`#{substringBefore(abc, d)}`             |`abc`
|`#{substringBefore(abc, )}`              |
|`#{substringBefore(a\,b\,c\,b\,a, c)}`   |`a,b,`
|`#{substringBefore("""a,b,c,b,a""", c)}` |`a,b,`

|===

=== `substringAfter`

Gets the substring after the first occurrence of a separator. The separator is not included in the result.

[source, subs="+quotes"]
----
#{substringAfter(*$input*, *$separator*)}
----

* *`$input`* - any string to get a substring from
* *`$separator`* - the string to search for

.Examples of the expressions getting the substring
|===
|Expression                              |Result

|`#{substringAfter(, a)}`                |
|`#{substringAfter(abc, a)}`             |`bc`
|`#{substringAfter(abcba, b)}`           |`cba`
|`#{substringAfter(abcba,b)}`            |`cba`
|`#{substringAfter(abc, c)}`             |
|`#{substringAfter(abc, d)}`             |
|`#{substringAfter(abc, )}`              |`abc`
|`#{substringAfter(a\,b\,c\,b\,a, c)}`   |`,b,a`
|`#{substringAfter("""a,b,c,b,a""", c)}` |`,b,a`

|===

=== `anyOf`

Pick a random value from a predefined list

[source, subs="+quotes"]
----
#{anyOf(*$list*)}
----

* *`$list`* - comma-separated list of values

.Examples of the expressions picking a random value
|===
|Expression |Result

|`#{anyOf(1, 2, 3)}`
|either `1`, or `2`, or `3`

|`#{anyOf(123)}`
|`123`

|`#{anyOf(1\,2)}`
|`1,2`

|`#{anyOf()}`
|<empty string>

|`#{anyOf( )}`
|<empty string>

|`#{anyOf(,)}`
|<empty string>

|`#{anyOf(, )}`
|<empty string>

|`#{anyOf("""a,b\, c""")}`
|`a,b\, c`
|===

=== `encodeToBase64`

Encode the input string to Base64 format

[source, subs="+quotes"]
----
#{encodeToBase64(*$input*)}
----

* *`$input`* - any string to be encoded to Base64 format

.Examples of the expressions encoding to Base64
|===
|Expression |Result

|`#{encodeToBase64(vividus)}`
|`dml2aWR1cw==`
|===

=== `decodeFromBase64`

Decodes the input string from Base64 format to the regular string

[source, subs="+quotes"]
----
#{decodeFromBase64(*$input*)}
----

* *`$input`* - Base64 string to decode

.Examples of the expressions decoding Base64
|===
|Expression |Result

|`#{decodeFromBase64(dml2aWR1cw==)}`
|`vividus`
|===


=== `decodeFromBase64ToBinary`

Decodes the input string from Base64 format to the binary data.

[source, subs="+quotes"]
----
#{decodeFromBase64ToBinary(*$input*)}
----

* *`$input`* - Base64 string to decode

.Decoding Base64-encoded image to perfrom visual check
----
When I compare against baseline with name `expected` from image `#{decodeFromBase64toBinary(iVBORw0KGgoAAAANSU...)}`
----

=== `toBase64Gzip`

Compress the input string to GZip and encode compressed bytes to Base64 format

[source, subs="+quotes"]
----
#{toBase64Gzip(*$input*)}
----

* *`$input`* - any string to be compressed and encoded

.Examples of the expressions compressing and encoding to Base64 GZip
|===
|Expression |Result

|`#{toBase64Gzip(vividus)}`
|`H4sIAAAAAAAAACvLLMtMKS0GANIHCdkHAAAA`
|===

=== `escapeHTML`

Escapes reserved characters in https://www.w3schools.com/html/html_entities.asp[HTML] string

[source, subs="+quotes"]
----
#{escapeHTML(*$input*)}
----

* *`$input`* - any string to be escaped

.Escape HTML string
|===
|Expression |Result

|`#{escapeHTML(M&Ms)}`
|`M&amp;Ms`
|===

=== `escapeJSON`

Escapes http://www.ietf.org/rfc/rfc4627.txt[reserved JSON characters]: converts any string into one that's properly escaped for inclusion in JSON as a value.

[source, subs="+quotes"]
----
#{escapeJSON(*$input*)}
----

* *`$input`* - any string to be escaped

.Escape JSON string
|===
|Expression |Result

|`#{escapeJSON("abc"+"xyz")}`
|`\"abc\"+\"xyz\"`
|===

=== `quoteRegExp`

Quotes the input literal so that metacharacters or escape sequences in the input sequence will be given no special meaning in regular expression.

[source, subs="+quotes"]
----
#{quoteRegExp(*$input*)}
----

* *`$input`* - any string to be quoted

.Quote regular expression
|===
|Expression |Result

|`#{quoteRegExp(Some(Value))}`
|`\QSome(Value)\E`
|===

.Verify the data
[source,gherkin]
----
Then `${frontEndData}` matches `#{quorePattern(${backEndData})}.*`
----

== Hash calculations

:algorithm-summary: hash algorithm (can use https://datatracker.ietf.org/doc/rfc1319[MD2], https://datatracker.ietf.org/doc/rfc1321[MD5], https://datatracker.ietf.org/doc/rfc3174[SHA-1], https://datatracker.ietf.org/doc/rfc6234[SHA-256], https://datatracker.ietf.org/doc/rfc6234[SHA-384], https://datatracker.ietf.org/doc/rfc6234[SHA-512])

=== `calculateHash`

Calculates the hash using the specified hashing algorithm

[source, subs="+quotes"]
----
#{calculateHash($algorithm, $input)}
----

* *`$algorithm`* - {algorithm-summary}
* *`$input`* - any string to calculate hash

.Example of hash calculating for string using MD5
|===
|Expression |Result

|`#{calculateHash(MD5, vividus)}`
|`0a05ba6064ae7e5d6ee9818f85b666ad`

|`#{calculateHash(SHA256, with,comma)}`
|`f93dcfd6fc4c91c058177af3b5de34090073f2cc4a658010609ed8778d6d89f3`

|`#{calculateHash(SHA256, with\,comma)}`
|`f93dcfd6fc4c91c058177af3b5de34090073f2cc4a658010609ed8778d6d89f3`
|===

=== `calculateFileHash`

:resource-info: xref:ROOT:glossary.adoc#_resource

Calculates the {resource-info}[resource] or file hash using the specified hashing algorithm

[source, subs="+quotes"]
----
#{calculateFileHash(*$algorithm*, *$resourceNameOrFilePath*)}
----

* *`$algorithm`* - {algorithm-summary}
* *`$resourceNameOrFilePath`* - the {resource-info}[resource name] or the file path

.Example of hash calculating for file using SHA-1
|===
|Expression |Result

|`#{calculateFileHash(SHA-1, data/file.txt)}`
|`0a05ba6064ae7e5d6ee9818f85b666ad`
|===

== Resources
:resource-name-argument: pass:quotes[*`$resourceName`* - the name of the xref:ROOT:glossary.adoc#_resource[resource] to load]

=== `loadResource`

Loads the resource by its name and replaces the expression with the content of the resource.

[source, subs="+quotes"]
----
#{loadResource(*$resourceName*)}
----

* {resource-name-argument}

.Load data from the project resource
[source,gherkin]
----
Given I initialize scenario variable `my-data` with value `#{loadResource(/data/body.txt)}`
----

=== `loadBinaryResource`

Loads the resource by its name as bytes. It could be useful for the steps that accepting raw binary data.

[source, subs="+quotes"]
----
#{loadBinaryResource(*$resourceName*)}
----

* {resource-name-argument}

.Load data from the project resource as bytes
[source,gherkin]
----
When I mock HTTP responses with request URL which CONTAINS `frames.html` using response code `200`, content `#{loadBinaryResource(page.html)}` and headers:
|name        |value    |
|Content-Type|text/html|
----

=== `resourceToBase64`

Finds the resource by its name and replaces the expression with the content of the resource in Base64 format.

[source, subs="+quotes"]
----
#{resourceToBase64(*$resourceName*)}
----

[subs="specialchars,attributes,quotes,replacements,macros,post_replacements"]
* {resource-name-argument}

.Load data as Base64 from the project resource
[source,gherkin]
----
Given I initialize scenario variable `my-data` with value `#{resourceToBase64(/data/body.txt)}`
----

== URL parsing
:url-argument: pass:quotes[*`$url`* - the URL to extract component from.]

=== `extractHostFromUrl`

Extracts host component from the given URL.

[source, subs="+quotes"]
----
#{extractHostFromUrl(*$url*)}
----

[subs="specialchars,attributes,quotes,replacements,macros,post_replacements"]
* {url-argument}

.Validate host component from URL
[source,gherkin]
----
Then `#{extractHostFromUrl(file://server/folder/data.xml?id=123)}` is = `server`
Then `#{extractHostFromUrl(https://docs.vividus.dev/vividus/latest?page=2)}` is = `docs.vividus.dev`
----

=== `extractPathFromUrl`

Extracts decoded path component from the given URL.

[source, subs="+quotes"]
----
#{extractPathFromUrl(*$url*)}
----

[subs="specialchars,attributes,quotes,replacements,macros,post_replacements"]
* {url-argument}

.Validate path component from URL
[source,gherkin]
----
Then `#{extractPathFromUrl(file://server/folder/data.xml?id=123)}` is = `/folder/data.xml`
Then `#{extractPathFromUrl(https://docs.vividus.dev/vividus/latest?page=2)}` is = `/vividus/latest`
----

=== `extractQueryFromUrl`

Extracts decoded query component from the given URL.

[source, subs="+quotes"]
----
#{extractQueryFromUrl(*$url*)}
----

[subs="specialchars,attributes,quotes,replacements,macros,post_replacements"]
* {url-argument}

.Validate query component from URL
[source,gherkin]
----
Then `#{extractQueryFromUrl(file://server/folder/data.xml?id=123)}` is = `id=123`
Then `#{extractQueryFromUrl(https://docs.vividus.dev/vividus/latest?page=2)}` is = `page=2`
----

== Script evaluation

=== `eval`

Evaluates https://commons.apache.org/proper/commons-jexl/[JEXL] script and converts result to a string.

[source, subs="+quotes"]
----
#{eval(*$script*)}
----

* *`$script`* - valid https://commons.apache.org/proper/commons-jexl/reference/syntax.html[JEXL] script to be evaluated

[TIP]
* Any Vividus variable is accessible in the JEXL script by its name


.Evaluate JEXL script
[source,gherkin]
----
Scenario: Verify eval expression
Then `#{<expression>}` is = `<expected>`
Examples:
|expected          |expression                                                        |
|null              |eval(null)                                                        |
|28                |eval(16 + 2 * 6)                                                  |
|10                |eval(math:abs(-10))                                               |
|here              |eval(stringUtils:substringAfterLast('namescpaces are %here', '%'))|
|108               |eval((16 + 2) * 6)                                                |
|-6                |eval(100 / 5 - 16 * 2 + 6)                                        |
|true              |eval(`string\n1` == `string\n1`)                                  |
|false             |eval(`string\n1` == `string1`)                                    |
|I Am FINE         |eval(wordUtils:capitalize('i am FINE'))                           |
|i am fINE         |eval(wordUtils:uncapitalize('I Am FINE'))                         |
|tHE DOG HAS A bone|eval(wordUtils:swapCase('The dog has a BONE'))                    |
|FRD               |eval(wordUtils:initials('Fus Ro Dah'))                            |
----

=== `evalGroovy`

Evaluates groovy script and converts result to a string.

[source, subs="+quotes"]
----
#{evalGroovy(*$script*)}
----

* *`$script`* - valid https://groovy-lang.org/index.html[Groovy] script to be evaluated

[TIP]
====
* Any Vividus variable is accessible in the groovy script by its name
* One could use any of online groovy evaluators to verify the script. For example see: https://groovyconsole.appspot.com/[Evaluator]
====


.Evaluate Groovy script
[source,gherkin]
----
When I initialize Scenario variable `listOfMaps` with values:
|key|
|2  |
|1  |
|3  |
Then `1-2-3` is = `#{evalGroovy(return listOfMaps.collect{it['key']}.sort().join('-'))}`
----

== Null value

=== `null`

Represents `null` (a.k.a. `NULL`). In most case `null` means no value (see https://www.w3schools.com/sql/sql_null_values.asp[`NULL` in SQL] and https://www.json.org/json-en.html[`null` in JSON]).

[source, subs="+quotes"]
----
#{null}
----

NOTE: Null expression can only be evaluated separately. Strings or other expressions with the nested null expression will be completely ignored and not executed.

.Validation of JSON element with `null` value
[source,gherkin]
----
Given I initialize scenario variable `json` with value `
{
    "persons": {
        "nemo": null
    }
}
`
Then JSON element value from `${json}` by JSON path `$.persons.nemo` is equal to `#{null}`
----
