= Variables

Variables are names used to store one or more values. Instead of repeating these
values in multiple places in tests, the variable will keep the results of
a calculation, step execution, expression evaluation, or any other user-defined data.

VIVIDUS provides the following syntax to access variable value:
[source,gherkin]
----
${variableName}
----

There are 2 types of variables:

* regaular - such variables are initialized and controlled by users;
* dynamic - these variables are available out of the box and provided by VIVIDUS
core and plugins, the values of such variables are calculated at the runtime
(i.e. the same variables in different parts of tests may result in different values).
+
[TIP]
Dynamic variables support both lower camel case (e.g. `$\{dynamicVariableName\}`)
and lower hyphen case (e.g. `$\{dynamic-variable-name\}`) name formats.

== Resolution

Whenever the variable placeholder is found in tests, VIVIDUS attempts to resolve
it using the chain having the following order:

* regular variables,
* default value if it's specified in the variable placeholder,
* system properties,
* OS environment variables,
* dynamic variables (keep in mind, if dynamic variable is available, but couldn't
be resolved due to errors or conditions mismatch, the error message will be
logged and variable will be kept unresolved).

If the end of chain is reached and the variable is not resolved, the variable
placeholder will be kept as is: `$\{variableName\}`.


== Scopes

Regular variables can have one of the following scopes.

NOTE: The scopes names are case-insensitive.

[cols="1,6", options="header"]
|===

|Name
|Description

|step
|The scope is used within nested steps and the variables are invalidated after the nested steps are executed.

|scenario
|Variable declared with the *scenario* scope is available in the rest of the scenario after its declaration. The *scenario*-scoped variables are invalidated once the scenario is completed.

|story
|Variable declared with the *story* scope is available in the rest of the story after its declaration. The *story*-scoped variables declared inside given stories are available in the parent story. The variables are invalidated once the story is completed.

|next_batches
|Variable declared with the *next_batches* scope is available in the next batches. The *next_batches*-scoped variable is not available in batch it's declared within.

|global
a|Such variables are declared only via properties with `bdd.variables.global.` prefix and available throughout the entire execution. An attempt to create the globally scoped variables during test execution leads to an error.

.Declaring global variable `login-endpoint`
[source,properties]
----
bdd.variables.global.login-endpoint=https://my-auth-server.com/api/login
----

.Using global variable `login-endpoint`
[source,gherkin]
----
Given request body:
{
    "username":"user",
    "password":"pass"
}
When I set request headers:
\|name        \|value           \|
\|Content-Type\|application/json\|
When I issue a HTTP POST request for a resource with the URL '${login-endpoint}'
Then the response code is equal to '200'
----

WARNING: It is possible to reuse VIVIDUS expressions using `global` variables. Please mind that expression will be executed lazily at the runtime and randomizing/generating expressions may produce different results per usage.

.Declaring global variable with expression `random-user`
[source,properties]
----
bdd.variables.global.random-user=#{anyOf(superadmin,admin)}
----

.Using global variable `random-user`
[source,gherkin]
----
Given request body:
{
    "username":"${random-user}",
    "password":"pass"
}
When I set request headers:
\|name        \|value           \|
\|Content-Type\|application/json\|
When I issue a HTTP POST request for a resource with the URL '/authenticate'
Then the response code is equal to '200'
----

|===
