= Steps available out of the box

== Description

Here one could find description of the steps that are delivered with Vividus itself without any plugins required.

=== Execute steps

Executes the steps located in the table.

[source,gherkin]
----
When I execute steps:$stepsToExecute
----

* `$stepsToExecute` - The ExamplesTable with a single column containing the steps to execute.

.Check and increment the value of a variable
[source,gherkin]
----
When I initialize the STORY variable `var` with value `0`
When I execute steps:
|step                                                                         |
|Then `${var}` is = `0`                                                       |
|When I initialize the STORY variable `var` with value `#{eval(${var} + 1)}`  |
Then `${var}` is = `1`
----

=== Execute while-like loop

Executes the steps while variable matches the comparison rule or until the maximum number of iterations is reached.

[IMPORTANT]
If the maximum number of iterations is reached no failure or exception will occur.

[source,gherkin]
----
When I execute steps at most $max times while variable `$variableName` is $comparisonRule `$expectedValue`:$stepsToExecute
----

Alias:
[source,gherkin]
----
When I execute steps at most $max times while variable '$variableName' is $comparisonRule '$expectedValue':$stepsToExecute
----

* `$max` - The maximum number of iterations
* `$variableName` - The name of the variable to check
* `$comparisonRule` - xref:parameters:comparison-rule.adoc[The comparison rule]
* `$expectedValue` - The expected value of the variable
* `$stepsToExecute` - The ExamplesTable with a single column containing the steps to execute

.Click button 5 times
[source,gherkin]
----
When I execute steps at most 5 times while variable `var` is less than `3`:
|step                                                                                                                   |
|When I click on element located `id(counter)`                                                                          |
|When I find <= `1` elements by `xpath(//div[@id='clickResult' and (text()='3' or text()='4')])` and for each element do|
|{headerSeparator=!,valueSeparator=!}                                                                                   |
|!step!                                                                                                                 |
|!When I set the text found in search context to the 'scenario' variable 'var'!                                         |
Then `${var}` is = `3`
----

=== Execute while-like loop with delays

Executes the steps while variable matches the comparison rule or until the maximum number of iterations is reached. The delay is used to define the amount of time to wait between iterations.

[IMPORTANT]
If the maximum number of iterations is reached no failure or exception will occur.

[source,gherkin]
----
When I execute steps with delay `$delay` at most $max times while variable variable `$variableName` is $comparisonRule `$expectedValue`:$stepsToExecute
----

Alias:
[source,gherkin]
----
When I execute steps with delay '$delay' at most $max times while variable '$variableName' is $comparisonRule '$expectedValue':$stepsToExecute
----

* `$delay` - The delay between iterations
* `$max` - The maximum number of iterations
* `$variableName` - The name of the variable to check
* `$comparisonRule` - xref:parameters:comparison-rule.adoc[The comparison rule]
* `$expectedValue` - The expected value of the variable
* `$stepsToExecute` - The ExamplesTable with a single column containing the steps to execute

.Click button 5 times with 1 second delay
[source,gherkin]
----
When I execute steps with delay `PT1S` at most 5 times while variable `var` is less than `3`:
|step                                                                                                                   |
|When I click on element located `id(counter)`                                                                          |
|When I find <= `1` elements by `xpath(//div[@id='clickResult' and (text()='3' or text()='4')])` and for each element do|
|{headerSeparator=!,valueSeparator=!}                                                                                   |
|!step!                                                                                                                 |
|!When I set the text found in search context to the 'scenario' variable 'var'!                                         |
Then `${var}` is = `3`
----

=== Wait for period

Waits during specified period for debug purposes

[WARNING]
The step is for debugging purpose only

[source,gherkin]
----
When I wait `$period` for debug
----

* `$period` - total duration to wait in {iso-date-format-link} format

.Wait 30 seconds for debug
[source,gherkin]
----
When I wait `PT30S` for debug
----

=== Initialize variable using template

Initializes a variable with a result of the processed https://freemarker.apache.org/docs/dgui_template_overallstructure.html[Freemarker template]

Set the `template-processor.resolve-bdd-variables` property to `true` value to be able to use `global`, `next batches`, `scenario` and `story` variables within templates. The variables can be referred using the variable reference notation. Note that the parameters passed to the step take precedence over the variables.

The vividus expressions can be used within templates by using `${execVividusExpression('expression name', args)}` syntax. It's also allowed to use nested expressions by using the following syntax `${execVividusExpression('expression name', arg1, execVividusExpression('expression name', args))}`.

[source,gherkin]
----
Given I initialize the $scopes variable `$variableName` using template `$templatePath` with parameters:$templateParameters
----

* `$scopes` - xref:commons:variables.adoc#_scopes[The comma-separated set of the variables scopes].
* `$variableName` - The variable name to store a result.
* `$templatePath` - The relative to `src/main/resources` path to a template.
* `$templateParameters` - The template parameters.

.Personal info template at templates/person.ftl
[source,json]
----
{
  "id": ${execVividusExpression('randomInt', 1, 10)},
  "postalCode": ${execVividusExpression('generate', "Number.digits '6'")},
  "hash": "${execVividusExpression('encodeToBase64', execVividusExpression('randomInt', 100, 1000))}",
  "name": "${name[0]}",
  "race": "${race[0]}",
  "age": ${age}
}
----

.Generate JSON from the personal info template
[source,gherkin]
----
When I initialize the scenario variable `age` with value `4510`
Given I initialize the scenario variable `personalInfo` using template `templates/person.ftl` with parameters:
|name     |race  |
|Dagoth Ur|Dunmer|
----

=== Assert the value matches regex

Asserts that the given value matches the specified regular expression.
The dotall mode is enabled by default: the expression `.` matches any character,
including a line terminator.

[source,gherkin]
----
Then `$value` matches `$regex`
----

* `$value` - The value to assert.
* `$regex` - https://en.wikipedia.org/wiki/Regular_expression[The regular expression].

=== Create a file

Saves the provided content to a file with the specified file path.

[source,gherkin]
----
When I create file with content `$fileContent` at path `$filePath`
----

* `$fileContent` - The content to be saved to the creating file.
* `$filePath` - The fully qualified file name including parent folders and extension (e.g. `temp/some_file.txt`).


=== Create a temporary file

Creates a temporary file with the provided content and puts its path to a variable with the specified name.
The created file will be removed upon test run completion.

[source,gherkin]
----
When I create temporary file with name `$name` and content `$content` and put path to $scopes variable `$variableName`
----

* `$name` - The logical name of the creating temporary file. For example, when `$name` is equal to `my-file.txt`, then `my-file` will be used as a prefix in the temporary file name and `.txt` - as a suffix.
* `$content` - The content to be saved to the creating temporary file.
* `$scopes` - xref:commons:variables.adoc#_scopes[The comma-separated set of the variables scopes].
* `$variableName` - The name of the variable to store the full path of the created temporary file.

If you want to use the created temporary file in further batches of the test suite as an input data, you should use https://datatracker.ietf.org/doc/html/rfc8089#appendix-A[URL with `file` protocol]

.Batch 1 - Create a temporary local file
[source,gherkin]
----
When I create temporary file with name `.table` and content `
|column|
|value |
` and put path to NEXT_BATCHES variable `examples-table-temporary-file`
----

.Batch 2 - Use the temporary file as `ExamplesTable`
[source,gherkin]
----
Then `<column>` is equal to `value`
Examples:
file:///${examples-table-temporary-file}
----


=== Compare variables

Compare the value from the first *variable* with the value from the second *variable* in accordance with the *condition*. Could compare Maps and Lists of maps using EQUAL_TO comparison rule.
Other rules will fallback to strings comparison.

INFO: The step prints the comparison results in the unified diff format for the strings with the legth more than specified in the property xref:ROOT:tests-configuration.adoc#_configuration_properties[report.text-length-diff-threshold].

WARNING: If the variables contain valid numbers than they will be converted into https://docs.oracle.com/en/java/javase/17/docs/api/java.base/java/math/BigInteger.html[BigInteger] and compared as numbers.

[source,gherkin]
----
Then `$variable1` is $comaprisonRule `$variable2`
----

* `$variable1` - The first variable.
* `$comparisonRule` - xref:parameters:comparison-rule.adoc[The comparison rule].
* `$variable1` - The second variable.


.Compare Strings
[source,gherkin]
----
Then `Duke` is != `Leto`
----

.Compare numbers
[source,gherkin]
----
Then `10` is = `10.0`
----

.Compare list of maps
[source,gherkin]
----
When I execute SQL query `SELECT * FROM test.launch_rockets WHERE name='Proton'` against `preprod` and save result to scenario variable `preprod-date`
When I execute SQL query `SELECT * FROM test.launch_rockets WHERE name='Proton'` against `prod` and save result to scenario variable `prod-data`
Then `${preprod-data}` is = `${prod-data}`
----
