:test-config: xref:ROOT:tests-configuration.adoc
:allowed-http-properties: {test-config}#_general[general], {test-config}#_authentication[authentication] or {test-config}#_ssl_handshake[SSL handshake] properties

== JIRA Configuration

IMPORTANT: The exporter requires configuration of JIRA instance to work with.

To configure connector to JIRA instance use `jira.` prefix followed by arbitrary sequence of alphanumerical 
characters that determine unique JIRA instance key and followed by the properties listed in the following table:

NOTE: The properties marked with bold are mandatory.

[cols="1,3", options="header"]
|===
|Property Name
|Description

|*project-key-regex*
|The regular expression to match JIRA project keys.

|*endpoint*
|The JIRA Endpoint.

|any of {allowed-http-properties}
|The HTTP properties.

|fields-mapping
|The mapping between human-readable fields used by VIVIDUS and fields used by JIRA.

|===

.jira.properties
[source,json,subs=attributes+, source-highlighter+]
----
jira.vividus.project-key-regex=(VIVIDUS|VSCODE|REACTAPP)
jira.vividus.endpoint=https://vividusframework.atlassian.net/
jira.vividus.http.auth.username=admin
jira.vividus.http.auth.password=5401a7d27b291c5d
jira.vividus.http.socket-timeout=10000
jira.vividus.fields-mapping.test-case-type=customfield_10002
----

In the example above the `vividus` is a key that can be used to refer this JIRA instance.
